### ISSUE TITLE
Expose token validity or improve token retrieval performance

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-for-android#1009]
We are using MSAL to call Exchange Webservices. One thing we want to avoid is to make several calls with invalid credentials, as this can lock the account and only an administrator can unlock it.

For every webservice call we want to ensure that there is a valid token before we do it.
As the library does not expose any validity check we just call acquireTokenSilent and ensure that we have a token, then create the request.

An issue is that this call takes a long time. Here are some log entries:
acquireTokenSilent took 3976 ms
acquireTokenSilent took 4261 ms
acquireTokenSilent took 5344 ms
acquireTokenSilent took 2973 ms

These values are after launching the application on the simulator. A bit later the timestamps go down, but are still a lot too high for my taste:

acquireTokenSilent took 412 ms
acquireTokenSilent took 443 ms
acquireTokenSilent took 424 ms

When running the app in debug mode there are a lot of log entries stating Long monitor contention, for example
2020-04-20 11:29:57.798 13605-13727: Long monitor contention with owner pool-8-thread-1 (13661) at java.util.List com.microsoft.identity.common.internal.cache.SharedPreferencesAccountCredentialCache.getCredentials()(SharedPreferencesAccountCredentialCache.java:-1) waiters=0 in java.util.List com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.loadWithAggregatedAccountData(java.lang.String, java.lang.String, com.microsoft.identity.common.internal.dto.AccountRecord, com.microsoft.identity.common.internal.authscheme.AbstractAuthenticationScheme) for **1.211s**
(the reason for that seems to be synchronized calls)

On a real device most calls take between 80 and 130ms, but there are some extreme values as well:
acquireTokenSilent took 29022 ms
acquireTokenSilent took 34328 ms
acquireTokenSilent took **5308418 ms**

Looking at the library i see two cache mechanisms, one for commands in CommandDispatcher, the other in SharedPreferencesAccountCredentialCache.
The comment in CommandDispatcher line 97 says; "Check cache to see if the same command completed in the last 30 seconds".
But as both the LoadAccountCommand and the TokenCommand return false in isEligibleForCaching() this cache does nothing.

Looking at the second cache it seems to me that it uses an encrypted shared preference file, which means file i/o with encryption overhead.

I think a in-memory cache for tokens would be very useful. By default the token validity is 1 hour, but the value can be changed, and it is not exposed by the library, which makes it difficult to implement an own caching strategy.

**Comment by slowcar** [comment]
Some more test results seem to indicate that the performance is increased a lot by forcing the local mode without broker, i.e. setting broker_redirect_uri_registered false in the configuration file.
A working token cache should resolve that.

It would be helpful if usage of the broker could be configured from the app without having to create a config file, for example by exposing createMultipleAccountPublicClientApplication with a PublicClientApplicationConfiguration parameter or changing the protected constructor to public.

**Comment by MariusVolkhart** [comment]
We're using Azure App Proxy, and so need to submit the token on every network call our app makes to the app proxy. This results in _a lot_ of `acquireTokenSilent` calls (one per network request).

**Comment by kreedula** [comment]
We do have `expiresOn` on [AuthenticationResult]( https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/AuthenticationResult.java#L77) here. Isn't it what you are looking for ?

**Comment by slowcar** [comment]
Thanks, i did not see the expiresOn!
With that we can implement our own caching. 
Personally i think the library should handle the caching.
