### ISSUE TITLE
Fix documentation for Configure Manifest Section

### ISSUE THREAD

**Issue by prmeno** [AzureAD/microsoft-authentication-library-for-android#1019]
**Describe the bug**
Request to fix the documentation for [the configure manifest section](https://github.com/AzureAD/microsoft-authentication-library-for-android#step-3-configure-the-androidmanifestxml).
It has an example `android:path="/<YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE>"`
Putting in the url encoded signature was causing the PublicClientApplication creation to fail, with an exception having an error message indicating at adding the right entry for BrowserTabActivity
Using the decoded signature works

**Comment by shahzaibj** [comment]
Hi @prmeno Thanks for pointing that out. The signature required for the Manifest should be base 64 only (not url encoded). We have the correct information here on our FAQ: https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-FAQ but looks like we missed this detail on our README - we'll get that fixed.

**Comment by shahzaibj** [comment]
@prmeno I've opened up a PR to fix there here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1022
