### ISSUE TITLE
Is there any ability to implement oAuth auth code flow with MSAL library?

### ISSUE THREAD

**Issue by arturalbov** [AzureAD/microsoft-authentication-library-for-android#1024]
Hello,

We're developing app that uses Microsoft authentication. We implementing auth code flow in web version. After receiving code we send it to our backend server. Server exchanging auth code for tokens and after all can perform some operations on-behalf of user. So, I'm wondering if there is any ability to implement same flow on our Android application using MSAL library. Thank you!

**Comment by iambmelt** [comment]
Hi @arturalbov -- I suggest taking a look at [Implementing OBO on the Microsoft Identity Platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)

The method you describe above is an [auth_code interception attack](https://docs.wso2.com/display/IS520/Mitigating+Authorization+Code+Interception+Attacks); something we have specifically[ implemented protections against](https://tools.ietf.org/html/rfc7636). As a matter of secure API design, I would caution against any design approach that relies on leaking the auth_code from a device and exposes a user `refresh_token` to any system outside of that users' control.
