### ISSUE TITLE
1.5.0 Failed to resolve: com.microsoft.device.display:display-mask:0.3.0

### ISSUE THREAD

**Issue by pequots34** [AzureAD/microsoft-authentication-library-for-android#1027]
**Describe the bug**
ERROR: Failed to resolve: com.microsoft.device.display:display-mask:0.3.0

**Comment by dabarnard** [comment]
I also started experiencing this error today (30 April 2020). Most of the documentation recommends using

`implementation 'com.microsoft.identity.client:msal:1.+'`

for the Gradle dependancy. I had to manually set my version number down to 

`implementation 'com.microsoft.identity.client:msal:1.4.0'`

for the issue to be resolved in the interim.

**Comment by fatihsokmen** [comment]
Same here. I am trying to upgrade to latest (1.5.0) but getting following error.


`Could not determine the dependencies of task ':app:compileLocalDebugJavaWithJavac'.
  Could not resolve all task dependencies for configuration ':app:localDebugCompileClasspath'.
     Could not find com.microsoft.device.display:display-mask:0.3.0.
     Required by:
         project :app > com.microsoft.identity:common:2.0.7`

**Comment by iambmelt** [comment]
Please consult the [changelog for version `1.5.0`](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.5.0)

[A new Maven artifact stream must be added to resolve this dependency](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/build.gradle#L32-L35).

Closing this issue; please comment/reopen if this doesn't resolve your issue.

**Comment by iambmelt** [comment]
@shahzaibj Can we also update the README to capture this?

**Comment by shahzaibj** [comment]
@iambmelt I've opened up a PR to update README here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1031

**Comment by joshfriend** [comment]
> add the following lines to your repositories section
> 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed%40Local/maven/v1'
> Please exclude classes under "com.microsoft.device.display" in your proguard file.

There's a bunch of reasons why I'm not a fan of this situation:

* Breaking dependency resolution of an artifact in a minor version bump
* Asking developers to add a strange package repo URL to their repo lists
* Forcing consumers to manually add proguard rules when that can be handled by the library. (If I ignore this will my app crash? I don't know)
* Forcing developers to opt out of an **optional** dependency for a _single_ unreleased device coming "Holiday 2020"?

I think you can make the duo sdk optional without the `exclude group` directive by depending on it with a `provided` dependency scope? My library authorship skills are rusty but I think that tells the library it can expect those classes to exist at runtime, but wont force the dependency to be resolved at build time.

**Comment by Nasicus** [comment]
I still get `Could not find com.microsoft.device.display:display-mask:0.3.0.`

Even though my `build.gradle` looks like this:

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
}

dependencies {
  implementation 'com.microsoft.identity.client:msal:1.5.+'
}
```

What am I missing?

**Comment by TylerJaacks** [comment]
@Nasicus You build.gradle in the top level should look something like this:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext.kotlin_version = '1.2.41'

buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.1"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()

        maven {
            url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by TylerJaacks** [comment]
@Nasicus and you build.gradle in the app level should look something like this

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.0"

    defaultConfig {
        applicationId "com.tylerj.surfaceduoapplication"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    implementation "com.microsoft.device.display:display-mask:0.3.0"
    implementation "com.microsoft.device:dualscreen-layout:1.0.0-alpha01"

    testImplementation 'junit:junit:4.13'

    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Comment by josmithua** [comment]
I'm creating a library that depends on this project. How can I specify the repository in the build.gradle of my library so that users don't have to add the repository in their project top level build.gradle?

**Comment by skbrijesh13** [comment]
Hi,
I have added all the repositories as mentioned above, however I am still facing the same issue where it is looking for deplay-mask library

Could not find com.microsoft.device.display:display-mask:0.3.0.
Required by:
    project :app
    project :app > com.microsoft.identity:common:2.0.12-hf1
Search in build.gradle files

strange that it is not fixed for dependencies, if I wish to use the latest MSAL, I am unable to do it due to this unknown method to solve the dependency issue.

**Comment by ZacSweers** [comment]
It's a little silly that this is still enforced despite the Surface Duo being a cancelled product line

https://www.engadget.com/microsoft-surface-duo-3-cancelled-foldable-phone-154945670.html

**Comment by akshaytandroid** [comment]
I fixed it like this:

```
implementation('com.microsoft.identity.client:msal:4.8.1') {
        exclude group: 'com.microsoft.device.display'
    }
```

**Comment by joshfriend** [comment]
I can't believe I just stubbed my toe on this same issue SIX YEARS later.

**Comment by joshfriend** [comment]
I created a PR to rip out the display-mask dependency from the core library: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/2873
