### ISSUE TITLE
How does one properly use SingleAccountPublicClientApplication.signOut()?

### ISSUE THREAD

**Issue by emmano** [AzureAD/microsoft-authentication-library-for-android#1028]
Currently, we get an instance of `SingleAccountPublicClientApplication` via `.createSingleAccountPublicClientApplication(context, R.raw.msal_config)` and everything works fine when the app is in memory.

Let's say the user swipes the app from memory. I would then create a new instance of `SingleAccountPublicClientApplication`, but this instance fails to sign out since there is no account associated to it. Do I need to call `acquireToken()` again so it can sign out? Is there a way to retrieve an instance of `SingleAccountPublicClientApplication` that knows if there is an account already?

**Comment by shahzaibj** [comment]
Hi @emmano It shouldn't make a difference whether you use an existing instance or create a new instance of SingleAccountPublicClientApplication when calling any of its methods including signOut. 

Are you running into any errors when calling sign out? 
Can you tell us what specific exception/error you are getting? 
Can you also provide us MSAL logs? 

Instructions to capture logs are here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=android

**Comment by emmano** [comment]
Thanks for replying so quickly. When I call `signOut()` it returns `false`.

**Comment by emmano** [comment]
I checked again and it seems to work. Thanks for responding!

**Comment by shahzaibj** [comment]
So everything is working fine now? The account is being sign-out properly?

**Comment by emmano** [comment]
Yes.

**Comment by shahzaibj** [comment]
Sounds good. I'll go ahead and close this issue then. Feel free to reopen if you run into issues again.

**Comment by emmano** [comment]
I am still having issues. I call `signOut()` and I take the user back to the login screen that shows the B2C login page. Now, if the user presses the back key and comes back into the app, they are automatically taken into the app. It seems that MSAL is remembering the account somehow? Is there a way to clear the account in Android? I did not find any remove method?

**Comment by emmano** [comment]
In the meantime I am using the following code to remove all user data and prevent automatic login after sign out. I am using "authorization_user_agent": "WEBVIEW".

(requireContext().getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager).clearApplicationUserData()
