### ISSUE TITLE
Single Account - Acquire Token Overloads provide conflicting behaviour

### ISSUE THREAD

**Issue by shahzaibj** [AzureAD/microsoft-authentication-library-for-android#1032]
In Single account mode, the overloads for acquiring a token are offering different behaviors.

For example [`acquireToken(activity, scopes, callback)`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L529) throws a `NO_CURRENT_ACCOUNT` exception if they user hadn't already signed in. 

See this block: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/fba4df5e50aded2370c296e25f4665549d5a5706/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L533-L537

However, [`acquireToken(AcquireTokenParameters)`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L560) allows acquiring token even if the user had never signed in before.

See this block: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L561-L596

We need to make the behavior consistent across each overload.

**Comment by shahzaibj** [comment]
@rpdome Need your help deciding if this is broken or expected behavior?

**Comment by rpdome** [comment]
The way I see this is that signIn() and acquireToken(activities,.... etc) are all 'helper' functions, and acquireToken(AcquireTokenParameters) is the 'advanced' option.

If I want to pass in claimsRequest, I can't do with signIn().

Maybe we should just keep signin() and signinAgain() in Single Account PCA and introduce their AcquireTokenParameter overloads? (Move *ALL* acquireToken() operations to Multiple Account PCA)

**Comment by shahzaibj** [comment]
@rpdome If the app is indeed expected to call `signIn` first in single account mode, then I think we can just modify[ this method](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/SingleAccountPublicClientApplication.java#L560) to throw the `NO_CURRENT_ACCOUNT_FOUND` error same as the other overload.

With that being said, I've been thinking if we should redesign the Public Api around single account mode so that calling sign in is not required at all. Do you have historical context on why this was done this way? Or more importantly why methods like `signin` were even needed in addition to the acquire token methods? We can also follow on this offline if that is better.

**Comment by rpdome** [comment]
The way I see this is that signIn() and acquireToken(activities,.... etc) are all 'helper' functions, and acquireToken(AcquireTokenParameters) is the 'advanced' option.

i.e. If I want to pass in claimsRequest, I can't do with signIn().

I think this is a gap in the existing Single Account mode API. In single account mode, the app is expected to call 'signin()' in its first call. 

The goal of Single Account Mode PCA is that the app does not have to call getAccounts() (since there's only 0 or 1 account at a time - so this would simplify the dev experience). signIn() and signInAgain() is designed around that. 

Throwing out an idea, maybe we should only keep signin() and signinAgain() in Single Account PCA and introduce their SignInParameters (AcquireTokenParameter WITHOUT the account object) overloads? (Move *ALL* acquireToken() operations to Multiple Account PCA)

**Comment by MariusVolkhart** [comment]
Non-MS library consumer here. I want to share my use case and my dev experience, in case you find it helpful.

I'm trying to make my app work with the Company Portal broker. In my app I only ever want the account that is signed in to the broker app to be used. Accordingly, I reached for the Single Account PCA. "Why deal w/ the complexity of multiple accounts when I only want 1?" was my thinking.

The [Azure Docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth#effects-of-installing-and-uninstalling-a-broker) and #906 made me think that calling `acquireToken()` was correct.

@rpdome's comment makes me think that is incorrect, and that I _must_ use the multi-account PCA instead?

What @shahzaibj described would have made things much clearer for me

> if we should redesign the Public Api around single account mode so that calling sign in is not required at all.

**Comment by shahzaibj** [comment]
@MariusVolkhart You should call `signIn` first from MSAL before you can use other acquire token methods in Single Account mode. We'll discuss internally if we need to change behavior around this, but for now we expect developers to call `signIn` and they can then use `signInAgain` or `acquireToken` to get tokens additional times.

You can also refer to this article for more info on Single Account mode: https://docs.microsoft.com/en-us/azure/active-directory/develop/single-multi-account

**Comment by rpdome** [comment]
@MariusVolkhart Single Account PCA is an effort to simplify developer experience for apps that only supports 1 account. Having said that, I think there's still a gap that we need to improve. As @shahzaibj said above, we're currently discussing on how to make it easier to use/understand. 

As of now, the flow looks like this
1. The user signs in for the first time -> app calls signIn()
2. The user signs in next time (silently) -> app calls acquireTokenSilent()
3. The user signs in and there is an issue that requires user attention (you'll get an error from acquireTokenSilent()) -> app calls signInAgain()

Sorry for the confusion, we'll take your feedback and improve the API and documentation. We also have the sample app [here](https://github.com/Azure-Samples/ms-identity-android-java)

**Comment by joshfriend** [comment]
I use single account mode and just ran into this weirdness. Also strange was the fact that `acquireToken(AcquireTokenParams)` totally works in place of `logIn()` even when no account is currently logged in.

I was upgrading from v0.2.2 which didn't have `logIn()` and didn't see anything in [the wiki](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-migration-guide-0.3.2-1.0.0) about it changing from `acquireToken()` to `logIn()`.

Now that I think about it, I'm honestly not sure when I would _ever_ use `acquireToken()`.
