### ISSUE TITLE
acquireTokenSilent: documentation & behavior mismatch

### ISSUE THREAD

**Issue by MariusVolkhart** [AzureAD/microsoft-authentication-library-for-android#1034]
**Describe the bug**
The Javadoc for `ISingleAccountPublicClientApplication#acquireTokenSilent(String[] scopes, String authority)` states 

> @param `authority` Optional. Can be passed to override the configured authority.

However, this is not the observed behavior. Instead, providing `null` or an empty string results in a `MsalArgumentException` indicating that the `authority` may not be null.

In fact, `SingleAccountPublicClientApplication#acquireTokenSilent(String[] scopes, String authority)` marks the `authority` parameter as `@NonNull` and walking the stack reveals that it never attempts to load the default authority from the configuration file and that is performs input validation of the provided `authority`.

**Smartphone (please complete the following information):**
 - MSAL Version: 1.4.0

**Expected behavior**
I expect that the `SingleAccountPublicClientApplication#acquireTokenSilent(String[] scopes, String authority)` function behaves as documented, and that the default authority is in fact loaded from the configuration file.

**Comment by iambmelt** [comment]
Thanks for reporting this issue, @MariusVolkhart -- this is a documentation issue; this parameter is currently required. I will update the documentation to reflect the required status
