### ISSUE TITLE
NullPointerException after updating app with msal from 1.4.0 to 1.5.1 and enabled proguard

### ISSUE THREAD

**Issue by azakharenka1** [AzureAD/microsoft-authentication-library-for-android#1039]
**NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.dto.AccountRecord.getHomeAccountId()' on a null object reference**

**Smartphone**
 - Pixel 3 Xl, android 10, WEB VIEW, msal 1.5.1, obfuscation is ON

**Stacktrace**
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: PID: 22613
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.dto.AccountRecord.getHomeAccountId()' on a null object reference
        at com.microsoft.identity.client.AccountAdapter$HomeAccountFilter.filter(AccountAdapter.java:82)
        at com.microsoft.identity.client.AccountAdapter.filterCacheRecords(AccountAdapter.java:351)
        at com.microsoft.identity.client.AccountAdapter.adapt(AccountAdapter.java:153)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.getAccountFromICacheRecordList(SingleAccountPublicClientApplication.java:515)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.getPersistedCurrentAccount(SingleAccountPublicClientApplication.java:479)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.acquireTokenSilentAsync(SingleAccountPublicClientApplication.java:603)
        at x.a.a.e.q.a$h$a.a(AuthorizationRepository.kt:56)
        at x.a.a.e.q.a$h$a.accept(AuthorizationRepository.kt:29)
        at m.b.i0.d.f.a(ConsumerSingleObserver.java:62)
        at m.b.i0.e.f.m$a.a(SingleDoOnSuccess.java:60)
        at m.b.i0.e.f.b$a.a(SingleCreate.java:67)
        at x.a.a.e.k.a$a$a.onCreated(AzureB2CConfig.kt:44)
        at com.microsoft.identity.client.PublicClientApplication$11.onCreated(PublicClientApplication.java:978)
        at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:906)
        at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:894)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:212)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**To Reproduce**
1) Login into app with msal 1.4.0 (Single mode, webview)
2) Update msal to 1.5.1
3) Install app update
4) run acquireTokenSilentAsync for loginApplication 

**Expected behavior**
No crash, success in acquireTokenSilentAsync

**Actual Behavior**
App crashed

**Additional context**
Does not repro on debug build without obfuscation

**Comment by kreedula** [comment]
@azakharenka1 : Does it only happen on upgrade or an fresh install with 1.5.1 with proguard obfuscation on?

Can you post your proguard config w.r.t to MSAL here ? Also we recently made some changes to add proguard rules in library here :https://github.com/AzureAD/microsoft-authentication-library-for-android/commit/5356c2f257a9d712252779b52dfe8eb2db79204b

**Comment by azakharenka1** [comment]
@kreedula Happens only on app update, on fresh install all works fine.

**Comment by azakharenka1** [comment]
# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

#https://github.com/pwittchen/ReactiveNetwork
-dontwarn com.github.pwittchen.reactivenetwork.library.rx2.ReactiveNetwork
-dontwarn io.reactivex.functions.Function
-dontwarn rx.internal.util.**
-dontwarn sun.misc.Unsafe

# Twilio Programmable Voice
-keep class com.twilio.** { *; }

-dontwarn com.google.errorprone.annotations.*

#Okhttp
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
# Animal Sniffer compileOnly dependency to ensure APIs are compatible with older versions of Java.
-dontwarn org.codehaus.mojo.animal_sniffer.*
# OkHttp platform used only on JVM and when Conscrypt dependency is available.
-dontwarn okhttp3.internal.platform.ConscryptPlatform

#nofo data classes
-keep class pl.predica.nofo.adddevice.data.** { *; }
-keep class pl.predica.nofo.home.data.model.** { *; }
-keep class pl.predica.nofo.common.data.model.** { *; }
-keep class pl.predica.nofo.settings.data.model.** { *; }
-keep class pl.predica.nofo.share.data.** { *; }
-keep class pl.predica.nofo.security.data.**{*;}
-keep class pl.predica.nofo.security.data.model.** { *; }

#software update data classes and dfu classes
-keep class pl.predica.nofo.softwareUpdate.domain.model.** { *; }
-keep class pl.predica.nofo.softwareUpdate.data.model.** { *; }
-keep class pl.predica.nofo.softwareUpdate.presentation.model.** { *; }
-keep class no.nordicsemi.android.dfu.** { *; }

-keep public class * extends java.lang.Error
-keep public class * extends java.lang.Exception

-keep @kotlinx.android.parcel.Parcelize class *


# Retain service method parameters when optimizing.
-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

# Ignore annotation used for build tooling.
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

# Ignore JSR 305 annotations for embedding nullability information.
-dontwarn javax.annotation.**

# Guarded by a NoClassDefFoundError try/catch and only used when on the classpath.
-dontwarn kotlin.Unit

# Top-level functions that can only be used by Kotlin.
-dontwarn retrofit2.-KotlinExtensions

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# Realm auto migrate
-keepnames public class * extends io.realm.RealmModel
-keep public class * extends io.realm.RealmModel { *; }
-keepnames public class * extends io.realm.RealmObject
-keep public class * extends io.realm.RealmObject { *; }
-keepattributes *Annotation*

#LockDetailsFragment crash fix
-keep class org.xmlpull.** { *; }
-dontwarn android.content.res.XmlResourceParser

### greenDAO 3
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties

# If you do not use SQLCipher:
-dontwarn org.greenrobot.greendao.database.**

# Crashlytics
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep public class * extends java.lang.Exception

-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**

### greenDAO 3
-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties {*;}

# If you do not use SQLCipher:
-dontwarn net.sqlcipher.database.**
# If you do not use RxJava:
#-dontwarn rx.**

### greenDAO 2
-keepclassmembers class * extends de.greenrobot.dao.AbstractDao {
public static java.lang.String TABLENAME;
}
-keep class **$Properties

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * implements com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

##---------------End: proguard configuration for Gson  ----------

### msal
-keep class com.microsoft.identity.client.** { *; }
-keep class com.microsoft.identity.common.internal.ui.** { *; }
-keep class com.microsoft.identity.common.internal.authorities.** { *; }
-keep class com.microsoft.identity.client.PublicClientApplicationConfigurationFactory { *; }
-keep public enum com.microsoft.identity.common.internal.ui.AuthorizationAgent { *; }
-keep public enum com.microsoft.identity.common.internal.authorities.Environment { *; }
-keep public enum com.microsoft.identity.common.internal.providers.oauth2.OpenIdConnectPromptParameter { *; }
-keep public class com.microsoft.identity.common.internal.request.AcquireTokenOperationParameters { *; }
-keep public enum com.microsoft.identity.common.internal.request.SdkType { *; }
-keep public class com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsAuthorizationResponse { *; }
-keep public class com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsTokenResponse { *; }
-keep class com.microsoft.identity.common.exception.** { *; }
-keep class **$Properties

**Comment by kreedula** [comment]
Can you trying excluding all microsoft files from obfuscation like below and see if it resolves the issue
 `-keep class com.microsoft.** { *; }`

**Comment by azakharenka1** [comment]
Yes, I tried it already - same issue:  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.identity.common.internal.dto.AccountRecord.getHomeAccountId()' on a null object reference

update from 1.4.0 to 1.5.1 - NPE
update from 1.4.0 to 1.5.1 + proguard rules change - NPE
proguard rules change - NPE

**Comment by azakharenka1** [comment]
@kreedula any updates with it? We could catch this exception and manually logout this user but i don't really like those solution and don't want to do it)

**Comment by tanmaymanolkar1** [comment]
@azakharenka1 I believe you may have found a documentation gap for us. Thank you for that, we will work to correct it and apologies for the inconvenience caused.

The possible reason you may be facing this problem is because B2C registered applications need to be used in conjunction with MultipleAccountPublicClientApplication and not SingleAccountPublicClientApplication.

Attaching the link to the resource for implementation details.

https://docs.microsoft.com/en-us/azure/active-directory/develop/single-multi-account#multiple-account-public-client-application

Please let us know if you encounter similar errors after doing the mentioned fix.
