### ISSUE TITLE
NullPointerException when calling acquireToken for authorization

### ISSUE THREAD

**Issue by perqin** [AzureAD/microsoft-authentication-library-for-android#1043]
**Describe the bug**

I've received a crash report from Crashlytics. The exception is received when calling `com.microsoft.identity.client.IPublicClientApplication#acquireToken(android.app.Activity, java.lang.String[], com.microsoft.identity.client.AuthenticationCallback)`.

**Smartphone (please complete the following information):**
 - Device: Redmi K20 Pro
 - Android Version: Android 10
 - Browser: Not sure
 - MSAL Version: 1.3.0

**Stacktrace**

![image](https://user-images.githubusercontent.com/7088631/81916829-edb12080-9606-11ea-9d9d-c471b79bffb4.png)

**To Reproduce**

I am sorry, but this report is from Crashlytics, so I can't provide more detail about user's interaction. The only thing I am sure is that the exception is received when calling `acquireToken` to sign in and authorize.

**Expected behavior**

No exception.

**Actual Behavior**

Exception received, as shown in the image above.

**Screenshots**

**Additional context**

It seems that the issue can be re-produced only on this user's device. My Pixel 3 is working fine.

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by pabloromeu** [comment]
Hello @perqin. I filled a bug some days ago (#1033) about a failure in token renewal. I tried the same configuration on the Example of the library and it threw the same error to me. Seems that the account information is not being retrieved at the acquireToken callback.

**Comment by iambmelt** [comment]
This issue is the result of using an incompatible ProGuard configuration; please use the one provided here:
https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/consumer-rules.pro
