### ISSUE TITLE
Security In MSAL(Android ID Collected)

### ISSUE THREAD

**Issue by wangyeking** [AzureAD/microsoft-authentication-library-for-android#1050]
The following Java or Kotlin classes within the App are collecting the
device's unique ANDROID_ID: `com.microsoft.identity.common.internal.telemetry.TelemetryContext`

 The `ANDROID_ID` is a 64-bit number (as a hex string) that is randomly
generated when the user first sets up their device and that remains constant for the lifetime of the device. It can be accessed using the `Setting.Secure` Android API.

Because the `ANDROID_ID` uniquely identifies a device for its lifetime and does not allow users to opt-out of it or prevent its collection, collecting `Settings.Secure` it has significant privacy implications.

Additionally, the Android "Best Practices for Unique Identifiers" guide explicitly recommend to not collect the `ANDROID_ID` (referred to as the "SSAID"):
"#1: Avoid using hardware identifiers. Hardware identifiers such as SSAID (Android ID) and IMEI can be avoided in most use-cases without limiting required functionality."
 
"Relying on hardware IDs is discouraged because the user cannot reset them and generally has limited control over their collection."

>Note: Google announced changes to several device identifiers in Android O. These changes were done to enhance user privacy
and provide more control to users over their device identifiers. In O, Android ID has a different value for each App and each user on the device. Two different Apps on the device will always receive different Android IDs. However, the Android ID will remain the same on App uninstall/reinstall as long as the App's package name and signing key are the same. This change was introduced to force developers to use the Advertising ID, which is an anonymous string that allows tracking and ad targeting. It is not unique to a device and can be reset by the user at any time.

**Comment by shoatman** [comment]
@shahzaibj, @Om83 - Possible to take a look at this.

**Comment by iambmelt** [comment]
ADO Tracking:
- https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1282149

**Comment by iambmelt** [comment]
Closed by https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1214
