### ISSUE TITLE
Issue with SSO

### ISSUE THREAD

**Issue by RajeshRam** [AzureAD/microsoft-authentication-library-for-android#1052]
**Not selecting personal account from the microsoft authenticator app**

Microsoft Authenticator app is installed, from the sample app(https://github.com/Azure-Samples/ms-identity-android-java) when trying to login the app opens login page in webpage not the authenticator app . Only after entering mail id there is option for password less authentication.

*My question is , will MSAL select the personal account already logged in the authenticator app like the facebook or google apps?*

**Smartphone (please complete the following information):**
 - Device: Android
 - MSAL Version

**Comment by rpdome** [comment]
Hi @RajeshRam,

That scenario is not currently supported in MSAL.

Thanks,
Dome
