### ISSUE TITLE
Can't use Dagger to inject instances of `PublicClientApplication` into activities or fragments

### ISSUE THREAD

**Issue by joshfriend** [AzureAD/microsoft-authentication-library-for-android#1061]
**Is your feature request related to a problem? Please describe.**
I apologize for being so late with this feedback. I was previously using v0.2.2 and was held back because of the time required to update to using the new async methods we are required to call if on the main thread. Plus v0.2.2 was working totally fine aside from some very rare crashes.

I also realize that the synchronous methods for worker threads which throw exceptions if called on main thread was one of my requests (#544). I stand by that suggestion though and appreciate you adding them 😄.

What I didn't realize til I updated was that there are now no public constructors for the `IPublicClientApplication` classes and their factory methods must also be called off of the main thread.

*So here's where my frustration begins*, I previously used Dagger to build instances of `PublicClientApplication` which concentrated the configuration into a single place, and the client instance could simply be injected into fragments where I needed it. With the latest versions, this crashes since the object graph is created by dagger on the main thread, or at least the provider in the graph is invoked on the main thread when activities or fragments are injected in `onCreate`.

Now I need to enter "callback hell" in fragments where I need an instance of `IPublicClientApplication`, I have to use a callback to get it. If I need to call `acquireToken`, I have to get the client instance async with a callback, then also get the token (again with a callback):

```kotlin
val params = AcquireTokenParameters.Builder()
  .withCallback(object : AuthenticationCallback {
    override fun onSuccess(authenticationResult: IAuthenticationResult) { }
    override fun onCancel() = Timber.w("Cancelled")
    override fun onError(exception: MsalException) = Timber.e(exception, "Failed to get token")
  })
  .build()

PublicClientApplication.createSingleAccountPublicClientApplication(
  applicationContext,
  R.raw.msal_config,
  object : IPublicClientApplication.ISingleAccountApplicationCreatedListener {
    override fun onCreated(application: ISingleAccountPublicClientApplication) {
      application.acquireToken(params)
    }

    override fun onError(exception: MsalException) {
      Timber.e(exception, "Failed to initialize PublicClientApplication")
    }
  }
)
```

[The README](https://github.com/AzureAD/microsoft-authentication-library-for-android#step-4-create-an-msal-publicclientapplication) suggests storing the `IPublicClientApplication` instance in a field on the class once retrieved, but this is prone to race conditions, especially in java where nullability might not be enforced.

Creating the client requires reading a JSON file to load the configuration, which if performed on the main thread would trigger strict mode violations, or cause jank so I understand why this is also asynchronous.

**Describe the solution you'd like**
I'd like the configuration loading to be performed lazily when needed. Then I can create a client instance with dagger and inject it easily. In this scenario any errors encountered configuring the client instance would be thrown by the synchronous `acquireToken()` methods or to the `onError()` method of the `AuthenticationCallback`. This would flatten the callback pyramid and make the API generally easier to use. Dagger or some other method could be used to save the client instance as a singleton as well.

**Comment by shahzaibj** [comment]
Hi @joshfriend I'm not personally familiar with Dagger but would the these methods that create instance of `PublicClientApplication` and don't need a callback work for your case? https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L387

**Comment by joshfriend** [comment]
I used to (in v0.2.2) provide an instance of `PublicClientApplication` to my activities, fragments and other things using Dagger:

```kotlin
@Provides
@Singleton
fun provideMsalPublicClientApplication(context: Context): PublicClientApplication {
  return PublicClientApplication(context.applicationContext, R.raw.msal_config)
}
```

Then inside `DaggerFragment` which fragments using dagger injection inherit from, this happens:

```java
@Override
public void onAttach(Context context) {
  AndroidInjection.inject(this);
  super.onAttach(context);
}
```

which is on the main thread. This calls `provideMsalPublicClientApplication()` or uses an already created result if the provider is a `@Singleton` to supply a field on the fragment or activity `@Inject lateinit var app: PublicClientApplication`. 

This allows the `PublicClientApplication` to be available to the fragment basically immediately in its lifecycle. At subsequent lifecycle methods, the instance will be available and there is no race condition possible as might happen with a callback. `Activity` and `Fragment` lifecycle methods are invoked on the main thread which is why you cannot use the sync method you referenced (It is marked `@WorkerThread` and throws an exception if called on the main thread).

**Comment by 4gus71n** [comment]
@joshfriend I also encountered the same issue, here's a hacky way to fix it:

```
    class HackySingleAccountPublicClientApplication(c: PublicClientApplicationConfiguration) :
            SingleAccountPublicClientApplication(c)

    @Provides
    @Singleton
    fun providePublicClientApp(
        context: Context
    ): ISingleAccountPublicClientApplication {
        return HackySingleAccountPublicClientApplication(
            PublicClientApplicationConfigurationFactory.initializeConfiguration(context, myResConfigFile)
        )
    }
```

I recently updated from the `1.0.0` version to the `1.5.0` and I started seeing issues like these all over the place, I'm thinking on going back to `1.0.0` 🤔

**Comment by shahzaibj** [comment]
@joshfriend @4gus71n Thanks for providing those insights. We'll discuss with the team and get back to you.

**Comment by MariusVolkhart** [comment]
@joshfriend We use Dagger's `Lazy` to work around this. We inject a `Lazy<ISingleAccountPublicClientApplication>` and then when we're at the point where we are ready to use the `ISingleAccountPublicClientApplication` call the [get()](https://dagger.dev/api/latest/dagger/Lazy.html#get--) from a non-main thread. We annotate our `provide` method with `@Singleton`.

**Comment by joshfriend** [comment]
@MariusVolkhart while that suggestion is certainly an improvement over the current method, I would really like the library to handle as much of the background thread stuff as possible. Having the client app class lazy configure itself, then passing configuration errors to the callback in `AuthenticationCallback` seems like an alright solution to me.

`Lazy` would still require me to use an asynctask or something.

**Comment by v-po** [comment]
Greetings!
I don't mean to resurrect this old issue. However, I thought I'd share my solution that builds upon some of the suggestions from this discussion. My intention was to support the more "modern" ways of working on Android (Dagger/Hilt, AAC VMs, Kotlin coroutines). The sample can be found here: https://github.com/v-po/msal-sample

It's still very much a work in progress and I would greatly appreciate any feedback on it.

@joshfriend @MariusVolkhart @4gus71n  - apologies for the ping, but just in case you might be interested ☺️
