### ISSUE TITLE
Memory leaks detected within SDK

### ISSUE THREAD

**Issue by josephkniestprometheanworld** [AzureAD/microsoft-authentication-library-for-android#1067]
We have seen the following object leaked. Does any of this ring a bell?

* Instance of com.microsoft.identity.common.internal.request.AcquireTokenOperationParameters
|   static $classOverhead = byte[576]@320152353 (0x13152321)
|   mActivity = <our main activity>.MainActivity@320781472 (0x131ebca0)                                                                                                                                        
|   mAuthorizationAgent = com.microsoft.identity.common.internal.ui.AuthorizationAgent@320151088 (0x13151e30)                                                                                                  
|   mBrokerBrowserSupportEnabled = false
|   mExtraQueryStringParameters = null
|   mExtraScopesToConsent = java.util.Arrays$ArrayList@320843352 (0x131fae58)
|   mFragment = null
|   mLoginHint = null
|   mOpenIdConnectPromptParameter = com.microsoft.identity.common.internal.providers.oauth2.OpenIdConnectPromptParameter@320158224 (0x13153a10)                                                                
|   mRequestHeaders = null
|   webViewZoomControlsEnabled = true
|   webViewZoomEnabled = true
|   clientId = "<our client ID guid>"
|   mAccount = null
|   mAppContext = <our android.app.Application>@319518872 (0x130b7898)                                                                                                                                         
|   mApplicationName = "<our consumer package name>"
|   mApplicationVersion = "<our app version>"
|   mAuthenticationScheme = com.microsoft.identity.common.internal.authscheme.BearerAuthenticationSchemeInternal@320851384 (0x131fcdb8)                                                                        
|   mAuthority = com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryAuthority@320851400 (0x131fcdc8)                                                                                       
|   mBrowserSafeList = java.util.ArrayList@320844752 (0x131fb3d0)
|   mClaimsRequestJson = "{}"
|   mCorrelationId = null
|   mForceRefresh = false
|   mIsSharedDevice = false
|   mRequiredBrokerProtocolVersion = null
|   mScopes = java.util.HashSet@320851464 (0x131fce08)
|   mSdkType = com.microsoft.identity.common.internal.request.SdkType@320151984 (0x131521b0)
|   mSdkVersion = "1.4.0"
|   mTokenCache = com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache@320843784 (0x131fb008)                                                                                                     
|   redirectUri = "msauth://<our redirect uri with secret>"
|   shadow$_klass_ = com.microsoft.identity.common.internal.request.AcquireTokenOperationParameters
|   shadow$_monitor_ = 0

**Comment by tanmaymanolkar1** [comment]
Hi @josephkniestprometheanworld could you please provide some additional context on the tool you used to detect the leak, and the steps taken to generate this leak report?

**Comment by josephkniestprometheanworld** [comment]
It came from leak canary https://square.github.io/leakcanary/

**Comment by shoatman** [comment]
@Om83 , @hamiltonha - Should we file this a bug for investigation?
