### ISSUE TITLE
ProgressBar has hardcoded color on common_activity_authentication.xml

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#1077]
Hi!

It's been a while since our designers have been bothering us about the loading that is presented before opening the webview being from a different color of the others in the app. When we started to work on this we noticed that we couldn't change it because it's hardcoded within MSAL.

![image](https://user-images.githubusercontent.com/18970657/85772885-aaf96280-b6f3-11ea-85eb-45a835dfbf5f.png)

if it was something like:
`android:indeterminateTint="@color/msal_loading"`

we could easily override it. Can someone take a look at this? (Not sure whether it's a bug or feature request though... it would be a code-review bug I think)

thanks!

**Comment by shoatman** [comment]
@Om83, @hamiltonha - Feature request.  Possible to add this to our backlog?

**Comment by tanmaymanolkar1** [comment]
@xyzwilliamxyz Thank you for bringing it to our attention, the required changes have been made as per your suggestions and you would be able to override the color value. The fix would be shipped in the next library release.

**Comment by iambmelt** [comment]
Shipped
