### ISSUE TITLE
createMultipleAccountPublicClientApplication not threadsafe

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-for-android#1079]
Our Android application calls PublicClientApplication.createMultipleAccountPublicClientApplication at startup.

When our workers do a network connection they ensure that a client application is available, otherwise they create one.

Creating the initial client application can take a lot longer than we expected. Example from a customer log:
ModernAuthUtil Created initial MSAL client application, took **69260 ms**
(See log here https://pastebin.com/25btuL2N )

Due to this long time our workers try to create their own client application instances instead of using the singleton.
See the log here: https://pastebin.com/mPh1fty8

I am investigating the issue since i posted the bug on the shared library 3 months ago, but as it seems to be ignored there i'll post it here with more data. https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/905

I will write a wrapper to synchronize access to the client application creation, but i think this behavior should either be documented prominently or changed in the library.
(I have also written a memory cache for the token, resulting in a performance gain of 200-1000ms for every network operation)

**Comment by shoatman** [comment]
@Om83, @hamiltonha - I think we should add this to our backlog for the next sprint.
