### ISSUE TITLE
Allow otpauth:// Links from Embedded Webview

### ISSUE THREAD

**Issue by andylegear** [AzureAD/microsoft-authentication-library-for-android#1080]
* Expected behavior

Link to authenticator apps on device - especially Authenticator Apps such as microsoft authenticator for time-based one time password (totp) flows (e.g. https://github.com/azure-ad-b2c/samples/blob/master/policies/custom-mfa-totp/readme.md )

If you are on a mobile device using msal, you will not be able to scan a QR code, and instead would want to link directly to your authenticator app on the device using the otpauth:// scheme

* Actual behavior

The msal checks links to http endpoints preventing them (correctly).   
![image](https://user-images.githubusercontent.com/4477187/86000020-df776200-ba04-11ea-81d2-dc86c7efdfad.png)

However I think the intention here is to prevent the use of http endpoints, rather than preventing all protocols other than https

* Steps to reproduce the problem

include a link to an authenticator app such as 

otpauth://totp/B2CDemo%3Aa%40b.c?secret=IU67PONWOM3AITKNT464LLF4YAL4OFUI&issuer=Azure%20AD%20B2C%20Demo

* Specifications like the version of the library, operating system etc.
msal 1.5.+
Pixel 2 Emulator
Android 28+

**Comment by iambmelt** [comment]
@hamiltonha This looks somewhere between a bug and feature request. I have filed a [backlog item in ADO here (corpnet required)](https://identitydivision.visualstudio.com/Engineering/_boards/board/t/DevEx%20-%20Android/Backlog%20items/?workitem=1063645). I suspect the _client_ library should not be responsible for making this REST call, but should instead just be presented the QR code for the user to scan. Unclear to me what the expectations are here: `otpauth` is not a protocol scheme we currently support

**Comment by iambmelt** [comment]
Assigning to @hamiltonha - as this needs PM definition

**Comment by andylegear** [comment]
@iambmelt @hamiltonha  

So there isn't that much to actually support.  It is more a case of not blocking "<a href="otpauth://totp/..." links in web views.  

When you install Microsoft or Google Authenticator, those app register themselves in Android OS as handlers of the otpauth scheme.  So if you click any link anywhere with that scheme the OS will open the app rather than a web page in a browser.  The only.  

If you were on a desktop browser you could pick up your phone and scan a QR Code.  But if you have visited the sign up flow on a mobile device you cant scan the QR Code because it is on the mobile screen.  However, the QR code is simply the otpauth://totp/... url encoded in a QR Code.  Clicking a link with that url on the mobile device works perfectly well.

In the msal library `./common/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java`

it would be a case of adding another handler to whitelist that scheme in 
`private boolean handleUrl(final WebView view, final String url)`
