### ISSUE TITLE
ADAL To MSAL Migration - Multiple app SSO Support

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1086]
Presently we have more than 1 app in market, that is using ADAL library.

Using first app if we try login with "xxx.com", we are maintain the cache information with the TokenCacheItem(ITokenCacheStore interface) class exposed by the ADAL.
Note: Without using Authenticator app.

So when we login with the second app using "xxx.com", it won't ask for interactive login, using the TokencacheItem it will be able to login silently.

**Now we are Migrating to MSAL:**
In MSAL, there is no class exposed to set or get the cache information, Could you please let us know how to achieve the multiple apps SSO feature using MSAL.

**Comment by shoatman** [comment]
By default, MSAL uses the default browser on a device to perform authorization.  Single sign on cookies issued by the Authorization server (in this case AAD) are issued after the user authenticates.  Other apps performing authorization on the device will benefit for the fact that the same account has already been signed in.  

In ADAL how are you sharing token cache items between your apps?  Do these app use the same client id?  

Apologies for the delayed response here.  

@hamiltonha - This is a potential blocker for this customer migrating from ADAL.  Let's discuss with the team.

**Comment by iambmelt** [comment]
With the latest version of MSAL, ADAL's cache will be automatically migrated to MSAL to support seamless SSO/migration.
