### ISSUE TITLE
Conditional Access Policies by selecting apps is ignored

### ISSUE THREAD

**Issue by da351hon** [AzureAD/microsoft-authentication-library-for-android#1094]
**Describe the bug**
I have set Conditional Access Policies on the Azure Portal Intune settings for [the sample app](https://github.com/Azure-Samples/ms-identity-android-kotlin/), but it seems to be ignored and I can sign in on incompliant devices.
I reported the same issue [here](https://github.com/Azure-Samples/ms-identity-android-kotlin/issues/15), but this may be an issue of library.

**Smartphone (please complete the following information):**
 - Android Version: 10(API 29)
 - MSAL Version: 1.0.+

**To Reproduce**
1. Sign in your Azure Portal on PC.
2. Select "Intune".
3. Select "Conditional Access".
4. Create New policy with some settings.
- "Users and groups" to "All users".
- "Cloud apps or actions" to "Select apps" including "Azure Samples - Android".
- "Conditions" - "Device platforms" to "Any device".
- "Grant" to "Grant access" with "Require device to be marked as compliant" checked.
- "Enable policy" to "On"
5. Set Device compliance policy.
- Add Compliance setting: e.g."Require a password to unlock mobile devices."
- Set action "Mark device noncompliant" to "Immediately"
Set Conditional Access on the Azure Portal Intune 

After the above set, on the device where Intune is not installed, launch Azure Samples app, press "SIGN IN",  enter your Azure account and password.
-> Sign-in is not blocked.

If "Cloud apps or actions" is set to "All cloud apps", Sign-in is blocked.

**Expected behavior**
Sign-in should be blocked on the incompliant device.

**Actual Behavior**
Sign-in is not blocked.

**Comment by rpdome** [comment]
Hi @da351hon ,

1. Could you please reproduce the issue and send logs?
   - Do you have Intune Company Portal or Microsoft Authenticator installed? If so, can you please upload logs from those apps and paste the incident IDs here?
   - Can you also provide MSAL logs? By default, it should at least 

2. By "Sign-in is not blocked", do you mean that the sample app succesfully got a token back?

**Comment by da351hon** [comment]
@rpdome 

> 1. Could you please reproduce the issue and send logs?

I enabled MSAL logging and captured logs. Please check the attached log.txt.
[log.txt](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/4915559/log.txt)

> Do you have Intune Company Portal or Microsoft Authenticator installed? If so, can you please upload logs from those apps and paste the incident IDs here?

No, I have not installed any of them. 

> By "Sign-in is not blocked", do you mean that the sample app succesfully got a token back?

Yes, the sample app seems to get a token and user information via Graph API (/me).

**Comment by rpdome** [comment]
Hi @da351hon,

I just got an access to a premium tenant and tried to reproduce the steps above, and was stumbled upon this step.

>> "Cloud apps or actions" to "Select apps" including "Azure Samples - Android".

This "Cloud apps" seems to refer to the application you're trying to get an access **_to_**. For example, if your mobile app is trying to access to GitHub (Step 6 in [this link](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/add-application-portal)), then you can set a CA to block token request for GitHub access. 

May I ask how did you add "Azure Samples - Android" into the cloud apps list? and what are the configuration for the app?

Thanks,
Dome

**Comment by da351hon** [comment]
I'm not sure, but maybe it was added because I ran the [sample app](https://github.com/Azure-Samples/ms-identity-android-kotlin/) on Android Studio and logged in before setting up Conditional Access.

<img width="1229" alt="スクリーンショット 2020-07-15 8 01 26" src="https://user-images.githubusercontent.com/26163353/87484573-7b45d680-c671-11ea-9d1d-91c8a0e55fb9.png">

**Comment by da351hon** [comment]
Hi @rpdome,
Could you run the [sample app](https://github.com/Azure-Samples/ms-identity-android-kotlin/) on Android Studio?

**Comment by rpdome** [comment]
@da351hon  I'll reach out to the Microsoft Intune team and will get back to you.

**Comment by rpdome** [comment]
Sorry for the delayed response. Here's the response from the team.

"When the customer creates a CA policy that applies to app X, they are saying that when another app will acquire a token **_for_** app X, then enforce this CA policy. That is not what it is happening when app X is acquiring a token for MS Graph."

In other words, the reason that you're blocked when "All Cloud apps" is selected is because MS Graph itself is blocked - not AzureSample

Thanks,
Dome

**Comment by da351hon** [comment]
Thanks,
I have confirmed that CA policy can be enabled by adding the custom scope for the app.

**Comment by OmarHassan25** [comment]
> Thanks, I have confirmed that CA policy can be enabled by adding the custom scope for the app.

Could you please show a sample for the custom scopes which enable CA policy?
