### ISSUE TITLE
B2C token validation by msal libraby

### ISSUE THREAD

**Issue by rajesh-naik-by** [AzureAD/microsoft-authentication-library-for-android#1095]
**Is your feature request related to a problem? Please describe.**
I have a generic question about token validation from msal library for js, does msal library takes care of validating below attributes from the token? or is it a responsibility of consumer to validate the token?

- Signature
- exp
- nbf
- iss
- aud

**Describe the solution you'd like**
I would like msal library to validate the token.

**Describe alternatives you've considered**
I have asked our application teams to validate their token at their end using RSA/jwt libraries.

**Comment by rpdome** [comment]
It looks like you've already posted an issue in the MSAL js GitHub page, so I'll be closing this issue.
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1952

May I ask for more details on what scenario you're trying to achieve?

**Comment by rajesh-naik-by** [comment]
I logged the other issue for `js` and this particular one was for android library.
