### ISSUE TITLE
Certificate Pinning issue in MSAL library 

### ISSUE THREAD

**Issue by pravinsk21** [AzureAD/microsoft-authentication-library-for-android#1099]
Hi Team, 

please help out on below issues,

1) Not able to do certificate pinning on MSAL library using Network Security Configuration file for API 24 and above.
   I have used below link for reference. 
   link : https://developer.android.com/training/articles/security-config

   here is code : 

network-security-config>
domain-config>
domain includeSubdomains="true">example.com </domain>
trust-anchors>
certificates src="@raw/certificateFile”/>
   /trust-anchors>
/domain-config>
/network-security-config>

AndroidManifest.xml 

manifest ... >
application android:networkSecurityConfig="@xml/network_security_config"
                    ... >
/application>
/manifest>
 
getting below error as : 
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

2) How to do certificate pinning to MSAL library for Android API level below 24 ?

please help out. Thanks.

**Comment by shoatman** [comment]
I don't think we test with certificate pinning configured.  Let me see what I can find out for you.

**Comment by pravinsk21** [comment]
@shoatman Thanks. it will be great help if you can share SHA256 pin along with backup pin and certificate pinning steps.
