### ISSUE TITLE
ADFS Certificate Based Authentication support in MSAL

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1116]
Currently to achieve ADFS Certificate Based Authentication, we are  modifying the source code of MSAL and doing some specific change in the MSAL library.  For reference, changes are in AuthChallengeHandler (Class name: ClientCertAuthChallengeHandler) uses the certificate and password of our own.
 
It will be helpful, if MSAL library could expose method to the client that accepts the certificate and the password or expose the interface to the client, we can have our logic without modifying the source code of MSAL.

Please suggest better way of handling ADFS Certificate based authentication here, without modifying the source code of MSAL.

The above case is with Webview approach.

**Comment by AdamBJohnsonx** [comment]
Typically, this certificate comes out of the android KeyChain object.  Can you give me a few more details about the change that you had to make, because it seems like it should have been unnecessary?  Is there some reason that you cannot use the android KeyChain to store the certificate?

**Comment by vramasam** [comment]
hello @AdamBJohnsonx 

Putting the certificate in Android Key Chain means any app on the device can use it for authentication. Our app establishes a container on the device, and only apps allowed by admin are part of that container. 

So the goal here is to only allow only these container apps to use this certificate for authentication. The way we achieve this is by storing by certificate within our app's sandbox and not in the KeyChain. So to support this kind of use-case it'll be helpful if there is some interface exposed by the MSAL library itself.

**Comment by vramasam** [comment]
hello @AdamBJohnsonx 

I have another question here, in case if we want to use  "Microsoft Authenticator" app, if we make the user certificate available in the android key chain, will "Microsoft Authenticator" app will pick the certificate and make ADFS certificate based make it work. 

Can you please confirm above workflow works?
