### ISSUE TITLE
ISinglePublicClientApplication#signInAgain() allowing different users

### ISSUE THREAD

**Issue by 4gus71n** [AzureAD/microsoft-authentication-library-for-android#1117]
Hi :wave:!

Sorry, just a quick and easy question, should the `ISinglePublicClientApplication#signInAgain()` function allow signing in with a different user than the one that's currently using?

Because of a product requirement, I need to re-authenticate the current user at X amount of time, one of the options for doing this is using the MSAL credentials. Now, something that I don't want to happen is that the user signs in with a different user, I thought that because the `ISinglePublicClientApplication` instance is for single accounts, re-authenticating the user through the `signInAgain()` function would trigger some sort of exception if I try to sign in with a different user?

Is this the correct behavior? Is there any way to prevent the user from authenticating using a different account?

Thanks!

**Comment by iambmelt** [comment]
Hi @4gus71n 

Please see [this answer](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1029#issuecomment-622489766) and the one immediately following it [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1029#issuecomment-622570468).

I believe these two previous comments will together answer your question. Please reopen this issue if it does not; thanks!

**Comment by 4gus71n** [comment]
Hi @iambmelt 👋 !

Thanks for the quick response 🙇 ! Sorry, maybe I didn't explain myself very well, let me give you a more detail example of what's going on.

So, on my app, you can authenticate yourself through MSAL using the `PublicClientApp#signIn()` function, all that works perfectly. Now, I have this new requirement where every X amount of time the user needs to verify his identity, one way of doing this is by using his MSAL credentials.

Let's say that I get the user `johnsomething/123qweasd` into the app, then he sends the app to the background, X amount of minutes pass by, he gets back into the app and he's prompt with this screen to verify his identity. He chooses to verify his identity through MSAL, but instead of using his `johnsomething/123qweasd` credentials, he goes with `petersomething/abcdef`. _This is an error, and this is something that I want to handle from my side. I want to prevent the user from authenticating with credentials different from the originals_.

I checked those answers that you shared but they didn't work. Let me tell you what I've tried so far:

Using the `acquireToken`
```
// I use the ISinglePublicClientApplication#getCurrentAccountAsync() to fetch the current account
singlePublicClientApp.acquireToken(
                                    AcquireTokenParameters.Builder()
                                            .withScopes(myScope)
                                            .startAuthorizationFromActivity(myActivity)
                                            .fromAuthority(myAuthorityURL)
                                            .forAccount(myAccount) // The current account that I just fetched
                                            .withCallback(callback)
                                            .build()
                                )
```
What happens above is that I get the WebView with my MSAL login page, the username gets autocomplete with the current account's email, but if I delete that, put any other credentials, and sign in, I can go through without a problem. What I want to happen in this scenario is that the MSAL library triggers some kind of error, because I'm signing in with credentials different from the ones of `myAccount`.

I also tried with the `ISinglePublicClientApplication#signInAgain()` but I get the same result.

I just want to know if it's possible to - through the MSAL API - prevent the user from signing in with different credentials. I'm a bit confused because the source code states that:
![image](https://user-images.githubusercontent.com/2055468/89072453-fc2def00-d34e-11ea-9896-5b05c9f69a27.png)
In the `TokenParameters` class, so I thought that this was something doable.

Thanks again for the quick response 🙇  I really appreciate how you guys are so prompt to answer any questions!

**Comment by iambmelt** [comment]
@4gus71n I believe the below gif captures the behavior you are describing; in this demo the account name cannot be changed.

To get this behavior, I used the following code in my local sample:
```java
mSingleAccountApp.signInAgain(getActivity(), getScopes(), Prompt.LOGIN, authCallback);
```

![disallow_name_change](https://user-images.githubusercontent.com/990063/89074621-81a2a680-d331-11ea-8134-b9d42ecd6008.gif)

**Comment by 4gus71n** [comment]
@iambmelt Awesomeee! 🎉  Thanks a lot! I'll try that 💪 and let you know if I find anything else, but I'm sure that'll do the trick! Thanks again! 🙇

**Comment by iambmelt** [comment]
@4gus71n Great! I'll keep an eye out for this thread in case you run into any issues.

And thanks for using MSAL, we're happy to have you!
