### ISSUE TITLE
How to get Refresh Token or "Code" for refresh token

### ISSUE THREAD

**Issue by eugenSt20** [AzureAD/microsoft-authentication-library-for-android#1120]
How i can get "code" for refresh token?
https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow#1-get-an-authorization-code

Or maybe i can get refresh token for:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow#4-refresh-the-token 

I used: 
 implementation 'com.microsoft.identity.client:msal:1.5.2'

**Comment by iambmelt** [comment]
Documentation on how to use this library is available in
- Our [ReadMe](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/README.md)
- Our [quickstart guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-android)
- Our [sample application](https://github.com/Azure-Samples/ms-identity-android-java#b2cmodefragment-class)
