### ISSUE TITLE
"prompt" parameter not set correctly during authentication

### ISSUE THREAD

**Issue by koesclem** [AzureAD/microsoft-authentication-library-for-android#1122]
The MSAL for Android allows to provide a `Prompt` parameter during interactive token requests by using `SingleAccountPublicClientApplication.signIn` or by providing `AcquireTokenParameters`. Possible `Prompt` parameters are: `[SELECT_ACCOUNT, LOGIN, CONSENT, WHEN_REQUIRED]`. As per documentation of the MSAL for Android's code those should map to their OIDC specification counterparts: `[select_account, login, consent, none]`.

Of those mentioned prompt parameters, all seem to work as expected, except for the `WHEN_REQUIRED` `Prompt`. The javadoc states the following:

```
/**
 * acquireToken will not send the prompt parameter to the authorize endpoint.  The user may be prompted to login or to consent as required by the request.
 */
```

After a `Prompt` `WHEN_REQUIRED` is supplied it is later overridden by the MSAL when creating the `InteractiveTokenCommandParameters` in the `CommandParametersAdapter.createInteractiveTokenCommandParameters` method using the following code segment:

```
private static OpenIdConnectPromptParameter getPromptParameter(@NonNull final AcquireTokenParameters parameters) {
    if (parameters.getPrompt() == null || parameters.getPrompt() == Prompt.WHEN_REQUIRED) {
        return OpenIdConnectPromptParameter.SELECT_ACCOUNT;
    } else {
        return parameters.getPrompt().toOpenIdConnectPromptParameter();
    }
}
```

It seems there is no option to provide the OIDC specification's `prompt=none` parameter and therefore there is no way of performing an authentication without the need for the user to input their credentials during login, even though there might be a valid session provided by the browser. You can also observe the set `prompt` parameter by inspecting the resulting authentication url opened in the Browser/CustomTab. 

In fact, even when fixing the above code segment the `Prompt.toOpenIdConnectPromptParameter()` method never results in an `OpenIdConnectPromptParameter.NONE` parameter since it seems to not support a `Prompt.WHEN_REQUIRED`.

MSAL Version: 1.6.0

**Comment by kreedula** [comment]
Thank you for reporting this.  I have added a backlog item to fix or infact see if we can add support for `prompt = none`

**Comment by tanmaymanolkar1** [comment]
@koesclem the implicit flow is not supported in MSAL, hence the OpenIdConnectPromptParameter.NONE is not included. Hence some prompt value is always passed in this case whether the value in the Android code is null or WHEN_REQUIRED.

**Comment by tanmaymanolkar1** [comment]
@koesclem the implicit flow is not currently supported by Library. Are there any specific scenarios where you would want to use the following

>  It seems there is no option to provide the OIDC specification's prompt=none parameter and therefore there is no way of performing an authentication without the need for the user to input their credentials during login, even though there might be a valid session provided by the browser.

As for the WHEN_REQUIRED, thank you bringing it to our attention we will be shipping the fix in the upcoming library version update.

**Comment by koesclem** [comment]
@tanmaymanolkar1 I am aware, that the Implicit Flow is not currently supported by the MSAL for Android, as this is also not the recommended authentication flow for mobile applications.
What I am using, is the Authorization Code Flow, therefore expecting of receiving an Authorization Code which will later be used to request an ID Token and an Access Token at the Token Endpoint. As per the OIDC specification the mentioned `prompt=none` parameter is a valid parameter during the initial Authentication Request in the Authorization Code Flow. So this report is not in any way tied to an Implicit Flow.

As to your question regarding the scenario: The goal is that if users already performed authentication on the web (browser cookies available), users do not have to input their credentials again when authenticating via the mobile application by using the `prompt=none` in the Authentication Request. I would also like to mention, that the `prompt=none` or a complete absence of the prompt parameter is already supported by the iOS Version of the MSAL. This is purely an issue of the MSAL for Android, meaning the described scenario works as expected for the iOS Version.

A final note regarding your commit: https://github.com/AzureAD/microsoft-authentication-library-for-android/commit/de5f77a7fb257d9af62819f45308a20d9ff12de3
I noticed that if the prompt paramter is not set in the `AcquireTokenParameters` this still defaults to `OpenIdConnectPromptParameter.SELECT_ACCOUNT`. Is there a specific reason for this? Since my understanding of the prompt values was, that not setting the `prompt` parameter at all and setting the `prompt` parameter to `none` should be treated equally.

**Comment by tanmaymanolkar1** [comment]
@koesclem yes we have taken a note of the null prompt value, and as of now the prompt value as null and NONE behave differently. In the near future we are planning to make them similar in implementation. As of the next release , the value OpenIdConnectPromptParameter.UNSET would work in a way where no prompt parameter will be injected into the request, and the release will also include a fix for the Prompt.WHEN_REQUIRED  functionality.

**Comment by tanmaymanolkar1** [comment]
Closing this issue, since fix has been rolled out.
the following library versions have the fix
The Msal version : 2.0.1
The common version : 3.0.2
