### ISSUE TITLE
API to fetch list of users from broker

### ISSUE THREAD

**Issue by vinagpur** [AzureAD/microsoft-authentication-library-for-android#1127]
We are migrating ADAL to MSAL

With ADAL, we were able to get broker users with below API

```
AuthenticationContext mAuthContext = new AuthenticationContext(mAppContext, Const.AUTHORITY, false);
final UserInfo[] users = mAuthContext.getBrokerUsers();
```

Do we have any similar API in MSAL? 

I tried below options but they all are returning empty response.

1. ISingleAccountPublicClientApplication.getCurrentAccount()
2. BrokerMsalController.getAccounts()

**Use case:**

- In _work profile_, our app is being pushed by the broker which is 'Company Portal Intune' Meaning the user is already signed in into Intune and the account data is available on device.

- We want trigger a silent authentication by fetching user account from broker and verify it. The advantage of this approach is we want to avoid showing UI because it is not necessary.

Note: Currently, we support single account only.

**Smartphone (please complete the following information):**

Device: All devices
Android Version: All version
Browser All tested browsers
MSAL Version 1.5.+

**Comment by iambmelt** [comment]
Unless you are sure there will only be _one_ account in the broker, you may want to consider using a `MultipleAccountPublicClientApplication`. Apps which are integrated with the broker may have multiple accounts available to authenticate with, Single Account Mode will return the _first_ account, though this may not be the behavior you're trying to achieve.

In MSAL, calling [`getAccounts()`](https://javadoc.io/doc/com.microsoft.identity.client/msal/1.5.5/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.html#getAccounts--) will return the list of available accounts both locally _and_ in the broker. It will return every account available to your application.

Please note that _unlike_ ADAL, only accounts which have _consented_ to use your application will be returned. If your application is part of the ['Family of Client IDs' (Microsoft Corpnet Access Reqd)](https://identitydocs.azurewebsites.net/static/v2/foci.html) you will be returned accounts which have previously authenticated with another FoCI app. If your application is not FoCI, you will need to initiate an interactive authentication call via `acquireToken()` prior to having access to any accounts stored in broker.

Regarding `BrokerMsalController`; note this class is part of the `internal` package space --  it is not intended to instantiated or used directly by consumers of this library.

I'll leave this issue open, as I expect there may be follow-up questions.

Tagging @rpdome as FYI ^^

**Comment by iambmelt** [comment]
Closing, as there is a StackOverflow issue where this question was asked. Answered there too.

**Comment by vinagpur** [comment]
Hi @iambmelt we are FoCI now. Interestingly, We are able to getAccounts() in personal mode. However, work profile is still giving null value. I am signed-in into 'Company Portal' of work profile so that we can fetch the account details from it. The same setup is working in personal mode. Do we need anything specific for work profile for SSO?

**Comment by iambmelt** [comment]
> Hi @iambmelt we are FoCI now. Interestingly, We are able to getAccounts() in personal mode. However, work profile is still giving null value. I am signed-in into 'Company Portal' of work profile so that we can fetch the account details from it. The same setup is working in personal mode. Do we need anything specific for work profile for SSO?

@vinagpur Please reach out to `androididentity` with this question
