### ISSUE TITLE
report legacy MSAL redirect uri more prominently and descriptively

### ISSUE THREAD

**Issue by clockworkant** [AzureAD/microsoft-authentication-library-for-android#1128]
I spent quite a few hours getting frustrated as to why the broker (MS Authenticator) wasn't being called. Everything looked fine in the configuration and the manifest, however it turned out that the redirect uri was incorrect. I had to debug the library to discover the following information in a comment. It's very frustrating as i was seeing the mUseBroker value being toggled to false even when i'd explictly set it to try in the configure file

PublicClientApplicationConfiguration.java line 554
`
if (!isBrokerRedirectUri()) {
            // This means that the app is still using the legacy local-only MSAL Redirect uri (already removed from the new portal).
            // If this is the case, we can assume that the user doesn't need Broker support.
            Logger.info(TAG, "The app is still using legacy MSAL redirect uri. Switch to MSAL local auth.");
            mUseBroker = false;
            return;
        }
`
I want some logging in the logcat that says that the broker can't be used. Maybe output the expected value for the redirectUri as well so it can be used to update the configs. The current log message is far too vague!!

**Comment by shoatman** [comment]
Adam made the message a warning here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1130

We also added a helper method for getting the expected values for the broker:

https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1111

Sorry for the frustrating experience!

**Comment by clockworkant** [comment]
Thanks for the quick turn around on this issue. 🙏

Sorry to be a pain but is it possible to highlight in the warning that the broker is being turned off when in legacy mode. Currently that piece of information is somewhat hidden as a comment in the code above the warning message:
`// If this is the case, we can assume that the user doesn't need Broker support.`

It was a real shock to me that the method `checkIntentFilterAddedToAppManifestForBrokerFlow()` that contains this had the side effect of changing the value for `mUseBroker` to false. This is why I would like it highlighted in the warning message so future developers don't have to read the sourcecode to see this side effect.
