### ISSUE TITLE
az ad app update in azure cli version 2.10.1 not working and getting error "Updates to converged applications are not allowed in this version."

### ISSUE THREAD

**Issue by yshkrishna** [AzureAD/microsoft-authentication-library-for-android#1136]
**Describe the bug**
When I am trying to update app roles in a registered app with Azure CLI it is trowing errors

 az ad app update --id e7d43612-c5fe-4c9e-b2c1-b355580077e5 --app-roles @C:\Users\v-sryala\Desktop\Appman.json                                                  Updates to converged applications are not allowed in this version.

Also ,I believe it is an existing issue by reference to  https://github.com/Azure/azure-cli/issues/7772

**Comment by iambmelt** [comment]
@yshkrishna This is not the correct bug tracker for this issue; this tracker is for Android MSAL issues
