### ISSUE TITLE
MSAL Client Exception: The redirect URI in the configuration file doesn't match 

### ISSUE THREAD

**Issue by prbiSeva** [AzureAD/microsoft-authentication-library-for-android#1146]
I have to integrate Microsoft authentication API for login in the android app. for that I registered my app to the Azure portal, by providing a package name and Signature hash. Signature hash is generated using this command
keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%.android\debug.keystore | openssl sha1 -binary | openssl base64

on app run, I'm getting this exception MsalClient Exception: The redirect URI does not match with the package name and signature hash. but both the package name and signature hash is the same at android and Azure. im following this tutorial 

https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android

**Smartphone (please complete the following information):**
 - Device:  Pixel XL emulator
 - Android Version: 9.0
 - MSAL Version 1.6.0

Logcat
com.microsoft.identity.client.exception.MsalClientException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.

**Comment by bondenn** [comment]
The command from the Azure portal doesn't seem to work, if you run signingReport in gradle and get the SHA1 hex value, then convert that to Base64 it will work (make sure to remove the ":" characters before converting). Also don't forget to urlencode the one that goes in the .json configuration :)

**Comment by anandlingaraj** [comment]
add below to MSAL Config file under raw

"broker_redirect_uri_registered": false,

**Comment by iambmelt** [comment]
@prbiSeva Please take a look at the troubleshooting API introduced in https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1111 -- it should help you debug where the mismatched URL value is.

**Comment by Pravin-shelke** [comment]
MsalClientException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.We expected 

same auth file and same manifest run in demo project but on actual project getting this kind of Exception
