### ISSUE TITLE
App Protection Conditional Access and MSAL

### ISSUE THREAD

**Issue by Innova133** [AzureAD/microsoft-authentication-library-for-android#1149]
**Describe the bug**
We have an application that we are developing that uses Intune and MSAL.  It has a  App Protection with Conditional Access.

**Smartphone (please complete the following information):**
 - Device:  Various
 - Android Version: Various
 - Browser Chrome
 - MSAL Version: 1.6.0

**Stacktrace**
There is no stacktrace, but after logging the user, we get an exception telling us remediation is needed:

2020-09-03 07:41:16.221 2615-2615/? E/IntuneActivity$c: Authentication failed: com.microsoft.identity.client.exception.MsalServiceException: AADSTS53005: Application needs to enforce Intune protection policies.

**To Reproduce**
Have a user log in using MSAL 1.6.0, and Intune 7.0.0, with Contitional Access set.

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
We expect an exception to be thrown after authentication, but the exception type should be: MsalIntuneAppProtectionPolicyRequiredException so that we can query the upn, aadid, tenant id and authority.

**Actual Behavior**
The exception is a MsalServiceException which doesn't contain the information needed to call MAMComplianceManager.remediateCompliance()

**Comment by rpdome** [comment]
Hi @Innova133,

May I ask which version of Company Portal/Authenticator is installed on the device? Can I also ask you to upload logs from those apps and provide incident IDs here?

Thanks,
Dome

**Comment by Innova133** [comment]
Company Portal: 5.0.4897.0
Authenticator: 6.2009.5879 (on a different device).

We have changed out Conditional Access settings, and are no longer pursuing this configuration.   You can close this ticket if you would like, and we will open a new one if we need to in the future.
