### ISSUE TITLE
SSO in Android Work Profile gives null value for getCurrentAccount()

### ISSUE THREAD

**Issue by nishidoshi** [AzureAD/microsoft-authentication-library-for-android#1151]
Hey,

We are working on an android project and our Client ID has been added to FoCI. 

We are able to run `ISingleAccountApplication.getCurrentAccount()` in personal profile on android device. We can see the details of the account with which we are logged in Company Portal.

However, the same piece of code returns a null value in Work Profile. We have company portal installed and logged in in work profile.

Are there more checks required for running the API in work profile? 

Side note : We are working with 1.5.4 version and testing on One Plus 7T pro device with Android version 10.

Thanks in advance!

**Comment by rpdome** [comment]
Hi @nishidoshi 

May I ask what is the exact scenario here - step-by-step?

Thanks,
Dome

**Comment by nishidoshi** [comment]
Hey @rpdome ,

Following are the steps :
1. I am in work profile on Android device.
2. I am also logged into Intune using a AAD account.
3. On my application which uses MSAL, I want SSO to exist. [Our client ID is part of FoCI]
4. When I call getCurrentAccount() api in work profile i dont see any accounts, that is the value of current account is null.

The same steps when performed on personal profile of Android device provide me values for current account.

Are there more steps that I need to perform in work profile to enable for SSO with MSAL?

Thanks!

**Comment by rpdome** [comment]
Hi @nishidoshi 

Thanks for the reply, but if you can go into more details (i.e. exact instruction that I can reproduce on my end for **both** scenarios. How do you create work profile - is it via 3rd party MDM or is it via intune, what is done first and what is done after, etc), it would really help.

Also, would you mind installing Outlook on your work profile, sign in with your AAD account and see if the account is showing up on your app? 

Thanks,
Dome

**Comment by nishidoshi** [comment]
Hey @rpdome,

Work profile can be set using Test DPC application : playstore [link](https://play.google.com/store/apps/details?id=com.afwsamples.testdpc&hl=en_IN). After installation, set it up and your android device will have work profile. In work profile playstore we download company portal, outlook and teams. We log into those apps with our account. Then install our app and try SSO.

I have tested with Company Portal, Outlook and Teams logged in Work Profile. I am still getting null values for getCurrentAccount(). 

The same API in personal profile provides me the account name, id token values.

Thanks!

**Comment by nishidoshi** [comment]
Hey @rpdome ,

Any updates on the issue raised?

Thanks.

**Comment by rpdome** [comment]
Hi @nishidoshi 

sorry for the delay, would you mind reproing the issue from scratch, upload logs from company portal and send me an incident id?

Thanks.

**Comment by nishidoshi** [comment]
Hey @rpdome ,

I have sent the logs via company portal with the message that "I am unable to implement SSO with MSAL in work profile" from Company Portal. Please look at the issue and let me know what all things are required as an addition to enable SSO in work profile.

Thanks.

**Comment by rpdome** [comment]
Hi @nishidoshi,

I'll still need an incident ID. our log system doesn't support look up via messages.

Thanks,
Dome

**Comment by nishidoshi** [comment]
Hey @rpdome ,

Can you tell me how at client end I can find the incident id? Or do I have to raise ticket or something?

Thanks.

**Comment by rpdome** [comment]
After you uploaded the logs, an incident id (a 8 character string) should be displayed.

**Comment by nishidoshi** [comment]
Hey @rpdome ,

I have uploaded the logs. The incident Id is FPVZ73QW.

Thanks.

**Comment by rpdome** [comment]
Synced offline. The issue seems to be resolved after updating to 2.0.1
