### ISSUE TITLE
Current proguard rule is keeping way too much library code

### ISSUE THREAD

**Issue by atulgpt** [AzureAD/microsoft-authentication-library-for-android#1157]
**Describe the bug**
This library Proguard file has -**keep class com.microsoft.\*\* \{ \*; \}** which keeps all the files inside that package which is very inefficient.

**Smartphone (please complete the following information):**
 - Device: Not Device specific but proguard rule specific
 - Android Version: NA
 - Browser NA
 - MSAL Version 2.0.0

**To Reproduce**
-  Add the 1. implementation 'com.microsoft.graph:microsoft-graph:2.2.+' and 2. implementation 'com.microsoft.identity.client:msal:1.5.+' 
- Turn on the R8/ProGuard in gradle file, compile the code with the libraries dependencies but without actually using any code from the library.
- Generate the APK(for the variant where proguard is enabled)
- Notice the size(generated APK should be around 3.3 MB)
- Now remove the implementation 'com.microsoft.identity.client:msal:1.5.+' dependency from the gradle file(now new APK size will be 1.6 MB round **51% size** reduction)

**Expected behavior**
When we are not using any code from these libraries then added size due to libs should be close to 0

**Actual Behavior**
It adds around 1.7 MB of size as it's keeping all its file and code under a way too general keep the rule

**Additional context**
While in Android, this library is supposed to be used with [MS-Graph-Java lib](https://github.com/microsoftgraph/msgraph-sdk-java) which clearly states that their library should be used with proper proguard configuration otherwise resulting APK will be bloated with unnecessary code([Link to ReadMe](https://github.com/microsoftgraph/msgraph-sdk-java#13-enable-proguard-android)) while this library doesn't support proper proguard rules and due to wrong(or way too general proguard rule also keeping the files from the Graph library) and hence increasing the size

See the corresponding issue in MS-Graph-Java lib: https://github.com/microsoftgraph/msgraph-sdk-java/issues/462

**Comment by baywet** [comment]
added #1161
