### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by icc-romeu** [AzureAD/microsoft-authentication-library-for-android#1165]
**Is your feature request related to a problem? Please describe.**
The MSAL Library relies on the JSON configuration file for the authentication url. I do not see anyway of dynamically change that as the MSAL library needs that file to be there and the information cannot be passed as a variable. Therefore, any need to change that configuration involves updating the App.

**Describe the solution you'd like**
Passing the configuration in a dynamic way to MSAL.

**Describe alternatives you've considered**
Blocking the users and preventing they use the App until they update, but obviously that has an impact.

**Comment by iambmelt** [comment]
Assigning feature request to you, @hamiltonha
