### ISSUE TITLE
"Forgot password" is not returning an error to initiate reset password flow with `IMultipleAccountPublicClientApplication` 

### ISSUE THREAD

**Issue by leggomymeggos** [AzureAD/microsoft-authentication-library-for-android#1170]
**Describe the bug**
We're changing our integration from using `ISingleAccountPublicClientApplication` to `IMultipleAccountPublicClientApplication`, since it's recommended in the docs when integrating with B2C and might help us with implementing Edit Profile functionality. However, when we made the change, "Forgot Password" started returning a cancellation error instead of the reset password error

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - Android Version: API 29
  - MSAL Version: 2.0.1

**To Reproduce**
Using `IMultipleAccountPublicClientApplication`
- Launch sign in flow
- Click "forgot password"

**Expected behavior**
The app receives a reset password error (through `AuthenticationCallback::onError`) and can launch the reset password flow

**Actual Behavior**
The app receives a cancellation through `AuthenticationCallback::onCancel`

**Comment by hfrank-abi** [comment]
We are having the same problem and it is preventing us from upgrading to this MSAL version.

**Comment by AdamBJohnsonx** [comment]
To be clear, I think you mean the "forgot password" link of the first screen, along with the sign-in button.  Is that correct?  If I supply an account and click the "forgot password" link at the password prompt, I'm prompted for a text messaging experience.

I just tried this on the current MSAL (2.0.4) and did see the result land in the OnError method.  I'm going to try downgrading to 2.0.1 to see if it repros there, but it might be worth trying out the newer version.  I am also using an MSA b2c account, and wanted to make sure that was your b2c provider.

**Comment by xyzwilliamxyz** [comment]
I tested this the other day using MSAL code from 'dev' branch and it was working. Is the fix  for this in any release? Do we have change logs?

**Comment by iambmelt** [comment]
@xyzwilliamxyz MSAL 2.0.4 is now available on [Maven Central](https://search.maven.org/artifact/com.microsoft.identity.client/msal/2.0.4/aar) -- feel free to try this bits out and let us know if it resolves (or does not resolve) your issue. Thanks!

**Comment by xyzwilliamxyz** [comment]
@iambmelt I tested on 2.0.4 and it's ok now :+1:

**Comment by iambmelt** [comment]
> @iambmelt I tested on 2.0.4 and it's ok now 👍

@xyzwilliamxyz Thrilled to hear it, thanks for closing the loop!

**Comment by leonardochiaranda** [comment]
@iambmelt the issue started occuring again in the latest app version. I believe we'll unfortunately need to reopen the ticket. Please check the image below with the occurrences being thrown for us.

![image](https://user-images.githubusercontent.com/75698143/101535849-fb017400-3977-11eb-871f-fe3d34b0585b.png)

**Comment by iambmelt** [comment]
Reopening this issue to investigate, as some customers report working and others report non-working.

Setting owner to myself, as I can pick up this investigation

**Comment by leonardochiaranda** [comment]
@iambmelt I apologize, but we've mistakenly asked for the ticket to be reopened. This can be closed for now.

**Comment by iambmelt** [comment]
> @iambmelt I apologize, but we've mistakenly asked for the ticket to be reopened. This can be closed for now.

No worries at all, @leonardochiaranda - thanks!
