### ISSUE TITLE
"BROWSER" user agent not honored in Android 11 

### ISSUE THREAD

**Issue by leggomymeggos** [AzureAD/microsoft-authentication-library-for-android#1173]
**Describe the bug**
In Android 11, a token request launched with the browser configuration will open in a webview. Android 11 updated the way Chrome Custom Tabs are launched: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - Android Version: API 30
 - Browser: Chrome
 - MSAL Version: 2.0.1

**To Reproduce**
- Initiate a token request with an MSAL application configured to launch in a browser

**Expected behavior**
The screen appears in a Chrome Custom Tab

**Actual Behavior**
The screen appears in a Webview

**Additional context**
Android 11 updated the way Chrome Custom Tabs are launched: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11

**Comment by shahzaibj** [comment]
@leggomymeggos Thanks for reporting the issue. I was able to reproduce it on my end as well and I've opened up a PR to fix it here: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1083

This will go out in the next MSAL release. We don't currently have an MSAL released planned for this month, so if you need a fix in the meantime, you can apply these changes directly to your `AndroidManifest` file and it should work. The changes are these: https://developers.google.com/web/updates/2020/07/custom-tabs-android-11#detecting_browsers_that_support_custom_tabs (and I made the same changes in my PR as well)

Thanks!
