### ISSUE TITLE
No available browser installed on the device when having Chrome & Chrome Beta installed

### ISSUE THREAD

**Issue by wondering639** [AzureAD/microsoft-authentication-library-for-android#1187]
**Describe the bug**
`E/BrowserSelector:  [..] No available browser installed on the device. Android 30`

**Smartphone (please complete the following information):**
 - Device: Pixel 2
 - Android Version: API 30
 - Browser: Chrome / Chrome Beta
 - MSAL Version 2.01

**Stacktrace**
n/a

**To Reproduce**
In addition to Chrome stable install Chrome beta, set it as default browser (maybe not required,  not sure).
Now no browser won't be found anymore. Uninstall Chrome Beta and everythings works fine.
Note that the query fix for Android API level 30 was applied in the Manifest, I'd like to stress that Chrome stable is found, so the fix was applied correctly. Guess this isn't an Android API level 30 issue, but I did no more research on this.

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
Should open auth flow in Chrome beta

**Actual Behavior**
No auth flow opened

**Screenshots**
n/a

**Comment by shahzaibj** [comment]
Hi @wondering639 Thanks for detailed information on the issue. I will try with Chrome Beta on my test device and will report back to you with my findings.

**Comment by eduardothiesen** [comment]
Hi. I'm having a similar problema with the default Mi Browser. Can you guide me on how do I find the correct browser signature hash for it?

I suppose that after that I just have to add 
```
"browser_safelist": [
    {
      "browser_package_name": "com.mi.globalbrowser",
      "browser_signature_hashes": [
        "CORRECT_HASH"
      ]
    }
]
```

to my auth_config file and it will be good to go.

Thanks in advance.
