### ISSUE TITLE
Username and password resource name Android

### ISSUE THREAD

**Issue by pandey-2019** [AzureAD/microsoft-authentication-library-for-android#1198]
We, from Microsoft Defender ATP for Android are trying to make use of the pre-launch functionality provided by Google Playstore. That effort requires us to add the resource name for username and password screens that show up while ADAL authentication happens that shows a sign-in prompt

I have tried using uiautomatorviewer but that only gives the index numbers and not the resource name. Could you please let us know the resource name for these two text boxes that show up in th esign-in authentication process -

- Username (Box displaying text Email address, phone number, skype)
- Password

![image](https://user-images.githubusercontent.com/49427683/96860910-fdb81080-1480-11eb-8066-af68ef725deb.png)

![image](https://user-images.githubusercontent.com/49427683/96860947-090b3c00-1481-11eb-9a02-f422e0c02ee6.png)

We'll really appreciate if you could help us with this information

**Comment by iambmelt** [comment]
This would be a question for the AAD (ESTS) team and, if using an on-prem setup also the ADFS team.

My suggestion is to use the [EdgeHTML Developer Tools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide) to inspect the page and determine the resource id through those means. Optionally, you could also create a [WebView with debugging enabled](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews) and inspect the elements that way

**Comment by shahzaibj** [comment]
@pandey-2019 These are the resource ids:

- **Username:** `i0116`
- **Password:** `i0118`

**Comment by pandey-2019** [comment]
Thanks for your response Brian. Would you mind directing me to a contact from AAD (ESTS) team?

**Comment by iambmelt** [comment]
> @pandey-2019 These are the resource ids:
> 
> * **Username:** `i0116`
> * **Password:** `i0118`

Thanks @shahzaibj 

/cc @pandey-2019 ^^

**Comment by pandey-2019** [comment]
This is very helpful. Thanks Shahzaibj and Brian. Really appreciate it

**Comment by pandey-2019** [comment]
@shahzaibj, Could you also please help me with Android resource name for "register" button?

![image](https://user-images.githubusercontent.com/49427683/96919582-98d4d880-14c9-11eb-97d4-3a61f2de77df.png)

**Comment by nishi1612** [comment]
Hey @iambmelt  / @shahzaibj ,

I am using "i0118" as resource id and yet not able to reference edit text for the password filling.
Additional information : I am trying to sign in using MSA account. I am able to add email id in the edit text but unable to add password for the password screen.

Can you please provide the next steps for solving this?

Thanks in advance!
