### ISSUE TITLE
WebView activity should have close button

### ISSUE THREAD

**Issue by redacted-text** [AzureAD/microsoft-authentication-library-for-android#1199]
**Describe the bug**
During login flow WebView does not have any close button, which causes user to press back several times to exit auth flow.

**Smartphone (please complete the following information):**
 - Device: any
 - Android Version: any
 - Browser WebView
 - MSAL Version: 1.3.0
![image](https://user-images.githubusercontent.com/6215729/97182298-6cf97180-17ad-11eb-9de0-806f45513dc9.png)

**Comment by iambmelt** [comment]
Assigning to you, @hamiltonha - as is a feature request
