### ISSUE TITLE
Getting Error while integrating Intune with MSAL

### ISSUE THREAD

**Issue by mohit1993** [AzureAD/microsoft-authentication-library-for-android#1210]
[Microsoft.Intune.MAM.SDK.aar] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\d871bd477cb5b76005413711e2326551\Microsoft.Intune.MAM.SDK\AndroidManifest.xml:19:9-77 Error:
	Missing 'package' key attribute on element package at [Microsoft.Intune.MAM.SDK.aar] AndroidManifest.xml:19:9-77
[Microsoft.Intune.MAM.SDK.aar] C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\d871bd477cb5b76005413711e2326551\Microsoft.Intune.MAM.SDK\AndroidManifest.xml Error:
	Validation failed, exiting

Expecting a key in SDk Menifest 
<queries>
        <package android:name="com.microsoft.windowsintune.companyportal" />
    </queries>

**Comment by iambmelt** [comment]
This is not the MAM SDK's repo
