### ISSUE TITLE
Getting issue with msal:1.5.+

### ISSUE THREAD

**Issue by mohit1993** [AzureAD/microsoft-authentication-library-for-android#1211]
his project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.core:core:1.0.1, androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0

I am using  implementation 'com.android.support:appcompat-v7:28.0.0'

**Comment by iambmelt** [comment]
This looks to be an issue in your local workspace, as this project already declares this attribute here:
https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/gradle.properties#L4
