### ISSUE TITLE
I want default UI only

### ISSUE THREAD

**Issue by mohit1993** [AzureAD/microsoft-authentication-library-for-android#1215]
Please suggest changes for MS default login UI, i am currently integrating Intune sdk with MSAL from MS internal app. I want to use Login UI by default as other internal apps usese.

**Comment by iambmelt** [comment]
Please consult the documentation on Authorization Agents:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#authorization-agents
