### ISSUE TITLE
authorization_user_agent on Android 11

### ISSUE THREAD

**Issue by ChairfaceChippendale** [AzureAD/microsoft-authentication-library-for-android#1230]
**Describe the bug**
It seems that providing authorization_user_agent=BROWSER in the msal_config.json has no effect on Android 11 (targetSDK 30). It still opens on a webView. For targetSDK 29 all fine.

**Smartphone (please complete the following information):**
 - Device: Pixel 3A
 - Android Version: 11 (sdk30)
 - Browser: Chrome
 - MSAL Version: 2.0.2

Probably this causes the problem:
https://developers.google.com/web/updates/2020/07/custom-tabs-android-11

**Comment by iambmelt** [comment]
Hi @ChairfaceChippendale -- Thanks for reaching out; we recently shipped an update to correct this behavior in [`2.0.4`](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/2.0.4). Can you update to this version reopen this issue it if your behavior is not resolved? Thanks!
