### ISSUE TITLE
50058 Azure AD errors when using Android Broker

### ISSUE THREAD

**Issue by harmjonker** [AzureAD/microsoft-authentication-library-for-android#1232]
We get a lot of Azure AD Sign-in error code 50058 responses when doing silent logins from MSAL based Xamarin apps on Android.
We use brokered login with MS Authenticator. We don't expect the 50058 in most cases.  I read various explanations on internet but can this also be caused by misconfiguration or wrong use of MSAL library?

**Comment by bgavrilMS** [comment]
Transferring to MSAL Android who may be able to help with this as the logic inside the broker is owned by them. MSAL.NET calling the broker does not seem to have any issues.

**Comment by iambmelt** [comment]
Thanks for sending this issue over, @bgavrilMS 

@harmjonker This looks like a bug in our Authentication broker; thank you providing the Incident ID -- I will be following up on this issue internally and will provide any relevant updates here. Thanks

**Comment by iambmelt** [comment]
> Thanks for sending this issue over, @bgavrilMS
> 
> @harmjonker This looks like a bug in our Authentication broker; thank you providing the Incident ID -- I will be following up on this issue internally and will provide any relevant updates here. Thanks

@bgavrilMS I looked at this `rawBytes` error with @rpdome -- we were able to determine this is a red herring and is unrelated to any interruption of SSO with respect to the calling app. This error is created by the broker itself calling into authinternals, but has no impact on the binding app (the Xamarin app) in this case. That said, there is an upcoming release of MS Authenticator (likely December) where this error will be resolved. Consider this to be _unrelated_ to the issue reported by @harmjonker 

@harmjonker Similar to @bgavrilMS, I too am not seeing any logs in incident `26QPYWH4` that would indicate any failure. In fact, I'm only seeing successes for app `api://ws20servicecoach-api-p.mobile-apps.ns.nl` with an accesstoken being successfully issued based on a previous successful auth on Sept 4

![image](https://user-images.githubusercontent.com/990063/99479242-a59eed80-290a-11eb-8de8-b645f469b9eb.png)


If you can provide logs showing the failure we may be able to determine where the fault is occurring however at this juncture I don't see unexpected errors in the provided logs

**Comment by harmjonker** [comment]
OK. thanks for investigating this incident.  I have another incident ID: XSPBZNDC,   from mondaymorning 10:54 NL time. Could you have a look if there are errors in this incident?

**Comment by iambmelt** [comment]
@harmjonker Logs are not indicating any failure in the broker (feel free to reach out to me via email at `brianmel@microsoft.com` if you'd like to request a copy of the logs).

Unless your users are reporting repeated unexpected prompts more frequently than your tenant's RT validity period, my suspicion is that this AADSTS50058 error is a red herring: the error AADSTS50058 is triggered (in this case, per your above supplied screen shot) during _interactive auth_ from the following user agent
![image](https://user-images.githubusercontent.com/990063/99567275-d589d780-2982-11eb-962e-a643a646562a.png)

This user agent is MS Authenticator, however there are a number of reasons there may not be any cookie-state in the broker's webview
- If `kmsi` ('Keep Me Signed In') is not enabled, this code will trigger
- If first sign-in, this code will trigger
- If cookies were cleared or are expired, this code will trigger

In my own testing, under 1st login circumstances I can see code while performing interactive auth -- in this case, it's fully expected and indicates no fault:
`Exception mapped to interrupt error code: Microsoft.AzureAD.Telemetry.Diagnostics.ServiceException: AADSTS50058: A silent sign-in request was sent but no user is signed in.`

**Comment by bgavrilMS** [comment]
@iambmelt - I don't understand the conditions in which this exception is thrown or how MSAL or an application is supposed to handle it. Are you saying that when the app calls `AcquireTokenSilent` on MSAL, and MSAL calls AcquireTokenSilent on the broker, the broker tries to use the browser cache to login the user instead of the PRT? And that this exception occurs? 

Should MSAL translate this error into an "UiRequiredException" ?

**Comment by iambmelt** [comment]
> @iambmelt - I don't understand the conditions in which this exception is thrown or how MSAL or an application is supposed to handle it. Are you saying that when the app calls `AcquireTokenSilent` on MSAL, and MSAL calls AcquireTokenSilent on the broker, the broker tries to use the browser cache to login the user instead of the PRT? And that this exception occurs?
> 
> Should MSAL translate this error into an "UiRequiredException" ?

@bgavrilMS Sorry, I should be more precise: this 'error' isn't actually surfaced to clients: in my testing it is emitted in AAD's logs (and presumably has some ADFS equivalent). From what I can ascertain, during interactive login AAD looks for presence of existing session cookies to try and grant the user SSO: if (for any reason) an existing session cookie is not present in the request (as would be expected for a 1st-time login) this error will be emitted in AAD's logs. This doesn't necessarily indicate a failure, just AAD logging out an error that no SSO cookie was present

**Comment by harmjonker** [comment]
We have done some further analysis and what we discovered is that there is a situation where MSAL falls back to the embedded browser and does ignore Authenticator, while Authenticator is actually installed and has been found by MSAL before.
This leads to a situation where the user is required to log in again because there is no context within the app yet because it worked with the Authenticator broker before.
In that case Authenticator actually was installed on the device but the power optimization option for Authenticator was still on. After turning that off and restarting the app it did find the broker and continued without any need to login again.
This is a very undesired flow, because if the user just goes on with logging in in this situation the SSO behavior is gone.
Do you recognize this behavior and is it intended behavior ? We prefer to catch this situation and warn the user.

**Comment by harmjonker** [comment]
Is it possible to receive the logs for incident 8JAVRK4P ? We would like to check whether this incident is such a case as described above.

**Comment by iambmelt** [comment]
> Is it possible to receive the logs for incident 8JAVRK4P ? We would like to check whether this incident is such a case as described above.

Sent offline via email

**Comment by iambmelt** [comment]
@harmjonker @bgavrilMS @trwalke I'm going to go ahead and close this issue, as the Android MSAL team isn't currently investigating this item as a bug. Please reopen or `@` me if this ticket needs to be reopened.

Thanks
