### ISSUE TITLE
White screen comes up when user clicks back button on page where he has to enter credentials.

### ISSUE THREAD

**Issue by nishi1612** [AzureAD/microsoft-authentication-library-for-android#1239]
**Describe the bug**
Our app is in development stage currently. Soon we will be in production with multiple users using the app. I received auth_cancelled_by_sdk error code for MSALClientException when I tried to acquire token in interactive mode. I had deliberately chosen not to add credentials and press back button. I observed two things :
1. I get a blank white screen on one press of back button.
2. I get auth_cancelled_by_sdk error code which I couldn't find in the list of error codes for MSALClientException [Source : [link](https://javadoc.io/static/com.microsoft.identity.client/msal/2.0.1/com/microsoft/identity/client/exception/MsalClientException.html) ]

**Smartphone (please complete the following information):**
 - Device: One Plus 7T Pro
 - Android Version: 10
 - Default Browser : Chrome
 - Broker app installed 
 - MSAL Version : 2.0.1

**To Reproduce**
Mentioned in the bug above.

**Expected behavior**
White screen should not come up. On one back press I should return to my app. An error code for exception should be present in the library constants for MSALException.

**Actual Behavior**
White screen comes up on one back press.

**Comment by iambmelt** [comment]
@nishi1612 Thank you for reporting this issue -- I am interested in reproducing it locally to resolve it

Can you provide the following info/answers?
- Is the WebView, browser, or chrome custom tabs being used? Is this consistent with the value specified as your preferred authorization user agent?
- your authorization user agent, as specified in your applications configuration JSON manifest
- does this issue appear device specific? Or does it reproduce consistently across all of your devices?
- can you reproduce it with the latest version of the library? (MSAL 2.0.4)

Any additional information you might have to help me reproduce this issue would be greatly appreciated -- maybe a video or minimal repro sample?

Thanks!

**Comment by nishi1612** [comment]
Hey @iambmelt ,

Providing the answers in order :
- As mentioned earlier, I already have broker app installed hence I am getting Broker Activity for login authorization.
- Authorization agent is "DEFAULT"
- I have tested on two devices : One Plus 7T Pro and Samsung Galaxy S9 both having Android Version 10. Both the devices show this behaviour.
- Yes, I was able to reproduce the same with 2.0.4 version.

The steps for repro are quite straightforward :
1. Have broker apps installed and logged in as well.
2. When you go for `acquireToken` in your app, it shows you account picker screen.
3. Instead go for adding the credentials manually.
4. The screen to enter credentials come up.
5. Press back button and a white screen comes up.

More technical info :
- We are using `mSingleAccountApp` which supports only one account to be logged in the app.
- For interactive login, we are passing `Prompt.SELECT_ACCOUNT` [as we want account picker screen to come up if broker app is installed and if its not then `login.microsoftonlint.com` which opens in browser shows accounts with which user was previously logged in].

**Comment by iambmelt** [comment]
@nishi1612 Can you tell me which account selection screen you're seeing? Does it look like one of the below? We have both a native and an HTML based selector, which is shown depends on broker/application state. In the event you are seeing the HTML selector, can you tell me which back button you are pressing (as there are multiple, labeled by color):

**Broker Native Selector:**
<img src="https://user-images.githubusercontent.com/990063/100950493-4c65bb00-34c1-11eb-87b5-fd891f9ce2ce.jpg" width="500"/>

**HTML Selector:**
<img src="https://user-images.githubusercontent.com/990063/100950512-54255f80-34c1-11eb-9ee5-8a818d73dc68.jpg" width="500"/>

Additionally, if you have any logs you provide from your application, these would be helpful.

**Comment by iambmelt** [comment]
I will add that I was able to identify a bug in the resulting error message when using the browser (_without broker_) while investigating this issue -- the fix is proposed in https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1145

**Comment by iambmelt** [comment]
Also related issue:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1149

**Comment by iambmelt** [comment]
Fixes are merged and will be released in a future update to the MSAL and Broker libraries
