### ISSUE TITLE
Is it possible to render the sign in page in our own WebView rather than a Chrome custom tab?

### ISSUE THREAD

**Issue by jstubing** [AzureAD/microsoft-authentication-library-for-android#1250]
I'm wondering if it's possible to bypass the Chrome custom tab and instead specify our own WebView where the sign in page will be rendered.

**Comment by iambmelt** [comment]
Please consult the documentation on `authorization_user_agent`
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#authorization_user_agent
