### ISSUE TITLE
Sign out MSAL android

### ISSUE THREAD

**Issue by mohit1993** [AzureAD/microsoft-authentication-library-for-android#1276]
Please help to find a way to sign out user from native app with MSAL, and let me know what would be experience of that api, it will auto trigger sign in again or do i need to do that separately.

**Comment by iambmelt** [comment]
Hi @mohit1993 

- For SAPCA, see [`signOut()`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/ISingleAccountPublicClientApplication.java#L147-L162)
- For MAPCA, see [`removeAccount()`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/IMultipleAccountPublicClientApplication.java#L78-L94)

Please read the javadoc to observe the various calling patterns of these APIs (regarding whether or not they may be used from a UI thread, etc) and how the use of these APIs impacts shared device mode (if this is applicable to your app).

In the case of both of these APIs, _only_ the locally cached tokens are deleted. Any cookies present in your application's `WebView` or device system browser **will not** be cleared. If you need those cookies to be ejected you must navigate the user to the AAD (or B2C) signout endpoint.

Please note that if your app is Microsoft 1P FOCI-integrated with TSL or the Android auth broker, your user may still be able to get SSO from another 1P app via a Workplace Join Account (PRT) or via TSL (through FOCI RT)

Related issues/questions:
- #426 
- #725 

Assuming this answers the question, I'll go ahead and resolve this issue. Please feel free to reach out or reactivate if you have further questions. Thanks
