### ISSUE TITLE
On pressing back button, it asks me to fill my email id

### ISSUE THREAD

**Issue by nishi1612** [AzureAD/microsoft-authentication-library-for-android#1294]
**Describe the bug**
The app is currently available for a set of people for dogfooding and we observe that when broker app is installed, and a new user signs in our app and clicks on back button, the app takes the user to text box to fill in email address.

**Smartphone (please complete the following information):**
 - Device: One Plus 7T Pro
 - Android Version: API Level 29
 - Browser : Chrome
 - Broker App : Company Portal Installed 
 - MSAL Version : 2.0.1

**To Reproduce**
Click on the back button in sign in page for a new user.
The SDK asks user to fill in email in the text field.

**Expected behavior**
I expect to receive MsalUserCancelException.

**Actual Behavior**
User was asked to fill in email id in the text box.

**Screenshots**
![Back button on sign in page](https://user-images.githubusercontent.com/27308851/106440979-804c6500-649f-11eb-999b-4c6cb8b2b58d.jpg)
Clicking on the back button as shown on the screen asks user to fill in email id

**Comment by iambmelt** [comment]
Hello @nishi1612 -- our team does not own this UI; that said, I will reach out to you personally via email and point you towards the proper team.
