### ISSUE TITLE
Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by HristoStoevZ** [AzureAD/microsoft-authentication-library-for-android#1295]
@iambmelt 
continuation of https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1289

seems that even if we have _expires_in_ in the token, exception still occurs, after further research seems it is related to the deserialization for the token.  _performTokenRequest_ in **BaseControler.java** sent properly the request and get the proper response from the Azure. Here is the  token 

```
{
  "exp": 1612174704,
  "nbf": 1612171104,
  "ver": "1.0",
  "iss": "https://tenant.b2clogin.com/d1308f65-c866-xxxxx-xxxx-7e3421bcbd41/v2.0/",
  "sub": "f2aca26a-0bcf-xxxx-xxxxx-e0c5f6f1a7ea",
  "aud": "08c4eea0-f169-xxxx-xxxx-d9e3de67355a",
  "acr": "b2c_1a_signup_signin",
  "iat": 1612171104,
  "auth_time": 1612170823,
  "name": "Hristo",
  "given_name": "Hristo",
  "family_name": "Stoev",
  "tid": "d1308f65-c866-4224-92a4-7e3421bcbd41",
  "expires_in": 3600
}
```

but then when it performs 
@SuppressWarnings(WarningType.unchecked_warning) final TokenResult tokenResult = strategy.requestToken(tokenRequest);

property _tokenResult.mTokenResponse.mExpiresIn_ is still null , which cause on the next step to get this exception.

**Comment by iambmelt** [comment]
Including the stacktrace from #1289, assuming it is still relevant

```java
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.getExpiresOn(MicrosoftStsAccountCredentialAdapter.java:231)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:78)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:45)
      at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:112)
      ...
```

**Comment by iambmelt** [comment]
@HristoStoevZ 

Please ensure you're not confusing `expires_in` with `exp`

There should be an `expires_in` in the payload of your `/token` response, as below
```json
{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q...",
    "token_type": "Bearer",
    "expires_in": 3599,
    "scope": "https%3A%2F%2Fgraph.microsoft.com%2Fmail.read",
    "refresh_token": "AwABAAAAvPM1KaPlrEqdFSBzjqfTGAMxZGUTdM0t4B4...",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIyZDRkMTFhMi1mODE0LTQ2YTctOD...",
}
```

**Comment by HristoStoevZ** [comment]
@iambmelt 

Seems that it is null in the parsed token object, even that it is presented in the received token  

```
TokenResponse {
	mExpiresIn = null,
	mAccessToken = 'null',
	mTokenType = 'Bearer',
	mRefreshToken = 'eyJraWQiOiJBanNhYjoiMS4wIiwiemlwIjoi...',
	mScope = '',
	mState = 'null',
	mIdToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJS...',
	mResponseReceivedTime = 0
}
```
I've captured short video for your reference. 
![tokenIssue](https://user-images.githubusercontent.com/61584808/106569196-e9ce8100-653c-11eb-9640-c38301357880.gif)
So your suggestion to configure custom policy with `expires_in` , should affect payload of /token response, shouldn't it ? 
Is there any other place which has to be configured, in order get the proper token payload ?

**Comment by HristoStoevZ** [comment]
Another thing that I've noticed is that the actual HTTPResponse looks like 
```
{
	"id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImt...",
	"token_type": "Bearer",
	"not_before": 1612270085,
	"client_info": "eyJ1aWQiOiJmMmFjYTI2YS0wYmNmLTRhMj...",
	"scope": "",
	"refresh_token": "eyJraWQiOiJBanNhY3pCaDZ0UkY2el80O...",
	"refresh_token_expires_in": 1209600
}

```

and the library is trying to deserialize this in `TokenResponse implements ISuccessResponse` which does not support `refresh_token_expires_in`, and i think in this case the `refresh_token_expires_in `should be stored in to the 
```
@SerializedName("expires_in")
    private Long mExpiresIn;
```

**Comment by iambmelt** [comment]
@HristoStoevZ Please review the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/b2c_required_artifacts_and_claims.md) -- your token response is missing required properties (scopes cannot be empty, AT must be returned)

**Comment by HristoStoevZ** [comment]
@iambmelt ,

so i had to configure TrustedFrameworkBase.xml from the starter pack https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack   
with the following metadata, which properly configure token issuer: 

` <TechnicalProfile Id="JwtIssuer">
...
<Metadata>
....
            <Item Key="token_lifetime_secs">3680</Item>
            <Item Key="id_token_lifetime_secs">3601</Item>
            <Item Key="refresh_token_lifetime_secs">86400</Item>
            <Item Key="rolling_refresh_token_lifetime_secs">86401</Item>
          </Metadata>
`

then for the scopes I have to use the exposed URL from this step https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started#register-the-identityexperienceframework-application 

then all start working.
