### ISSUE TITLE
"Forgot Password" Flow Appears Mobile-Unfriendly on 400x800 Device

### ISSUE THREAD

**Issue by Tyler-A** [AzureAD/microsoft-authentication-library-for-android#1296]
**Describe the bug**
Using MSAL v2.0.6, when the user is directed to the Azure login screen and clicks "Forgot Password", the experience becomes quite unfriendly to the point of being unusable.

Our application is enterprise internal only using new hardware. The screens look like they were made with some mobile friendly characteristics, but still results in the pages being cutoff and needing to scroll, zoom in/out, etc.. This makes these pages quite difficult to be used by our users.

**Smartphone (please complete the following information):**
 - Device: Zebra MC9300
 - Android Version: API Level 29
 - Browser: WEBVIEW
 - MSAL Version 2.0.6

**To Reproduce**
1. Go to the Login screen
2. Select "Forgot Password" to begin the password reset flow.
3. Notice you have to scroll down to enter a captcha. Also email box extends off screen.
4. Next screen asking "Why are you having trouble signing in" begins in the middle of the page with some text cut off.
5. After selecting "Forgot my password" and hitting next...
6. Screen once again in the middle, cutting off text, and requires you to zoom far out in order to see everything (but now has tiny text).....

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

For configuration, "authorization_user_agent" is set to "WEBVIEW" in our case, but experimenting with "BROWSER" showed no difference.

**Expected behavior**
We expect that the "Forgot Password" flow is formatted in a way that is easy to use for our mobile devices.

**Actual Behavior**
Multiple screens in the "Forgot Password" flow have text cut off, require zooming in and out, and small text.

**Screenshots**
Screenshots provided are of screenshare sessions of an actual device, but with logos/userPrincipalNames covered for privacy:

![ForgotPassword1](https://user-images.githubusercontent.com/74934150/106511172-b9c3a700-6484-11eb-9a61-e18166d31293.png)
![ForgotPassword2](https://user-images.githubusercontent.com/74934150/106511168-b92b1080-6484-11eb-8f26-2af71b142164.png)
![ForgotPassword3](https://user-images.githubusercontent.com/74934150/106511170-b9c3a700-6484-11eb-94ec-6211cdb8b1be.png)

**Additional context**
Understandably this may not necessarily be an issue with MSAL, but with the Azure Forgot Password pages themselves. Starting the conversation here though to get a better idea, and perhaps there is something that can be done on the client to allow the pages to render more appropriately (perhaps we're missing a configuration).

**Comment by iambmelt** [comment]
Hi @Tyler-A -- Thanks for reaching out to inform us of this poor UX

>Understandably this may not necessarily be an issue with MSAL, but with the Azure Forgot Password pages themselves

This is correct, these pages are hosted external to the MSAL library.

I can try to get this issue routed to the proper engineering team to address these issues. First, I need some additional information and details from you:
- Is this a B2C or AAD application?
- Are you (@Tyler-A) an employee of Microsoft?

**Comment by Tyler-A** [comment]
Hi @iambmelt, thanks for responding.

- This is an AAD application, used internally by my company.
- I am not an employee of Microsoft.

Let me know if I can provide any further information to assist.
Thanks again!

**Comment by iambmelt** [comment]
> Hi @iambmelt, thanks for responding.
> 
> * This is an AAD application, used internally by my company.
> * I am not an employee of Microsoft.
> 
> Let me know if I can provide any further information to assist.
> Thanks again!

Thanks @Tyler-A -- This is enough for me to run with. I'll need to track down the relevant contact for these pages and raise this issue with them

**Comment by iambmelt** [comment]
Hi @Tyler-A

Just reaching out to let you know: this engineering team who owns the password reset experience has been made aware of the issue on mobile/small-screen devices and acknowledged the issue. I cannot provide an ETA on when a new UX will be made available.

I will leave this issue open and tagged `External` / `Service Issue`

**Comment by Tyler-A** [comment]
Hi @iambmelt, thank you for the update. Good news to hear that it is acknowledged.

Is there a case ID or internal reference number that I can use for speaking with our Microsoft rep? I'd like to make sure this gets the right level of attention and see if we can pull any strings.

Thanks again for following up!

**Comment by iambmelt** [comment]
> Hi @iambmelt, thank you for the update. Good news to hear that it is acknowledged.
> 
> Is there a case ID or internal reference number that I can use for speaking with our Microsoft rep? I'd like to make sure this gets the right level of attention and see if we can pull any strings.
> 
> Thanks again for following up!

@Tyler-A I was not provided one, but will follow-up with the engineering team to see what they can provide and get back to you

**Comment by iambmelt** [comment]
@Tyler-A The engineering team tracking this issue got back to me: there's currently no case ID for it, however they gave me an Epic ID you may be able to mention with your rep: `1010586`. This corresponds to a service called SSPR ("Self-Service Password Reset").

Hope this helps.

**Comment by iambmelt** [comment]
@hamiltonha Assigning this item over to you so it doesn't get lost to the sands of time. This is an external ask on SSPR: it is on their backlog.
