### ISSUE TITLE
Azure MSAL Integration not work when app download from play store

### ISSUE THREAD

**Issue by fongfuse** [AzureAD/microsoft-authentication-library-for-android#1304]
I have some Issues when app download from play store

https://stackoverflow.com/questions/59622440/azure-msal-integration-not-work-when-app-download-from-play-store

lib version : 'com.microsoft.identity.client:msal:2.+'

How to fixed this issue?

**Comment by iambmelt** [comment]
Hi @fongfuse -- You might try using our debugging activity to troubleshoot this issue:
https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Troubleshooting-Redirect-URI,-IntentFilter-Issues

This issue could occur if the release signing certificate does not match the configured redirect uri in the `AndriodManifest.xml` or in the app configuration json file

**Comment by iambmelt** [comment]
Closing to inactivity
