### ISSUE TITLE
Repeated calls to StorageHelper:decryptWithSecretKey and info logging 

### ISSUE THREAD

**Issue by snijsure** [AzureAD/microsoft-authentication-library-for-android#1308]
**Describe the bug**

Noticed ton of messages like these are getting logged when I am running my app on Pixel 3XL phone, it slows down the app and actually crashes adb logcat!!

```
02-20 16:29:42.116 12984 13012 I StorageHelper:decryptWithSecretKey:  [2021-02-21 00:29:42 - {"thread_id":"89186","correlation_id":"UNSET"}] Using key with thumbprint XXX Android 30
02-20 16:29:42.116 12984 13012 I StorageHelper:decryptWithSecretKey:  [2021-02-21 00:29:42 - {"thread_id":"89186","correlation_id":"UNSET"}] Using key with thumbprint XXX Android 30
02-20 16:29:42.117 12984 13012 I StorageHelper:decryptWithSecretKey:  [2021-02-21 00:29:42 - {"thread_id":"89186","correlation_id":"UNSET"}] Using key with thumbprint XXX Android 30
02-20 16:29:42.117 12984 13012 I StorageHelper:decryptWithSecretKey:  [2021-02-21 00:29:42 - {"thread_id":"89186","correlation_id":"UNSET"}] Using key with thumbprint XXX Android 30
02-20 16:29:42.117 12984 13012 I StorageHelper:decryptWithSecretKey:  [2021-02-21 00:29:42 - {"thread_id":"89186","correlation_id":"UNSET"}] Using key with thumbprint XXXX Android 30
```

Eventually adb crashes:

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.
If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

**Smartphone (please complete the following information):**
 - Device:  Pixel 3 XL
 - Android Version:  11
 - Browser : N./A
 - MSAL Version : 1.6.0

**To Reproduce**

**Comment by iambmelt** [comment]
Thanks for reaching out to report this issue @snijsure -- this issue should be resolved by changes submitted by @AdamBJohnsonx  in the following PR:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1213

These changes are available in the following `androidcommon` releases:
- [`3.1.0`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/releases/tag/v3.1.0)

Our next MSAL release will include the fix

**Comment by snijsure** [comment]
Thanks @iambmelt. Not sure what MSAL policy is in terms of keeping older versions updated, any chance this change will make it to 2.X 

In case we don't want to jump on latest release right away!

**Comment by AdamBJohnsonx** [comment]
@snijsure It'll be a 2.x release of MSAL, which will take the leading version of MSAL-Android-Common (which has been in the 3.x series for at lease a little while now).

**Comment by snijsure** [comment]
Thanks @iambmelt thanks for that clarification, will test out next MSAL 2.x release.

**Comment by iambmelt** [comment]
Fixed in our latest release, sorry for the trouble:
https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.0.8

This fix will be available in the Intune Company Portal & Microsoft Authenticator builds in the late-March/early-April releases
