### ISSUE TITLE
Is there a way to cache the username and password in the webview?

### ISSUE THREAD

**Issue by smckenzieSP** [AzureAD/microsoft-authentication-library-for-android#1310]

**Comment by iambmelt** [comment]
@smckenzieSP Please review the documentation for [prompt behavior](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/prompt_behavior.md) -- this parameter will control how the cached user's state/identity are presented during interactive auth with AAD. I'd recommend supplying the [`login_hint`](https://javadoc.io/doc/com.microsoft.identity.client/msal/2.0.2/com/microsoft/identity/client/AcquireTokenParameters.Builder.html) when performing interactive auth, if the intent is prepopulate the username text box's input field. I'll go ahead and close this question, assuming this provides the answer you need. Feel free to reopen if you have a more specific question about this functionality that is unaddressed by our documentation
