### ISSUE TITLE
Intent filter for: BrowserTabActivity is missing

### ISSUE THREAD

**Issue by Nealsoni00** [AzureAD/microsoft-authentication-library-for-android#1313]
**Describe the bug**
In development and production, the error "Intent filter for: BrowserTabActivity is missing" keeps coming up even though I had added the activity with the intent-filter in the AndroidManifest.xml file.

It worked previously before upgrading to 3.0.4 from 3.0.1 (not sure when it broke — sometime in the last 2 months and didn't verify login after updating) and I verified the `Signature hash` and `Redirect URI` are entered correctly in the msal_config.json and console as well as the `host` and `path` in the `AndroidManifest` using the `PublicClientApplication.showExpectedMsalRedirectUriInfo(this);` command. 

Even going back to 3.0.1 does not solve the issue. 

**Smartphone:**
 - Device: All Devices tested (SAMSUNG, SONIM, Pixel)
 - Android Version: 9
 - MSAL Version: 3.0.4, 3.0.6, 3.0.1

**Manifest:**
```
 <application ...>
      <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                        android:host="[SAME HOST]"
                        android:path="[SAME HASH]"
                        android:scheme="msauth" />
            </intent-filter>
        </activity>
...
</application>
```
**msal_config.json**
```
copied directly from portal: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Authentication/appId/[APP ID]
{
  "client_id" : "[from portal]",
  "authorization_user_agent" : "DEFAULT",
  "account_mode" : "SINGLE", <-- issue regardless of this line being here or not
  "redirect_uri" : "msauth://[bundle_id]/c4W9Rxvqd85n7KZiQTzPhrpUgOM%3D",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount",
        "tenant_id": "common"
      }
    }
  ]
}
```

**Code:**
```
 PublicClientApplication.createSingleAccountPublicClientApplication(
    this,
    R.raw.msal_config,
    object : IPublicClientApplication.ISingleAccountApplicationCreatedListener {
        override fun onCreated(application: ISingleAccountPublicClientApplication) {
            Timber.e("Created MSAL application")
        }
        override fun onError(exception: MsalException) {
            Timber.e("UNABLE TO CREATE MSAL application $exception")
        }
    }
)
```

**Stacktrace**
```
E/LoginActivity$initViews: UNABLE TO CREATE MSAL application com.microsoft.identity.client.exception.MsalClientException: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml 
    
    <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
    	<intent-filter>
    		<action android:name="android.intent.action.VIEW" />
    		<category android:name="android.intent.category.DEFAULT" />
    		<category android:name="android.intent.category.BROWSABLE" />
    		<data
    			android:host="[SAME HOST]"
    			android:path="[SAME HASH]"
    			android:scheme="msauth" />
    	</intent-filter>
    </activity>
```

Any advice on how to resolve this would be amazing.

**Comment by rpdome** [comment]
@Nealsoni00 I just noticed that we're missing an extra '/' under android:path in `PublicClientApplication.showExpectedMsalRedirectUriInfo` 

e.g. it should be android:path="/[SAME HASH]", not android:path="[SAME HASH]"

Could you please give it a try and let me know if you still run into the issue? Thanks!

**Comment by Nealsoni00** [comment]
Apologize, I am unable to test this as I migrated to use standard OAuth2.0 flow with `net.openid:appauth` 

Hopefully, this is helpful for other people!
