### ISSUE TITLE
Microsoft Modern Authentication using Chrome with MSAL on Android

### ISSUE THREAD

**Issue by sbiton123** [AzureAD/microsoft-authentication-library-for-android#1320]
The question is related to https://stackoverflow.com/questions/66053874/microsoft-modern-authentication-using-chrome-with-msal. 
Using MSAL library for Android with Edge browser, then the redirection URL below works properly. The user is required to choose the identity certificate installed as part of Microsoft Intune Company portal. 

https://login.microsoftonline.com/common/oAuth2/v2.0/authorize?web_view_zoom_enabled=true&x-client-CPU=arm64-v8a&response_type=code&x-client-Ver=2.0.0&code_challenge_method=S256&x-client-DM=XYZ&x-client-OS=28&x-client-SKU=MSAL.Android&web_view_zoom_controls_enabled=true&client_id=...&client-request-id=...&instance_aware=false&scope=Calendars.Read%20User.Read%20openid%20offline_access%20profile&claims=%7B%7D&redirect_uri=...%3A%2F%2Fcallback&state=...&prompt=select_account&code_challenge=...

However, using Chrome not. There is no request of identity certificate installed as part of Microsoft Intune Company portal and the user is requested to enroll the device (although the device already enrolled and compliant). 

Using the above link but without "x-client-SKU=MSAL.Android" or even changing it to "x-client-SKU=Android", then Chrome behavior is the same as Edge behavior and user is prompt to choose the identity certificate. How can this be resolved?

**Comment by tanmaymanolkar1** [comment]
Hi, This does seem to be the way to trigger Client TLS which helps pick the certificate in chrome, this can be done by removing the "x-client-SKU=MSAL.Android" filed from the URL. I would soon update this thread with a possible solution/explanation.

**Comment by tanmaymanolkar1** [comment]
@sbiton123, I wanted to clarify, why isn't the broker being used here? It looks like you are skipping the broker and trying to use chrome.

**Comment by sbiton123** [comment]
Hi, Thanks.
In general, we use MSAL library 2.0.1 (and now moved to 2.0.10 - still same problem remain). Therefore, we can not remove the field "x-client-SKU=MSAL.Android" filed from the URL (or at least we prefer that the change will be in the library if needed). 
Regarding broker, we use Microsoft Company Intune Company Portal application on the Android device. The application is installed, signed in and and we installed the certificate by "Enable Browser Access" in the Microsoft Company Intune Company Portal application settings. The device complies to the enterprise security policy. 
When we are trying to connect to retrieve calendar meetings (from our application which includes MSAL library to support Microsoft Modern authentication), the browser is opened, we enter email address, the browser is redirected  to company SSO portal and then with Edge we are requested to provide the relevant certificate (Microsoft Account) and then we get calendar events, but with Chrome we are not requested to provide the relevant certificate and there is an error message that we need to enroll the device while it is already enrolled... The URL is the same when using Chrome and Edge.

**Comment by tanmaymanolkar1** [comment]
@sbiton123 yes there is a special provisioning for chrome, so the work around for now is to use the Edge browser.
I would provide some clarity about the situation with Chrome browser soon.

**Comment by tanmaymanolkar1** [comment]
Currently the way chrome can access the cert installed is when the `x-client-SKU=MSAL.Android` is removed from the url and then the URL is loaded again.

**Comment by sbiton123** [comment]
When looking on network capture with Chrome when doing the Microsoft 
Modern Authentication using our app (immediately after entering credentials on the company SSO portal), then I do not see any TLS CERTIFICATE REQUEST from a any server that the Android device connects to. Therefore, Chrome does not provide a popup to choose the certificate. This is not the case with Edge.

**Comment by shepeliev** [comment]
The issue still exists in v.4.0.2. I can't complete authentication in Chrome without deleting `x-client-SKU=MSAL.Android`. Is there any workaround that I could apply in the code? Or using Edge is only way for now?
