### ISSUE TITLE
How to authenticate with different scopes?

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-for-android#1322]
Hello,
we have an application that utilizes Exchange Webservices (EWS). For accounts on O365 we user OAuth2/ModernAuth via MSAL.
I would like to add functionality that is only available via the Graph API, for example creating an online meeting.

According to https://docs.microsoft.com/en-us/outlook/rest/compare-graph#moving-from-outlook-endpoint-to-microsoft-graph
>  you cannot mix permissions for one endpoint with permissions for the other in a single request

My default authorization is EWS.AccessAsUser.All, and for the calendar operation i need Calendars.ReadWrite.
I have tried the following scenarios:  

1. Use both scopes (prior to reading the article linked above). Results in a token that can be used for Graph, but gets a 401 on EWS
2.  Aquire a token with EWS permission. Then use MSAL acquireTokenSilent with the graph scope. Gives me the same token for both, resulting in an "Invalid Audience" error on the Graph API
3. Use interactive authorization (MSAL acquireToken). This gives me a second token with the correct scope, but now i have to present the user with two authentication flows and would probably have to retain two separate IMultipleAccountPublicClientApplication instances (which i have not tried yet, maybe not even possible)

Any tips on how i can use both EWS and Graph API?

**Comment by iambmelt** [comment]
Hi @slowcar 

#&#x2060;2 is the pattern for doing this; these requests should not yield the same token. Can you confirm the scopes you are sending in your request are the correct ones for the EWS / Graph endpoint? As these are separate resources, you should have two separate access tokens for them. You should be able to acquire 1 silently from the refresh token of another

**Comment by slowcar** [comment]
Hi @iambmelt 

My default scope is EWS.AccessAsUser.All
My first call is
`AcquireTokenParameters acquireTokenParameters = new AcquireTokenParameters.Builder()
                            .withLoginHint(mailAddress)
                            .withScopes(SCOPES_LIST)
                            .startAuthorizationFromActivity(activity)
                            .withCallback(authenticationCallback)
                            .build();
                        clientApplication.acquireToken(acquireTokenParameters);`
with clientApplication being an instance of IMultipleAccountPublicClientApplication.
We store the returned accountId and use it for further calls.

For my test case i call
`IAuthenticationResult result = clientApplication.acquireTokenSilent(SCOPES, account, authorityURL.toString());`
(SCOPES containing the mentoned EWS.AccessAsUser.All only)
and use the resulting access token for a simple EWS operation (successfully).

As a second step, i call
`IAuthenticationResult result = clientApplication.acquireTokenSilent(GRAPH_SCOPES, account, authorityURL.toString());`
with GRAPH_SCOPES containing Calendars.ReadWrite only.
The token returned from this call is the same as in the first call.
I try to use it for a simple graph operation
`IGraphServiceClient graphClient =
	GraphServiceClient
		.builder()
		.authenticationProvider(new IAuthenticationProvider() {
			@Override
			public void authenticateRequest(IHttpRequest request) {
				Logger.d(LOG_TAG, "Authenticating request," + request.getRequestUrl());
				request.addHeader("Authorization", "Bearer " + token);
			}
		})
		.buildClient();
ICalendarCollectionPage calendars = graphClient.me().calendars().buildRequest().get();`
and get  468Graph service exception Error code: InvalidAuthenticationToken
468Error message: Access token validation failure. Invalid audience.

What i find interesting: When i check the token with https://jwt.ms i see that the additional permissions are on the token.
For example, after trying both the calendars() and the me() graph operation, my token has these:
`"scp": "Calendars.ReadWrite EWS.AccessAsUser.All User.Read User.ReadBasic.All User.ReadWrite",`
the audience, however, is
`"aud": "https://outlook.office.com",`
and if i understand the inner mechanisms correctly, i would need https://graph.microsoft.com/ as audience.

Writing this inspired my to add the url to the graph scopes, and it is working, i get a second token with the correct audience.

So thank you for your question about the scopes, that put me on the right track.

To conclude:
Retrieve the EWS token with scope EWS.AccessAsUser.All
Retrieve the graph token with scope https://graph.microsoft.com/Calendars.ReadWrite (fully qualified)
