### ISSUE TITLE
JSON Parsing exception instead of clear and understandeble MSAL exception

### ISSUE THREAD

**Issue by ZBlaZe** [AzureAD/microsoft-authentication-library-for-android#1331]
Hello,
I'm using MSAL library to create another lib that provides a simple interface for authorization and covers some routine flow that uses MSAL and API of our product. When I'm trying to use `acquireTokenSilentAsync()` before the user will sign in via B2C flow, MSAL throws an exception and that is logical. In the IOS version of MSAL we will get for this case something like InteractiveLoginRequired exception but in Android MSAL we will get an exception that contains the message **com.microsoft.identity.client.exception.MsalClientException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $**. It happens because the library receives a 404 response code and tries to parse HTML like a JSON object. It would be very nice to receive a clear and understandable exception at least because the cause of the exception is possible to be related to another kind of problem. 

- Device: Samsung Galaxy A40
- Android Version: 10
- MSAL Version: 2.0.8 (also reproduced on few previous version)
- App type: IMultipleAccountPublicClientApplication

Here is the code also. The account information was taken by `getAccounts()` method
```kotlin

acquireTokenSilentAsync(
                        LIB_CONF.scopes.toTypedArray(),
                        account,
                        account.authority,

                        object : SilentAuthenticationCallback {
                            override fun onSuccess(authResult: IAuthenticationResult) {
                                onSuccess.invoke(authResult)
                            }

                            override fun onError(exception: MsalException?) {
                                // Here I get com.microsoft.identity.client.exception.MsalClientException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
                                onError.invoke(error)
                            }
                        }
                    )
```

**Comment by iambmelt** [comment]
Hi @ZBlaZe

This is unexpected. In my local testing I was unable to reproduce this behavior and am instead seeing the following exception, which looks to match the desired behavior you described.
![image](https://user-images.githubusercontent.com/990063/110992540-e93ebc80-832a-11eb-84ca-0da6d5a31b14.png)

To help me troubleshoot this issue, could you provide:
- Approximate repro steps, generic to B2C
- A screenshot or dump of the HTML you are seeing in the response, as well as the URL that served it

**Comment by iambmelt** [comment]
I'll add, I am using the following B2C sample to test:
https://github.com/Azure-Samples/ms-identity-android-java

**Comment by ZBlaZe** [comment]
Hi @iambmelt 
Here are the steps:
1. Open the app with
2. Sign in interactively
3. Open the app again when it will not possible to authorize via an interactive flow
4. Run silent login (in code I try to get users first and then run `acquireTokenSilentAsync `method)

My exception:
![зображення](https://user-images.githubusercontent.com/7900439/111310331-a3a12d00-8665-11eb-83ba-b3437ac041b7.png)
Stack:
![зображення](https://user-images.githubusercontent.com/7900439/111310538-de0aca00-8665-11eb-98cc-4dc773928561.png)
HTML dump:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

**Comment by iambmelt** [comment]
Thank you for the details @ZBlaZe - I will need to route this issue over to our B2C service team; these endpoints shouldn't be returning HTML for error cases

**Comment by iambmelt** [comment]
@hamiltonha Assigning over to you so that this doesn't get lost. This HTML instead of JSON issue is a B2C service issue and not an MSAL client lib problem.
