### ISSUE TITLE
Customize loading on common_activity_authentication.xml

### ISSUE THREAD

**Issue by matheusfreire** [AzureAD/microsoft-authentication-library-for-android#1335]
We have a new feature in our app and we'd like to replace or even customize a loading for Msal WebView. We want to know if the option is available or if not, it's possible to create a way to pass a view to be used as loading?

**Comment by iambmelt** [comment]
Hi @matheusfreire -- We don't currently have a _documented_ way to do this /cc @hamiltonha FYI

However, looking at the implementation it should be possible to style the colors of the WebView frame and loading bar by overriding the following color and style elements... Note, you may need to apply `tools:override="true"` to override the library's defaults, I've not tried it locally

Color name of app top-bar:
```xml
<color name="colorPrimaryDark">#F44336</color>
```

Color name of indeterminate progress bar:
```xml
<color name="msal_loading">#0078D4</color>
```

As a potential helpful pointer, you might peek at this file inside of our sample and see how it styles the top bar:
https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/src/main/res/values/colors.xml

**Comment by iambmelt** [comment]
Closing as answered. We could consider taking this level of customization 'officially' with a feature ask /cc @hamiltonha

**Comment by mpomiankiewicz** [comment]
Hi @iambmelt, is there a way to change the background of the loading screen? Or delay showing WebView until login page is loaded? Our app and login page has dark background and it would be great if we could skip showing the white loading page.
