### ISSUE TITLE
Sign ins requests are using Microsoft Graph as a resource while not requested

### ISSUE THREAD

**Issue by MathieuCalba** [AzureAD/microsoft-authentication-library-for-android#1340]
**Describe the bug**
Our application is a B2B application, our customers are large companies, they use Microsoft as an identity provider for their employees.

Our application is using the latest version of the MSAL library to let employees authenticate with their Microsoft account, we then provide the access token to our backend so the user can be authenticated within our product. After that, we don’t use the MSAL SDK or the access token to do anything from the mobile app. We don’t even need to refresh the token. We provide the scope `openid` (the default scopes `profile` and `offline_access` are then added to our sign in request by the MSAL Library via [the common library](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/44438ef4ec673552b5d7da47e033b6945bc1272d/common/src/main/java/com/microsoft/identity/common/internal/controllers/BaseController.java#L106-L110)).

This works fine for most customers. Except we have some customers who are blocking Microsoft Graph resource from being used and that prevent their employees to connect. When looking at our sign in requests, we’ve found out that Microsoft Graph is used a resource in our sign in requests while we didn’t request it or used anything that could lead to that.

We tried to use [the sample](https://github.com/Azure-Samples/ms-identity-android-kotlin) and remove the call to Microsoft Graph, sign in requests to the Azure application configured in the sample are also recognised as using Microsoft Graph API, when putting our configuration in the manifest and the json configuration we also still have the resource Microsoft Graph API used… Our customers can’t sign in…

This issue is happening on the MSAL Library for objective C as well.

**We think that the MSAL library is doing something that make it use the Microsoft Graph API, do you have any information about that?** Is it normal? Is it possible to disable that on our side?

**Smartphone (please complete the following information):**
 - Device: any devices
 - Android Version: from API Level 23 to 30
 - Browser: tested with Chrome & Edge as default browser
 - MSAL Version: latest version (2.0.6)

**To Reproduce**
1. Use the provided sample project: [ms-identity-android-kotlin-master-edited.zip](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/6170385/ms-identity-android-kotlin-master-edited.zip) (it is [the official Kotlin sample project](https://github.com/Azure-Samples/ms-identity-android-kotlin) but with the `openid` scope forced and the call to graphApi disabled.
2. Sign in with any Microsoft account
3. Go to [the administration](https://endpoint.microsoft.com/#blade/Microsoft_AAD_IAM/UsersManagementMenuBlade/MsGraphUsers)
4. Find you user
5. Go to Sign-ins
6. Check that the sign-in request is using the Microsoft Graph API as a resource

**Expected behavior**
Sign-ins with MSAL library that don’t use Microsoft Graph API directly shouldn’t use Microsoft Graph API.

**Actual Behavior**
Any sign-ins with MSAL library that use Microsoft Graph API as a resource.

**Screenshots**
The sign in request that use Microsoft Graph:
<img width="947" alt="Screenshot 2021-03-19 at 11 27 38" src="https://user-images.githubusercontent.com/541565/111766844-4647ee80-88a6-11eb-8dd9-82250457286d.png">

**Comment by iambmelt** [comment]
>We think that the MSAL library is doing something that make it use the Microsoft Graph API, do you have any information about that? Is it normal? Is it possible to disable that on our side?

Hi @MathieuCalba -- Thanks for reaching out; this is an implementation detail of the Azure Active Directory (AAD) identity backend implementation regarding where certain properties (claims) of a user's identity are sourced. As I recall, not all ID token claims are authoritatively owned/sourced from AAD's own backend: some of this data is derived from tenant information that is known to MSGraph. 

To the best of my knowledge, this cannot be disabled or worked around.

Assuming this answers your question, feel free to close/resolve this issue. If you need more information, let me know

**Comment by iambmelt** [comment]
Closing (presumed answered).

**Comment by CPonchet** [comment]
Hi @iambmelt,

Thanks for your feedback. We had the same issue on the python SDK and some improvements have been done by the team:
https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/207#issuecomment-841502996

The root reason seems to be the same (impossible to define the scopes asked during the login). If true, is it possible for you to do the same please?

**Comment by iambmelt** [comment]
> Hi @iambmelt,
> 
> Thanks for your feedback. We had the same issue on the python SDK and some improvements have been done by the team:
> [AzureAD/microsoft-authentication-library-for-python#207 (comment)](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/207#issuecomment-841502996)
> 
> The root reason seems to be the same (impossible to define the scopes asked during the login). If true, is it possible for you to do the same please?

Hi @CPonchet /cc @hamiltonha 

I'm curious to learn a bit more about this ask; is this a matter of compliance? User perception? As I understand it, there's some desire to not request a `refresh_token`... The general impact of such a change [were someone to adopt it] would be interactive auth prompts according to the lifetime of the `access_token`, typically about an hour for most tenant configurations. In general, we understand most of our users and customers almost ubiquitously want to avoid prompts wherever possible... 

As a note to other devs and PMs reviewing this ask; there are some "gotchas" here that make implementing this slightly less than straightforward: mainly, that we define the presence of an account in the cache by it having a corresponding refresh token. Were we to actually implement this ask, we'd have to revisit this logic, in addition to tweaks in the response validation/caching

**Comment by iambmelt** [comment]
> @iambmelt first thanks for taking some time :).
> 
> Today, we are using an enterprise app deployed on the AAD Marketplace. This app is using mainly the graph for integrations (getting and pushing info).
> 
> In some cases, our customers are using conditional access to limit the use of Office (off-site mode). In this particular case, we (as an application) are not authorized to generate a refresh and access token but only an id-token. In this case, we wish we could ask only for the openid/profile in the scopes without the offline_access.
> 
> We performed some tests on our end with a basic app (aka without the offline_access) and passing the .default scope seems fine.
> To avoid getting multiple applications on our side (and for the customers too), is it possible to not ask in some cases the offline_access scope?
> 
> Available if needed, I would be pleased to exchange on the subject if expected.

Thanks for this additional info, @CPonchet - I'm going to forward this request as well as the context you've provided over to our Program Management team to evaluate this work for inclusion on our roadmap. Thanks!

/cc @hamiltonha

**Comment by iambmelt** [comment]
> > @iambmelt first thanks for taking some time :).
> > Today, we are using an enterprise app deployed on the AAD Marketplace. This app is using mainly the graph for integrations (getting and pushing info).
> > In some cases, our customers are using conditional access to limit the use of Office (off-site mode). In this particular case, we (as an application) are not authorized to generate a refresh and access token but only an id-token. In this case, we wish we could ask only for the openid/profile in the scopes without the offline_access.
> > We performed some tests on our end with a basic app (aka without the offline_access) and passing the .default scope seems fine.
> > To avoid getting multiple applications on our side (and for the customers too), is it possible to not ask in some cases the offline_access scope?
> > Available if needed, I would be pleased to exchange on the subject if expected.
> 
> Thanks for this additional info, @CPonchet - I'm going to forward this request as well as the context you've provided over to our Program Management team to evaluate this work for inclusion on our roadmap. Thanks!
> 
> /cc @hamiltonha

Hi @CPonchet - I wanted to let you know that I've sent this item over to our PM team and it is on our backlog for Community Feature Asks. This backlog is prioritized quarterly, so I cannot give any estimate or commitment on it at this time

**Comment by CPonchet** [comment]
@iambmelt thanks for the update and again, thanks for your time.

**Comment by OmarHassan25** [comment]
Any updates on this issue?

**Comment by MathieuCalba** [comment]
@negoe was this implemented?
