### ISSUE TITLE
SIGSEGV AuthorizationActivity Segmentation violation (invalid memory reference)

### ISSUE THREAD

**Issue by evenlan1990** [AzureAD/microsoft-authentication-library-for-android#1349]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: samsung Galaxy Tab A (SM-T510)
 - Android Version: 10
 - Browser 
 - com.microsoft.identity.client:msal:1.6.0

**Stacktrace**
SIGSEGV · Segmentation violation (invalid memory reference)
/data/app/com.google.android.trichromelibrary_438909030-7HafP6JIyWMBHAMXHUKDZg==/base.apk!/lib/armeabi-v7a/libmonochrome.so:43097786 0xc8e8feba

**To Reproduce**
collect log by third SDK

**Expected behavior**
don't crash

**Actual Behavior**
crash

**Screenshots**

**Additional context**

**Comment by iambmelt** [comment]
This is not an MSAL library issue.

Consider reviewing the following, possibly related thread:
https://android.stackexchange.com/questions/234830/com-google-android-trichromelibrary-causes-many-android-apps-to-crash
