### ISSUE TITLE
CacheRecord without oid claim and clientInfo causes NullPointerException in PublicClientApplication.homeAccountMatcher when account.getId() is null

### ISSUE THREAD

**Issue by VinSmile** [AzureAD/microsoft-authentication-library-for-android#1369]
I'm running our app inside Company Portal Work Profile 
Just a moment after intune sdk starts configuring app after first launch app crashes

Here are some of my investigations:
MultipleAccountPublicClientApplication.getAccountInternal
migrationCallback
one CacheRecord found, but it doesn't contain neither client info
![image](https://user-images.githubusercontent.com/12799579/115417561-64846f80-a201-11eb-8cb3-58f400e4dfcd.png)

Nor oid clime in IdToken
```json
{
  "aud": "29d9ed98-a469-4536-ade2-f981bc1d605e",
  "iss": "https://login.microsoftonline.com/d6b4b8f5-d70a-4959-821d-7ab813a6aaa8/v2.0",
  "iat": 1618916813,
  "nbf": 1618916813,
  "exp": 1618920713,
  "aio": "AUQAu/8TAAAA/lNveHPWy4SIDfZozV+TawUDo9A3N8AXVId5r1LeghELpkT7lrZ3mGJJvBAI3/hoJ+S/4M9xE+UUdpdSjuo9Bg==",
  "email": "alex@intunegf.onmicrosoft.com",
  "rh": "0.AXwA9bi01grXWUmCHXq4E6aqqJjt2SlppDZFreL5gbwdYF58AF4.",
  "sub": "dXceb-vuZUHtLrDxHBgpCo9xRtEF2GgrIwEl2Xt3pYk",
  "tenant_region_scope": "NA",
  "tid": "d6b4b8f5-d70a-4959-821d-7ab813a6aaa8",
  "uti": "14BFGMSdu0qzht3YwyD8AA",
  "ver": "2.0"
}
```

Latter this account will cause exception in one of the matchers

![image](https://user-images.githubusercontent.com/12799579/115418151-ef656a00-a201-11eb-95ec-6193f4489b17.png)

As account.getId() will return null
![image](https://user-images.githubusercontent.com/12799579/115418248-0441fd80-a202-11eb-97a7-f1465f0f6f75.png)

Not sure why is there no oid claim at the first place.
One week ago the same app in the same tenant worked fine. So maybe initial cause of this issue is somewhere else

Exception itself
```java
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at java.lang.String.contains(String.java:2224)
        at com.microsoft.identity.client.PublicClientApplication$17.matches(PublicClientApplication.java:1760)
        at com.microsoft.identity.client.PublicClientApplication$AccountMatcher.matches(PublicClientApplication.java:1745)
        at com.microsoft.identity.client.MultipleAccountPublicClientApplication$3$1.onTaskCompleted(MultipleAccountPublicClientApplication.java:251)
        at com.microsoft.identity.client.MultipleAccountPublicClientApplication$3$1.onTaskCompleted(MultipleAccountPublicClientApplication.java:223)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:212)
```

**Comment by iambmelt** [comment]
@VinSmile Are you with the Intune team? Or external to Microsoft?

**Comment by Depesha** [comment]
Is there any update on it? The same issue in this [example application ](https://github.com/msintuneappsdk/ms-intune-app-sdk-android)
