### ISSUE TITLE
Not able to perform SSO with ISingleAccountPublicClientApplication.getCurrentAccount()

### ISSUE THREAD

**Issue by nishi1612** [AzureAD/microsoft-authentication-library-for-android#1370]
**Describe the bug**
MDE Android app with ADAL is currenlt available on Google Play Store. We have migrated to MSAL and want to ship the app. Our app with ADAL supports SSO in Android Enterprise Work Profile, however with MSAL SSO is failing here. We receive that there is no signed in account however CP [broker app] has user logged in. 

**Smartphone (please complete the following information):**
 - Device: One Plus, Samsung
 - Android Version: 29
 - Browser: Chrome
 - MSAL Version: 2.0.8
 - Broker app installed

**To Reproduce**
1. Install Company Portal in Android Enterprise Work Profile.
2. Log into Company Portal in Android Enterprise Work Profile. 
3. Install app in Android Enterprise Work Profile.

Try to login via SSO which fails.

**Expected behavior**
We want SSO to be successful in order to provide best user experience.

**Actual Behavior**
We observe that SSO fails. As a fallback we have kept Interactive login to be triggered and user has to perform interactive login.

**Additional context**
Our app is a first party app and we are part of FoCI. Hence, SSO should be working fine. But we receive failure in SSO.

**Comment by iambmelt** [comment]
@rpdome Assigning this over to you; this appears to be the `getAccounts()` question we got w.r.t no tokens in cache. @nishi1612 AFAIK our team has already communicated with you via IcM and we are tracking this incident there

**Comment by nishi1612** [comment]
Yes @iambmelt , our team has raised ICM for this same issue and it is being tracked there.
