### ISSUE TITLE
After successful authentication with Azure AD B2C access token is available but no id token and claims.

### ISSUE THREAD

**Issue by sidgrover21** [AzureAD/microsoft-authentication-library-for-android#1373]
This is an issue we are facing during development. 

MSAL requires preferred name attribute passed by idp in id token. If not passed MSAL library shows no id_token and null claims after successful authentication and gives error "Missing from the token response"  (ref#https://docs.microsoft.com/en-us/azure//active-directory/develop/msal-net-aad-b2c-considerations#known-issue-with-azure-ad-b2c). ID Token with preferred username from Azure AD works fine. However, with B2C
it is a problem since B2C doesn't send preferred username in ID Token. We'd like to request for flexibility in MSAL library to use any other attribute other than name/preferredusername. Please let us know if that can be done and the timeline for the same

During our debugging, after authentication with proper scope, we did a network trace on the token call's response and found that the id_token is part of the server response. However, this authentication result object has the access token but does not contain a id token and the `result.account.claims` object is also null. So there is no way for us to lay our hands on the `id_token`. Our requirement is to get an `id_token`.

See redacted network response below. All tokens were successfully deciphered in https://jwt.io/ and the tokens are different.

```json
{
  "access_token": "eyJ0eXAiOiJKV1Q...",
  "id_token": "eyJ0eXAiOiJKV1QiLCJhbG...",
  "token_type": "Bearer",
  "not_before": 1619017302,
  "expires_in": 3600,
  "expires_on": 1619020902,
  "resource": "8d661e64-10e5-4aa2-ac13-fd27bafa16cb",
  "client_info": "eyJ1aWQiOiItYjJjXzFhX3...",
  "scope": "https://ourcompanystagingenvironment.onmicrosoft.com/api1/read",
  "refresh_token": "eyJraWQiOiJrMk53dkJ1VjZ4eU9WaU9...",
  "refresh_token_expires_in": 1209600
}
```

Our code is from the Azure AD B2C java samples on github. We have barely made any changes to it except the config file from our Azure subscription and a few tweaks to prevent a crash.

**Smartphone (please complete the following information):**
 - Android Pixel 2 emulator, Sonim XP8
 - Android Version  API Level 24, 25 and 28
 - MSAL Version - 2.+

**Expected behavior**
Upon successful authentication we should get an id token and claims in the authentication result object but are only getting an access token.

**Actual Behavior**
Authentication result object has null claims and no id token in it `authenticationResult.account.idToken` property

**Comment by iambmelt** [comment]
@sidgrover21 If you getting the `id_token` in the response and successfully completing `acquireToken` (interactive), this should be available on the resulting `IAuthenticationResult` object yielded by this library. If you're still facing this issue, consider creating a test/demo account I might be able to troubleshoot with and reach out to me at `brianmel` at `microsoft.com`
