### ISSUE TITLE
MSAL For Android Platform Auto Computed Redirect URI

### ISSUE THREAD

**Issue by vinhdp195** [AzureAD/microsoft-authentication-library-for-android#1391]
MSAL version: 2.0.10
Using MSAL to get token
Code in My App:
```
PublicClientApplication.create(context
                               , ClientId
                               , authority
                               , redirectUri
                               , new PublicClientApplication.ApplicationCreatedListener() {
                                 @Override
                                 public void onCreated(IPublicClientApplication application) {
                                     clientApplication = (IMultipleAccountPublicClientApplication) application;
                                     listener.onCreated(INSTANCE);
                                 }

                                 @Override
                                 public void onError(MsalException exception) {
                                     listener.onError(exception);
                                 }
                               });
```
I initialized PublicClientApplication with the above code
Required parameters pass a redirectUri
In case of using a config file, it is also required to pass a redirectUri
(Or setting redirectUri at AppManifest)
I'm having to copy directly from the AzurePortal Android Platform

However, if I refer to MSAL.NET, the redirectUri is automatically computed
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#redirect-uri-for-public-client-apps
> You don't need to add a redirect URI if you're building a Xamarin Android and iOS application that doesn't support the broker redirect URI. 
> It is automatically set to msal{ClientId}://auth for Xamarin Android and iOS.

Is there an automatic computed mechanism in MSAL for Android like MSAL.NET?
I did not find any documentation about this.
MSAL for Android does not automatically computed Redirect URI, in the future do you intend to develop this?

**Comment by vinhdp195** [comment]
@vladzaharia @i-am-dan @shuagarw-ms @RamonPage

**Comment by vinhdp195** [comment]
Help Me !!! @shoatman

**Comment by slowcar** [comment]
Try showExpectedMsalRedirectUriInfo of the PublicClientApplication class

If you want to check out the source it uses, it's in the PackageHelper class

**Comment by vinhdp195** [comment]
@slowcar showExpectedMsalRedirectUriInfo seems to be just for viewing
I need to get a value that I can use to pass it to the function PublicClientApplication.create

**Comment by slowcar** [comment]
Well, you view it, copy it and put it into your configuration file (and register it with Azure AD).
If you are somehow unable to start the activity, you can execute the code from PackageHelper in your class somewhere, it's basically just your package signature in base64

**Comment by markbeij** [comment]
Something like this


    /**
     * This code can be used to show the internally detected base64 signing hash of the package
     *
     * @return
     * @throws PackageManager.NameNotFoundException
     * @throws NoSuchAlgorithmException
     */
    private String CalculateSigningHash() throws PackageManager.NameNotFoundException, NoSuchAlgorithmException, UnsupportedEncodingException {
        final PackageInfo info = getContext().getPackageManager().getPackageInfo(getContext().getPackageName(), PackageManager.GET_SIGNATURES);

        final MessageDigest md = MessageDigest.getInstance("SHA");

        final Signature signature = info.signatures[0];
        md.update(signature.toByteArray());
        final byte[] bytes = md.digest();
        final String base64EncodedSigningHash = Base64.encodeToString(bytes, Base64.DEFAULT);

        return base64EncodedSigningHash.replace("\n", "");
    }
