### ISSUE TITLE
MSAL Authenticator approach - Authenticator app is not getting launched (Once killed the Authenticator explicitly) 

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1396]
**Describe the bug**
In Android, when we call the method "publicClientApplication.acquireToken(mAcquireTokenParameters);" with the usebroker values as true, it launches the Authenticator app fine and entering the password every thing working fine.

Suppose when we press back on the Authenticator app we get this log in MSAL sdk, which is expected
2021-05-13 18:18:34.366 1430-1844/com.fiberlink.maas360.android.pim W/MaaS360 Mail:MaaS360SDK: pool-3-thread-1 | MaaS360MSALLogger |  [2021-05-13 12:48:34 - thread_name : interactive-1, correlation_id : 1e552da1-ce9c-4545-8be7-3cd0c604c226] Received a com.microsoft.identity.common.exception.UserCancelException from Broker : User cancelled Android 28

**But the scenario like when we explicitly kill the Authenticator app(Either force stop or kill the app with swipe) without giving password, in this case when we try call this api again "publicClientApplication.acquireToken(mAcquireTokenParameters);" Authenticator app is not get launched**. 
In the above case third party app wont get this call back "com.microsoft.identity.common.exception.UserCancelException".

**Smartphone (please complete the following information):**
 - Device: All Devices
 - Android Version: All version
 - Browser NA
 - MSAL Version 2.0.10

**Stacktrace**
No crash 
**But in the "com.microsoft.identity.common.internal.controllers.CommandDispatcher" "beginInteractive()" method didn't  get proceed.  sInteractiveExecutor.execute(new Runnable() {} Here task is keep get queued up.**

**To Reproduce**
1. From third party app launch the Authenticator app. (publicClientApplication.acquireToken(mAcquireTokenParameters))
2. When Authenticator app prompts for the login screen.
3. Kill the Authenticator app explicitly. (Either force stop or kill the app with swipe)
4. After that same code flow to launch Authenticator is not working.

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
Even when we kill the Authenticator App , when we try to launch again using "publicClientApplication.acquireToken(mAcquireTokenParameters);" it should work

**Actual Behavior**
Once kill the Authenticator App, when we call this method "publicClientApplication.acquireToken(mAcquireTokenParameters);" its not launching the Authenticator.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by shoatman** [comment]
Hi @vramasam  - When you say that you close the authenticator do you mean that you opened the recents/overview window and closed the task hosting the authenticator(broker)/signin page?

**Comment by vramasam** [comment]
Hello @shoatman  It's happening in Android device. So for clear understanding when I meant close we can take the case of force stop the Authenticator when it shows the sign-in page . ( Settings -> Apps -> Authenticator - > Force stop) . Other case simply swipe the Authenticator app when it shows the sign-in page kills the Authenticator app process.

In both these cases I m seeing com.microsoft.identity.common.internal.controllers.CommandDispatcher" "beginInteractive()" method didn't get proceed. sInteractiveExecutor.execute(new Runnable() {} Here task is keep get queued up. 

During above case (kill the Authenticator explicitly) , Everytime when I call the publicClientApplication.acquireToken(mAcquireTokenParameters) queue size is keep on increasing but it's not launching the Authenticator sign-in page.

**Comment by shoatman** [comment]
Thanks.  I'm working on a fix for this; however the fix will require configuration changes in MSAL config and your manifest.

**Comment by vramasam** [comment]
Okay @shoatman . Thank you.

Can you please tell what can be the change in configuration, is there any effect custom browser/ browser based flow?
And also what is the change we need to add in the manifest, please add that also.

Thank you

**Comment by davidkarlsson** [comment]
For me this can happen even if you don't kill the Authenticator app but just simply switch back to the app that you're logging in with by clicking the launcher icon or the apps foreground notification. I'm guessing this is because the activity it launches has its `launchMode` set to `singleTask`?

When you call `SingleAccountPublicClientApplication:signIn()` a subsequent time after switching back to the app the runnable passed to `sBackgroundExecutor` in `acquireTokenInternal()` never runs.

This completely breaks the sign in flow because the the app has no way of knowing that something went wrong with the sign in since the error callback is never called.

**Comment by vramasam** [comment]
For your information, we are using using MultiAccountPublicClientApplication and I observed this issue is happening only when we the Authenticator app is killed explicitly. Suppose if we press back button in phone or back button of the Authenticator app screen, it gives the proper callback "MSALUserCancelException".

And the activity that launches the Authenticator app , there is no launch mode has been set. so it's standard. 

What we observed during the Authenticator app kill scenario, in the MSAL SDK we have mentioned like **com.microsoft.identity.common.internal.controllers.CommandDispatcher" "beginInteractive()" method didn't get proceed. sInteractiveExecutor.execute(new Runnable() {} Here task is keep get queued up.**

And also there is VisibleForTesting (Note: Just for testing) "static method clearState()" is present in the MSAL sdk "CommandDispatcher" class when we call that method before calling publicClientApplication.acquireToken(mAcquireTokenParameters) during that case, Authenticator app is launching every time even if we kill the app.

"This completely breaks the sign in flow because the the app has no way of knowing that something went wrong with the sign in since the error callback is never called."
 Here your point is valid, the same happening in case of Authenticator app killing case. So our suggestion, the same way when we press back button in the Authenticator there is an error call back is sent to the app, when the Authenticator app gets killed, it should sent "MSALUserCancelException" along with data clearance in the SDK.

Please let us know if you have any suggestion from your end.

**Comment by davidkarlsson** [comment]
> And the activity that launches the Authenticator app , there is no launch mode has been set. so it's standard.

I think maybe you misunderstood this. I meant that the activity of our app that the click on the foreground service notification or the launcher icon starts has `launchMode` set to `singleTask` and not the Authenticator apps activity.

I'm guessing this is relevant to this issue because this launch mode makes it so the activity will always be at the root of the activity stack for the task it creates so this will remove the task the Authenticator app started in when `signIn()` is called.

**Comment by vramasam** [comment]
@shoatman  Can you give any approximate release plan

**Comment by gauravadr** [comment]
@shoatman, any update on this issue.

**Comment by mundhava** [comment]
@shoatman facing the same issue, is there any alternative to breaking the flow to handle such a situation? what's the release plan for a permanent fix?

**Comment by chanakya-raichur** [comment]
We also facing the same issue if fix was provided can you provide the details of it & the version in which that issue resolved.
