### ISSUE TITLE
ISingleAccountPublicClientApplication#getCurrentAccount() returns null while trying to achieve complete SSO between native apps

### ISSUE THREAD

**Issue by emilmarkose** [AzureAD/microsoft-authentication-library-for-android#1403]
**Describe the bug**
I am trying to achieve SSO between two native apps. The device doesn't have a broker app installed.

```
mSingleAccountApp?.currentAccount?.currentAccount
```
The getCurrentAccount method returns null when I tried to login to the second application after success-full login with the first app.

**Smartphone:**
 - Device: Samsung Galaxy S10+
 - Android Version: Android 11 (API Level 30)
 - Browser: Chrome tab
 - MSAL Version: 2.0.6

**To Reproduce**

1. Login to App-1 with `authorization_user_agent=DEFAULT`
2. Entered credentials and successfully logged in (via chrome tab)
3. Launched App-2 and successfully logged in with `authorization_user_agent=DEFAULT` (via chrome tab)

I am using the below configuration for both of the apps, but with different `client_id` and `redirect_uri`

```
{
  "client_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "msauth://com.xxxx.xxx/xxxxxxxxxxxxxxxxxxxxx%3D",
  "account_mode": "SINGLE",
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
      }
    }
  ]
}
```

**Expected behavior**
App-2 should get the silent token without showing the account selector page.

**Actual Behavior**
App-2 shows account selector page (but the account shows as signed in) in chrome tab. This happens because the `getCurrentAccount()` returns null.

**Additional context**
Both of the apps are registered as two separate applications in Azure under same tenant.

**Comment by rpdome** [comment]
Hi @emilmarkose 

This is by design. MSAL does not share account between apps.

User must take an 'action' to sign into each app -  either by logging in from scratch, or just provide a login hint [If the broker is installed and the user has registered their device](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/walkthrough--workplace-join-to-an-android-device) - we don't want them to be silently signed into another app without their knowledge. 

Thanks,
Dome

**Comment by emilmarkose** [comment]
Thanks @rpdome for the information. I have one more questions in this case.

I am getting this same behaviour if both of my applications has only one registration in Azure. Means both of the apps are using same `clientId` but different `redirect_uri`. Here also I am getting the currentAccount as null.

Is is also by design? Because I am not getting this accountSelector in iOS if both apps are under same clientId.

**Comment by rpdome** [comment]
@emilmarkose yes, we also use app uid to store account data.
