### ISSUE TITLE
AuthorizationFragment using deprecated fragment manager

### ISSUE THREAD

**Issue by Tarapaty** [AzureAD/microsoft-authentication-library-for-android#1406]
**Is your feature request related to a problem? Please describe.**
AuthorizationFragment line 116 and 117 is using getFragmentManager() 

**Describe the solution you'd like**
Should be using getChildFragmentManager()

**Comment by iamgusain** [comment]
Thanks for reporting this, 
I have added a workitem in our backlog to address this. (PRODUCT BACKLOG ITEM 1409307)
