### ISSUE TITLE
Adding Chromium to "browser_safelist" is not working

### ISSUE THREAD

**Issue by hkobagh** [AzureAD/microsoft-authentication-library-for-android#1407]
**Describe the bug**
I want to use Chromium (org.chromium.chrome) with MSAL. But, my app never open Chromium for authentication. My app uses MSAL which I added Chromium to "browser_safelist" then.

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X705F
 - Android Version: API 29
 - Browser Chromium
 - MSAL Version 2.0.10

Other devices (API 16 and 21) got the same result. I guess that any device never open Chromium with my app.

**Stacktrace**
n/a

**To Reproduce**
I referred to #1187. Then I added the following code to "browser_safelist" and built it.
```
    },
    {
      "browser_package_name": "org.chromium.chrome",
      "browser_signature_hashes": [
        "flIU1iFHjL3IKEqiD5L3/74rcaTicT7NigI4wiAa7BE6YyWvUNv50O1/NpBnmdS2unOBHIQ1URMREIkPHJO8nw=="
      ]
```

When Chrome or Firefox is set as the default browser, they are opened. Then, when those browsers are not installed, WebView is opened.

Even if Chromium is installed and set as the default browser, then it is ignored.

**Expected behavior**
Chromium is opned by MSAL that is added Chromium in "browser_safelist".

**Actual Behavior**
Chrome, Firefox and WebView is opened by MSAL, but Chromium is ignored.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by iamgusain** [comment]
@hkobagh What is the value of "authorization_user_agent" set to in your config?

**Comment by hkobagh** [comment]
@iamgusain The value of "authorization_user_agent" is set to "DEFAULT".

**Comment by iamgusain** [comment]
@hkobagh I will try you scenario and get back. Which chromium based browser are you trying with?
Also do you see any errors/warnings in the logs

**Comment by hkobagh** [comment]
@iamgusain The browser that I'm trying is Chromium (org.chromium.chrome), not other chromium based browsers. 

The download URL is here.
https://download-chromium.appspot.com/
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html

I'm trying to find error/warnings in the log, but I couldn't find it when MSAL didn't open Chromium.

**Comment by iamgusain** [comment]
@hkobagh I think the package name that you want to use is "**com.android.chrome**" instead of "org.chromium.chrome"


    {
      "browser_package_name": "com.android.chrome",
      "browser_signature_hashes": [
        "7fmduHKTdHHrlMvldlEqAIlSfii1tl35bxj1OXN5Ve8c4lU6URVu4xtSHc3BVZxS6WWJnxMDhIfQN0N0K2NDJg=="
      ]
  }

**Comment by iamgusain** [comment]
If you are trying other channels (beta/dev/canary) than the package name would be either
"com.chrome.beta", "com.chrome.canary", "com.chrome.dev"

**Comment by hkobagh** [comment]
@iamgusain I think that using "com.android.chrome" instead of "org.chromium.chrome" is the same of the original MSAL code. Also, I have already used "com.android.chrome", because I didn't delete it when I added "org.chromium.chrome" to "browser_safelist".

I am not trying other channels of Chromium, but I confirmed that the package name is "org.chromium.chrome" by "adb shell pm list packages" command after installing it.

**Comment by iamgusain** [comment]
@hkobagh how are you installing the browser, I tried to install from the links you provided above and I don't see the package name "org.chromium.chrome" from the command "adb shell pm list packages".  I only see the package names as I listed above.

**Comment by hkobagh** [comment]
@iamgusain 
I installed Chromium by the following process and confirmed the package name.

0. Run "adb shell pm list packages" and save the results.
1. Open "https://download-chromium.appspot.com/?platform=Android&type=snapshots".
2. Click "downloadchromium" and download "chrome-android.zip".
3. Install "ChromePublic.apk".
4. Run "adb shell pm list packages" and compare with before.
There are a new line "package:org.chromium.chrome" then.

This way is for the latest version. The way to install the old version is almost the same, but you have to look for it from "continuous builds archive" to download it.
For example, this url is the "800212" Commit Position.
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Android/800212/

**Comment by iamgusain** [comment]
@hkobagh Thanks for the details, I was able to install it that way and figured that the problem is with the signature hash 
Please try with this hash
flIU1iFHjL3IKEqiD5L3_74rcaTicT7NigI4wiAa7BE6YyWvUNv50O1_NpBnmdS2unOBHIQ1URMREIkPHJO8nw==

**Comment by hkobagh** [comment]
@iamgusain Thank you for your advice. My app opens Chromium now! The hash I calclated is wrong.

Why did the underscore become a slash? I confirmed that both of Windows and Mac is the same "slash" result. My commands is here. 

```
$ openssl pkcs7 -in CHROMIUM.RSA -print_certs -inform DER > CERT.pem
$ openssl x509 -in CERT.pem -outform der | openssl sha512 -binary | openssl base64
```

**Comment by iamgusain** [comment]
I am not sure, maybe something to do with the base64 encoding. 

I will be marking this issue as closed.
