### ISSUE TITLE
During MSALUIRequiredException when sign-in-freqency expired gives expired token for sometime even after successful interactive login

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1409]
**Describe the bug**
We have set the sign-in frequency for 1 hour to an account. Once the Sign-in frequency got expired, it throws MSALUIRequiredException with the following error code "invalid-grant" and the error message contains "Caused by: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on xxxxxxxxxxxx and the maximum allowed lifetime for this request is 3600." which is expected.

In this case, we have did the interactive login and it gives the proper token with proper expiry time. After successful interactive login, if we call the silent api it gives the "invalid grant" exception with old token information for 5 to 15 seconds(this time varies) time interval. And also some times, it gives the proper token at first silent api call but most of the time it gives after 5 seconds till then giving old token. This issue is mostly observed in Azure password based approach not seen in ADFS Certificate based.

**Smartphone (please complete the following information):**
 - Device: All
 - Android Version: All
 - Browser All
 - MSAL Version 2.0.10

**Stacktrace**
04-28-2021 14:50:45.555 | E | main | sa0 | getSilentAuthenticationCallback failed to acquire token silently invalid_grant msg : AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-04-27T09:53:13.5952036Z and the maximum allowed lifetime for this request is 3600.
Trace ID: ab2de6ef-96f1-4460-971d-2808e12ac400
Correlation ID: f3263040-1e03-44f0-8d69-e8ece2fdd277
Timestamp: 2021-04-28 09:20:31Z
com.microsoft.identity.client.exception.MsalUiRequiredException: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-04-27T09:53:13.5952036Z and the maximum allowed lifetime for this request is 3600.
Trace ID: ab2de6ef-96f1-4460-971d-2808e12ac400
Correlation ID: f3263040-1e03-44f0-8d69-e8ece2fdd277
Timestamp: 2021-04-28 09:20:31Z

Caused by: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-04-27T09:53:13.5952036Z and the maximum allowed lifetime for this request is 3600.
Trace ID: ab2de6ef-96f1-4460-971d-2808e12ac400
Correlation ID: f3263040-1e03-44f0-8d69-e8ece2fdd277
Timestamp: 2021-04-28 09:20:31Z
at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(SourceFile:16)
at com.microsoft.identity.client.PublicClientApplication$18.onError(SourceFile:2)
at com.microsoft.identity.client.PublicClientApplication$18.onError(SourceFile:1)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(SourceFile:1)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100(SourceFile:1)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(SourceFile:4)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8512)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Azure password based.
2. Set the sign-in frequency for an account for 1 hour.
3. Wait for the token to expire.
4. Do the interactive login.
5. Silent api should give the valid token immediately every time.

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
Once the interactive login gets success, in the next silent api call it should return the proper valid token immediately.

**Actual Behavior**
Even after the interactive login gets success, in the next silent api call it's returning old token information.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by iambmelt** [comment]
@vramasam Can you try this scenario with the [`2.0.12` build](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.0.12)? I suspect what you're seeing here is our request cache turnover, which was disabled in our [common 3.4.3](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/releases/tag/v3.4.3) release. If that doesn't resolve the issue, you can try specifying `forceRefresh=true` on the request to bypass the cache for a new token... I suspect that `2.0.12` has the fix you need

**Comment by vramasam** [comment]
@iambmelt  Thank you its working as expected with latest library. I am closing the ticket.
