### ISSUE TITLE
OpenID App authentication Issue in Android app

### ISSUE THREAD

**Issue by ChetnaNakum** [AzureAD/microsoft-authentication-library-for-android#1413]
I found below log and can not complete OpenID App authentication in application. Could you please help?
```
W/BrowserAuthorizationFragment:  [2021-05-31 13:12:14 - {"thread_id":"1","correlation_id":"UNSET"}] Calling activity class is NULL. Unable to create intent for response. Android 24

 W/BrowserTabActivity:  [2021-05-31 13:12:14 - {"thread_id":"1","correlation_id":"UNSET"}] Received NULL response intent. Unable to complete authorization. Android 24
```

**Comment by AdamBJohnsonx** [comment]
This would typically happen when the calling application is closed after the authorization request was started.  Can you give us some more insight into what you've got going on here?

**Comment by ChetnaNakum** [comment]
My application remain open while authorization request going on. I have integrated openId Authentication in my application using this library [](https://github.com/openid/AppAuth-Android)
I got below error from Microsoft. 
**Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.**
