### ISSUE TITLE
How is invalid_grant handled?

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#142]
The error code for `OauthConstants.ErrorCode.INVALID_GRANT` seems to be unused. Do we plan to wire this up? If not, we should remove it.

**Comment by weijjia** [comment]
Well, we should use the error code in oauth2Constants for error_code comparison. Sent the PR, see https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/151

**Comment by weijjia** [comment]
Closed with PR#151
