### ISSUE TITLE
Need To access Web application which is hosted in Azure MSAL in android webview

### ISSUE THREAD

**Issue by EcAkash** [AzureAD/microsoft-authentication-library-for-android#1443]
We are having two application one is deployed in web and secured using msal now we have made another mobile app and we want to access that web application in android mobile app. After successfully authenticating android mobile app i launch web application. It again ask for sign in. 
I tried to pass the MSAL Access token in header to webview where website url is loading but nothing changed it again requested for sign in. 
Is there a way i can pass MSAL android access token to Web application and access it without again sign in request?

App is in development

**Smartphone (please complete the following information):**
 - Pixel
 - Android 11
 -Chrome
 - 2.0+

**Stacktrace**
No Stack trace.

**To Reproduce**
Login in mobile app. Open any web app which is msal secured in webview. Pass the access token. even after being part of sso that webapp is asking again sign in

**Comment by shahzaibj** [comment]
Hi @EcAkash Thanks for reaching out. Which website are you trying to access? Is this a Microsoft site or some custom site? If this is a custom website, what authentication library are you using to authenticate with the website?

**Comment by EcAkash** [comment]
Hi @shahzaibj  this is microsoft site developed and deployed by same organisation. So its an ESO authentication in that website using msal library. while i login from chrome i can access that website as it accepts my enterprise login credentials. But when i login into my native app from same login credential and inside my app i access that website in webview its not taking that msal token. May be website takes cookie jar or some other issues.

**Comment by EcAkash** [comment]
Hi @shahzaibj. did you get a chance to look into this?
