### ISSUE TITLE
Error OOM when try to access MSAL

### ISSUE THREAD

**Issue by matheusfreire** [AzureAD/microsoft-authentication-library-for-android#1453]
**Describe the bug**
We are receiving an error (thus killing the journey) when trying to go through our journeys. It's live in production.

**Smartphone (please complete the following information):**
Device: Samsung (J2 Core, J4, J5, J7 and A20) and Motorola (Moto E)
Android Version: Android 8 and 10
Browser Chrome
MSAL Version 2.0.12

**Stacktrace**
`com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getInputStream (HttpsURLConnectionExtension.java:379)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.executeHttpSend (UrlConnectionHttpClient.java:262)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.access$100 (UrlConnectionHttpClient.java:72)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call (UrlConnectionHttpClient.java:175)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call (UrlConnectionHttpClient.java:173)
com.microsoft.identity.common.internal.net.StatusCodeAndExceptionRetry.attempt (StatusCodeAndExceptionRetry.java:59)
com.microsoft.identity.common.internal.net.StatusCodeAndExceptionRetry.attempt (StatusCodeAndExceptionRetry.java:20)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.method (UrlConnectionHttpClient.java:173)
com.microsoft.identity.common.internal.net.AbstractHttpClient.method (AbstractHttpClient.java:14)
com.microsoft.identity.common.internal.net.HttpRequest.sendWithMethod (HttpRequest.java:387)
com.microsoft.identity.common.internal.net.HttpRequest.sendGet (HttpRequest.java:214)
com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery (AzureActiveDirectory.java:186)
com.microsoft.identity.common.internal.authorities.Authority.performCloudDiscovery (Authority.java:288)
com.microsoft.identity.common.internal.authorities.Authority.getKnownAuthorityResult (Authority.java:370)
com.microsoft.identity.common.internal.controllers.LocalMSALController.acquireToken (LocalMSALController.java:129)
com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute (InteractiveTokenCommand.java:67)
com.microsoft.identity.common.internal.commands.InteractiveTokenCommand.execute (InteractiveTokenCommand.java:39)
com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand (CommandDispatcher.java:279)
com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200 (CommandDispatcher.java:74)
com.microsoft.identity.common.internal.controllers.CommandDispatcher$4.run (CommandDispatcher.java:470)`

**To Reproduce**
Open MSAL and expected to acquireToken.

**Expected behavior**
The msal should acquire token and run without error

**Actual Behavior**
The app which is running throw MSAL is crashing.

@ralexandre-ciandt

**Comment by shoatman** [comment]
Does OOM mean out of memory?  Possible to share your MSAL configuration file here?

**Comment by matheusfreire** [comment]
@shoatman is there some way to send to you a safe way this info? Here we can't display.
