### ISSUE TITLE
Distribution of MS-Authenticator app in shared mode (for single-sign-on) without Intune.

### ISSUE THREAD

**Issue by meinto** [AzureAD/microsoft-authentication-library-for-android#1457]
This is not directly library related but it's necessary to know before you start using it. Therefore I ask this question here.

We want to use the brokered authentication with the MS-Authenticator for our apps as SSO solution and I was told that distributing the MS-Authenticator app in shared mode without Intune is not really possible. The thing is, we already have a MDM and already have our workflows implemented. Assuming switching our MDM wouldn't be an option for us. 

Is it correct that the usage of this library with MS-Authenticator in shared mode, to implement a brokered SSO flow for native apps is only scalable by using Intune for the MS-Authenticator rollout? Or is there a way to configure MS-Authenticator with, for example sending intents with payload, to setup the [shared device mode](https://docs.microsoft.com/de-de/azure/active-directory/develop/tutorial-v2-shared-device-mode#set-up-an-android-device-in-shared-mode). 

I hope I haven't missed this section in the documentation.
Thank you for your support.

**Comment by shoatman** [comment]
@rpdome @hamiltonha @iamgusain @Om83 - FYI - I'm not sure what the official restrictions are here.  I believe that I suggested a long time ago that it be possible for the cloud device admin to be able to enroll a device in shared device mode in the way that's proposed by @meinto.

**Comment by meinto** [comment]
Just to clarify my concern: We were able to set the MS-Authenticator in shared mode with [the instructions of the documentation](https://docs.microsoft.com/de-de/azure/active-directory/develop/tutorial-v2-shared-device-mode#set-up-an-android-device-in-shared-mode). But this is the manual way to do this. We want to automate the rollout process for the MS-Authenticator on our company devices with our existing MDM. Therefore I asked for way to do this, because the manual instructions doesn't fit here. 

Reading the manual instructions you need to click several buttons, type in your cloud admin password and so on. This is not practicable for a remote initialization of the MS-Authenticator.

The question is, how can we achieve a MS-Authenticator initialization in shared mode, without manual interactions.

**Comment by meinto** [comment]
Are there any news on this topic? We need to decide in the next view days wether to go with MS-Authenticator for SSO or looking for another solution.

**Comment by jsroest** [comment]
> Are there any news on this topic? We need to decide in the next view days wether to go with MS-Authenticator for SSO or looking for another solution.

Did you ever had an answer or found a solution?

**Comment by meinto** [comment]
@negoe, why did you close this issue? Is there a solution for this in the meantime?

**Comment by meinto** [comment]
@shoatman, @iamgusain, @rpdome, @hamiltonha, @Om83, do you have further informations reguarding this topic?

**Comment by jsroest** [comment]
It's the same for an issue that I have raised #1514. All issues are being closed with the 'cleanup' label. I also asked about the reason why it was closed, but there is just no response.

**Comment by akgoel23** [comment]
Hi @meinto, 
Currently, Zero Touch Provisioning (ZTP), which includes automation of rollout process for the MS-Authenticator on company devices, is only available with Microsoft Endpoint Manager. We acknowledge the importance of supporting ZTP for Microsoft’s Shared Device Mode (SDM) by 3rd party MDMs and are thus working tirelessly with them to support it. To get the latest update on the status of your MDM in enabling ZTP with Microsoft's SDM, please reach out to your MDM.

**Comment by markdegrootnl** [comment]
In the Managed Configuration of the Microsoft Authenticator app for Android, there is a configuration option called `sharedDeviceRegistrationToken`:
```
description: Temporary token used to auto-complete device registration in shared mode (Do not update manually).
key: sharedDeviceRegistrationToken
title: Shared Device Mode Registration token
```

Is there a way to generate this token? This way we could use the Authenticator app in Shared Device Mode with any MDM solution.
