### ISSUE TITLE
Sign-in with "Accounts in this organizational directory only - single tenant" not work with this library

### ISSUE THREAD

**Issue by wgbnyes** [AzureAD/microsoft-authentication-library-for-android#1461]
**Describe the bug**
We are having a serious problem when trying to log in via Azure AD Single-tenant.
We've read many forums and many other issues and no solution or answer seems to explain how to correctly configure a native android application, using msal library, to work as it should.
The error says that we are using an incompatible endpoint, but there is no way to force an endpoint in the current configuration of the msal.config file. We are currently with our hands tied.

We did all the setup correctly. We chose "Accounts in this organizational directory only - single tenant" in Supported Account Types.
We configure the return URLs using package name + sha when adding the Android platform.
We configured msal_config.json as shown:
```
{
  "client_id": "my-client-id",
  "redirect_uri": "msauth://my-package-name/sha",
  "broker_redirect_uri_registered": true,
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "my-tenant-id"
      }
    }
  ]
}
```

We configure the intent-filter in android manifest as shown:
```
<activity
      android:name="com.microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data
          android:scheme="msauth"
          android:host="my-package-name"
          android:path="/sha" />
      </intent-filter>
    </activity>
```

**Smartphone (please complete the following information):**
 - Device: OnePlus 3T
 - Android Version: 9
 - Browser Chrome and Edge
 - MSAL Version: 2.+

**Stacktrace**
```
Authentication failed: com.microsoft.identity.client.exception.MsalServiceException: AADSTS50194: Application 'my-tenant-id-here'(PORTAL_APPGAMIFICATION) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
    Trace ID: db590646-c5c9-4c06-8af5-d826f4127301
    Correlation ID: cafd4040-eb7c-4ebb-ac08-3950048fd58e
    Timestamp: 2021-07-12 10:17:58Z
```

**To Reproduce**

1 - Set up an Azure app with single-tenant
2 - Configure the android platform with your package name and the sha generated with your subscription key
3 - Configure msal.config as indicated above
4 - Try running the app on your mobile 

**Expected behavior**
It was expected that the token would be returned and the login process would complete. 

**Actual Behavior**
The login process runs well halfway through. The app correctly opens the Microsoft login screen, you can fill in the user's email and password, but when you go to login, this error appears in the android LOG: 
```
Application 'my-tenant-id-here'(PORTAL_APPGAMIFICATION) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

**Additional context**
We don't want multi-tenant. We don't want any logins that aren't from within our organization's directory. It makes no sense to reconfigure Azure AD to "multi-tenant", the library should work fine with the single-tenant option.

**Comment by wgbnyes** [comment]
It appears that the "authorities" > "audience" > "tenant_id" setting in msal.config is simply ignored.

```
{
  "client_id": "3d67efb5-285d-401c-bd5c-081b8b56e97c_",
  "redirect_uri": "msauth://com.ageas.somosageas/q5%2BA09hsPfQ%2B2kSpzs4bz%2BCJbWI%3D",
  "broker_redirect_uri_registered": false,
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "e7f9d69c-13f3-457c-a04c-f555c1134fa4"
      },
      "default": true
    }
  ]
}
```

**Comment by iambmelt** [comment]
Hi @wgbnyes - Sorry to hear you're running into issues.

I tried using your configuration in my local test harness (using MSAL 2.1.0) and am not observing the behavior you reported -- I am instead taken to a tenant specific endpoint. Are there perhaps multiple configurations in your workspace which could be getting mixed up? Any hints you can give me that might help me troubleshoot this issue?

Screenshot below from my local test

![image](https://user-images.githubusercontent.com/990063/125358664-0e195f80-e31e-11eb-8db8-eaeb004c664e.png)

**Comment by wgbnyes** [comment]
Thanks for the answer, however, even this screen that you are showing I can also get there without any problems.
The problem occurs when I login on this screen, the feedback that the MSAL Library gives is the error.

But I discovered one thing, there is an incompatibility between the redirect created in the manifest and the string registered in Azure AD on the Android platform.

Special characters that may exist in the SHA generated from the app's subscription key are transformed to URLEncoded. This works fine for msal.config.json in redirect_uri.
But when creating the Intent Filter on manisfest, errors occur if I use this SHA with URLEncoded
