### ISSUE TITLE
Migrating MSAL 1.3 and Sign in with MSAL 2.0.8 cause error at acquireTokenSilentAsync

### ISSUE THREAD

**Issue by MiguelBenitezGomez** [AzureAD/microsoft-authentication-library-for-android#1475]
I'm getting the following error when I'm calling acquireTokenSilentAsync with a user who is using MSAL 2.0.8 and was sign in using MSAL 1.3:

2021-08-02 11:35:17.298 6153-6153/ng.sch.bridge.letsmark D/AuthenticationRepository$getAcquireTokenSilentAsyncCallbackNew:  Error occurred while Logging in The signed in account does not match with the provided account.
    com.microsoft.identity.client.exception.MsalClientException: The signed in account does not match with the provided account.
        at com.microsoft.identity.client.SingleAccountPublicClientApplication.acquireTokenSilentAsync(SingleAccountPublicClientApplication.java:676)
        at com.bridge.adloginflow.data.repository.AuthenticationRepository$acquireTokenSilentAsyncNew$1.subscribe(Unknown Source:98)

**Comment by rpdome** [comment]
@MiguelBenitezGomez 
- may I ask for MSAL logs? 
- Are you always calling getAccounts/getCurrentAccount prior to the silent token request, or are you caching it somewhere?

**Comment by MiguelBenitezGomez** [comment]
@rpdome 

I put relevant part of the log in the previous post. I don't think is there anything else that talk about the problem but I can get you a full log if you really need it.

I'm getting the application using this:
`    fun getApplication(context: Context) =
        Single.create<PublicClientApplicationData> { singleSubscriber ->
            PublicClientApplication.createSingleAccountPublicClientApplication(
                context, BridgeAADLoginFlowManager.CONFIG_FILE_RESOURCE_ID,
                applicationCallback(singleSubscriber)
            )
        }` 
        
 And I'm getting tokens using the app as this:
 `    fun acquireTokenSilentAsyncNew(
        tokenDataInfo: TokenDataInfo,
        application: ISingleAccountPublicClientApplication
    ): Single<AuthToken> =
        if (!clientsIdMap.containsKey(tokenDataInfo.resourceId)) {
            Single.just(AuthToken(AuthStatus.NOT_A_KEY_ERROR, tokenDataInfo))
        } else if (!refreshToken(tokenDataInfo.timestamp, tokenDataInfo.expireOn)) {
            Single.just(AuthToken(AuthStatus.SUCCESS, tokenDataInfo))
        } else {
            Single.create<AuthToken> { singleSubscriber ->
                try {
                    val callback = getAcquireTokenSilentAsyncCallbackNew(
                        singleSubscriber,
                        tokenDataInfo.resourceId
                    )
                    Timber.d(
                        "Calling acquireTokenSilently with resourceId = %s userId = %s",
                        tokenDataInfo.resourceId,
                        preferences.userID
                    )

                    val resource = clientsIdMap[tokenDataInfo.resourceId]
                    val scope = arrayOf("$resource/user_impersonation")
                    getParameters(callback, scope)?.let {
                        application.acquireTokenSilentAsync(it)
                    } ?: run {
                        singleSubscriber.onSuccess(
                            AuthToken(
                                AuthStatus.GENERIC_ERROR,
                                TokenDataInfo(tokenDataInfo.resourceId)
                            )
                        )
                    }
                } catch (e: Throwable) {
                    Timber.e(e, "Error in AAD.acquireTokenSilentAsync()")
                    singleSubscriber.onError(e)
                }
            }
        }`
        
  The error is happening when I'm calling `application.acquireTokenSilentAsync(it)` before even using the tokens.

**Comment by rpdome** [comment]
Can you share how you're constructing `AcquireTokenSilentParameters`? (The `getParameters()` function?)

**Comment by MiguelBenitezGomez** [comment]
`    fun getParameters(callback: SilentAuthenticationCallback, scope: Array<String>):
            AcquireTokenSilentParameters? {
        return AcquireTokenSilentParameters.Builder()
            .withScopes(scope.toMutableList())
            .forAccount(account)
            .fromAuthority(BridgeAADLoginFlowManager.AD_AUTHORITY)
            .withCallback(callback)
            .build()
    }`
    
    `val resource = clientsIdMap[tokenDataInfo.resourceId]
                    val scope = arrayOf("$resource/user_impersonation")`

**Comment by jari-kuipers** [comment]
Also running into this right now. Is there any lead as to what causes this error in the first place?

**Comment by Alvarez-GIT** [comment]
Issue with identity mapping between MSAL identity provider accounts and device accounts cache.
Use `acquireTokenSilentAsync` deprecate method.

`app.acquireTokenSilentAsync(scopes, authority, callback)`

This worked to acquire tokens correctly.
