### ISSUE TITLE
URGENT: Refresh token not being returned?! Please, help!

### ISSUE THREAD

**Issue by mirkocuidado** [AzureAD/microsoft-authentication-library-for-android#1486]
I am using this following code to get refresh and access tokens from MSAL Graph, but it only returns the access one.

Code :
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android
      
Obviously, I am using single account mode and the following problems occur. When I add offline_access to the scopes, it says that "Authentication failed: com.microsoft.identity.client.exception.MsalDeclinedScopeException: Some or all requested scopes have been declined by the Server" even tough I added it on the azure portal as enabled. 

Furthermore, I found out that you don't have to specify it, but when I don't specify it (offline_access), but no refresh token is being returned to me...

Does anyone know what is the problem?

If I am making any mistakes or if I keep missing something, could anyone explain the process of getting these tokens?

Thank you!

**Comment by duca9** [comment]
Hi, I have same problem too.

**Comment by p3dr0rv** [comment]
@mirkocuidado @duca9 
The Microsoft Authentication Library (MSAL) currently specifies offline_access, openid, profile, and email by default in authorization and token requests. This means that, for the default case, if you specify these permissions explicitly, Azure AD may return an error.
https://docs.microsoft.com/en-us/graph/permissions-reference#remarks-17
Regarding to refresh token
There are currently no plans to expose the refresh token from MSAL as it would too easily enable developers to implement scenarios that run contrary to our recommended security guidance; for instance, it is not advised for developers to transmit access tokens or refresh tokens off of the device for use elsewhere (that is, except by the intended resource server) -- the refresh token is intended to remain on the device to which it was transmitted. In part, this is so Conditional Access policies can be enforced but it is also to protect credentials from being compromised by man-in-middle or other kinds of interception attacks.

**Comment by rakeshh025** [comment]
@p3dr0rv Since refreshtoken is not exposed now, Could you please advise on how to access files from SharePoint? How do I  get the accessToken for Sharepoint? Please help.

I'm using MSAL SDK 2.2.3 for Android
