### ISSUE TITLE
Non external browser login type

### ISSUE THREAD

**Issue by Halfpint-Code** [AzureAD/microsoft-authentication-library-for-android#1487]
Is there any way to not load an external browser tab when accessing the login screen? Before we updated MSAL, it used to use the native web view and stayed in the app. We have a client who can't allow browsers to be accessible by their users and now has to unlock them. We are hoping we can help them out.

**Comment by p3dr0rv** [comment]
@Halfpint-Code 
You can modify the Android Microsoft Authentication Library configuration file to use an embedded webview when signing in an account or authorizing access to a resource 
 `"authorization_user_agent": "WEBVIEW",`
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration
