### ISSUE TITLE
Failed to load generated key from keystore

### ISSUE THREAD

**Issue by saeidz70** [AzureAD/microsoft-authentication-library-for-android#1489]
**Describe the bug:**

We are using MSAL-for-Android in our application, but we got an error on our device.

Error: com.microsoft.identity.clinet.expection.MsalClinetException: Failed to load generated key from keystore

**Smartphone:**
 - Device: An android device that doesn't have any security settings
 - Android Version: 7.1
 - MSAL Version: 2.0.5
 - Account Mode: Single account
 - Authorization user agent: "WEBVIEW"

**Details:**

The application launches, we enter to WebView page, after pressing the login button, the app returns to the main page and gets the error. 
We tried in both release and debug modes. The result was the same.
I should mention, we have set the Keystore in Azure and Application as well.

![Error on MSAL](https://user-images.githubusercontent.com/63140944/129691513-91a4339b-1e27-4fe3-95be-bd3d9162095f.png)

**Comment by AdamBJohnsonx** [comment]
Looks like this may have been around.  There can be difficulties with AndroidKeyStore on older devices.

See: https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore

Related issue: https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/740
