### ISSUE TITLE
The account set on silent operation parameters is NULL  for multi-tenant accounts

### ISSUE THREAD

**Issue by adarshmanoharan** [AzureAD/microsoft-authentication-library-for-android#1505]
Refresh Token Silently causing these errors when using some of users, not all accounts showing this issue

**Smartphone: 
 - Device: Pixel, OnePlus 6
 - Android Version: 30
 - Chrome
 - MSAL Version 2.0.10

W/MsalOAuth2TokenCache:getAccount:  [2021-08-31 04:00:09 - thread_name : pool-3-thread-1, correlation_id : UNSET] No matching account found. Android 30
W/SilentTokenCommandParameters:  [2021-08-31 04:00:09 - thread_name : silent-1, correlation_id : {Value}] The account set on silent operation parameters is NULL. Android 30

D/MSAL: Message: No cached accounts found for the supplied homeAccountId and clientId

**Expected behavior**
 Refresh Token Silently turns to this issue, normal login works for the first time, when refresh token silently its giving these messages.

**Actual Behavior**
should generate new token

Additional Context: 
iOS and Web works fine, issue is only with Android

**Comment by shahzaibj** [comment]
Hi @adarshmanoharan I think you've got the expected behavior and actual behavior swapped? Is that right?

It looks like you not getting the account back after calling getAccount, while it seems that you've already acquire token with that account before. Can you share MSAL logs with us so we can investigate further?

Instructions for capturing MSAL logs: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-android

**Comment by adarshmanoharan** [comment]
He @shahzaibj 

I am seeing the difference in those accounts responses I am attaching the screenshots
<img width="489" alt="Screenshot 2021-09-06 at 12 31 27 PM" src="https://user-images.githubusercontent.com/49401818/132174358-ce43dcab-6cc7-400d-9676-73997575fe92.png">
<img width="483" alt="Screenshot 2021-09-06 at 12 30 33 PM" src="https://user-images.githubusercontent.com/49401818/132174373-cf60b403-4db7-4b60-af04-49ff5a83d1f7.png">

I can see the some params are null on the tenant, is there anything associated with policy or with the account type ?

**Comment by adarshmanoharan** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1033

This is the exact issue I am getting

W/MsalOAuth2TokenCache:getAccount: [2021-08-31 04:00:09 - thread_name : pool-3-thread-1, correlation_id : UNSET] No matching account found. Android 30
W/SilentTokenCommandParameters: [2021-08-31 04:00:09 - thread_name : silent-1, correlation_id : {Value}] The account set on silent operation parameters is NULL. Android 30

these two messages also coming at logs

**Comment by adarshmanoharan** [comment]
it was some account privileges problem. Support Team made some changes on the account preferences. its go resolved

**Comment by saeedalhamed** [comment]
what was the issue please, what account privileges?

**Comment by saeedalhamed** [comment]
> it was some account privileges problem. Support Team made some changes on the account preferences. its go resolved

what was the issue please, what account privileges, is it custom policy changes or account previliges on the B2C tenant side!
