### ISSUE TITLE
Support for Mi Browser

### ISSUE THREAD

**Issue by eduardothiesen** [AzureAD/microsoft-authentication-library-for-android#1509]
**Is your feature request related to a problem? Please describe.**
Since Mi Browser is not on the safe list, the fallback for DEFAULT agent is WebView, which does not work with Google and Facebook Login. And the BROWSER agent gives the "No browser found on this device" error. 

**Describe the solution you'd like**
It would be nice to add the Mi Browser (com.mi.globalbrowser) to the safe list since Xiaomi Devices are widely used world wide

**Comment by iamgusain** [comment]
Thanks for your feedback,
You can also add specific browser to the safelist from the Msal config file [See here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#browser_safelist)
