### ISSUE TITLE
Getting "The user has denied access to the scope requested by the client application" after granting access

### ISSUE THREAD

**Issue by MatteCarra** [AzureAD/microsoft-authentication-library-for-android#1512]
**Describe the bug**
A couple of users are getting the error "The user has denied access to the scope requested by the client application" after granting access to the application.
Most users do not have that issue.

**Smartphone (please complete the following information):**
Two people have currently reported the same issue:

 - Device: Huawei Mate 10 Pro
 - Android Version: Android 10
 - Browser: Chrome
 - MSAL Version: 2.1.0

Second person:
 - Device: Huaway p10 lite
 - Android Version:  8.0
 - Browser: ?
 - MSAL Version: 2.2.0

**Stacktrace**
```
Caused by com.microsoft.identity.client.exception.MsalServiceException: The user has denied access to the scope requested by the client application.
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1903)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1894)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:424)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**To Reproduce**
The IPublicClientApplication is initialized this way, and everything runs well:
```
PublicClientApplication.createMultipleAccountPublicClientApplication(
        app,
        R.raw.microsoft_auth_config,
        object : IPublicClientApplication.IMultipleAccountApplicationCreatedListener {
            override fun onCreated(app: IMultipleAccountPublicClientApplication) {
                mMicrosoftLogin = app
            }

            override fun onError(ex: MsalException) {
                ex.printStackTrace()
            }
        }
)
```

I have only some users reporting this issue, but for them the token fails in the "onError" callback:
```
mMicrosoftLogin?.acquireToken(activity, arrayOf("XboxLive.signin"), object: AuthenticationCallback {
    override fun onSuccess(result: IAuthenticationResult) {
              //this is not happening
    }

    override fun onError(ex: MsalException) {
        ex.printStackTrace() //The exception is thrown here
    }

    override fun onCancel() {
        //this is not happening
    }
})
```

The users are then correctly inserting their credentials and tapping "yes" when asked to authorize the app to get certain permissions.
The flow ends with the exception reported above.
Users where asked to screenshot their https://account.live.com/consent/Manage and they confirmed that the app was there with the required permissions.

**Expected behavior**
Most users insert the credentials and tap "yes" when asked to provide permissions.
The authorization flow ends correctly.

**Additional context**
Note that the app is working for most users.
The requested scope is XboxLive.signin

My auth config looks like that:
```
{
  "client_id" : "MY_ID",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "MY_REDIRECT_URI",
  "account_mode" : "MULTIPLE",
  "broker_redirect_uri_registered": true,
  "authorities" : [
    {
      "type": "AAD",
      "authority_url": "https://login.microsoftonline.com/consumers"
    }
  ]
}
```

**Comment by iamgusain** [comment]
From the error it looks like the consent is not setup correctly. Therefore the library is returning the error code that it gets from the service.
Can you compare the permissions between the users for which it is working and users who are experiencing the problem.
Also you can try clearing the permissions from the consent management page and try again to see if that solves the issue

**Comment by MatteCarra** [comment]
Hello,

I tried to contact back the original users that reported the issue, but they are not responding currently.
Some other users reported me that the issues happens to them as soon as they tap the "Use another account".
I was able to reproduce the same bug on my device two days ago, but I'm not able to reproduce it anymore (without changing anything).
I will ask the user again. I'm thinking it was a microsoft server side issue.

I am using the "MULTIPLE" account_mode, as you can see in the original issue.

**Comment by MatteCarra** [comment]
The issue seems indeed gone, indicating that it was probably a server issue.

**Comment by mateyakje** [comment]
I'm getting the same error on my smartphone.  Have we found a solution yet?
