### ISSUE TITLE
Open tenant-specific login page

### ISSUE THREAD

**Issue by markbeij** [AzureAD/microsoft-authentication-library-for-android#1513]
**Describe the bug**
When only one tenant is configured, the wrong login page is shown.

**Smartphone (please complete the following information):**
 - Browser Webview
 - MSAL Version 2.1.0

**To Reproduce**
```
{
  "client_id" : "--client_id--",
  "redirect_uri" : "--redirect_uri--",
  "broker_redirect_uri_registered": true,
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "contoso.onmicrosoft.com"
      }
    }
  ],
  "authorization_user_agent": "WEBVIEW",
  "account_mode": "SINGLE"
}
```

**Expected behavior**
When only one tenant(authority) is configured, the login page specific for that tenant should be shown.

**Actual Behavior**
The general login page from Microsoft is shown.

**Comment by markbeij** [comment]
I believe ADAL used to support this, so I consider this a bug.

**Comment by iamgusain** [comment]
The list of authorities defined in the config files tells MSAL to treat those as trusted authorities, in addition to the list of authorities known to Microsoft. [See here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#authorities).
The login page that is shown depends upon what was the authority passed in the token request to MSAL, 
So I think what you are seeing here is an expected behavior.

**Comment by markbeij** [comment]
Thank you @iamgusain.
I'm not sure how to accomplish this for `PublicClientApplication`

```
this.app = PublicClientApplication.createSingleAccountPublicClientApplication(getActivity(), file);
...
app.signIn(getActivity(), null, scopes, Prompt.LOGIN, getInteractiveCallback(call));
```

`app.signIn(...)` does not have a way to pass the authority.

`app.acquireToken(...)` does, but we need it at signIn.
```
AcquireTokenParameters params = new AcquireTokenParameters.Builder()
        .startAuthorizationFromActivity(getActivity())
        .withScopes(Arrays.asList(scopes.clone()))
        .withPrompt(Prompt.LOGIN)
        .fromAuthority("contoso.onmicrosoft.com")
        .withCallback(getInteractiveCallback(call))
        .build();
app.acquireToken(params);
```
