### ISSUE TITLE
Signout  experience shared device mode 

### ISSUE THREAD

**Issue by jsroest** [AzureAD/microsoft-authentication-library-for-android#1514]
When a device is in "shared device mode", the signout experience is not optimal.

During the 'sign in' process, the user stays in the comfort of the installed broker, in my case that is the Microsoft Authenticator.

During the 'sign out' process, the user switches to the default browser, showing the message "You signed out of your account".

With every 'sign out' a new browser tab is opened, which may result in many tabs after some time.

![Screenshot 2021-09-14 at 09 43 20](https://user-images.githubusercontent.com/17854207/133217387-64eb51bc-abd3-421d-8335-8bdf9a083d38.png)

This is the experience when switching users:

https://user-images.githubusercontent.com/17854207/133216928-d132701e-d5bb-42f3-a74e-b66346ad8e40.mp4

From what I understood from another issue, the signing out of the default browser is on purpose: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1190#issuecomment-709895503

As I understood, this is done 'just to be sure', while SSO for web apps with the current broker is not supported.

So I see three problems:
1) The increasing amount of browser tabs
2) The unnecessary call of https://login.microsoftonline.com/common/oauth2/v2.0/logout in the default browser, when not using web apps while in "shared device mode".
3) A message that says "It's a good idea to close all browser windows.", does not make sense for front-line workers using an Android device. What about multilingual? Usually, there is more than one native language on the work floor.

This makes the experience a lot less intuitive for front-line workers like warehouse personnel and forklift drivers.

Is it possible to make the logout call optional by adding an option in the config file?

```
{
  "client_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "msauth://com.dalosyapps.msal_mobile_example/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D",
  "account_mode": "SINGLE",
  "broker_redirect_uri_registered": true,
  "shared_device_mode_supported": true,
  >>"broker_signout_default_browser": true,<<
  "authorities": [
    {
      "type": "AAD",
      "authority_url": "https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      }
    }
  ]
}
```

Smartphone :
 - Device: Honeywell CT40
 - Android Version: Android 10
 - Browser: default
 - MSAL 2.+

**Comment by jsroest** [comment]
Is it fixed?

**Comment by jsroest** [comment]
Hi @negoe, can you explain why this is closed? This issue is still relevant to me.

**Comment by negoe** [comment]
Hi @jsroest This entire logout call has been removed. You should not be running into this issue anymore. Please checkout this PR https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1783
