### ISSUE TITLE
Package Inspector does not find all apps starting from Android 11

### ISSUE THREAD

**Issue by ClaudioConsolmagno** [AzureAD/microsoft-authentication-library-for-android#1516]
**Describe the bug**
I tried using the Package Inspector to double check the Signature Hash of an app running on my Pixel 4a-Android 11 device but it couldn't find the application. I found out that since [Android 11, there's been some package visibility changes](https://developer.android.com/about/versions/11/privacy/package-visibility) meaning the current inspector won't show all installed apps. I managed to fix this issue by adding the following to the `AndroidManifest.xml`:
```xml
    <permission android:name="android.permission.QUERY_ALL_PACKAGES" />
    <queries>
        <intent>
            <action android:name="android.intent.action.MAIN" />
        </intent>
    </queries>
```

**Comment by HoangHuyVoZ** [comment]
I think I can refer to this way
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1425#issuecomment-929032648
