### ISSUE TITLE
Extra scopes are not shown for consent 

### ISSUE THREAD

**Issue by lukaspechar** [AzureAD/microsoft-authentication-library-for-android#1520]
#stashenergy/react-native-msal/issues/98

I've linked the issue posted on https://github.com/stashenergy/react-native-msal. We've tested this and all the appropriate scopes are being sent to `AzureAD/microsoft-authentication-library-for-android`. The issue seems to be in MSAL for Android.

Any help would be appreciated.

**Comment by lukaspechar** [comment]
bump

**Comment by SirElTomato** [comment]
Please can this be looked into?

**Comment by lukaspechar** [comment]
Just some extra information. I've tested both Android and iOS (on the iOS MSAL library) and made the identical requests and permissions. The JWTs are identical (with some exceptions like expiry etc).

**Comment by paulkagiri** [comment]
This is being looked into, will share an update soon
