### ISSUE TITLE
Error trying to change applicationid in Android

### ISSUE THREAD

**Issue by ljunquera** [AzureAD/microsoft-authentication-library-for-android#1524]
I have changed the name of my Android application, but am getting an error when I change the name of the redirect_uri in the json configuration file.

I am using:
   implementation 'com.microsoft.identity.client:msal:2.0.4'

The error I am getting is:
    E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.enablewear.xxxxxxxxxx, PID: 8032
    java.lang.StackOverflowError: stack size 8192KB
        at d.b.a.l.a$c.onError(:764)

I updated the **package name** in the **Redirect URI** in the **Android Platform Configuration** of the **App Registration** in the **Azure AD B2C tenant**.

I updated the **android:host** in the **AndroidManifest.xml**

I did these changes 1 by 1 to see what was causing the problem because when I did them all at once, I received the above error. 

- Changing the package name in the redirect in Azure did not break the app
- Changing the android:host in the AndroidManifest did not break the app
- When I changed the "redirect_uri" in the auth_config_multiple_account.json the app crashed.

At other times I would get this error:

The app is still using legacy MSAL redirect uri. Switch to MSAL local auth.  For brokered auth, the redirect URI is expected to conform to 'msauth://<authority>/.*' where the authority in that uri is the package name of the app. This package name is listed as 'applicationId' in the build.gradle file. Android 29

**Comment by paulkagiri** [comment]
Hello @ljunquera, kindly start by updating the MSAL version to the latest - https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.2.1 and then if the problem persists share the full exception stack traces to enable us figure out what the issue is

**Comment by ljunquera** [comment]
I changed this in the build.gradle:

    implementation 'com.microsoft.identity.client:msal:2.2.1'

Here is the error I get:

2021-09-29 22:22:46.469 9261-9261/com.xxxxxxx.yyyyyyyyy, E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxxxxx.yyyyyyyyy, PID: 9261
    java.lang.StackOverflowError: stack size 8192KB
        at d.b.a.l.a$c.onError(:764)
        ......
        at d.b.a.l.a$c.onError(:764)
        at com.microsoft.identity.client.PublicClientApplication$10.onError(:1011)
        at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(:946)
        at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(:929)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(:448)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$900(:83)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(:427)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-09-29 22:22:46.862 9261-9261/com.xxxxxxx.yyyyyyyyy W/AppCenterCrashes: Crash frames truncated from 178969 to 256 frames.
2021-09-29 22:22:46.905 9261-9261/com.xxxxxxx.yyyyyyyyy I/Process: Sending signal. PID: 9261 SIG: 9

**Comment by ljunquera** [comment]
The patch says this:

[PATCH] Picks up common@3.6.2
[PATCH] Allow Authenticator to pass older format for redirect uri (#1517)

Is there some other format I should be using?

**Comment by ljunquera** [comment]
FYI the only line I change to get this error is in:

auth_config_multiple_account.json

it is represented by the z's in this line:

 `"redirect_uri" : "msauth://com.xxxxxxxxxx.zzzzzzzzzzzz/xxxxxxxxxxxxxxxxxx",`

I change it to what is in the AndroidManifest.xml:

     `android:host="com.xxxxxxxxxx.zzzzzzzzzzzz"`

and what is in the build.gradle:
```
    defaultConfig {
        applicationId "com.xxxxxxxxxx.zzzzzzzzzzzz"
       .......
```

and the "Redirect URI" (I change the package name Package name) azure portal:

      `msauth://msauth://com.xxxxxxxxxx.zzzzzzzzzzzz/xxxxxxxxxxxxxxxxxx`


I can leave the AndroidManifest.xml, the build.gradle, and the Azure Redirect URI on the new id (the zzzzzzzzzzzz) and change only the 'redirect_uri' in the auth_config_multiple_account.json back to the old one and it does not crash.

**Comment by ljunquera** [comment]
Here is the error:

AuthHelper.loadB2CApp.onError: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.

**Comment by ljunquera** [comment]
I read [this](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-FAQ) and ran the keytool again. I received a different hash which seems to work. I cannot tell you why the previous one seemed to work, which is disconcerting. I am also not sure how or if this hash changes as I move the app through environments (from dev to test, from test to prod). I read some additional threads like [this one](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/914) which ask about AAB vs APK, but I don't see a response or a more comprehensive explanation.

**Comment by paulkagiri** [comment]
Hello @ljunquera, kindly go through this doc that details how to configure your application - https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android, specifically, note the following:
- You generate the signature hash from the specific key you're signing the application with at the time
- The format of the redirect uri is `msauth://{app package name}/{encoded signature hash}`
- In app > src > main > AndroidManifest.xml the android:path configuration under the BrowserTabActivity should have the value of the **NOT-encoded** signature hash and there should be a leading / at the beginning of your Signature Hash i.e it should look something like:
```
<data android:scheme="msauth"
    android:host="com.example.hello"
    android:path="/1wIqXSqBj7w+h11GifsnqsgyKrY=" />
```

**Comment by ljunquera** [comment]
I got it working. I changed the signature hash to the one with the default password. Previously I created a signature hash with a custom password, as I thought the default one was just an example. It seemed to be working for a few months, until I got this error. I'm not sure why. Perhaps it coincided with the expiration of the 90 day token.
