### ISSUE TITLE
Generating signature hash for the app signed by Google in Google play store

### ISSUE THREAD

**Issue by Kameswari** [AzureAD/microsoft-authentication-library-for-android#1531]
Hi, I have integrated MSAL in my Android app and uploaded in Google play store using my own keystore. Once it got uploaded, the MSAL initialization failed. I found that Google is using a different keystore to sign the application. Could somebody help me on how to get the signature hash from keystore used by Google? 

I can see the MD5, SHA-1, SHA-256 keys like below.

![image](https://user-images.githubusercontent.com/1224954/136414014-3aedf7df-6195-472e-b38e-eae8b553bf88.png)

Please let me know how to generate signature hash(which is required to be registered in MS Azure portal) by using any one of the above keys. As its released to customer, I need some urgent help on this. TIA.

**Comment by paulkagiri** [comment]
Yeah, did it help?
