### ISSUE TITLE
Google Play reporting "Unsafe cipher mode" for StorageHelper.java

### ISSUE THREAD

**Issue by StuSharpe** [AzureAD/microsoft-authentication-library-for-android#1540]
**Issue**

Our android app is receiving this error in our Google Play pre-launch report : 

```
Your app contains a less secure encryption mode:
 * com.microsoft.identity.common.adal.internal.cache.StorageHelper->getKeyThumbPrint
```

**Proposed Solution**

To resolved the error.  The report suggests changing from existing cyber algorithm from:

` private static final String CIPHER_ALGORITHM_FOR_KEY_TRACKING = "AES/ECB/PKCS5Padding";`

to 

` private static final String CIPHER_ALGORITHM_FOR_KEY_TRACKING = "AES/GCM/NoPadding";`

as described in [this linked faq](https://support.google.com/faqs/answer/10046138)

**Affected Lib Versions**

We have been getting the same error for apps using MSAL releases 2.2.1 and 2.1.0.

**Comment by Digipom** [comment]
Just commenting that the issue is still present in version 2.2.2. I'm receiving this warning as well.

**Comment by premnirmal** [comment]
Any updates on this issue? It is still being reported in google play and it can prevent apps from being released

**Comment by aeroxr1** [comment]
The new version 2.2.3 resolve the issue ?

**Comment by nithinyell** [comment]
Any Update on issue?

**Comment by Digipom** [comment]
I tried version 2.2.3 and the warning no longer appears in Google Play for me.

Now if only the team would update their Proguard documentation. :)
