### ISSUE TITLE
How to configure Signature Hash with Google Play Signing

### ISSUE THREAD

**Issue by ljunquera** [AzureAD/microsoft-authentication-library-for-android#1550]
How do you generate a signature hash for an app when Google manages the key. I am getting errors when deploying to internal testing:

![image](https://user-images.githubusercontent.com/4500512/140608836-80dd33a1-1e7b-4591-8455-b65c5c86bc25.png)

The redirect URI matches. It seems to be related to the signature hash and how it is generated. The instructions for generating a production (I think this means any buildType/flavor in the Google Play Store) signature hash in the Azure portal are not working for me:

![image](https://user-images.githubusercontent.com/4500512/140608541-01eb9ac2-f207-4d84-8a1a-9777a970c249.png)

When creating the app in Google Play it is recommended that you "Let Google generate an app signing key":

![image](https://user-images.githubusercontent.com/4500512/140608416-9c4ac944-ef49-47aa-9add-901b5f9550eb.png)

There are other options as well, but they are not the recommended option:
![image](https://user-images.githubusercontent.com/4500512/140608612-f8a19f2a-5e33-43b9-a7a9-a6b82e0d0c35.png)

Is there any recommendation or documentation on the end to end process and if you can/can't use the recommended option of having Google manage your keys when using Azure AD B2C?

**Comment by ljunquera** [comment]
Here is the solution, which I found [here.](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/931#issuecomment-632837482)

Go to the app in the Google Play Console and in the Release section of the menu options you will see:
![image](https://user-images.githubusercontent.com/4500512/140650760-3c4888ce-888e-40b6-97c3-3bcb5f5dfcba.png)

The main screen will show:
![image](https://user-images.githubusercontent.com/4500512/140651096-8c05629d-e3c0-4c02-95f6-7e4d275ccbf9.png)

Download the certificate and run this in the directory of the downloaded certificate:
openssl x509 -inform der -in deployment_cert.der -outform der | openssl sha1 -binary | openssl base64

You will get the signature hash you can use in the manifest, portal, and configuration file (encoding required here).

**Comment by ansonsiby86-del** [comment]
Are you trying to sign in to Minecraft for Android?
Only continue if you downloaded the app from a store or website that you trust.
