### ISSUE TITLE
com.microsoft.identity.client.exception.MsalClientException: Sdk cancelled the auth flow as the app launched a new interactive auth request.

### ISSUE THREAD

**Issue by MarceloEsser** [AzureAD/microsoft-authentication-library-for-android#1561]
**Describe the bug**
Hi guys! I'm experiencing literally the same closed [issue](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/923#issue-561208423) in a production app.  But my authorization_user_agent cannot be WEBVIEW (social login don't work with webview).

 - Device: any
 - Android Version:  6 or higher
 - Browser: any
 - MSAL Version - 2.2.1

**Stacktrace**
com.microsoft.identity.client.exception.MsalClientException: Sdk cancelled the auth flow as the app launched a new interactive auth request.
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1903)
       at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1894)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:424)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8019)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**To Reproduce**

If related to user experience, use the format:
1. Turn on 'Don't keep activities' in the developer settings on your device
2. Try to sign in (reproducible in the app found at the quickstart)
3. When the browser open sign in with your credentials 
4. Browser will close and nothing happens

my current config file

{
  "client_id": "client_id",
  "authorization_user_agent": "DEFAULT",
  "account_mode": "MULTIPLE",
  "redirect_uri": "redirect_uri",
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "authority_url",
      "default": true
    },
    {
      "type": "B2C",
      "authority_url": "authority_url"
    }
  ],
  "browser_safelist": [
    {
      "browser_package_name": "com.mi.globalbrowser",
      "browser_signature_hashes": [
        "g7zGEnZipieE6ZyBA4Bz00kxU8h0F9QTwPLL-dnRVwngI0FJWJiD3rCEJsIQ_VK064SNdxzqggnnnAqT8LI89A=="
      ]
    }
  ]
}

**Expected behavior**
Authorization should work

**Actual Behavior**
AuthenticationCallback throws that exception and the authentication flow isn't properly finished

**Additional context**
The users report are exactly like this: 
- Browser opens, you do your auth thing, hit continue
- Browser closes, nothing happens

**Comment by LTMezzari** [comment]
I'm having the same problem in a production app as well. We cannot use the **authorization_user_agent** as WebView.

**Comment by samai2** [comment]
Very similar issue with account mode "SINGLE". After start authentication, browser won't close and will get in loop with authorization window. Issue reproduced only with enabled  'Don't keep activities' in the developer settings on your device

**Comment by felipe-allmeida** [comment]
Just tried on my machine. I'm using a Mac Air Bigsur M1 ARM64. Facing the exact same issue.

Dou you guys have any update on this? 

Thanks

**Comment by wainaina** [comment]
When you have "Don't keep activities enabled", Android System calls onStop to the Activity/ Fragment.when a new interactive request is started, this leads to a `Hosting Activity is destroyed before Auth request is completed` which then leads to cancelling of the authentication flow.

**Comment by shoatman** [comment]
@wainaina - Let's discuss if this is something that we want to try and fix.  Do we have a repro without configuring this developer option?  A user impacted by memory pressure in this scenario?

**Comment by waqarul** [comment]
For me, the issue was that in developer options, I set **_Don't keep activities_** to **_TRUE_** which was killing one of the Activity in MSAL library which result in getting the above exception.

**Comment by dwane13** [comment]
Is this resolved? For some reason, this bug is marked as closed, but I'm still facing this issue.

**Comment by kientrant1** [comment]
Besides of turning OFF - Don't keep activities in  in the developer settings on device. Do we have any other way to prevent it?

**Comment by asdolo** [comment]
> For me, the issue was that in developer options, I set **_Don't keep activities_** to **_TRUE_** which was killing one of the Activity in MSAL library which result in getting the above exception.

You're a life saver. Thank you!
