### ISSUE TITLE
ADFS?

### ISSUE THREAD

**Issue by trev83** [AzureAD/microsoft-authentication-library-for-android#1569]
Hello, i have an android app running msal 2.2.2 and have been connecting to azure ad perfectly.
I now have a need to get it to connect to ADFS
Does this library support it and if so how do i format the .json for it?

Ive been given 

Client ID: ???????
Client Secret: ?????
Metadata: https://f????

URLS configured:
https://???
https://?????

Application identifier:
???? (this seems to be the same as Client ID is this right?

Many thanks

Trev

**Comment by shoatman** [comment]
We don't support ADFS in MSAL.  We only support Microsoft Identity cloud IDPs....  Which version of ADFS are you hoping to support?  We had plan to add support, but it was de-prioritized.
