### ISSUE TITLE
(Android App) invalid_request: the provided value for the input parameter 'redirect_uri' is not valid. the expected value is a uri which matches a redirect uri registered for this client application.

### ISSUE THREAD

**Issue by nguyenvanminhc9nvm** [AzureAD/microsoft-authentication-library-for-android#1574]
**Describe the bug**
i try implement oneDriveSDK https://github.com/OneDrive/onedrive-sdk-android like this
but when i Get a OneDriveClient object i was receiver this error and i can't resolved this, please 

**Smartphone (please complete the following information):**
 - Device: [Note 20 Ultra]
 - Android Version: [11]
 - Browser [e.g. Chrome, Edge]
 - MSAL Version 0.8.6

**Comment by wainaina** [comment]
Hello, kindly raise this issue on https://github.com/OneDrive/onedrive-sdk-android/issues
