### ISSUE TITLE
SSO is asking for login again in Webview in few devices

### ISSUE THREAD

**Issue by muhammad-farhan-bakht** [AzureAD/microsoft-authentication-library-for-android#1582]
**Describe the bug**
The app is in Production.
We have followed the MASL SSO implementation from the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android) after login we show the content in Webview.

1. The flow is working fine in almost all testing devices as we sign in through MASL SSO then go to Webview Activity and load the content everything works perfectly.
2. But We are facing the problem with only the Samsung S10 testing device. After Login its asks for login in Webview again for showing the content.

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - Android Version: 11
 - Browser Webview
 - MSAL Version 2.2.3

**To Reproduce**
After Login through MASL SSO, it asks again to login into the Webview.

**Expected behavior**
After Login through MASL SSO, it just loads the content in the Webview.

**Actual Behavior**
After Login through MASL SSO, it asks again to login into the Webview.

**Additional context**
**NOTE:** we are using `authorization_user_agent : WEBVIEW` in config.json

**Comment by tabassumfatima4321** [comment]
> **Describe the bug** The app is in Production. We have followed the MASL SSO implementation from the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android) after login we show the content in Webview.
> 
> 1. The flow is working fine in almost all testing devices as we sign in through MASL SSO then go to Webview Activity and load the content everything works perfectly.
> 2. But We are facing the problem with only the Samsung S10 testing device. After Login its asks for login in Webview again for showing the content.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung S10
> * Android Version: 11
> * Browser Webview
> * MSAL Version 2.2.3
> 
> **To Reproduce** After Login through MASL SSO, it asks again to login into the Webview.
> 
> **Expected behavior** After Login through MASL SSO, it just loads the content in the Webview.
> 
> **Actual Behavior** After Login through MASL SSO, it asks again to login into the Webview.
> 
> **Additional context** **NOTE:** we are using `authorization_user_agent : WEBVIEW` in config.json

Hey , i have worked on the same thing recently this could be resolved if we change **_authorization_user_agent : WEBVIEW to authorization_user_agent : DEFAULT_** then it wont ask again in Samsung as well Hope this would be helpful
