### ISSUE TITLE
Hello, my organization uses google as its main directory and authentication provider. Our veolia.com domain is "federated to google". So when I connect to azure from a browser, google authentication page opens and guides me through the MFA that's configures for my google account

### ISSUE THREAD

**Issue by DavidPROVOST** [AzureAD/microsoft-authentication-library-for-android#1588]
From Samsung A41, trying to connect teams or power bi through google-federated Azure accounts.
Works fine from à browser : Microsoft sign on buttons opens a google webview which guides me through the mfa configured on my google account.
But trying to connect from an Android app (teams, power bi, Microsoft aithenticator) always triggers a Google 403 error and message complaining about disallowed user agent.
![Screenshot_20220128-223703](https://user-images.githubusercontent.com/43402895/151624985-8ab797b1-2434-45e1-be89-8bd8b9e67466.jpg)

**Comment by negoe** [comment]
@DavidPROVOST Are you using MSAL Android? Feel free to reach out and reopen if you are still struggling with this isssue.
