### ISSUE TITLE
Custom tabs color

### ISSUE THREAD

**Issue by vicpinm** [AzureAD/microsoft-authentication-library-for-android#1589]
Hi, I need to set the toolbar color when opening chrome custom tab. I've seen this issue: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/57

No updates in 5 years? Can we set the color of chrome custom tab somehow?

**Comment by negoe** [comment]
@vicpinm . Thank you for taking the time to provide us with your valuable feedback. Unfortunately, the suggested feature is not currently a priority for us to develop. However, we are constantly evaluating and updating our roadmap based on customer feedback and changing market trends, and we will keep your suggestion in mind for future updates.
