### ISSUE TITLE
MsalException - BrowserTabActivity is missing

### ISSUE THREAD

**Issue by bshigley** [AzureAD/microsoft-authentication-library-for-android#1590]
For a quick background, my Android project has more than 100 `productFlavors` in the `app/build.gradle` file. Each `productFlavor` is a distinct app, with a different package name, different resources, and different Office SSO information. I inject the `host`, `path` and `scheme` values into the manifest from the `app/build.gradle` file like this:

```
<activity android:name="com.microsoft.identity.client.BrowserTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="${hostName}"
                    android:path="${pathName}"
                    android:scheme="${schemeName}" />
            </intent-filter>
        </activity>
```

and 

```
AppName {  
            applicationId 'xxx.xxx.packagename'
            manifestPlaceholders = [schemeName: "msauth", hostName: "xxx.xxx.packagename", pathName: "/path"]
            signingConfig signingConfigs.AppName
        }
```

My `compileSdkVersion` and `targetSdkVersion` are both 31, this happens to all Android devices and all OS versions I've tested, and this is what I have for the dependencies:

```
implementation 'com.microsoft.identity.client:msal:2.+'
implementation 'com.microsoft.graph:microsoft-graph:1.5.+'
```

This is my gradle tools version:

`classpath 'com.android.tools.build:gradle:7.1.1'`

```
repositories {
    mavenCentral()
    jcenter()
    maven { url 'https://repo.gradle.org/gradle/libs-releases' }

    google()
    mavenLocal()
    maven {
        url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
    }
    maven {
        name "vsts-maven-adal-android"
        url "https://identitydivision.pkgs.visualstudio.com/_packaging/AndroidADAL/maven/v1"
        credentials {
            username System.getenv("ENV_VSTS_MVN_ANDROIDADAL_USERNAME") != null ? System.getenv("ENV_VSTS_MVN_ANDROIDADAL_USERNAME") : project.findProperty("vstsUsername")
            password System.getenv("ENV_VSTS_MVN_ANDROIDADAL_ACCESSTOKEN") != null ? System.getenv("ENV_VSTS_MVN_ANDROIDADAL_ACCESSTOKEN") : project.findProperty("vstsMavenAccessToken")
        }
    }
}
```

When I run any of the variants **in bundle form, except for the defaultConfig**, I get the error in the title. When I run these apps in APK form, SSO works fine. It's only when I run the app using the bundle that I get the _BrowserTabActivity is missing_ MsalException.

I used [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android) to configure Office SSO for the apps.

To reproduce this issue, configure your `app/build.gradle` file to use the `productFlavor` and `manifestPlaceholder` injection pattern. Then, in Android Studio for example, run the app by deploying the APK from the app bundle, by clicking `Run -> Edit Configurations... -> General -> Installation Options -> Deploy -> APK from app bundle` and then run the app. 

The key to this issue is probably in the difference between APK packaging and bundle packaging. Please let me know how I can fix this!

**Comment by negoe** [comment]
@bshigley It seems like the MsalException class is missing from one or more of the split APKs that are generated when you use an app bundle to install your app. This can happen if the class is not used by any code that is included in the split APKs, so the build system may optimize it out to reduce the size of the APKs. One way to address this is to force the build system to include the MsalException class in all split APKs, regardless of whether it is used or not.

**Comment by LucaZiegler** [comment]
When using 4.61.0 of Microsoft.Identity.Client in Xamarin Forms (Android Platform) I get this error (previous release 4.60.3 works fine):

`The type or namespace name 'browsertabactivity' could not be found (are you missing a using directive or an assembly reference?)`
