### ISSUE TITLE
Chrome is the only option, MS Sign-in Page not opening on other browser. If chrome is not set as default, this page won't open at all. 

### ISSUE THREAD

**Issue by FarazJelani** [AzureAD/microsoft-authentication-library-for-android#1591]
**Describe the bug**
The app is live and in production. If chrome is not set as default the MS sign-in page won't open. Other than chrome if we choose browser for example Samsung's Internet browser, the sign-in page won't open.

**Smartphone (please complete the following information):**
 - Device: [ALL]
 - Android Version: [Android 5.0 and above]
 - Browser [ALL]
 - MSAL Version - 1.5.5

**Stacktrace**
If a crash occurs, include the stacktrace.

**To Reproduce**
Steps to reproduce the behavior: 1> Set Internet as default browser. 2> Call acquireToken. 3> Tab has crashed.

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
MSAL authentication should work on all mobile browser

**Actual Behavior**
Only chrome is an option.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by FarazJelani** [comment]
Please let me know if more information is required.

**Comment by paulokagiri** [comment]
@FarazJelani kindly update MSAL to the latest version, also have a look at the tested browsers here and how to switch between the different options here - https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#tested-browsers
