### ISSUE TITLE
How to create PublicClientApplicationConfiguration dynamicly?

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#1592]
Hi, I am trying to build PublicClientApplicationConfiguration  in Java rather than using json file.
 My json config is 
      `   {
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount"
      },
      "default": true
    }
  ],
  "account_mode": "SINGLE",
  "authorization_user_agent": "WEBVIEW",
  "multiple_clouds_supported": true,
  "client_id": "XXXXX",
  "redirect_uri" : "msauth://XXXXX",
  "broker_redirect_uri_registered": true,

  "http": {
    "connect_timeout": 10000,
    "read_timeout": 30000
  }
     }`

So far I have below but cannot seem to figure out how to set      "account_mode": "SINGLE" and "authorization_user_agent": "WEBVIEW" in Java.  Where/How would I set those?

                PublicClientApplicationConfiguration publicClientApplicationConfiguration = new PublicClientApplicationConfiguration();

                publicClientApplicationConfiguration.setClientId("XXXXX");
                publicClientApplicationConfiguration.setRedirectUri("msauth://XXXXX");
                publicClientApplicationConfiguration.getHttpConfiguration().setConnectTimeout(10000); 
                publicClientApplicationConfiguration.getHttpConfiguration().setReadTimeout(30000);  
                publicClientApplicationConfiguration.setPowerOptCheckEnabled(false); //Disable so that we can work in background 

                AzureActiveDirectoryAuthority azureActiveDirectoryAuthority = new AzureActiveDirectoryAuthority(new AllAccounts());
                azureActiveDirectoryAuthority.setDefault(true);
                azureActiveDirectoryAuthority.setMultipleCloudsSupported(true);

                publicClientApplicationConfiguration.getAuthorities().add(azureActiveDirectoryAuthority);

**Comment by paulokagiri** [comment]
@NLLAPPS kindly use the `SingleAccountPublicClientApplication`, refer to https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android
