### ISSUE TITLE
Documentation says 'com.microsoft.identity.client:msal:2.0.+' when v2.2.3 is recommended

### ISSUE THREAD

**Issue by ljunquera** [AzureAD/microsoft-authentication-library-for-android#1606]
Why does the [documentation ](https://github.com/AzureAD/microsoft-authentication-library-for-android#step-1-declare-dependency-on-msal) say:

```
dependencies {
    implementation 'com.microsoft.identity.client:msal:2.0.+'
}
```
When it looks like you're up to [2.2.3](https://github.com/AzureAD/microsoft-authentication-library-for-android#microsoft-authentication-library-msal-for-android) and recommending when [triaging issues](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1568#issuecomment-1062965276) to upgrade.

**Comment by wainaina** [comment]
Thanks for this feedback, we will quickly update the same to reflect the progress.
