### ISSUE TITLE
JavaDocs Feedback/Inconsistencies

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#161]
thanks @sunilbandla for reviewing our stuff.  Here's some of this feedback:

-Extra vs additional scopes and query params
-PCA explanation is also in Browser tabs
-PII is not defined.
-Interface naming is not consistent
-GetIDToken and GetRawIDTOken descriptions are too similar and cant tell the difference.
-Id upper and lower case not consistent.

**Comment by iambmelt** [comment]
Updated by #163 

thanks @sunilbandla for reviewing our stuff.  Here's some of this feedback:

-Extra vs additional scopes and query params
-PCA explanation is also in Browser tabs
-PII is not defined.
- described differently in some places
-Interface naming is not consistent
-~GetIDToken and GetRawIDTOken descriptions are too similar and cant tell the difference.~
-Id upper and lower case not consistent.

**Comment by danieldobalian** [comment]
Expanding on feedback: 

-Extra vs additional scopes and query params.  Wanted to make sure we are using the correct term for scopes that was decided. 
-PCA explanation is also in Browser tabs. Both classes have the same sample code in both spots.  Does it belong in PCA?
-PII is not defined as in didn't know what we meant by PII.
-Interface naming is not consistent. Some start with i, but not all of them. 
-GetIDToken and GetRawIDToken descriptions are too similar and cant tell the difference.
-Id upper and lower case not consistent. Example getIdToken (sometimes the i is not capitalized).

**Comment by weijjia** [comment]
merged already.
