### ISSUE TITLE
Chrome browser not found error for android 11

### ISSUE THREAD

**Issue by ansari9546** [AzureAD/microsoft-authentication-library-for-android#1626]
when i use microsofy identity client library for signing in on android 11 i get an error that Chrome browser not found. working fine on android 10.
Android 11 (any device)
microsoft identity client:msal : 0.1.3

![image](https://user-images.githubusercontent.com/29058348/170018525-5729bbb1-5aa7-431f-b5c7-61e3d60df852.png)

**Comment by negoe** [comment]
@ansari9546 Please upgrade to the [latest release ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v3.0.2)of MSAL Android.
