### ISSUE TITLE
Trying to get App Only token silently

### ISSUE THREAD

**Issue by richshepard** [AzureAD/microsoft-authentication-library-for-android#1632]
I am trying to find an API that works for this and having problems. from the research I have been doing I think I need App Only tokens, whereas the examples here are for user tokens by the looks of it as they require an interactive login.

We have a C# example working which uses ConfidentialClientApplicationBuilder, but no such class exists for Android. The aim is to get a Access Token silently in the app so that this can be used as the Auth token in the header of requests going forward.

Any help would be appreciated.

**Comment by negoe** [comment]
Hi @richshepard MSAL Android library is only for Public Clients/Mobile Apps scenario. Please read this [documentation ](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications)for more clarity around Public and Confidential client scenarios. Thanks.
