### ISSUE TITLE
Obtain "deviceId" programmatically

### ISSUE THREAD

**Issue by andkrawiec** [AzureAD/microsoft-authentication-library-for-android#1634]
Can I programmaticaly retrive "deviceId" UUID visible in Microsoft Authenticator app and protal.azure.com?

![image](https://user-images.githubusercontent.com/32813983/172161633-918173da-2e02-4996-896d-5e98d4ef9ad2.png)

I've tried to fetch it like that: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/637

but "deviceId" is not present in either "mAccount#mIdTokenClaims" or "mAccessToken#mAdditionalFields" (it returns empty map)

**Comment by negoe** [comment]
@Andrzej-Krawiec Sorry, we do not support this feature programmatically today.
