### ISSUE TITLE
AssertionError: No NameTypeIndex match for SHORT_DAYLIGHT

### ISSUE THREAD

**Issue by alzakharenk** [AzureAD/microsoft-authentication-library-for-android#1638]
**Crash from appcenter**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: moto g(6) plus
 - Android Version: Android 8.1.0
 - MSAL Version 3.0.2

**Stacktrace**
android.icu.impl.TimeZoneNamesImpl$ZNames.getNameTypeIndex TimeZoneNamesImpl.java:724
android.icu.impl.TimeZoneNamesImpl$ZNames.getName TimeZoneNamesImpl.java:790
android.icu.impl.TimeZoneNamesImpl.getTimeZoneDisplayName TimeZoneNamesImpl.java:183
android.icu.text.TimeZoneNames.getDisplayName TimeZoneNames.java:261
java.util.TimeZone.getDisplayName TimeZone.java:405
java.util.Date.toString Date.java:1066
java.lang.String.valueOf String.java:2827
java.lang.StringBuilder.append StringBuilder.java:132
yb.f.onSuccess SourceFile:6
com.microsoft.identity.client.PublicClientApplication.postAuthResult SourceFile:8
com.microsoft.identity.client.PublicClientApplication$18.onTaskCompleted SourceFile:2
com.microsoft.identity.client.PublicClientApplication$18.onTaskCompleted SourceFile:1
com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted SourceFile:1
com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1100 SourceFile:1
com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run SourceFile:3
android.os.Handler.handleCallback Handler.java:790
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:164
android.app.ActivityThread.main ActivityThread.java:6626
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:438
com.android.internal.os.ZygoteInit.main ZygoteInit.java:811

**Comment by shahzaibj** [comment]
This issue is external to MSAL. This is actually a known issue specific to Android OS Version 8.1.0

Issue tracked at Google here: https://issuetracker.google.com/issues/110848122
