### ISSUE TITLE
HTTP request to /me/joinedTeams fails

### ISSUE THREAD

**Issue by rojaslcc** [AzureAD/microsoft-authentication-library-for-android#1642]
**Describe the bug**
I implement a single account login, I get the token in my Android app. But I can only get data from the /me endpoint, but if I try to use /me/joinedTeams I get an unknown error with code 401 Unauthorized. To implement the login I relied on the code from this repo: https://github.com/Azure-Samples/ms-identity-android-kotlin

**Smartphone**
 - Device: Samsung s21+ and Android Studio Emulator
 - Android Version: Android 12
 - Browser: Brave
 - MSAL Version: 3.0.+

**Result**
`{
    "error": {
        "code": "Unauthorized",
        "message": "UnknownError",
        "innerError": {
            "date": "2022-06-24T14:02:08",
            "request-id": "59b26e4a-331a-423f-8ece-fda856bd18f1",
            "client-request-id": "59b26e4a-331a-423f-8ece-fda856bd18f1"
        }
    }
}`

**Comment by negoe** [comment]
@rojaslcc Can you please share the the arguments to acquiretoken in order to request this token. Also if you can share the correlationid?

**Comment by negoe** [comment]
@rojaslcc Let us know, if this is solved for you. We will close the issue. Thanks!
