### ISSUE TITLE
App stopped working for GCC High tenants after migrating from ADAL to MSAL

### ISSUE THREAD

**Issue by Happy202121** [AzureAD/microsoft-authentication-library-for-android#1655]
**Describe the bug**
Our app is in production. After migrating from ADAL to MSAL, our Intune-integrated app no longer works for GCC High customers. After entering their email and password, they get the error "AADSTS700016: Application with identifier not found in the directory (domain name)".

With ADAL, our GCC High customers did not get this error.

**Smartphone (please complete the following information):**
 - Device: All Android devices
 - Android Version: All Android versions
 - Browser: All Android browsers
 - MSAL Version: 1.13.0

**Stacktrace**
The issue is not a crash.

**To Reproduce**
User opens the app
User enters their email address
User enters their password
Auth request goes to user's tenant
User gets error "AADSTS700016: Application with identifier not found in the directory (domain name)"

**Expected behavior**
The GCC High tenant finds the client_id in the Azure commercial cloud and allows the sign-in to complete.

**Actual Behavior**
The client_id is not found and the sign-in fails.

**Comment by negoe** [comment]
Follow up with @shoatman.

**Comment by negoe** [comment]
@Happy202121 What's the authority you are using here?

**Comment by Happy202121** [comment]
Hi @negoe , the AzureCloudInstance is Azure Public, the AadAuthorityAudience is AzureAdAndPersonalMicrosoftAccount. We have also tried using the AzureAdMultipleOrgs authority audience.

The cloud instance has to remain Azure public so our public cloud customers can continue to use it. We've found that no matter the authority we use, the auth request is routed to the correct tenant based on the user's email domain. 

The problem is once the request hits a GCC High domain, it checks for the client_id and can't find it. This is because the client_id exists in the Azure public cloud.

**Comment by negoe** [comment]
This error means that wrong configuration is made for the Client ID OR tenant ID in your code, first please confirm that both are same as your azure portal application client and tenant.

![image](https://user-images.githubusercontent.com/38259657/184421003-de73f83b-f358-4410-9783-a900aae1d92e.png)
