### ISSUE TITLE
Call option feature is not redirecting to client app - Call Option redirection not working

### ISSUE THREAD

**Issue by AbhinawTripathi** [AzureAD/microsoft-authentication-library-for-android#1689]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.
My app is live and in production. Earlier I was using MSAL B2C version 1.4.0 to text me feature was working for all Android Devices and Call Me was not working below Android OS version 11 for MFA(Multi-factor Authentication). Now I have upgraded the MSAL version to 3.0.2 and for this library, version text me is working for all android devices but the Call Me feature is not working for Android OS versions above 11. So after call for MFA Authentication . it is not redirecting to our client app . Sometime is stuck on that page and also we did not get any access token. 

**Smartphone (please complete the following information):**
 - Device: Pixel 3a , Samsung Galaxy S12, and Samsung Galaxy S20
 - Android Version: API Level 30,31,32,33, Build Number
 - Browser -  Chrome
 - MSAL Version - 3.0.2

**Stacktrace**
If a crash occurs, include the stacktrace.

**To Reproduce**
Multi factor authentication to acquire access token after text and call option.
it should redirect to our client app but it is not happening only for Call option

**Comment by shoatman** [comment]
@negoe - I think we need to add or redirect this to the B2C team.  It's possible that it's a B2C server configuration issue or it's possible that this is a userflow parameter or authority not being correctly used.  

@AbhinawTripathi - Feel free to attach your MSAL configuration.

**Comment by negoe** [comment]
Following up with B2C team.

**Comment by negoe** [comment]
@JasSuri Assigning it to you based on Katherine Legg's email.

**Comment by JasSuri** [comment]
Does this reproduce with a **Sign In** User Flow with Multi Factor Auth set to always on?
Does this reproduce with the current latest version of MSAL? (Version 4.1.3)

**Comment by negoe** [comment]
No response. Closing the issue.
