### ISSUE TITLE
Unable to open BrowserTabActivity with an emulator on a PC connected to a VPN

### ISSUE THREAD

**Issue by saharami** [AzureAD/microsoft-authentication-library-for-android#1696]
Dear team,

Our app currently uses B2C library for login authentication.
We would like to run this app on an Android emulator on a PC with a VPN setup.
We have already configured the proxy settings to pass through the VPN in the emulator settings, so the app can launch.
However, when we try to start B2C's BrowserTabActivity, we get the following error;
"Unable to perform cloud discovery".

Environment;
- minSDK...28
- Android emulator...Pixel4 API28
- The proxy setting is configured from the emulator's wifi settings (the following photo on the left).
- AndroidStudio proxy setting is also configured (the following photo on the right).
- We have configured Android NetworkSecurityConfig.

As a side note, it works fine on a PC without VPN.

How can we make it work on the PC with the VPN? Is there anything else we need to do?

We would highly appreciate it if you could help us.

emulator setting | AndroidStuido setting
---- | ----
<img width="188" alt="emulator_settings" src="https://user-images.githubusercontent.com/105252452/191419647-e19eb938-5c4b-4722-9fdd-c993f3536690.png"> | <img width="500" alt="androidstudio_setting" src="https://user-images.githubusercontent.com/105252452/191419700-4d2b01c0-f370-4b71-b8e4-73ed072881cc.png">

**Comment by shoatman** [comment]
@negoe - Let's document the endpoints that must be reachable for the library and then have @saharami confirm that those endpoints are reachable via the VPN configuration.

**Comment by negoe** [comment]
@saharami Can you please test that you are able to reach this [endpoint ](https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/common/oauth2/v2.0/authorize)with VPN connected?

**Comment by negoe** [comment]
@saharami Please let us know if you have any follow up questions? Closing due to no response.
