### ISSUE TITLE
AcqureTokenSilently gives old access token. Access token returned is from previous 2-3 days

### ISSUE THREAD

**Issue by FarazJelani** [AzureAD/microsoft-authentication-library-for-android#1699]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel, OnePlus 6, etc]
 - Android Version: [e.g. API Level, Build Number]
 - Browser [e.g. Chrome, Edge]
 - MSAL Version

**Stacktrace**
If a crash occurs, include the stacktrace.

**To Reproduce**

If related to user experience, use the format:

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**

**Actual Behavior**
A description of what actually happened.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by FarazJelani** [comment]
Due to security issue, i cannot include the logs. Let me explain issue again.
1> User logged in successfully
2> Next time login happens via acquire token silently. This works fine some few days and then it returned access token 2 days back(by seeing, it already expired.)

**Comment by negoe** [comment]
@FarazJelani Do you mean it is returning an expired access token?

**Comment by FarazJelani** [comment]
Yes, the access token was expired already. As we know it last for about 1 to 1.5 hrs. The access token was from past. i got a logs from one user on 10/06/2022 and while going through logs i came to know that its expiry time is 09/20/2022. She was calling  acquire token silently.

**Comment by negoe** [comment]
@FarazJelani Can you share the repro steps and the version of MSAL lib you are using?

**Comment by FarazJelani** [comment]
MSAL Version - 4.0.0
Reproducible steps:-
1> Acquire token interactively (first login).
2> Acquire token silently (consecutive login)
3> Returned expired token (after few days of login via acquire token silently)

**Comment by negoe** [comment]
We created a hotfix and have released it in the September 2022 Broker release and should be distributed to 100% by end of October 2022.
