### ISSUE TITLE
No JavaDoc for latest release

### ISSUE THREAD

**Issue by Innova133** [AzureAD/microsoft-authentication-library-for-android#1702]
**Describe the bug**
I am unable to find the JavaDoc (Library Reference) for the latest release.

**Smartphone (please complete the following information):**
 - Device: Any device with internet access.
 - Android Version: Any
 - Browser Any
 - MSAL Version:  any MSAL version > 2.23

**Stacktrace**
N/A

**To Reproduce**

> 1. Go to the MSAL Android SDK Github site.
> 2. Click on "Library Reference"

**Expected behavior**
You should be taken to the MSAL Java Doc for the latest version (4.0.2) as of this writing.  

**Actual Behavior**
You are taken to the MSAL Java Doc of version 2.2.3

**Comment by negoe** [comment]
Hi @Innova133

Thanks for sharing this. There was no Java Doc published as part of this release. We will update the link with the right url. 

Thanks.

**Comment by Innova133** [comment]
Do you know when that will be completed?
