### ISSUE TITLE
Unable to open BrowserTabActivity on API 32

### ISSUE THREAD

**Issue by aazamk** [AzureAD/microsoft-authentication-library-for-android#1708]
com.microsoft.identity.client.exception.MsalClientException:  
 Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a  PendingIntent.
 Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by negoe** [comment]
Thanks for the comment. We use this section for issues, bugs, and feature requests specifically. If you would like to start a discussion or drop a comment please use [Discussion ](https://github.com/AzureAD/microsoft-authentication-library-for-android/discussions)section for posts like these.

**Comment by aazamk** [comment]
Thanks @negoe, What is the status of this bug. It will include in upcoming releases ?
