### ISSUE TITLE
Microsoft Modern Authentication using Chrome with MSAL on Android 

### ISSUE THREAD

**Issue by shepeliev** [AzureAD/microsoft-authentication-library-for-android#1711]
Unfortunately, there is no way to re-open the issue, so I raised a new one that is follows #1320

> The question is related to https://stackoverflow.com/questions/66053874/microsoft-modern-authentication-using-chrome-with-msal.
Using MSAL library for Android with Edge browser, then the redirection URL below works properly. The user is required to choose the identity certificate installed as part of Microsoft Intune Company portal.

> https://login.microsoftonline.com/common/oAuth2/v2.0/authorize?web_view_zoom_enabled=true&x-client-CPU=arm64-v8a&response_type=code&x-client-Ver=2.0.0&code_challenge_method=S256&x-client-DM=XYZ&x-client-OS=28&x-client-SKU=MSAL.Android&web_view_zoom_controls_enabled=true&client_id=...&client-request-id=...&instance_aware=false&scope=Calendars.Read%20User.Read%20openid%20offline_access%20profile&claims=%7B%7D&redirect_uri=...%3A%2F%2Fcallback&state=...&prompt=select_account&code_challenge=...

> However, using Chrome not. There is no request of identity certificate installed as part of Microsoft Intune Company portal and the user is requested to enroll the device (although the device already enrolled and compliant).

> Using the above link but without "x-client-SKU=MSAL.Android" or even changing it to "x-client-SKU=Android", then Chrome behavior is the same as Edge behavior and user is prompt to choose the identity certificate. How can this be resolved?

The issue still exists in v.4.0.3. I can't complete authentication in Chrome without deleting x-client-SKU=MSAL.Android. Is there any workaround that I could apply in the code? Or using Edge is only way for now?

**Comment by rpdome** [comment]
Hi @shepeliev,

Is there any correlation ID + timestamp I can look at? 
https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Diagnostic-Data-Collection

NOTE: you can get SSO and acquire token without having to prompt for certificate by utilizing the broker. This could be done by modifying the following value in your MSAL configuration. (if not manually set, MSAL will use the broker by default. 

"broker_redirect_uri_registered": true

The broker does not support any Browser though. It would use its own webview.

Broker is shipped as part of Intune Company Portal - [link](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on).

Thanks,
Dome

**Comment by shepeliev** [comment]
Thank's for response. Unfortunately, we can't utilize the broker as we also have users that don't use Microsoft Intune MAM. 

Here is a correlation ID: 63c00eec-2b73-41e4-9cc7-7425c574fd7f
Timestamp: 2022-10-20T11:44:53.165Z
Some logs that I could collect: [msal2.log](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/9829554/msal2.log)

**Comment by rpdome** [comment]
> Thank's for response. Unfortunately, we can't utilize the broker as we also have users that don't use Microsoft Intune MAM.
> 
> Here is a correlation ID: 63c00eec-2b73-41e4-9cc7-7425c574fd7f Timestamp: 2022-10-20T11:44:53.165Z Some logs that I could collect: [msal2.log](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/9829554/msal2.log)

I'll take a look.

Even if the users doesn't use Intune/MAM, they should still benefit from getting SSO from broker. Just to give you an example - all Microsoft apps, e.g. Word/Excel/Powerpoint, are all using broker - and not all users are using Intune/MAM.

This particular "identity certificate" is actually device certificate that the Broker owns. By clicking the button, what happens is that the app would ask the broker to install the cert onto device's KeyChain. This is to unblock the scenario where broker cannot be involved, i.e. when you're trying to access Office Web App on Chrome.

With broker, there is another mean to perform device authentication without having to prompt the user to get the certificate from KeyChain. For scenarios without the certificate, Broker will simply operate like MSAL.

In general, there is no reason not to use broker - unless you specifically requires external Browser apps in your flow.

Thanks,
Dome

**Comment by shepeliev** [comment]
Thank you @rpdome, I'll take a look at suggested how-to.
