### ISSUE TITLE
API >21  "Unable to perform cloud discovery" on signin

### ISSUE THREAD

**Issue by whiteLT** [AzureAD/microsoft-authentication-library-for-android#1723]
newest msal 4.0.5 throws error: "Unable to perform cloud discovery" on signin with newer android devices API >21. When I use older device everything works alright.

Related to this issue:

https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/676

**Comment by negoe** [comment]
@whiteLT Can you please provide a stack trace for this issue?

**Comment by negoe** [comment]
Closing as no response.
