### ISSUE TITLE
fingerprint: Biometric login does not automatically proceed to log user in

### ISSUE THREAD

**Issue by kshah25** [AzureAD/microsoft-authentication-library-for-android#1726]
We have Azure B2C set up in our organization, and we are using MSAL to open the B2C login webview.

We are able to successfully use the fingerprint reader to fill in our username/password, but after that is done, the webpage does not proceed to log in. It just remains on the login screen with the username/password information filled in. Usually, other apps proceed to perform a login after a successful fingerprint authentication.

Does MSAL not handle this currently? BTW I'm on version 4.0.5

**Comment by negoe** [comment]
@kshah25 Which username/pswd it is? Have you tried acquiring the token silently first?

**Comment by negoe** [comment]
Hi @kshah25 
Currently, MSAL Android does not directly integrate with biometrics, but end-user applications can integrate with it directly. However, it only works for silent authentication and not for interactive scenarios. In this case, it seems that the user is trying to use interactive authentication, which is not possible. We have noticed that fingerprint sign-in is required for most of the mobile apps and prompted for password in some cases too. We believe the same is expected for AAD, where the user needs to do interactive authentication once, then silent authentication with biometric APIs. This integration is something that the app developer would need to do on their own.

Thanks,
Neha

**Comment by helpajith** [comment]
Hi @negoe 
If I read your answer right, if MFA is enabled, I have to go through interactive authentication. In that case, if I need fingerprint functionality in my Android app while having MFA enabled in the tenant, I have to first ask the user to do an interactive authentication and once the user has completed it, can the subsequent logins be done using silent authentication even though MFA is enabled in the tenant?

**Comment by ajithsrepo** [comment]
Hi @negoe 
If I read your answer right, if MFA is enabled, I have to go through interactive authentication. In that case, if I need fingerprint functionality in my Android app while having MFA enabled in the tenant, I have to first ask the user to do an interactive authentication and once the user has completed it, can the subsequent logins be done using silent authentication even though MFA is enabled in the tenant?

**Comment by ajithsrepo** [comment]
Hi @negoe 
Is there any update on my previous question regarding silent authentication?
