### ISSUE TITLE
Device ID not detected in MSAL aquire token using MSAL 4.0.2

### ISSUE THREAD

**Issue by rkrsgithub** [AzureAD/microsoft-authentication-library-for-android#1729]
**Describe the bug**
My app is live and in production. While I check sign in events. I am not able to see device ID and Join type.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android Version: Android 13
 - Browser : Chrome, Edge
 - MSAL Version 4.0.2

**To Reproduce**
Just login using mobile app and check sign in events in portal. the device ID and Join Type is blank

**Comment by negoe** [comment]
@dstrockis Who can I reach out to in portal team? Can you please help with this one?

**Comment by rajohns08** [comment]
@negoe, what was your solution to this issue?
