### ISSUE TITLE
Biometric or FaceID authentication 

### ISSUE THREAD

**Issue by AliAzaz** [AzureAD/microsoft-authentication-library-for-android#1732]
**Problem**
Is there any way to log-in user through a touch id or face id inside our application having integrated MSAL SDK because it is frustrating for a user to retype the password again and again as it was already authenticated at first-time login.

**Solution**
Users would easily log-in through touch id or face id.

**Comment by AliAzaz** [comment]
@negoe any sort of solution or workaround on my above query?

**Comment by negoe** [comment]
@AliAzaz MSAL Android doesn't provide biometric APIs directly. You can try Android documentation [here ](https://developer.android.com/training/sign-in/biometric-auth) to integrate with biometric id.
