### ISSUE TITLE
Version "Chaos"

### ISSUE THREAD

**Issue by torsten-sauer** [AzureAD/microsoft-authentication-library-for-android#1733]
Hi guys,

our dependency scanner recognised a new version **4.1.0** of the msal lib. But after having a closer look at this new version we got really confused:

Released date is "9 days ago" (Nov 12th), but the assets are from January...

![image](https://user-images.githubusercontent.com/7765372/203072180-3e1df4b0-eac5-44e1-994a-210d1703c093.png)

The linked PR https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1703 is from October 4th.

So it's pretty weird. We still stick to version **4.0.5** as this seems the "latest" to us, but maybe you can clarify this?

**Comment by fadidurah** [comment]
Hello @torsten-sauer, this issue has been fixed now. Please refer to the new 4.1.0 release:
![image](https://user-images.githubusercontent.com/88730756/208768380-7c844bf8-db18-4510-8962-558171d1a046.png)
