### ISSUE TITLE
Credentials are not asked again after signout and using Prompt.LOGIN

### ISSUE THREAD

**Issue by jcraane** [AzureAD/microsoft-authentication-library-for-android#1736]
User is not prompted for credentials when calling aquireToken

Scenario:
1. (first time) User logs in using the aquireToken call. The withPrompt(Prompt.LOGIN) option is used. As authorization user agent SYSTEM is used.
2. Browser opens and user enters credentials.
3. User logs out using the signOut method
4. User logs-in again using the System browser.

Expected behavior:
After step 4, user should enter new credentials.

Actual behavior:
User does not have to enter new credentials and logs in automatically.

When using a WEBVIEW (instead of system browser) as authorization user agent, and after clearing cookies using CookieManager.getInstance().removeAllCookies(null), the user is asked for new credentials.

Is the above intended behavior or are we missing some steps in the signin/signout process?

Device/version information
- All devices
- All Android versions
- MSAL version: 4.1.0

If you need any additional information let me know.

**Comment by tinjump** [comment]
We are also facing the same issue. We are using MultiAccount mode application, and every time when we call removeAccount API, it says account is removed, but not asking user to enter the password again.

**Comment by harsha973** [comment]
Facing a similar issue. This means the user is in an infinite loop of logged-in state even if the account is removed on MSAL. Browser doesn't know this and it will quickly redirect back to the app with tokens of the previously logged-in user.

**Comment by negoe** [comment]
The behavior you are describing is expected when using the SYSTEM browser as the authorization user agent in MSAL for Android. When using the SYSTEM browser, the user's session is persisted across multiple authentication attempts, which can lead to the behavior you are observing.

One way to force the user to enter new credentials is to use a different authorization user agent, such as the WEBVIEW as you have already mentioned. When using the WEBVIEW, MSAL for Android relies on the webview's cookie store, which is separate from the system browser's cookie store. This means that when you clear cookies using CookieManager.getInstance().removeAllCookies(null), the user's session is also cleared, and they will be prompted to enter new credentials.

**Comment by harsha973** [comment]
I understand the alternatives via WEBVIEW. This comes with its own pitfalls. This means if I go to my default browser I won't have ability to perform SSO. I do believe MSAL library should provide a mechanism to revoke refresh token when removing account. It can be passed via params when calling signout or remove account. Without this, the seemless experience for the user to signout is compromised.

**Comment by akshaytandroid** [comment]
I am still facing this issue. 

I am explicitly clearing the webview cookies along with calling the `mSingleAccountApp?.signOut()` method. It still persists the previous logged in account. and directly logs the user in without asking the password again.

Can anyone help me with this? @jcraane  @harsha973
