### ISSUE TITLE
use big networking and big memory when I try signIn after changed device time to future (about 7days later)

### ISSUE THREAD

**Issue by woongs0901** [AzureAD/microsoft-authentication-library-for-android#1738]
**Describe the bug**
 
1. Set "cleartextTrafficPermitted" true on my app (or your sampleapp) 
2. Changed Device time to future time (about 7 days later) 
3. try signIn with this library.

then, use big networking (15mb per second) and use big native memory(over 1GB) in very shorttime.

**Smartphone (please complete the following information):**
 - Device: all
 - Android Version: all
 - Browser all
 - MSAL Version : 4.1.0
 
 * set "cleartextTrafficPermitted" is true

**Stacktrace**
no crash

**To Reproduce**

If related to user experience, use the format:

1. Set "cleartextTrafficPermitted" true on my app (or your sampleapp) 
2. Changed Device time to future time (about 7 days later) 
3. try signIn with this library.

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
no use big memory and networking.

**Actual Behavior**
use big memory and networking.

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by negoe** [comment]
@woongs0901 Please provide more details on what do you mean by "use big memory and networking."?

**Comment by woongs0901** [comment]
> @woongs0901 Please provide more details on what do you mean by "use big memory and networking."?

if i try sign in than increase allocate  memory and use many network resource.
i attached capture.
![스크린샷 2023-01-09 오후 1 17 36](https://user-images.githubusercontent.com/69625396/211240966-c9c9db1b-57be-4f44-9e1a-aa29f133a861.png)
![스크린샷 2023-01-09 오후 1 20 46](https://user-images.githubusercontent.com/69625396/211240973-4bc0c895-a560-4571-9d9d-fd814209e5c2.png)

I think when you need to renew the ssl certificate, it seems that the network request is made repeatedly if the setting (usesCleartextTraffic) is turned on.

**Comment by negoe** [comment]
@woongs0901 If your SSL certificate has expired or needs to be renewed,  enabling the "usesCleartextTraffic" setting may cause issues when renewing the SSL certificate, especially if the server requires HTTPS connections. If the server requires HTTPS connections, your app will continue to make unencrypted HTTP requests and may encounter errors or repeated network requests.

To avoid these issues, it is recommended to disable the "usesCleartextTraffic" setting and use HTTPS or TLS to encrypt your traffic. This will ensure that your app communicates securely with the server and that the SSL certificate is properly validated.
Additionally, you may want to check if there are any issues with the server's SSL certificate configuration or if there are any other issues that could be causing repeated network requests.
