### ISSUE TITLE
acquireTokenSilentAsync: The signed in account does not match with the provided account

### ISSUE THREAD

**Issue by wondering639** [AzureAD/microsoft-authentication-library-for-android#1742]
**Describe the bug**
I am using MSAL for Android and confused about this error:

```
The signed in account does not match with the provided account.
(Error code current_account_mismatch, from acquireTokenSilentAsync)
```
This is what I am doing:

1. Uninstall my own app to get clean testing conditions
2. Install it again
3. Login via `signIn()` method of MSAL
4. Call `acquireTokenSilentAsync()`:

```
     val parameters = AcquireTokenSilentParameters.Builder()
         .withScopes(scopes.toList())
         .withCallback(authenticationCallback)
         .build()

     _msalPublicClient.acquireTokenSilentAsync(parameters)
```
This call leads to a call of the onError method of the authenticationCallback with

`com.microsoft.identity.client.exception.MsalClientException: The signed in account does not match with the provided account.`
How can that be fixed? How can the provided account (whatever that is?) be different from the signed in account on a new app installation?

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: Latest Android
 - Browser Chrome
 - MSAL Version 4.1.0

**To Reproduce**
See above

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Comment by RoarGronmo** [comment]
Here are at least 2 stackoverflow issues on this error: 

https://stackoverflow.com/questions/74975180/microsofts-java-implementation-of-msal-isingleaccountpublicclientapplication-acq

https://stackoverflow.com/questions/74956535/acquiretokensilentasync-the-signed-in-account-does-not-match-with-the-provided

and has been mentioned before here, but the issue is closed... 
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1475

**Comment by negoe** [comment]
Adding @rpdome.

**Comment by RoarGronmo** [comment]
Still an issue in `4.1.3`

**Comment by wondering639** [comment]
@negoe @rpdome Is there any update on this? This renders the new API completely useless which however is part of a stable release!?
Edit: Workaround: Use the deprecated method overload. But that can only be a workaround as it's deprecated.

**Comment by luongvo** [comment]
@wondering639 we need to provide mandatory fields
```
            val parameters = AcquireTokenSilentParameters.Builder()
                .withScopes(SCOPES)
                .forAccount(account)
                .fromAuthority(AUTHORITY)
                .withCallback(callback)
                .build()
```

**Comment by RoarGronmo** [comment]
> @wondering639 we need to provide mandatory fields
> 
> ```
>             val parameters = AcquireTokenSilentParameters.Builder()
>                 .withScopes(SCOPES)
>                 .forAccount(account)
>                 .fromAuthority(AUTHORITY)
>                 .withCallback(callback)
>                 .build()
> ```

As far I have observed there may be situations where you receive this error `Do not provide callback for synchronous methods`, 
then you need to omit it the callback and just handle the result like this (in android kotlin): 
```
    suspend fun generateAccessToken(accessScope: String = MICROSOFT_ACCESS_SCOPE_USER_READ):String?
    {
        /**
         * Generates accessToken
         * */

        var accessToken: String?=null
        try {
            microsoftAccountViewModel.apply {
                singleAccountAppMLD.value?.let { singleAccountApp->
                    withContext(Dispatchers.IO){


                        val iAuthenticationResult = singleAccountApp.acquireTokenSilent(
                            AcquireTokenSilentParameters(
                                AcquireTokenSilentParameters.Builder()
                                    .withScopes(arrayOf(accessScope).toMutableList())
                                    .fromAuthority(MICROSOFT_ACCESS_AUTHORITY)
                                    .forAccount(singleAccountApp.currentAccount.currentAccount)
                                    /*.withCallback(object: SilentAuthenticationCallback{
                                        override fun onSuccess(authenticationResult: IAuthenticationResult?) {
                                            accessToken = authenticationResult?.accessToken
                                            lastIAuthenticationResultMLD.postValue(authenticationResult)
                                            Log.i(TAG, "generateAccessToken: accessToken = $accessToken")
                                            if(accessToken==null) Message.error("accessToken was null")
                                        }

                                        override fun onError(exception: MsalException?) {
                                            exception?.message?.let{
                                                Message.error(it)
                                            }?:let{
                                                Message.error("Unknown MSAL exception")
                                            }
                                        }

                                    })*/
                            )
                        )
                        /*
                        val iAuthenticationResult = singleAccountApp.acquireTokenSilent(
                                arrayOf(accessScope),
                                MICROSOFT_ACCESS_AUTHORITY
                        )
                        */
                        accessToken = iAuthenticationResult.accessToken
                        lastIAuthenticationResultMLD.postValue(iAuthenticationResult)
                        Log.i(TAG, "M678: generateAccessToken: accessToken = $accessToken")


                    }
                }?:let {
                    Log.e(TAG, "generateAccessToken: singleAccountMLD.value = null !!")
                    Message.error(applicationContext.getString(R.string.message_error_you_may_not_be_signed_in_sign_in_again))
                }
            }
        }catch (exception: Exception)
        {
            Log.e(TAG, "generateAccessToken: acquireTokenSilent exception", exception)
            Message.error(exception.message?:applicationContext.getString(R.string.message_error_acquire_token_unknown_error))
        }

        return accessToken
    }
```
