### ISSUE TITLE
acquireToken requires Fragment, while signIn is happy with an Activity

### ISSUE THREAD

**Issue by wondering639** [AzureAD/microsoft-authentication-library-for-android#1744]
**Describe the bug**
acquireToken requires Fragment, while signIn is happy with an Activity, however with Jetpack Compose we only have an Activity, not a Fragment. Also to my understanding signIn does basically the same as acquireToken , so why do we need a Fragment for acquireToken? We should be ableo to use acquireToken with an Activity.

 - MSAL Version 4.1.0

**Comment by negoe** [comment]
@wondering639 AcquireToken requires a Fragment because it utilizes the Authorization Code Grant Flow for OAuth2, which requires user interaction for authentication and consent. The user interaction is handled by a web view displayed in a Fragment, which manages the lifecycle of the web view to ensure the security of the authentication process and safeguard the user's credentials.

**Comment by wondering639** [comment]
@negoe There's the deprecated version of `acquireToken` which requires only an `Activity`, also shows the web view (aka chrome custom tab) and even works fine with Jetpack Compose.
```
@Deprecated 
public abstract void acquireToken(     @NonNull android.app.Activity activity,
    @NonNull String[] scopes,
    @NonNull com.microsoft.identity.client.AuthenticationCallback callback )
```

Then there's the newer version
```
public abstract void acquireToken(     @NonNull com.microsoft.identity.client.AcquireTokenParameters acquireTokenParameters )
```
which requires a `Fragment` as `AcquireTokenParameters.Builder()` only has a `withFragment` method.

So we have an old, deprecated version that's happy with an Activity and a new version that requires a Fragment in a time where you don't have Fragments anymore with Jetpack Compose. Obviously there's no technical reason for a Fragment (at least not for one passed in directly by the consuming developer) as it worked with an Activity in the past. Also note that the deprecated version that only requires an Activity works fine in modern Android versions with Jetpack Compose. But that's the version that was deprecated. Sorry, but something really goes wrong here. Please have a look at this again, thanks.

**Comment by negoe** [comment]
@wondering639 One possible workaround is to create a simple Fragment that acts as a bridge between the Activity and the MSAL library. This Fragment can be added to the Activity's FragmentManager and used to call the acquireToken method with the newer version of the AcquireTokenParameters parameter.
