### ISSUE TITLE
Getting ClientException: Missing required tokens of type: {0} after login

### ISSUE THREAD

**Issue by krunaldarji** [AzureAD/microsoft-authentication-library-for-android#1763]
public class MainActivity extends AppCompatActivity {

    String[] scopes = {"openid","offline_access"};
    IMultipleAccountPublicClientApplication mMultipleAccountApp = null;
    IAccount mFirstAccount = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        PublicClientApplication.createMultipleAccountPublicClientApplication(this,
                R.raw.config_msal,
                new IPublicClientApplication.IMultipleAccountApplicationCreatedListener() {
                    @Override
                    public void onCreated(IMultipleAccountPublicClientApplication application) {
                        mMultipleAccountApp = application;
                        Log.e(this.getClass().getSimpleName(), "onCreated: ");
                    }

                    @Override
                    public void onError(MsalException exception) {
                        //Log Exception Here
                        Log.e(this.getClass().getSimpleName(), "onError: "+exception.getMessage());
                    }
                });

    }

    private AuthenticationCallback getAuthInteractiveCallback() {
        return new AuthenticationCallback() {
            @Override
            public void onSuccess(IAuthenticationResult authenticationResult) {
                /* Successfully got a token, use it to call a protected resource */
                String accessToken = authenticationResult.getAccessToken();
                // Record account used to acquire token
                mFirstAccount = authenticationResult.getAccount();
                Log.e("MainActivity", "Success : username " + mFirstAccount.getUsername());
                Log.e("MainActivity", "Success : token " + mFirstAccount.getIdToken());
            }

            @Override
            public void onError(MsalException exception) {
                if (exception instanceof MsalClientException) {
                    //And exception from the client (MSAL)
                    Toast.makeText(getApplicationContext(),"onError" +  exception.getMessage() + "",Toast.LENGTH_LONG).show();
                } else if (exception instanceof MsalServiceException) {
                    //An exception from the server
                    Log.e("MainActivity", "onError service exception :  " + exception.getMessage());
                }
            }

            @Override
            public void onCancel() {
                /* User canceled the authentication */
                Log.e("MainActivity", "onCancel:  ");
            }
        };
    }

    public void getToken(View view) {
        mMultipleAccountApp.acquireToken(this, scopes, getAuthInteractiveCallback());
    }
   }

**Comment by negoe** [comment]
@krunaldarji The ClientException: Missing required tokens of type error occurs when the access token or other required tokens are missing or not obtained during authentication.

The scopes array includes "openid" and "offline_access" scopes. It is not clear to me though which resource or API the token is being requested for. Can you please check if the requested scopes are valid or not for the resource?

Make sure that you are requesting the correct scopes for the resource you are trying to access. Also, verify that the user is correctly authenticated and that the token is being requested after authentication is completed. Additionally, you may need to check the configuration file (R.raw.config_msal) to ensure it is properly configured with the correct authority and redirect URI.
