### ISSUE TITLE
SignInInteractive returns result without authenticating.

### ISSUE THREAD

**Issue by ggGoblin** [AzureAD/microsoft-authentication-library-for-android#1773]
**Describe the bug**
When using Active directory to sign into App authentication can be skipped.

**Smartphone (please complete the following information):**
tested Android

**To Reproduce**

1. Sign in once using Active Directory login screen.
2. Logout
3. Open sign in page then close it when it asks for email/password
4. Open sign in page a second time, and no need for email/password you are logged in successfully.

Noticed the issue when I started testing with corporate account.
Interested to know if anyone has come across this, and what solution they used.

**Expected behavior**
Unable to log in without entering credentials

**Actual Behavior**
Able to log in without credential

**Comment by negoe** [comment]
@ggGoblin To address this issue, you can try implementing these steps:

1. Disable token caching by calling PublicClientApplication.setTokenCacheEnabled(false) when initializing the MSAL instance.
2. Force the user to sign in again by calling PCA.remove(Account) to remove the previously authenticated account from the MSAL instance. 
3. If the above steps do not work, you can also try adding a flag to the authentication request to force the server to require user interaction for authentication. This can be done by setting the Prompt parameter in the authentication request to Prompt.FORCE_PROMPT.
