### ISSUE TITLE
MsalClientException: No cached accounts found for the supplied homeAccountId and clientId

### ISSUE THREAD

**Issue by Pramitjain** [AzureAD/microsoft-authentication-library-for-android#1779]
Getting Refresh token issue with Active Directory Accounts.

It is happening due to Active Directory User where there is no username and password.
With username and Password account we get the refresh token properly.

**Smartphone:**
 - Device: Pixel 2
 - Android Version: 10
 - MSAL Version 2+

**Stacktrace**
com.microsoft.identity.client.exception.MsalClientException: No cached accounts found for the supplied homeAccountId and clientId
at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1903)
at com.microsoft.identity.client.PublicClientApplication$18.onError(PublicClientApplication.java:1894)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:442)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$800(CommandDispatcher.java:83)
at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:424)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**To Reproduce**
[Steps to reproduce the behavior:](https://github.com/Azure-Samples/ms-identity-android-java)
https://github.com/Azure-Samples/ms-identity-android-java

Additional context
We have asked Microsoft support, but haven't received an answer so far.
We've been riddled with this bug for a couple of weeks now, and we have no idea how to proceed.
My assumption is, there is a specific setting on the B2C config that is breaking the MSAL Android implementation, but we cannot find anything.

What can be the possible reasons this error occurs?
Can someone share a clue on what to look for?

Below is the configuration and method we are using.

{  
"client_id": "",
"authorization_user_agent": "DEFAULT", 
"account_mode": "MULTIPLE",  
"redirect_uri": "msauth://com.example.azureb2c/FpJ3U%2F1Xii%2F9TB63TWmR%2BLI6EsU%3D",  
"broker_redirect_uri_registered": false,  
"authorities": [    {      
"type": "B2C",      
"authority_url": "",      
"default": true    
} 
]}

fun acquireTokenSilentAsync(
    multipleAccountPublicClientApplication: IMultipleAccountPublicClientApplication,
    policyName: String,
    scopes: List<String?>?,
    callback: SilentAuthenticationCallback
) {
    for (account in accounts) {
        if (policyName.equals(getB2CPolicyNameFromAccount(account), ignoreCase = true)) {
            val parameters = AcquireTokenSilentParameters.Builder()
                .fromAuthority(getAuthorityFromPolicyName(policyName))
                .withScopes(scopes)
                .forAccount(account)
                .withCallback(callback)
                .build()
            multipleAccountPublicClientApplication.acquireTokenSilentAsync(parameters)
            return
        }
    }
    callback.onError(
        MsalUiRequiredException(
            MsalUiRequiredException.NO_ACCOUNT_FOUND,
            "Account associated to the policy is not found."
        )
    )
}

**Comment by negoe** [comment]
@Pramitjain Have you configured authority? The authority is a URL that indicates a directory that the MSAL can request tokens from. Use the following format: https://<your-tenant-name>.b2clogin.com/<your-tenant-name>.onmicrosoft.com/<your-sign-in-sign-up-policy>. Replace <your-tenant-name> with your Azure AD B2C [tenant name](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tenant-management-read-tenant-name#get-your-tenant-name). Then, replace <your-sign-in-sign-up-policy> with the user flows or custom policy

You can read more about it [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-sample-android-app?tabs=kotlin)

**Comment by Pramitjain** [comment]
Hi @negoe thanks for your response.
Yes i have configured the authority I am getting the token when first time i login but after one hour token expiry time when we call the Refresh token on that time we are getting the below error  No cached accounts found for the supplied homeAccountId and clientId.

This error is happening only with the user who are Approved AD-User account.

Users with UserName and Password are getting the refresh token properly.

**Comment by negoe** [comment]
@Pramitjain Can you please clarify what do you mean by "Users with UserName and Password"?

**Comment by Pramitjain** [comment]
@negoe 

![image](https://user-images.githubusercontent.com/13433844/226569817-a71d0549-33a2-4595-a362-c2c2cb178313.png)

We are getting refresh token when we login with entering username and password.
but when we login as an approved AD user accounts we are not getting refresh token.

**Comment by negoe** [comment]
Sorry would need to understand the differentiation on your side in what case you say Approved AD Users v/s email and password. Are email password users using a different account than Azure AD?

**Comment by SkyleKayma** [comment]
@Pramitjain
Did you manage to get this part working? I'm encountering the same issue over a year later.

Edit: As crazy as it seems, this is the way to go:
https://stackoverflow.com/a/74352248/9326289

It changes the `tid` returned in the JWT token, and then the account match is successful.

**Comment by montrifork** [comment]
I'm still having this issue, @negoe what he means in this case is the difference between an AD account that uses Microsoft login and an account using the regular login using a user name and password, can this be reopened or shall I make a new one?

@Pramitjain did you get a solution for this?

**Comment by montrifork** [comment]
> @Pramitjain Did you manage to get this part working? I'm encountering the same issue over a year later.
> 
> As crazy as it seems, this is the way to go: https://stackoverflow.com/a/74352248/9326289
> 
> It changes the `tid` returned in the JWT token, and then the account match is successful.

Where can I change this policy?

**Comment by SkyleKayma** [comment]
In **Identity Experience Framework** menu item in your B2C tenant in the Azure portal, you should have a file named `TrustFrameworkBase.xml`. It is one of the file that you need to configure for MSAL ADB2C connection to work with internal & external account.

After that, as stated in the StackOverflow post, you need to get rid of that line:
`<OutputClaim ClaimTypeReferenceId="tenantId" PartnerClaimType="tid" />`
This line is adding a wrong `tid` field in the JWT token that is breaking the MSAL verification.

And then (if needed, for me if I remember correctly it was), you need to remove the `tenantId` OutputClaim in the `SignUpSignIn.xml` policy.

See: https://learn.microsoft.com/en-us/azure/active-directory-b2c/trustframeworkpolicy
(And maybe this: https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy#upload-the-policies)

**Comment by montrifork** [comment]
> In **Identity Experience Framework** menu item in your B2C tenant in the Azure portal, you should have a file named `TrustFrameworkBase.xml`. It is one of the file that you need to configure for MSAL ADB2C connection to work with internal & external account.
> 
> After that, as stated in the StackOverflow post, you need to get rid of that line: `<OutputClaim ClaimTypeReferenceId="tenantId" PartnerClaimType="tid" />` This line is adding a wrong `tid` field in the JWT token that is breaking the MSAL verification.
> 
> And then (if needed, for me if I remember correctly it was), you need to remove the `tenantId` OutputClaim in the `SignUpSignIn.xml` policy.
> 
> See: https://learn.microsoft.com/en-us/azure/active-directory-b2c/trustframeworkpolicy (And maybe this: https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy#upload-the-policies)

Thanks @SkyleKayma it works now :)
