### ISSUE TITLE
acquireTokenSilentAsync does not refresh the account token id after it expires

### ISSUE THREAD

**Issue by angelmilici** [AzureAD/microsoft-authentication-library-for-android#1790]
**The Bug:**
I am using MSAL version 4.2.0 for Android java for development.

After calling acquireTokenSilentAsync, it does not refresh the account token id after it expires. On the success of the getAuthSilentCallback, the same expired token is returned, it is expected to return a new and valid token. I do not get any MSAL exception error, but I do get this error every time the method is called:

I have also found that the new signIn method is package-private and cannot be used. Maybe this is has something to do with the issue.

This works and there is no issue. However I get the following error:
`Cannot be accessed from outside package` 

I have followed [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1699) and have updated the library version to 4.2.0, but still facing the problem.
I have also looked at [this](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1742) and [this](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1742) issue.

**Comment by negoe** [comment]
@angelmilici, 
Use the SigninParameter Builder, not the constructor, then please share the updates from your side. Following is the example: 

AuthenticationRequestParameters params = new AuthenticationRequestParameters.Builder()

**Comment by angelmilici** [comment]
@negoe Thank you for the response.
As I provided in the original comment, using the construct/builder throws the same error. I am using the builder like so: 
`SignInParameters signInParameters = new SignInParameters.SignInParametersBuilder().withScope(getScopes()).withActivity(this).withCallback(getAuthInteractiveCallback()).build();` 
This throws the following error: 
`'SignInParametersBuilder()' is not public in 'com.microsoft.identity.client.SignInParameters.SignInParametersBuilder'. Cannot be accessed from outside package`
I have also tried: 
`SignInParameters signInParams = SignInParameters.builder().withActivity(this).withLoginHint("").withScopes(Collections.singletonList(("User.Read"))).withPrompt(null).withCallback(getAuthInteractiveCallback()).build();` 
which doesn't throw an error, but the acquire token silent still does not get a new id token, it provides the same old expired one.

**Comment by angelmilici** [comment]
@negoe  Thank you for the response. I accidentally closed this issue so I am reopening it.
As I provided in the original comment, using the construct/builder throws the same error. I am using the builder like so: 
`SignInParameters signInParameters = new SignInParameters.SignInParametersBuilder().withScope(getScopes()).withActivity(this).withCallback(getAuthInteractiveCallback()).build();` 
This throws the following error: 
`'SignInParametersBuilder()' is not public in 'com.microsoft.identity.client.SignInParameters.SignInParametersBuilder'. Cannot be accessed from outside package`
I have also tried: 
`SignInParameters signInParams = SignInParameters.builder().withActivity(this).withLoginHint("").withScopes(Collections.singletonList(("User.Read"))).withPrompt(null).withCallback(getAuthInteractiveCallback()).build();` 
which doesn't throw an error, but the acquire token silent still does not get a new id token, it provides the same old expired one.

**Comment by umangmathur92** [comment]
I am facing exactly the same issue. Is there any update ? This issue occurs intermittently and I have been observing this since the last 7+ days.
I updated to the latest version and have used `SignInParameters` Builder - but to no avail.

**Comment by negoe** [comment]
@umangmathur92 Please share the logs.

**Comment by negoe** [comment]
@umangmathur92 Closing due to lack of response. Feel free to reopen if you have more information to share.
