### ISSUE TITLE
LeakCanary detected memory leak in AuthorizationActivity

### ISSUE THREAD

**Issue by kshah25** [AzureAD/microsoft-authentication-library-for-android#1799]
This happens when I call PublicClientApplication.createMultipleAccountPublicClientApplication() and even pass in the Application context. Here is the heap dump from leak canary:

┬───
│ GC Root: Global variable in native code
│
├─ L1 instance
│    Leaking: UNKNOWN
│    Retaining 787.1 kB in 3132 objects
│    ↓ WindowAndroid.p
│                    ~
├─ l30 instance
│    Leaking: UNKNOWN
│    Retaining 785.5 kB in 3071 objects
│    ↓ l30.b
│          ~
├─ com.android.internal.policy.PhoneWindow instance
│    Leaking: YES (Window#mDestroyed is true)
│    Retaining 785.5 kB in 3070 objects
│    mContext instance of com.microsoft.identity.common.internal.providers.
│    oauth2.AuthorizationActivity with mDestroyed = true
│    mOnWindowDismissedCallback instance of com.microsoft.identity.common.
│    internal.providers.oauth2.AuthorizationActivity with mDestroyed = true
│    ↓ Window.mContext
╰→ com.microsoft.identity.common.internal.providers.oauth2.
  AuthorizationActivity instance
     Leaking: YES (ObjectWatcher was watching this because com.microsoft.
     identity.common.internal.providers.oauth2.AuthorizationActivity received
     Activity#onDestroy() callback and Activity#mDestroyed is true)
     Retaining 6.5 kB in 224 objects
     key = 95317073-bc70-4569-abe4-2b453b4fd9c7
     watchDurationMillis = 5688
     retainedDurationMillis = 684
     mApplication instance of com.shockoe.publix.PublixApplication
     mBase instance of android.app.ContextImpl

**Comment by negoe** [comment]
@kshah25 Thanks for bringing this to our notice. Currently we are busy on working on some other high priority work. However, rest assured that we have noted your concern and we will make sure to revisit it as soon as we have the capacity to do so.
