### ISSUE TITLE
Update the state parameter value to use GUID

### ISSUE THREAD

**Issue by weijjia** [AzureAD/microsoft-authentication-library-for-android#18]
For the request sent to authorize endpoint, we are sending the state as an extra query parameter. The reason for sending state is to verify the value we sent to the sever is the same as the one returned back. 

Simply the state parameter to use a GUID and verify the returned GUID is the same as the one we send.

**Comment by iambmelt** [comment]
This functionality is implemented in `MicrosoftAuthorizationRequest#generateEncodedState()`
