### ISSUE TITLE
4.3.1 and 4.4.0 missing in maven?

### ISSUE THREAD

**Issue by abailey-netzebw** [AzureAD/microsoft-authentication-library-for-android#1801]
I am not able to include msal after version 4.2.0 in our android project. It's missing in https://repo1.maven.org/maven2/com/microsoft/identity/client/msal/ and also including 

```
maven {
            url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
        }
```

doesnt resolve the issue

**Comment by parttimer777** [comment]
I'm seeing the same thing

**Comment by vramasam** [comment]
Hello @negoe  Is there any estimate time period for the latest version to be available in maven? please let us know here

**Comment by negoe** [comment]
@abailey-netzebw  @parttimer777 and @vramasam , This has been fixed for now. Thanks for your patience.
