### ISSUE TITLE
How to set the corresponding scope for Android mailbox reading and sending

### ISSUE THREAD

**Issue by gnmmdk** [AzureAD/microsoft-authentication-library-for-android#1808]
Our company has developed an app that uses mailcore2 to set oauth2 to obtain tokens and then connect. Now I have set the values for the scope as follows:

private val mScopes = listOf(

"User.Read",

"Mail.Read",

"Mail.ReadWrite",

"Mail.Send"

)

Alternatively:

private val mScopes = listOf(

"User.Read",

"IMAP.AccessAsUser.All",

)

This way, access can be obtained_ Toekn, but access obtained_ There seems to be a problem with the token, and it cannot be connected using mailcore2.

The following is the scope I configured in the Azure backend：
![image](https://user-images.githubusercontent.com/18391426/234249478-8c39c288-d890-411b-99df-b4c1188794bc.png)

**Comment by negoe** [comment]
@gnmmdk 
Can you provide more details about the problem with the token? What error message are you seeing when trying to connect using mailcore2? Have you checked if the token is still valid? Tokens usually have an expiration date, and if the token has expired, you won't be able to use it to connect.

**Comment by negoe** [comment]
Closing due to no response. Please feel free to reopen it.
