### ISSUE TITLE
ID Token refresh fails intermittently when using acquireTokenSilentAsync

### ISSUE THREAD

**Issue by umangmathur92** [AzureAD/microsoft-authentication-library-for-android#1809]
**The Bug**
I am using version `4.4.0` of the library and am working on integrating Microsoft Login into an Android App. The `acquireTokenSilentAsync` function fails to refresh the ID Token intermittently and returns the old expired ID Token. I was earlier using version `1.2.0` and faced the same issue.

**Smartphones Used:**
 - Device: Pixel 6A, Samsung S22+
 - Android Version: 13
 - MSAL Android Version: 4.4.0

**Stacktrace**
- No crashes occur

**To Reproduce**

Inside the `dependencies` section of app/build.gradle:
```
implementation 'com.microsoft.identity.client:msal:4.4.0'
```

Inside settings.gradle file:
```
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set RepositoriesMode.FAIL_ON_PROJECT_REPOS
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1'
        }
    }
}

rootProject.name = 'MyApp'

include ':app'
```

The App has a 'Sign in with Microsoft Button' inside `LoginActivity.java`. Along with other business logic, the following code corresponding to the library is executed when this button is clicked:

```
String[] SCOPES = {"User.Read"};

PublicClientApplication.createSingleAccountPublicClientApplication(this, createJsonConfigFile(),
                            new IPublicClientApplication.ISingleAccountApplicationCreatedListener() {
                                @Override
                                public void onCreated(final ISingleAccountPublicClientApplication application) {
                                    application.signIn(SignInParameters.builder()
                                    .withActivity(LoginActivity.this)
                                    .withLoginHint("")
                                    .withScopes(Arrays.asList(SCOPES))
                                    .withCallback(getAuthInteractiveCallback())
                                    .build());
                                }

                                @Override
                                public void onError(final MsalException exception) {
                                    // error handling
                                }
                            }
                    );
```
```
private AuthenticationCallback getAuthInteractiveCallback() {
       return new AuthenticationCallback() {

            @Override
            public void onSuccess(final IAuthenticationResult authenticationResult) {
                String idToken = authenticationResult.getAccount().getIdToken();
                // save idToken inside sharedpreferences
               // other business logic
            }

            @Override
            public void onError(final MsalException exception) {
                // exception handling logic here
            }

            @Override
            public void onCancel() {
                //User cancelled the authentication
            }
        };
    }
```

```
private File createJsonConfigFile() {
        final JSONObject json = new JSONObject();
        // Logic to populate json for config file
        final File file = File.createTempFile("msft", null, null);
        file.deleteOnExit();
        FileUtils.writeStringToFile(file, json.toString(), Charset.defaultCharset());
        return file;
}
```
The contents of the created config file look like:
```
{
  "client_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "msauth://com.my.package.name/keystorehashxxxxxxxxxxxxxxxx",
  "account_mode": "SINGLE",
  "broker_redirect_uri_registered": true,
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount",
        "tenant_id": "common"
      }
    }
  ]
}
```

Code used to get refreshed ID Token:
```
String AUTHORITY = "https://login.microsoftonline.com/common";
String[] SCOPES = {"User.Read"};

IAccount account = mSingleAccountApp.getCurrentAccount().getCurrentAccount();
mSingleAccountApp.acquireTokenSilentAsync(new AcquireTokenSilentParameters.Builder()
        .forAccount(account)
        .withScopes(Arrays.asList(SCOPES))
        .fromAuthority(AUTHORITY).withCallback(new SilentAuthenticationCallback() {
            @Override
            public void onSuccess(IAuthenticationResult authenticationResult) {
              // Old ID Token is returned here intermittently by the API. This behaviour needs to be fixed.
              String newidToken = authenticationResult.getAccount().getIdToken());
              // update idToken value in  sharedpreferences
            }

            @Override
            public void onError(MsalException exception) {
              // error handling
            }
        }).build());
```

Android Project configuration details:
```
minSdkVersion: 21
targetSdkVersion: 33
Gradle Version: 7.4
Gradle Plugin Version: 7.3.0
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8

```
**Expected behavior**
New ID Token should be fetched after expiry. This however does not happen consistently. 

**Actual Behavior**
In my experience there have been cases where ID Token was successfully refreshed 4 times in a row upon expiry - but that was the best this API performed. Many times, the old token is returned by the MSAL API.

**Additional context**

The request for a new token is made only after the existing token is expired (Was able to confirm this by inspecting the token's expiration timestamp).

I noticed that another person was facing a similar issue [Issue 1790](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1790). This issue was also reported in the past few weeks.

I started off by using an older version of the library (1.2.0) and faced the same issue in that case. I proceeded to try versions 2.x.x and 3.x.x but there was no change in the results.

I have followed instructions on [Issue 1699](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1699) and decided to update the library to the latest version but that did not solve the issue as can be seen above.

**Comment by negoe** [comment]
@umangmathur92 Can you please share if you are getting an access token successfully or not? If yes, then please tell me what is your requirement for ID token?

**Comment by umangmathur92** [comment]
Yes. I am getting an access token successfully. It is currently not being used.
I am using the ID Token within the authorization header in all requests made by the mobile app to an HTTP API.

Also, I was able to workaround the inconsistent ID Token Refresh behavior by setting `forceRefresh(true)` while using the `AcquireTokenSilentParameters.Builder()`. I am now able to get refreshed ID tokens consistently. I noticed that a lot of developers using the [MSAL-javascript library](https://github.com/AzureAD/microsoft-authentication-library-for-js) are doing the same: [msal-js Issue 4206](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4206)

**Comment by negoe** [comment]
@umangmathur92 ID tokens should not be used for authorization purposes. [Access tokens](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens) are used for authorization. Please read this [documentation ](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens)on the right set of use of ID token v/s Access token .
