### ISSUE TITLE
We got a 401 code when we applied for an EAS request

### ISSUE THREAD

**Issue by DoctorHe** [AzureAD/microsoft-authentication-library-for-android#1811]
### Discussed in https://github.com/AzureAD/microsoft-authentication-library-for-android/discussions/1810

<div type='discussions-op-text'>

<sup>Originally posted by **DoctorHe** April 28, 2023</sup>
My interest team is having some problems trying to adapt ADAL to MSAL.
I have an Outlook developer account. I made a series of settings according to the development instructions in the related documentation. I successfully obtained the access token and concatenated it into the bearer string. However, we returned code 401 when requesting the Exchange Active Sync service. I'd be grateful if you could answer my question.</div>

**Comment by negoe** [comment]
@DoctorHe Can you please share which documentation you followed and the details on error like logs etc. ?

**Comment by negoe** [comment]
Closing due to no response. Please feel free to reopen it.
