### ISSUE TITLE
Prefetch pages using `mayLaunchUrl()` in custom tab

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-android#1821]
**Is your feature request related to a problem? Please describe.**
The Authentication pages can load faster with a pre-fetch on Android devices

**Describe the solution you'd like**

In Chrome custom tabs, the recommendation is to use `warmup()` and `mayLaunchUrl()` to speed up the browser start-up so that the page loads fast.

Ref: https://developer.chrome.com/docs/android/custom-tabs/guide-warmup-prefetch/

I see that the MSAL library uses `warmup()`. Is there a way to hook `mayLaunchUrl()` as well? i.e., let the client app provide/configures the URL and the custom tab implementation in the MSAL library uses it to pre-fetch the pages.

https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/af128744ec6beaf134ecde0cf619dd0d589382d8/msal/src/main/java/com/microsoft/identity/client/MsalChromeCustomTabManager.java#L184

**Describe alternatives you've considered**
I do not have much experience to propose any alternatives here.

**Comment by negoe** [comment]
@slakshmanan-isn unfortunately we do not support it today. Thanks for your feedback. Currently MSAL Android team is busy with other high priority work.  We will keep an eye on it if we have more customers asking for this enhancement,.

**Comment by ghost** [comment]
@negoe Currently, In our app, We notice a slight delay when the Azure B2C screen loads, a white background, and then the page loads. Since the login screen is one of the first screens the user sees, We'd like to improve their experience by avoiding/removing this white background delay. This issue is more pronounced for customers in a different region, i.e., Australia. We thought if we could `pre-load' the web page using `mayLaunchUrl()` along with 'warmup', We could improve this behavior. 

I'd appreciate it if you could provide any input on anything else that we could do on the app side or even on the server side to avoid this white screen. Maybe on the server side, host the login page in different regions or cache the page in CDN?
