### ISSUE TITLE
Ability to customise webview when using msal for android

### ISSUE THREAD

**Issue by hatched-MaciejPrzybylski** [AzureAD/microsoft-authentication-library-for-android#1823]
**Is your feature request related to a problem? Please describe.**
currently we are using msal in android project, but whenever user needs to login password manager is not showing up and he needs to put credential by hand which leads to frustration

**Describe the solution you'd like**
I would like to have control over webview used by msal so I can customise it in a way that default system password manager could be used

**Comment by negoe** [comment]
Hi @hatched-MaciejPrzybylski thanks for your feedback. We will investigate and get back to you.

**Comment by negoe** [comment]
@negoe We do not provide any customization for MSAL WebView as it is designed for authentication activities only. Can you please provide some details on what scenario you're trying to achieve here?
