### ISSUE TITLE
SDK 33 Android trouble Implementation

### ISSUE THREAD

**Issue by sebaudracco** [AzureAD/microsoft-authentication-library-for-android#1845]
**Describe the bug**
I am having difficulties to implement MSAL with the latest version of android sdk (33), the compilation error tells me that I have to download my sdk to be able to use the library. That's right? Is there a version of MSAL for sdk 33?

**Comment by negoe** [comment]
@sebaudracco Please elaborate what do you mean by "my sdk" here?

**Comment by sebaudracco** [comment]
the development kit used in android. Currently the last and recommended is 33, but MSAL works with 31 or less

**Comment by negoe** [comment]
Let me check and get back to you.

**Comment by negoe** [comment]
@sebaudracco  Can you please share the detailed logs and errors?

**Comment by celabud** [comment]
Maybe it's related to #1882 
¿any news on version release?

**Comment by negoe** [comment]
@celabud Try with the [latest version](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases) of MSAL i.e. 4.9.0, our team has [fixed](https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1882) this. Please let me know if that solved your problem.
