### ISSUE TITLE
receive v1 id_token 

### ISSUE THREAD

**Issue by whiterabbitj** [AzureAD/microsoft-authentication-library-for-android#1849]
I am managing to receive the v2 id_token using the library. 

Having some issues receiving a v1 id_token? As in changing the request URL like this would result in different versions of the id_token :

**https://login.microsoftonline.com/{{TenantId}}/oauth2/v2.0/token** - v2 id_token 
**https://login.microsoftonline.com/{{TenantId}}/oauth2/token** - v1 id_token 

Is there any way to achieve this using this library?

**Comment by negoe** [comment]
@whiterabbitj Can you please elaborate your scenario, so that I can help you better? Why do you need v1 token? MSAL supports v2 token which supports work/school and personal accounts both.

**Comment by negoe** [comment]
@whiterabbitj Closing due to no response. Please feel free to reopen if you have any follow up.
