### ISSUE TITLE
Sign out does not clear SSO token 

### ISSUE THREAD

**Issue by onovotny** [AzureAD/microsoft-authentication-library-for-android#185]
Looking at the code, I don't see Sign Out being properly implemented. There is a way to remove the user tokens from the local cache, but it does not appear to invoke the system web view to hit the `end_session_endpoint` endpoint value. That may leave the cookie between the system and the device valid such that a subsequent authenticate call may not prompt for credentials.
Seems like the `end_session_endpoint` value should be read from the OIDC metadata and then invoked on a sign out?

**Comment by weijjia** [comment]
@onovotny For the preview, we only support signout by removing tokens from the cache. Sigout from system webview will be the next step, we'll add the support later.

**Comment by weijjia** [comment]
Closed the issue for now.

**Comment by onovotny** [comment]
@weijjia Can this issue stay open for tracking until it's implemented?

**Comment by mgursch** [comment]
we have problems with the cookies - we do a logout (removeAccount) but with the next login, we are signed in automatically.

what can we do to clear really everything from the session? (android and ios)

thanks a lot

**Comment by iambmelt** [comment]
@mgursch If you look at the `.well-known` config of your configured app there should be property called `end_session_endpoint`, if your `authorization_agent` is set to `DEFAULT` or `BROWSER` opening this URL will clear the session for any signed-in users.

For an example of this document see this [Fabrikam tenant example](https://login.microsoftonline.com/fabrikamb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=b2c_1_sign_in)

**Comment by iambmelt** [comment]
I'll also add, we're looking into how this experience can improve with MSAL in a future release.

**Comment by emmano** [comment]
In the meantime I am using the following code to remove all user data and prevent automatic login after sign out. I am using `"authorization_user_agent": "WEBVIEW"`.

` (requireContext().getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager).clearApplicationUserData()`
