### ISSUE TITLE
MSALException meaning and how to prevent this from occurring in the app 

### ISSUE THREAD

**Issue by ekahannah** [AzureAD/microsoft-authentication-library-for-android#1869]
**Describe the bug**
App is in Production

 - MSAL Version 4.2.0

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

Users on the app are randomly getting these errors after logging in and going back to the app after some time:
1. no_current_account There is no signed in account.
2. invalid_grant AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is need
3. invalid_grant AADSTS50078: Presented multi-factor authentication has expired due to policies configured 

**Additional context**
 I just  want to know why these errors are being shown regarding MSALAuthentication and what can we do in the app side in order to avoid those errors. Thanks!

**Comment by negoe** [comment]
@ekahannah Please follow this [documentation ](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-handling-exceptions)for how you can handle these errors.
