### ISSUE TITLE
IntuneAppProtectionPolicyRequiredException can returns empty accountUserId 

### ISSUE THREAD

**Issue by sun950605** [AzureAD/microsoft-authentication-library-for-android#1874]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

**Smartphone (please complete the following information):**
 - Device: Android
 - Android Version: 12
 - Browser MSAL SDK browser
 - MSAL Version: 4.6.3

**Stacktrace**
onAuthError: IntuneAppProtectionPolicyRequiredException(accountUpn=IsaiahL@intune3.kapilpant.com, accountUserId=, tenantId=organizations, authorityUrl=https://login.microsoftonline.com/organizations, errorCode=unauthorized_client)

this is the Response from from login to azure, and we get IntuneAppProtectionPolicyRequiredException error 

Then we need to remediate with conditional access, using the information in the IntuneAppProtectionPolicyRequiredException error

but sometime the acountUserId could be empty so we can't finish the remediation with CA

**To Reproduce**
Log in in to a account with CA remediation required, not always reproducible

**Expected behavior**
accountUserId should not be empty

**Actual Behavior**
accountUserId is empty

**Comment by negoe** [comment]
@sun950605 This can happen if the local or home account id info is not available as part of the token parameters passed to the token request. Can you please validate the request you are creating?
