### ISSUE TITLE
SSO login not working using MSAL Library for android 

### ISSUE THREAD

**Issue by chanakyaraichur** [AzureAD/microsoft-authentication-library-for-android#1875]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

It is live & we have rechecked issue using latest  MSAL test app as well still issue is there. 
https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/dev/testapps/testapp
Post login into Sample MSAL application will try to check the login status in Office or Teams application , it doesn't auto login into the app. 

**Smartphone (please complete the following information):**
 - Device: Pixel 6a 
 - Android Version: Android 13
 - MSAL Version:4.6.3
 - It happens in all the devices.

**Stacktrace**
No crash in application

**To Reproduce**
Login into MSAL test application on android device using one of office account . 
Post login when we check the login status Teams or Office apps  it is not auto logged in . 

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

Here is the auth_config_single account json - 
{
  "client_id" : "******",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://com.azuresamples.msalandroidapp/*****",
  "account_mode" : "SINGLE",
  "shared_device_mode_supported": true,
  "broker_redirect_uri_registered": true,
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount",
        "tenant_id": "common"
      }
    }
  ]
}

**Expected behavior**
Post login to MSAL app sso should work across all the microsoft apps like teams , office. 

**Actual Behavior**
Post login to MSAL app sso not working with  all the microsoft apps like teams , office

**Comment by negoe** [comment]
@chanakyaraichur What account are you using to login, AAD or MSA? You can follow this documentation to [Enable cross-app SSO on Android using MSAL](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on).

**Comment by negoe** [comment]
Please feel free to reopen if you have follow up questions.

**Comment by chanakyaraichur** [comment]
What account are you using to login, AAD or MSA? - We are using AAD account for login .
We are following the same steps, still we couldn’t make it work  - https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on
we have also rechecked the steps followed in this video as well - https://www.youtube.com/watch?v=x1_snVp0rIw 
Can you help us way to identify the issue ?
