### ISSUE TITLE
Take long time under speical WIFI

### ISSUE THREAD

**Issue by Joemiao120** [AzureAD/microsoft-authentication-library-for-android#1881]
**Describe the bug**
The app is in Production. the issue is one of our users using the Slingshot WIFI, but it takes like more than 10 mins for calling the `getAccount` methods, and also happen when the user clicks the `Login` button, need to wait for a few mins to get the response.

**Smartphone (please complete the following information):**

- Device: All Android devices under this WIFI
- Android Version: 13
- Browser: Insider Webview
- MSAL Version: 4.6.3

**Additional context**
Here are some WIFI information I got from the bug report:

> SignalState[spec=Wifi,icon=ResourceIcon[resId=0x7f080a81],iconSupplier=null,label=Your New Wi-Fi,secondaryLabel=null,contentDescription=Wi-Fi,On,Your New Wi-Fi,stateDescription=null,dualLabelContentDescription=null,expandedAccessibilityClassName=null,disabledByPolicy=false,dualTarget=true,isTransient=false,state=2,slash="null",sideViewCustomDrawable=null,tileClassName=null,value=true,forceExpandIcon=false,activityIn=false,activityOut=true]
> Previous WiFiNetwork(32): 07-28 16:02:15.272,onCapabilitiesChanged: network=113,networkCapabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=30000Kbps TransportInfo: <SSID: "Your New Wi-Fi", BSSID: 18:f1:45:7a:58:92, MAC: 02:00:00:00:00:00, IP: /192.168.1.21, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 4, RSSI: -63, Link speed: 78Mbps, Tx Link speed: 78Mbps, Max Supported Tx Link speed: 300Mbps, Rx Link speed: 104Mbps, Max Supported Rx Link speed: 300Mbps, Frequency: 2437MHz, Net ID: 4, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none>"Your New Wi-Fi"wpa2-pskMLO Information: , AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>> SignalStrength: -63 SSID: "Your New Wi-Fi" UnderlyingNetworks: Null]

**Comment by negoe** [comment]
@Joemiao120 Please answer these questions to provide more context. 

- Is the delay only happening in these two scenarios or there are delayed responses in case of accessing other features or resources from your App? 
- Is your App performing this way for all the users using Slingshot wifi or it is happening for a particular user only  who is using Slingshot?

**Comment by Joemiao120** [comment]
Hi @negoe thanks for your response,
1. The delay only happens in these two scenarios, and it works fine for our other API calls.
2. it happens for all Android devices that use Slingshot, and it works fine on iOS devices even using the same WIFI.

**Comment by negoe** [comment]
@Joemiao120 Thanks for the response, we appreciate your patience.  Based on your update, it appears that the performance issue is isolated to the Slingshot WIFI network, and users do not encounter delays on different networks. 

In the meantime, here are a few additional steps you can take to help us further diagnose the issue:

- Detailed Logs: If possible, could you provide us with more detailed logs from the application when the delay occurs?
- Network Configuration: Are there any specific network configurations or security settings on the Slingshot WIFI network that's different from the other networks that might be causing the delay? 
- Update MSAL: While we investigate the issue, you can try updating to the latest version of MSAL and test if the issue still persists. 

Thanks,
Neha
