### ISSUE TITLE
Unable to handle click(through href) in MSAL Android WebView 

### ISSUE THREAD

**Issue by pom1004** [AzureAD/microsoft-authentication-library-for-android#1884]
We are tring to click a hyperlink in Android MSAL Webview. But we are not able to see any intent is coming. How to get intent by clicking on a hyperlink?

We are running Android MSAL v4.6.3

The ablve issue is similler to https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/930 this issue. But I can see there is no futher response to this issue.

Wanted to know how other apps are apps a re dealing with this issue who are using MSAL Android library.

<img width="1075" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/8271730/ac6e707e-24a9-4555-93ee-0f1cdfef84ef">

**Comment by negoe** [comment]
hi @pom1004, This is not supported as of today and is new feature request. We will keep it on our radar.
