### ISSUE TITLE
Huawei Browser not part of the default browser safe list

### ISSUE THREAD

**Issue by Eselfar** [AzureAD/microsoft-authentication-library-for-android#1890]
**Describe the bug**
`BrowserSelector.select(...)` method returns `"No available browser installed on the device."` for the Huawei Browser (package: `com.huawei.browser`)

**Smartphone (please complete the following information):**
 - Device: Huawei P50 Pro
 - Android Version: EMUI 12.0.1
 - Browser Huawei Browser
 - MSAL Version 4.7.0

**Stacktrace**
"No available browser installed on the device.""

**To Reproduce**
- Take a Huawei phone
- Set the Huawei Browser as default browser
- Set `auth_config.json` with `"authorization_user_agent": "BROWSER"`
- Open a B2C policy

**Expected behavior**
The policy is opened in the browser. No error is shown in the log.

**Actual Behavior**
The B2C screen opens in a webview instead of the browser. The mentioned error is shown in the log. For B2C policies using log in with a Google account, it results in the Google page to display the below error:

<img width="259" alt="image-20230731-153405" src="https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/4113411/41a4ae97-6281-42b1-9366-081ac6a61289">

**Additional context**
Adding the Huawei Browser to the `browser_safelist` int the `auth_config.json` fixes the issue.

In the [documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#sso-through-system-browser) the Huawei Browser (package `com.huawei.browser`) is marked as _Passed Tested Browser_.
However, it is not included in the default browser safelist, resulting in the `BrowserSelector.select(...)` method to return `"No available browser installed on the device."`

![Screenshot 2023-08-25 at 10 30 15](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/4113411/bdebd047-93ef-4615-b1ec-7d96ec361105)

**Comment by negoe** [comment]
@Eselfar Thanks for sharing this issue. I will test it on my end will get back to you.
