### ISSUE TITLE
MSAL support for authorization code , analgous to response_type = code 

### ISSUE THREAD

**Issue by GauravGupta17** [AzureAD/microsoft-authentication-library-for-android#1891]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GauravGupta17** [comment]
Hi , 
i was able to id_token in MSAL sdk in android , but how to get 
code token in android or in ios both 
which is same as response_type = code ?

**Comment by negoe** [comment]
@GauravGupta17 Please find the documentation [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-mobile-app-android-sign-in)

**Comment by GauravGupta17** [comment]
Hi @negoe  thanks for reply but thats not the solution to my problem please read my question properly
