### ISSUE TITLE
MSAL and launching a URL with SSO

### ISSUE THREAD

**Issue by opt05** [AzureAD/microsoft-authentication-library-for-android#1893]
**Is your feature request related to a problem? Please describe.**
My company has implemented MSAL with Azure B2C successfully with a login and all is working as expected. We have a situation where we are trying to launch a URL that also has a login with the same Azure B2C. Depending on the user's device/browser choice and how [MSAL determines its brower](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#browser-selection-heuristic) to store its token, having passthrough SSO is hit or miss. For example, if a user doesn't have Chrome Stable installed but Chrome Beta, MSAL is currently using a WebView instead of using Chrome Custom Tabs, even though it is available.

**Describe the solution you'd like**
1. Have the ability to launch a url through MSAL that would therefore use its browser heuristics to have successful SSO passthrough
2. An ability to query MSAL for where it stored the token (Chrome Custom Tabs, Browser or WebView) so the app can launch a url the same way and have successful SSO passthrough

**Describe alternatives you've considered**
Currently, our app implements its own Custom Chrome Tabs and doesn't have its own browser safe list so therefore depending on the user's device, SSO passthrough sometimes works and other times it does not

**Additional context**
Let me know if there is any further context is needed, thank you!

**Comment by negoe** [comment]
@opt05 Unfortunately, we don't have a  functionality where a you can configure a custom browser. We will keep the feature on our radar, and if other customers express a need for this feature, we will try to prioritize it.
