### ISSUE TITLE
How to config proxy in MSAL

### ISSUE THREAD

**Issue by Philntps** [AzureAD/microsoft-authentication-library-for-android#1901]
Due to security restrictions, we need to connect through a proxy to access the internet. However, we've found that we can successfully connect to the proxy at the application level, but we're having trouble doing so within the BrowserTabActivity. What should we do?

**Comment by negoe** [comment]
@Philntps Can you please provide more details about the issues like errors or stack trace? Also can you please share the MSAL version, device details and repro steps if possible?
