### ISSUE TITLE
SSO login not working using MSAL Library for android 

### ISSUE THREAD

**Issue by chanakyaraichur** [AzureAD/microsoft-authentication-library-for-android#1906]
**Describe the bug**
Is your app live and in production or is this a development issue? Provide a clear and concise description of what the bug is.

It is live & we have rechecked issue using latest MSAL test app as well still issue is there.
https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/dev/testapps/testapp
Post login into Sample MSAL application will try to check the login status in Office or Teams application , it doesn't auto login into the app.

**Smartphone (please complete the following information):**

Device: Pixel 6a
Android Version: Android 13
MSAL Version:4.6.3
It happens in all the devices.
**Stacktrace**
No crash in application

**To Reproduce**
Login into MSAL test application on android device using one of office account .
Post login when we check the login status Teams or Office apps it is not auto logged in .

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

Here is the auth_config_single account json -
{
"client_id" : "*",
"authorization_user_agent" : "DEFAULT",
"redirect_uri" : "msauth://com.azuresamples.msalandroidapp/",
"account_mode" : "SINGLE",
"shared_device_mode_supported": true,
"broker_redirect_uri_registered": true,
"authorities" : [
{
"type": "AAD",
"audience": {
"type": "AzureADandPersonalMicrosoftAccount",
"tenant_id": "common"
}
}
]
}

**Expected behavior**
Post login to MSAL app sso should work across all the microsoft apps like teams , office.

**Actual Behavior**
Post login to MSAL app sso not working with all the microsoft apps like teams , office

As per the early discussion in previous ticket this info was requested -  https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1875
What account are you using to login, AAD or MSA? - We are using AAD account for login .
We are following the same steps, still we couldn’t make it work - https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on
we have also rechecked the steps followed in this video as well - https://www.youtube.com/watch?v=x1_snVp0rIw
Can you help us way to identify the issue ?

**Comment by negoe** [comment]
@chanakyaraichur Do you have broker app installed?

**Comment by chanakyaraichur** [comment]
Yes we have tried with broker app .
broker app will be Microsoft Authenticator or something else - https://play.google.com/store/apps/details?id=com.azure.authenticator ?

**Comment by negoe** [comment]
@chanakyaraichur You must register a redirect URI that is compatible with the broker. The redirect URI for the broker should include your app's package name and the Base64-encoded representation of your app's signature.

The format of the redirect URI is: "msauth://yourpackagename/base64urlencodedsignature"

here is the [doc ](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#integrating-with-a-broker)and [video ](https://youtu.be/x1_snVp0rIw?si=3fOLene4BzOVcdCP)for more details.

**Comment by Colaman0** [comment]
I got the same problem, i think this issue need to reopen. 

The reporter use the Microsoft Authenticator to login , it should be work , he doesn't use his application to login.

**Comment by vermala04** [comment]
Hi All,

I was stuck exactly on the point, and what I have discovered is  Base64-encoded representation of your app's signature is changed, I used logcat to log the init error and got this error :
**Initialization error: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.We expected 'msauth://au.com.test.dev.app/Regenratedkeyhash' (I am not sure how this is created) and we received 'msauth://au.com.test.dev.app/Actualkeyhash'**

I have change regenrated key hash in my android manifest and on AAD and it's working for me. 
Not a solution but this for now this is working for me

I fi
