### ISSUE TITLE
Turn caching on TravisCI

### ISSUE THREAD

**Issue by jaredsburrows** [AzureAD/microsoft-authentication-library-for-android#192]
This way you do not download the dependencies each time.

Example: https://github.com/jaredsburrows/android-gif-example/blob/master/.travis.yml#L31

```
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
```

**Source:** https://docs.travis-ci.com/user/languages/android/#Caching

**Comment by weijjia** [comment]
@jaredsburrows This is what we should update. Thanks for filing the issue.

**Comment by jaredsburrows** [comment]
I can make a quick PR for this! When can we merge my other PRs?

**Comment by weijjia** [comment]
we'll take care of this one. What's your other PRs?

**Comment by jaredsburrows** [comment]
For the older library:
https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/841
and
https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/842

**Comment by weijjia** [comment]
This is msal repo. please comment on issues to its related repo.

**Comment by jaredsburrows** [comment]
@weijjia I already did. I duplicated this issue for both repos as both repos need this.

**Comment by weijjia** [comment]
We'll get back to you on that PR then. If there is delay, i'm sorry. But if you want to follow up on a PR or issue, you should do in that particular repo.

**Comment by jaredsburrows** [comment]
I have.

**Comment by weijjia** [comment]
@jaredsburrows Actually this won't help improve the build process time. Travis doc explicitly says that large files i.e. AndroidSDK should not be cached. as they take as long to download from the cache as from the original source. Downloading android sdk and build tools are taking the majority time of the current travis build.

**Comment by jaredsburrows** [comment]
@weijjia This caches the downloaded jars **not** the android sdk.

As for the documentation, the example **code was taken directly** from the TravisCI docs:
```
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
```
**Source:** https://docs.travis-ci.com/user/languages/android/#Caching

**Comment by weijjia** [comment]
yup, i agree. What i'm saying is that it will not improve a lot cause we'are not taking many external dependencies.

**Comment by jaredsburrows** [comment]
@weijjia It will help prevent downloading these each time: https://travis-ci.org/AzureAD/microsoft-authentication-library-for-android/builds/238053176#L1826.

**Comment by iambmelt** [comment]
See #197

**Comment by weijjia** [comment]
Close iwth PR #197

**Comment by jaredsburrows** [comment]
Great work!
