### ISSUE TITLE
Unit Test failed when the emulator not connected to network | CI Connected Unit Tests

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#193]
MSAL Android CI got failed on tests with mocked HTTP connections when running the emulator without network. This is not expected as unit tests, there probably is a bug on the mocked URL connections code.

```
05-26 14:13:16.633 1634-1659/? E/BaseRequest: MSAL 0.1.1 Android 23 [2017-05-26 21:13:16 - 351b338b-3f8a-437e-8e52-fe78148f27e3] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Device network connection is not available.
                                                  at com.microsoft.identity.client.BaseRequest.throwIfNetworkNotAvailable(BaseRequest.java:219)
                                                  at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:166)
                                                  at com.microsoft.identity.client.SilentRequest.performTokenRequest(SilentRequest.java:103)
                                                  at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:107)
                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                  at java.lang.Thread.run(Thread.java:818)
05-26 14:13:16.633 1634-1634/? W/System.err: com.microsoft.identity.client.MsalClientException: Device network connection is not available.
05-26 14:13:16.633 1634-1634/? W/System.err:     at com.microsoft.identity.client.BaseRequest.throwIfNetworkNotAvailable(BaseRequest.java:219)
05-26 14:13:16.633 1634-1634/? W/System.err:     at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:166)
05-26 14:13:16.633 1634-1634/? W/System.err:     at com.microsoft.identity.client.SilentRequest.performTokenRequest(SilentRequest.java:103)
05-26 14:13:16.633 1634-1634/? W/System.err:     at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:107)
05-26 14:13:16.633 1634-1634/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-26 14:13:16.633 1634-1634/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-26 14:13:16.633 1634-1634/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by iambmelt** [comment]
Investigation into this issue yields two things of interest:

- Hyper-V Manager seems to disallow connections to an external network (WiFi/wired) by default -- we could consider changing this.
- `BaseRequest#throwIfNetworkNotAvailable` doesn't seem to be picking up mocked connectivity: I attempted to use the following code to mock this:

```java
// Mock the network connectivity check...
        final Context context = Mockito.mock(Context.class);
        final ConnectivityManager connectivityManager = Mockito.mock(ConnectivityManager.class);
        final NetworkInfo networkInfo = Mockito.mock(NetworkInfo.class);

        Mockito.when(context.getSystemService(Context.CONNECTIVITY_SERVICE)).thenReturn(connectivityManager);
        Mockito.when(connectivityManager.getActiveNetworkInfo()).thenReturn(networkInfo);
        Mockito.when(networkInfo.isConnected()).thenReturn(true);
```

**Comment by iambmelt** [comment]
Update on the status here:

Tried using `Mockito#spy()` to mock `mAppContext`'s method for `getSystemService(String)` -- no change to test result.

Investigated creating a new Virtual Switch in Hyper-V manager for the machine: yields warning that the host system may lose network connectivity if settings are changed: I did not apply settings in the event that it takes the build machine offline

**Comment by heidijinxujia** [comment]
Thank you for the update. :) I  also tried to debug last Friday. Agree, the BaseRequest#throwIfNetworkNotAvailable did not pick up the mock connection for some reason. My concern is, for unit tests, it could be better to make the mocked network connection work instead of connecting the VM with WiFi. How do you think? @iambmelt

**Comment by heidijinxujia** [comment]
Hi @iambmelt, update. I've fixed the emulator network issue in Hyper-V. The unit tests get passed now. 
 Thanks for the help of @addev-ashish on Hyper-V knowledge. :)
Our next task, as discussed with @addev-ashish , is to remove the dependencies of the unit tests on the emulator network connection.

**Comment by iambmelt** [comment]
@heidijinxujia Alright! I'm glad to hear that you were able to get the test to pass! I absolutely agree with the above sentiment: good that Hyper-V could be configured to make this work, but a superior solution would be functional mocks of the HTTP stack / `ConnectivityManager`

**Comment by weijjia** [comment]
We should be mocking the network connection instead of using the wifi network. No unit test should be running under wifi. I'll take a look at this and update the unit tests that doesn't have mocked connection.

**Comment by weijjia** [comment]
@heidijinxujia If you get the unit test passed in CI, can you close the issue and we'll open another one to track unit tests update. Thanks.
