### ISSUE TITLE
Configure Travis CI to run emulator tests

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#194]
Builds should initialize an emulator and run `connectedAndroidTest `

**Comment by iambmelt** [comment]
See #184 for prior work done by @weijjia

**Comment by weijjia** [comment]
Per discussion in standup, we're going to use vsts.

**Comment by iambmelt** [comment]
See #197

**Comment by weijjia** [comment]
Closed with PR #197
