### ISSUE TITLE
Invalid audience in Graph (App kotlin+Jetpack compose+Retrofit)

### ISSUE THREAD

**Issue by raszagar** [AzureAD/microsoft-authentication-library-for-android#1956]
Hi!

I am try get token need for graph:  
<https://graph.microsoft.com/v1.0/me> 
In Andoid app with kotlin, Jetpack compose and Retrofit, in my repository:  
<https://github.com/raszagar/DemoOauth2Android>

In microsoft Entra ID create one application of plataform "Mobile and desktop applications" and 
redirect_uri: "joseapp://com.mkiperszmid.emptyapp"
(single tenant)

This application have permision for "User.read"

Use library 4.9.2 (build.gradle)
```
implementation('com.microsoft.identity.client:msal:4.9.2') {
        exclude group: 'com.microsoft.device.display'
    }
```

In (MSALAuth.kt) setter scope for login in constant TOKEN_SCOPE, I had try multiple scopes:
```
const val TOKEN_SCOPE = "https://graph.microsoft.com/.default"
const val TOKEN_SCOPE = "User.Read"
const val TOKEN_SCOPE = "https://graph.microsoft.com/User.Read"
const val TOKEN_SCOPE = "openid profile User.Read email"
```
But allways get Error:
"Access token validation failure. Invalid audience."
(GET https://graph.microsoft.com/v1.0/me, with Bearer Token auth)

When I log in it never asks to grant permissions to read profile.

Token from login without "scp" and "aud" no graph (**** write for me):
```
{
  "aud": "f92863b8-16ec-45b6-851f-********",
  "iss": "https://login.microsoftonline.com/bdf029de-3bb7-4f38-b6c4-*******/v2.0",
  "iat": 1700232208,
  "nbf": 1700232208,
  "exp": 1700236108,
  "name": "raszagar",
  "oid": "4587a513-1fbd-472a-924e-***********",
  "preferred_username": "raszagar@raszagaroutlook.onmicrosoft.com",
  "rh": "0.Aa8A3inwvbc7OE-...",
  "sub": "dEgYbB-_0-KoM97ESkECfEbnTEu2wdFQ...",
  "tid": "bdf029de-3bb7-4f38-b6c4-*********",
  "uti": "kMn3I4PyZUez_*****",
  "ver": "2.0"
}
```
 
Thanks!
(Sorry for my english)

**Comment by raszagar** [comment]
Hi!

After very investigation (and test and error) my example work fine.

First token return by Msal library android in signIn is a token v2.0 and it can't be used in graph API, but token return in acquireTokenSilent method is v1.0 and this token work in Graph Api.

I'm use:  
const val TOKEN_SCOPE = "https://graph.microsoft.com/.default"

You can close this issue.
Thanks!

**Comment by negoe** [comment]
Thanks for the update.
