### ISSUE TITLE
com.microsoft.identity.common.internal.controllers.LocalMSALController.onFinishAuthorizationSession

### ISSUE THREAD

**Issue by HappyWizard25** [AzureAD/microsoft-authentication-library-for-android#1958]
**Describe the bug**
 java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.identity.common.java.providers.oauth2.IAuthorizationStrategy.completeAuthorization(int, com.microsoft.identity.common.java.providers.RawAuthorizationResult)' on a null object reference
 

**Smartphone (please complete the following information):**
 - Device: Galaxy Z Fold5
 - Android Version: 13
 - MSAL Version: 4.05

**Stacktrace**
MSALLogger: LocalMSALController:MicrosoftStsAuthorizationResult | [2023-11-09 13:17:01 - thread_name: pool-17-thread-1, Android 30] Failure Result.
W LocalMSALController:MicrosoftStsAuthorizationResult: [2023-11-09 13:17:01 - thread_name: pool-17-thread-1, Android 30] Failure Result.
W MSALLogger: LocalMSALController:MicrosoftStsAuthorizationResult | [2023-11-09 13:17:01 - thread_name: pool-17-thread-1,  Android 30] Error: auth_cancelled_by_sdk.
W LocalMSALController:MicrosoftStsAuthorizationResult: [2023-11-09 13:17:01 - thread_name: pool-17-thread-1, Android 30] Error: auth_cancelled_by_sdk.

**Comment by negoe** [comment]
Hi @HappyWizard25 , Can you please update the app with [latest version ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases) can check if this addresses issue for you?

**Comment by HappyWizard25** [comment]
Hi @negoe 

We observed this issue for a few users in the production. We're going to update the library to the latest version, but it more or less will happen in the 2024 Q1 release and then we'll able to see whether the issue was fixed or not.

**Comment by negoe** [comment]
I am closing this thread. Please feel free to reopen if you experience this issue again once you update the library.
