### ISSUE TITLE
Create "no-args" constructor for GSON POJOs to prevent using "sun.misc.Unsafe"

### ISSUE THREAD

**Issue by jaredsburrows** [AzureAD/microsoft-authentication-library-for-android#199]
Please read this post: https://stackoverflow.com/a/18645370/950427.

If you are not using a "no-args" constructor in Gson, it will use: `sun.misc.Unsafe`. See https://github.com/google/gson/blob/master/UserGuide.md#writing-an-instance-creator

Also, users will no longer have to keep "unsafe" for proguard: https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg#L10

Same idea from https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/839

**Comment by iambmelt** [comment]
Thanks @jaredsburrows for the level of detail in this issue. I'll be reviewing #200 now

**Comment by jaredsburrows** [comment]
@iambmelt Thank you!
