### ISSUE TITLE
Please provide sample code for forgot password.

### ISSUE THREAD

**Issue by prashantgunit** [AzureAD/microsoft-authentication-library-for-android#2006]
Need sample code and steps for forgot password flow for native android app.
 After getting the Msal password exception. How to invoke forgot password page.

**Comment by negoe** [comment]
Hi @prashantgunit, MSAL already supports forgot password when a user tries to add an account and password during the sign-in flow. You do not need to explicitly create forgot password flow. 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/38259657/bee228ba-626c-4d48-8d38-45817efec99c) ![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/38259657/4361e935-2e48-4002-a4f5-afed55d404b6)
