### ISSUE TITLE
MSAL for KMM projects

### ISSUE THREAD

**Issue by emanuelecastelli** [AzureAD/microsoft-authentication-library-for-android#2018]
I'm trying to use the library inside a KMM project with Jet Compose multiplatform.
Gradle is able to install the library correctly, but then i'm unable to import `com.microsoft.identity.client.IAccount`.
I think this is because there is a lot of java code and KMM requires libraries to be written in Kotlin.

Can you confirm that this is not possible?
Or am I doing something wrong?

Here the `build.gradle.kt` relevant part:
```
sourceSets {
       //....

       commonMain.dependencies {
           //.....

            //==================== MSAL ====================
            implementation("com.microsoft.identity.client:msal:4.10.0") {
                exclude(group = "io.opentelemetry")
                exclude(group = "com.microsoft.device.display")
            }
            implementation(libs.opentelemetry.api)
            implementation(libs.opentelemetry.context)
```

Thank you

**Comment by negoe** [comment]
@emanuelecastelli This is supported. We are in process of updating our Kotlin Sample. You can follow the sample, I will share the link here once updated by end of this week.
