### ISSUE TITLE
Expose Refresh Token for Backward Compatibility

### ISSUE THREAD

**Issue by shuurai** [AzureAD/microsoft-authentication-library-for-android#202]
Some existing systems require refresh token, and integration with other means of auth. However, MSAL seems to hide this layer.

**Comment by danieldobalian** [comment]
@shuurai Can you expand on the scenario you're trying to build that requires a refresh token to be exposed?

**Comment by shuurai** [comment]
Hi, at work here, the auth system (connected through salesforce) right now uses the refresh token to revoke existing refresh tokens + access tokens on a user, this is one use case. Another case I recall is that the refresh token is used by another service that is tied in. We are at the stage of deprecating the need of touching the refresh token, by changing/upgrading our system, but in the mean time, we kind of needed the refresh tokens to be backward compatible.

**Comment by fistuk** [comment]
Hi, the straightforward use case is enabling server-side access, a client connects to one drive and its desired to grant the server the same access so it can act on the user behalf. There is a similar functionality available for google drive:
https://developers.google.com/identity/sign-in/android/offline-access

**Comment by danieldobalian** [comment]
@fistuk we're evaluating this request right now, but wanted to note that Azure AD / Microsoft Accounts recommends a different pattern for getting service side refresh tokens called the [On Behalf Of](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-on-behalf-of) flow.  

In this case, the Android app requests an AT/RT pair, then sends it's AT in a normal bearer request to the service The service can then, in turn, use the AT to request a new AT/RT pair for a downstream resource.

**Comment by rekhaagarwal** [comment]
@danieldobalian any update on above request to get refresh token as well in the auth result?

**Comment by mgursch** [comment]
would also need the refresh token to be exposed - something new here?

**Comment by mgursch** [comment]
would also need the refresh token to be exposed - something new here?

**Comment by iambmelt** [comment]
There are currently no plans to expose the refresh token from MSAL as it would too easily enable developers to implement scenarios that run contrary to our recommended security guidance; for instance, it is _not_ advised for developers to transmit access tokens or refresh tokens off of the device for use _elsewhere_ (that is, except by the intended resource server) -- the refresh token is intended to remain on the device to which it was transmitted. In part, this is so [Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview) policies can be enforced but it is also to protect credentials from being compromised by man-in-middle or other kinds of interception attacks. Transmitting Refresh Tokens off of the device, aside from the security concerns, also creates some usability issues (particularly around MFA) that I won't go into here.

As @danieldobalian calls out above, for scenarios requiring authentication and access by a service the recommended pattern is to use the [On Behalf Of (OBO)](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-on-behalf-of-flow) flow.

If you're using MSAL and need the refresh token, chances are there is alternative flow which suits your needs and doesn't require circumventing the app model's security guidance. For help on those scenarios you can post here, though StackOverflow is preferred: tag your question with `[msal]` and `[azure-active-directory]`

**Comment by mgursch** [comment]
I would like to explain our scenario:

we build an android/ios app with b2c connector login. this is working ok (we have some issues with cookie management, but that is another topic).
Now we want to build a second app with the same login credentials and would love to be signed in, if the user is signed in in the first app.

so we just want to share the login state (and account) between two or more own apps.

Is there any other possibility to share this on ios and android?

**Comment by iambmelt** [comment]
@mgursch This should be supported if you use MSAL w/ `DEFAULT` or `BROWSER` as the authorization agent.

This kind of SSO requires some tweaks in the portal: `Properties` > `Session Behavior` > `Single sign-on configuration`. By default, the config should be set to tenant which means any app or policy in the same tenant should auto-SSO. You can also set scopes by specific applications or policies.

Take a look and let me know what you see - hopefully this unjams your scenario.
