### ISSUE TITLE
Gradle Task 'jacocoTestReport' is always SKIPPED

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#206]
Executing:
`$ ./gradlew jacocoTestReport`

yields:

```sh
Incremental java compilation is an incubating feature.
:msal:preBuild UP-TO-DATE
:msal:preDebugBuild UP-TO-DATE
:msal:checkDebugManifest
:msal:preDebugAndroidTestBuild UP-TO-DATE
:msal:preDebugUnitTestBuild UP-TO-DATE
:msal:preReleaseBuild UP-TO-DATE
:msal:preReleaseUnitTestBuild UP-TO-DATE
:msal:prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
:msal:prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
:msal:prepareComAndroidSupportCustomtabs2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportV42531Library UP-TO-DATE
:msal:prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
:msal:prepareDebugDependencies
:msal:compileDebugAidl UP-TO-DATE
:msal:compileDebugRenderscript UP-TO-DATE
:msal:generateDebugBuildConfig UP-TO-DATE
:msal:generateDebugResValues UP-TO-DATE
:msal:generateDebugResources UP-TO-DATE
:msal:mergeDebugResources UP-TO-DATE
:msal:processDebugManifest UP-TO-DATE
:msal:processDebugResources UP-TO-DATE
:msal:generateDebugSources UP-TO-DATE
:msal:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:msal:compileDebugJavaWithJavac UP-TO-DATE
:msal:incrementalDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:msal:prepareDebugUnitTestDependencies
:msal:compileDebugUnitTestJavaWithJavac UP-TO-DATE
:msal:processDebugJavaRes UP-TO-DATE
:msal:processDebugUnitTestJavaRes UP-TO-DATE
:msal:compileDebugUnitTestSources UP-TO-DATE
:msal:mockableAndroidJar UP-TO-DATE
:msal:assembleDebugUnitTest UP-TO-DATE
:msal:testDebugUnitTest UP-TO-DATE
:msal:jacocoTestReport SKIPPED

BUILD SUCCESSFUL

Total time: 10.999 secs
```

Presently, the only way to generate a coverage report is to run:
`$ ./gradlew createDebugCoverageReport`

**Comment by iambmelt** [comment]
Resolved by #207

**Comment by YashNagayach95** [comment]
For me also, it is skipping. Any idea?


> Task :demo:compileProdPerfInstrumentationUnitTestJavaWithJavac NO-SOURCE
> Task :demo:testProdPerfInstrumentationUnitTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/home/runner/.gradle/caches/transforms-3/4bab49e38167b37dc6d512f0b3f95435/transformed/jetified-retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`> Task :demo:testProdPerfInstrumentationUnitTestCoverage SKIPPED`
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 14m 9s
139 actionable tasks: 113 executed, 26 from cache

**Comment by CristhianUNI** [comment]
@YashNagayach95 could you solve?

In my case I have Jacoco 0.8.8 and the Skipped message was because it couldn't find the .exec file that was generated in the root directory in previous versions.

In version 0.8.8 I have these parameters configured in the build.gradle, maybe it will work for you:

```
def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', 'android/**/*.*']
def debugTree = fileTree(dir: "$project.buildDir/intermediates/javac/debug/classes/ni", excludes: fileFilter)
def mainSrc = "$project.projectDir/src/main/java"

sourceDirectories.from = files([mainSrc])
classDirectories.from = files([debugTree])
executionData.from = "${project.buildDir}/outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec"
```

let me know if it works for you
