### ISSUE TITLE
The refresh token expired because not renewed after new signIn

### ISSUE THREAD

**Issue by gcastaldi** [AzureAD/microsoft-authentication-library-for-android#2105]
**Describe the bug**
We are in production with an android app using msal. We are still using version 4.7.0 (soon 4.10.0) and two users were logged out because the refresh token expired: 

2024-04-25 09:44:51.975: acquireTokenSilentAsync error: 
error code: invalid_grant
error message: AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2024-03-26T07:05:58.0377614Z and the maximum allowed lifetime for this request is 2592000.

As you can see the allowed lifetime is 30 days. Considering that these users execute signIn/signOut every working day shouldn't happen that the expiration time is reached.
They executed first login 30 days before the problem so seems that in MSAL or Authenticator is maintained the same refresh token until valid even the user execute signIn/signOut.
I tried to reproduce the problem using a session of 4h but worked correctly.

**Smartphone (please complete the following information):**
 - Device: Samsung A52
 - Android Version: Android 12, Sdk 31
 - Browser: Internet Samsung
 - MSAL Version: 4.7.0
 - Microsoft Authenticator installed

**To Reproduce**
* Create accountApp (account mode single)
* Call signIn/signOut every day obtaining a session of 30d
* The problem happens after 30d: used logged out for session expired even logged in 4h before

**Expected behavior**
If after each signIn is generated a new 30d refresh token shouldn't happen expires in 24h.

**Actual Behavior**
Refresh token expires in 24h

**Screenshots**

**Additional context**

**Comment by negoe** [comment]
@gcastaldi This is performing as expected. It seems like you have  Token lifetime policies applied for refresh tokens. You can read more details at [Configurable token lifetimes in the Microsoft identity platform](https://learn.microsoft.com/en-us/entra/identity-platform/configurable-token-lifetimes#configurable-token-lifetime-properties).
