### ISSUE TITLE
Brokered Auth / SSO

### ISSUE THREAD

**Issue by DiestelkampA** [AzureAD/microsoft-authentication-library-for-android#211]
I know that SSO is supported in the iOS version of MSAL by using cookie sharing in the utilized webview (cookie sharing is slated to be removed in iOS 11...), how is SSO supported in Android MSAL?  I haven't been able to find any documentation on how it works?  Also, does MSAL have any concept of authentication brokers like Microsoft Authenticator or Intune and if not do you plan to add them in eventually?

**Comment by weijjia** [comment]
MSAL uses the chrome custom tab, in which every apps will be sharing the same cookie jar.
