### ISSUE TITLE
Error: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml

### ISSUE THREAD

**Issue by Mradul296** [AzureAD/microsoft-authentication-library-for-android#2127]
I have a react native android app which is using AAD B2C for authentication with MSAL library. I have added the below intent filter in my AndroidManifest.xml file but I still get "Error: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml" when the try to initialize the PublicClientApplication.

My manifest|

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.lyfter">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
          android:name="com.google.android.geo.API_KEY"
          android:value="key"/>
      <uses-library android:name="org.apache.http.legacy" android:required="false"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
                android:scheme="msauth"
                android:host="com.lyfter"
                android:path="/signature_hash" />
        </intent-filter>
    </activity>
    </application>
</manifest>
`

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M51
 - Android Version: 12
 - Browser [e.g. Chrome, Edge]
 - MSAL Version: "react-native-msal": "^3.1.2",

**Stacktrace**
Error: 

`[Error: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml

<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                        android:host="com.authapp"
                        android:path="/Pz9KAD8/Pz8/Pz8DCyhkP24/Pz8K"
                        android:scheme="msauth" />
        </intent-filter>
</activity>
]`

**Screenshots**
![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/29627274/ff2d0ddc-e049-4a8e-9f49-81574c6f1d3f)

**Additional context**
One thing to note here is that the error still shows old values for host(package name) and path(hash). if you see in manifest.xml, I have updated these values but the error still shows older settings.

**Comment by Mradul296** [comment]
I also used the below command to debug app-debug.apk file and I can see the updated intent filter is present

` apktool d -o output_directory_name app-debug.apk`

![Screenshot (45)](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/29627274/6a3e824d-4b8a-4590-a6fc-3dbbedb0f799)

**Comment by misiektg86** [comment]
Any progress on this ?

**Comment by misiektg86** [comment]
> Any progress on this ?

Ok. In my case, it turned out to be the wrong authorization endpoint passed to the client app

**Comment by negoe** [comment]
@misiektg86 Please post your issue on the right path [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues).
