### ISSUE TITLE
Fetching tokens from cache fails when there is no Internet connection

### ISSUE THREAD

**Issue by robertszuba** [AzureAD/microsoft-authentication-library-for-android#2132]
Not sure if this is a bug or missing functionality. 

**Is your feature request related to a problem? Please describe.**
As a mobile app I'd like to check is user has a valid Access Token stored in cache. If the token is stored in cache it should be possible to retrieve it even when device has no active Internet connection. If the AT is expired and there is no Internet connection to refresh it, it should return an error. Currently, when there is no Internet connection, sometimes the token is returned as expected, but other times we face an exception "unable to perform cloud discovery" even though we know there should be valid token stored in cache.

**Describe the solution you'd like**
Precondition: user was able to authenticate when there was active network connection, a valid Access Token is stored in cache and is not expired yet.

When there is internet connection: calling `acquireTokenSilentAsync` should return us the Access Token, potentially doing AAD discovery during the process, as it does now

When there is no internet connection: calling `acquireTokenSilentAsync` should return the valid (not expired) AT ignoring network connection issues. This could be part of the app configuration or additional flag in AcquireTokenSilentParameters

**Describe alternatives you've considered**
I was trying to see if there is any flag or setting that we could use to make the app return valid tokens regardless of the AAD connection state, but was not able to find any. We are considering storing the AT in our own cache but this introduces additional security risks.

**Additional context**
Our use case is to allow users to use the app in limited scope when they are having network connection issues, but we can confirm that they were able to authenticate recently. We do know that AT validation without active network connection has some limitations, but we should be able to at least verify that the token was stored in cache and has not expired yet, so that some limited access can be granted until user is able to authenticate online or until the token has expired.

I've seen [this answer](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1607#issuecomment-1104111428) where the "unable to perform cloud discovery" exception is explained, but I don't see how can we make the MSAL library to ignore the connectivity issue while performing the silent token cache lookup.

**Comment by negoe** [comment]
@robertszuba Thanks for the sharing the feedback. Currently, we are occupied with other important features, We will try to improve the experience in near future considering your feedback.

**Comment by negoe** [comment]
Tracked internally.
