### ISSUE TITLE
Provided authority is not known.  MSAL will only make requests to known authorities.

### ISSUE THREAD

**Issue by abhishekagra** [AzureAD/microsoft-authentication-library-for-android#2202]
**Describe the bug**
On MSAL Android library version **above** 5.0.1 (Android Gradle Plugin v8.0.0 and above), we are getting below error while calling **acquireToken()**:
"Provided authority is not known.  MSAL will only make requests to known authorities."

But on v5.0.1, authentication is working fine (Android Gradle Plugin v7.5.1).

{
  "client_id": "xyz",
  "authorization_user_agent": "WEBVIEW",
  "redirect_uri": "<REDIRECT URL>",
  "account_mode": "**MULTIPLE**",
  "broker_redirect_uri_registered": false,
  "authorities": [
    {
      "type": "**B2C**",
      "authority_url": "<AUTHORITY URL>",
      "default": true
    }
  ]
}

**Smartphone (please complete the following information):**
 - Device: [Sonim XP10]
 - Android Version: [12]
 - MSAL Version: above 5.0.1

**To Reproduce**
Update the MSAL library version from 5.0.1 to 5.1.0 (and above).

Are there any specific procedures or steps to follow to use the latest version of MSAL library v5.7.0 ?

**Comment by negoe** [comment]
Hi @abhishekagra Ensure that the authority_url specified in the JSON configuration is correct and follows the exact expected format for your B2C authority (e.g., https://<tenant>.b2clogin.com/tfp/<tenant_name>/<policy>. You can follow the guidance here : https://learn.microsoft.com/en-us/entra/msal/dotnet/acquiring-tokens/desktop-mobile/social-identities#authority-for-an-azure-ad-b2c-tenant-and-policy
