### ISSUE TITLE
Custom tabs without Chrome problem

### ISSUE THREAD

**Issue by Apisov** [AzureAD/microsoft-authentication-library-for-android#225]
### I've tried your library with Emulator running Android 4.4.

And it doesn't work due to lack of Chrome application.

### The funny thing is that in the code I found comments that it should use default browser instead of Chrome in the case as described above.

But after those comments, you send error and closes auth activity and nothing happens obviously.
```java
// We'll use custom tab if the chrome installed on the device comes with custom tab support(on 45 and above it
// does). If the chrome package doesn't contain the support, we'll use chrome to launch the UI.
if (MsalUtils.getChromePackage(this.getApplicationContext()) == null) {
            Logger.info(TAG, null, "Chrome is not installed on the device, cannot continue with auth.");
            sendError(MsalClientException.CHROME_NOT_INSTALLED, "Chrome is not installed on the device, cannot proceed with auth");
return;
}
```

Maybe later I could create PR or something, but I after fast trying to fork and edit I've faced "jacoco" problem in dependencies and don't know how to solve it yet.

Thank you for any ideas and fast fixes!

**Comment by Helen2018** [comment]
I run into the same issue.

**Comment by iambmelt** [comment]
Hi @Apisov @Helen2018 -- Currently, MSAL supports API levels 21+ (as this is the minimum required API level to support the use of `CustomTabs`).

**Comment by bozhiqian** [comment]
I use Marshmallow (6.0.0) API Levele 23 with VS2017 emulator for Android. No Chrome has been installed. 
When I run Xamarin app against Azure AD B2C with Google identity. I stilll get exception. 

```
03-03 15:59:08.141 E/mono    ( 2071): Unhandled Exception:
03-03 15:59:08.141 E/mono    ( 2071): Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
03-03 15:59:08.141 E/mono    ( 2071):   at (wrapper dynamic-method) System.Object:28948aa6-8366-4dd3-8192-e700e67b3283 (intptr,intptr)
03-03 15:59:08.141 E/mono    ( 2071): 	ErrorCode: chrome_not_installed
03-03 15:59:08.141 E/mono-rt ( 2071): [ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication
03-03 15:59:08.141 E/mono-rt ( 2071):   at (wrapper dynamic-method) System.Object:28948aa6-8366-4dd3-8192-e700e67b3283 (intptr,intptr)
03-03 15:59:08.141 E/mono-rt ( 2071): 	ErrorCode: chrome_not_installed
```
I have already updated nuget packages "Xamarin.Android.Support.v4" and all dependencies to v26.1.0.1 but Xamarin app crashed when trying to call AcquireTokenAsync(...).
