### ISSUE TITLE
Customised domain with MSAL 

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-android#226]
How can I add customised domain rather than https://login.microsoftonline.com ?

**Comment by iambmelt** [comment]
Hi @kirthika - Please see [`PublicClientApplication(Context, String, String)`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L198-L219) - the third parameter allows for custom authorities to be set.

**Comment by iambmelt** [comment]
Going to resolve this issue. @kirthika feel free to follow up with any further questions or consult the javadoc available [here](http://javadoc.io/doc/com.microsoft.identity.client/msal/0.1.1).

**Comment by kirthika** [comment]
Hey @iambmelt here's the code snippet that I tried : 
`
public void initializeMSAL(Context context,AzureLogin callback){
    this.instance = callback;
    ArrayList<String> scopesList = new ArrayList<String>();
    sampleApp = null;
    if (sampleApp == null)
    {

        PropertyService propertyService = new PropertyService();
 
        Properties properties=propertyService.getAuthProperties();
        //only for test
        sampleApp = new PublicClientApplication(context.getApplicationContext(),properties.getProperty("clientId")/*CLIENT_ID*/,
                String.format(properties.getProperty("authority"),properties.getProperty("tenant"),properties.getProperty(policyName)));

        // build scopes
        String[] scopesCrud={"read", "write"};;
        for (int i = 0; i < scopesCrud.length; i += 1) {
            scopesList.add(propertyService.getAuthProperties().getProperty("scopeAccessToken") + resource + "/" + scopesCrud[i]);
        }
        SCOPES = scopesList.toArray(new String[scopesList.size()]);
    }
    /* Attempt to get a user and acquireTokenSilent
     * If this fails we do an interactive request */
    List<User> users = null;
    try
    {
        users = sampleApp.getUsers();
        if (users != null && users.size() == 1)
        { 
            String strname=users.get(0).getName(); 

             /* We have 1 user */
            sampleApp.acquireTokenSilentAsync(SCOPES, users.get(0), getAuthSilentCallback());
        }
        else
        {
            /* We have no user */
            /* Let's do an interactive request */
            // sampleApp.acquireToken(this, SCOPES, getAuthInteractiveCallback());
        }
    }
    catch (MsalClientException e)
    {
        Log.d("DEBUG", "MSAL Exception Generated while getting users: " + e.toString());
    }
    catch (IndexOutOfBoundsException e)
    {
        Log.d("DEBUG", "User at this position does not exist: " + e.toString());
    }
`
And here is the authority domain that I tried to access : "dev.driverslogin.com"
I get Error code - **42002** which says authority validation is not supported .
Please help.

**Comment by iambmelt** [comment]
Hi @kirthika - It appears that the `42002` error you are encountering is emitted from Zscaler App and may be attributable to a misconfigured IdP.

See [this link](https://webcache.googleusercontent.com/search?q=cache:Q6f3-I7xXHcJ:https://help.zscaler.com/zia/zscaler-app-zpa-authentication-errors+&cd=1&hl=en&ct=clnk&gl=us) for more information about this error. It appears to be a network configuration/topology issue.

![zscaler](https://user-images.githubusercontent.com/990063/31512507-30ad5f76-af59-11e7-980a-e6e08e8b08aa.PNG)
