### ISSUE TITLE
Azure B2C : Need help with scope parameter...

### ISSUE THREAD

**Issue by AdarshanaBlr** [AzureAD/microsoft-authentication-library-for-android#231]
Hi, 
Please consider the following set of constants I have defined and also created the azure B2C porta also.
    final static String AUTHORITY = "https://login.microsoftonline.com/tfp/%s/%s";
    final static String TENANT = "sample1.onmicrosoft.com";
    final static String CLIENT_ID = "xxxx..xxx...x";

    //final static String SCOPES = "https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read";
    final static String SCOPES = "openid email profile";//"User.Read"
   final static String API_URL = "";

     final static String SISU_POLICY = "B2C_1_UPIN";
    final static String EDIT_PROFILE_POLICY = "B2C_1_PROF";

Please note that my Interface is just Mobile APP and no Web App. So I have configured everything fine.

Now I'm fiding it hard to mentione the Scope parameter. 
1. Initiall User.Read did not work. The modified fabrikamb2c sample crashes.
2. When I use "https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read" as the scope, at least App does not crash. But not sure why it works.
3. After several trial and error, now I have used following "openid email profile". It seems to work. But not sure why and how.

There seems to be mystery and confusion around scope definition. Remember I just want only Mobile APP and no Web App interface. 

Any help is much appreciated.

Regards
Adarshanasa

**Comment by danieldobalian** [comment]
Going to close this due to date of creation and inability to repro. 

Feel free to re-open if you're still seeing issues. If possible, expand on the error and attach logs if your app is collecting them.  I suspect it was a transient failure at the Auth service.
