### ISSUE TITLE
National cloud requests cannot be handled with this library

### ISSUE THREAD

**Issue by hschottm** [AzureAD/microsoft-authentication-library-for-android#232]
I am using a national cloud microsoft account (onmicrosoft.de) to connect to a AD 2.0 app with this library. I am getting a 

`com.microsoft.identity.client.MsalServiceException: AADSTS90043: National Cloud request processing failed: CallNationalCloud: http request failed with errorcode: BadRequest, Content:{"error":"invalid_grant","error_description":"AADSTS70000: Transmission data parser failure: Authorization Code is malformed or invalid. }
`

Why is Microsoft having no general SSO capability for all kinds of account (Microsoft Live, Office 365, Office 365 National Cloud). There is no way to connect with such a national cloud account (e.g. onmicrosoft.de).

I was trying to use all available OAuth mechanisms and I only got a valid access token when I used the client credentials grant approach but only when I modified the access token URL and used the tenant of the national account and the top level domain of the national account instead of the com TLD which I both don't have when I provide a login form for a user that only enters his Microsoft account email.

The OneDrive app is capable of doing this and obviously using the same login screens as this library is using and it works. Why can't this flow being considered in this library?

**Comment by danieldobalian** [comment]
Hey @hschottm, supporting national cloud environments/accounts is on the roadmap. We're still in preview, but plan to support this before GA.  

Let me know if you want to connect so we can let you know when it's available.

**Comment by iambmelt** [comment]
Sovereign cloud support (instance aware) is supported and is now available in GA (`1.0.0`)
