### ISSUE TITLE
Migrate from ADAL to MSAL

### ISSUE THREAD

**Issue by Eqbalazar** [AzureAD/microsoft-authentication-library-for-android#236]
Can we migrate from ADAL to MSAL in **production** app ?

**Comment by danieldobalian** [comment]
Hey @Eqbalazar, sorry about the delay to respond to this issue.  

MSAL Android is in a production-supported public preview as found in the [official Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-libraries).  Support statement from the article:

> The MSAL preview libraries are suitable for use in a production environment. We provide the same production level support for these libraries as we do our current production libraries (ADAL). During the preview we may make changes to the MSAL API, internal cache format, and other mechanisms of these libraries without notice, which you will be required to take along with bug fixes or feature improvements. This may impact your application. For instance, a change to the cache format may impact your users, such as requiring them to sign in again. An API change may require you to update your code. When we provide the General Availability release we will require you to update to the General Availability version within six months, as applications written using a preview version of library may no longer work.

**Comment by iambmelt** [comment]
Thanks for following up, @danieldobalian 👍
