### ISSUE TITLE
Msal Library is taking too much time(5min) to throw MSAL exception in Failure case

### ISSUE THREAD

**Issue by NavalKishor** [AzureAD/microsoft-authentication-library-for-android#238]
Please find the log where I have try 2 attempts and it taking more then 2 and 5 min of time to throw the exception in case of failure

Attempt 1
Line 251: 11-26 21:23:36.731
Line 91: 11-26 21:21:03.109
Time Taken by MSAL: 00-00 00:02:33.622

Attempt 1
Line 461: 11-26 21:36:13.927
Line 371: 11-26 21:31:13.689
Time Taken by MSAL: 00-00 00:05:00.238

Is There Any way is there to reduce this time when Msal is throwing the Exception withing 40sec instead of 2 or 5+ minute for the good experience??
Any work arround solution for this from MSAL end
as in 1st attempt the correlation id had not returned in the header of response.So it took 2min.33sec.622ms
as in 2st attempt the Request timeout with SocketTimeoutException and its retry one more time but that Token request failed with error as Connection reset by peer.So it took 5min.0sec.238ms

Log Details start here related to MSAL.

Line 91: 11-26 21:21:03.109 7703-7703/com.package.name I/PublicClientApplication: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03] Create new public client application.
Line 92: 11-26 21:21:03.123 7703-7703/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 97: 11-26 21:21:03.126 7703-7703/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - d8f10a6d-28e0-4ff0-81f0-af02c830470e] Retrieve users with the given client id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Line 102: 11-26 21:21:03.150 7703-7703/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - d8f10a6d-28e0-4ff0-81f0-af02c830470e] Retrieve all the refresh tokens for given client id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; Returned refresh token number is 1
Line 103: 11-26 21:21:03.152 7703-7703/com.package.name I/TAGAzureUtils: initializeMSAL:getAuthSilentCallback
Line 104: 11-26 21:21:03.154 7703-7703/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 105: 11-26 21:21:03.155 7703-7703/com.package.name I/PublicClientApplication: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Preparing a new silent request
Line 107: 11-26 21:21:03.179 7703-7806/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 108: 11-26 21:21:03.180 7703-7806/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Access token item found in the cache is already expired.
Line 109: 11-26 21:21:03.192 7703-7806/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Retrieve refresh tokens for the given cache key
Line 110: 11-26 21:21:03.193 7703-7806/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Perform authority validation and tenant discovery.
Line 111: 11-26 21:21:03.219 7703-7806/com.package.name V/HttpRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:51:03 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Sending Http Get request.
Line 160: 11-26 21:21:40.197 7703-7806/com.package.name V/HttpRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:51:40 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Returned status code is: 200
Line 161: 11-26 21:21:40.202 7703-7806/com.package.name W/Oauth2Client: MSAL 0.1.1 Android 23 [2017-11-26 15:51:40 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Returned response doesn't have correlation id in the header.
Line 162: 11-26 21:21:40.210 7703-7806/com.package.name I/Oauth2Client: MSAL 0.1.1 Android 23 [2017-11-26 15:51:40 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Http response status code is: 200
Line 163: 11-26 21:21:40.217 7703-7806/com.package.name V/HttpRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:51:40 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Sending Http Post request.
Line 186: 11-26 21:23:36.691 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:53:36 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Token request failed with error: Read error: ssl=0x7f1904918e00: I/O error during system call, Connection reset by peer javax.net.ssl.SSLException: Read error: ssl=0x7f1904918e00: I/O error during system call, Connection reset by peer
Line 215: 11-26 21:23:36.722 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:53:36 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f1904918e00: I/O error during system call, Connection reset by peer
Line 215: 11-26 21:23:36.722 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 15:53:36 - ea5e7220-d718-4909-9d19-ae20ac323cf1] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f1904918e00: I/O error during system call, Connection reset by peer
Line 251: 11-26 21:23:36.731 7703-7703/com.package.name I/TAGAzureUtils: getAuthSilentCallback Authentication failed: com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f1904918e00: I/O error during system call, Connection reset by peer
Line 371: 11-26 21:31:13.689 7703-7703/com.package.name I/PublicClientApplication: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13] Create new public client application.
Line 372: 11-26 21:31:13.711 7703-7703/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 373: 11-26 21:31:13.712 7703-7703/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - b836beb8-c8c4-4027-9dc3-4c9b795e7a26] Retrieve users with the given client id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Line 374: 11-26 21:31:13.734 7703-7703/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - b836beb8-c8c4-4027-9dc3-4c9b795e7a26] Retrieve all the refresh tokens for given client id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; Returned refresh token number is 1
Line 375: 11-26 21:31:13.735 7703-7703/com.package.name I/TAGAzureUtils: initializeMSAL:getAuthSilentCallback
Line 376: 11-26 21:31:13.735 7703-7703/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 377: 11-26 21:31:13.735 7703-7703/com.package.name I/PublicClientApplication: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Preparing a new silent request
Line 378: 11-26 21:31:13.740 7703-7806/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13] Passed in authority string is a b2c authority, create a new b2c authority instance.
Line 379: 11-26 21:31:13.740 7703-7806/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Access token item found in the cache is already expired.
Line 381: 11-26 21:31:13.753 7703-7806/com.package.name V/TokenCache: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Retrieve refresh tokens for the given cache key
Line 382: 11-26 21:31:13.754 7703-7806/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Perform authority validation and tenant discovery.
Line 383: 11-26 21:31:13.769 7703-7806/com.package.name I/Authority: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Authority has already been resolved.
Line 384: 11-26 21:31:13.773 7703-7806/com.package.name V/HttpRequest: MSAL 0.1.1 Android 23 [2017-11-26 16:01:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Sending Http Post request.
Line 395: 11-26 21:34:05.899 7703-7806/com.package.name V/HttpRequest: MSAL 0.1.1 Android 23 [2017-11-26 16:04:05 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Request timeout with SocketTimeoutException, will retry one more time.
Line 396: 11-26 21:36:13.903 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 16:06:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Token request failed with error: Read error: ssl=0x7f190491b880: I/O error during system call, Connection reset by peer javax.net.ssl.SSLException: Read error: ssl=0x7f190491b880: I/O error during system call, Connection reset by peer
Line 425: 11-26 21:36:13.904 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 16:06:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f190491b880: I/O error during system call, Connection reset by peer
Line 425: 11-26 21:36:13.904 7703-7806/com.package.name E/BaseRequest: MSAL 0.1.1 Android 23 [2017-11-26 16:06:13 - 5b62dea7-d206-49a7-aec0-375c8c6bc76c] Error occurred during authentication. com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f190491b880: I/O error during system call, Connection reset by peer
Line 461: 11-26 21:36:13.927 7703-7703/com.package.name I/TAGAzureUtils: getAuthSilentCallback Authentication failed: com.microsoft.identity.client.MsalClientException: Auth failed with the error Read error: ssl=0x7f190491b880: I/O error during system call, Connection reset by peer

**Comment by NavalKishor** [comment]
[MSALFilterLogTookLongTimeToThrowException.txt](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/1521176/MSALFilterLogTookLongTimeToThrowException.txt)

**Comment by iambmelt** [comment]
[This is now configurable](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#http)
