### ISSUE TITLE
HTTPRequest does not have configurable timeouts

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/microsoft-authentication-library-for-android#239]
static final int CONNECT_TIME_OUT_MSEC = 30000;
    static final int READ_TIME_OUT_MSEC = 30000;

Connect timeout and read timeout both should have a user configurable setting.

**Comment by heidijinxujia** [comment]
HttpRequest is a package-visible final class.

**Comment by heidijinxujia** [comment]
As we need to sync the behavior with other platforms, so this issue is currently postponed.

**Comment by heidijinxujia** [comment]
This one is cut. And the network timeout will be included in Shane's configuration feature.
