### ISSUE TITLE
When/If MSAL starts encrypting tokens it should use OAEP padding in place of PKCS1

### ISSUE THREAD

**Issue by amishra-dev** [AzureAD/microsoft-authentication-library-for-android#240]
PKSC1 is fine at the moment and it would be fine for next few years but the standard and recommended is OAEP padding.  However, as of now, this issue does not pose any security threat but has to be implemented in MSAL.
Attack Vector: javax.crypto.Cipher.getInstance
Description: The RSA algorithm is used without using the OAEP padding scheme, which effectively weakens the encryption.
Remediation: Use OAEP padding scheme when using RSA algorithm for encryption/decryption.
References: https://cwe.mitre.org/data/definitions/780.html

**Comment by iambmelt** [comment]
Platform defaults pre API 18 currently use `2048` bit key length -- PoP scenarios explicitly apply `2048` bit keys where possible (API 18+)

/cc @hamiltonha as FYI

**Comment by iambmelt** [comment]
Closing as this ask will come from PM/sec-compliance via SDL
