### ISSUE TITLE
When/If MSAL starts encrypting tokens the key size should be 2048

### ISSUE THREAD

**Issue by amishra-dev** [AzureAD/microsoft-authentication-library-for-android#241]
Its recommended that RSA should be implemented with atleast 2048 key size. But, as of now this is not a security threat but has to be implemented in MSAL when MSAL does token encryption
Attack Vector: java.security.KeyPairGenerator.initialize
Description: The key size specified for this algorithm is not large enough to protect it from brute force attacks.
Remediation: For Symmetric algorithms other than DES, use a key size >= 128bit, for RSA >= 2048bit, 3DES == 192 (168 effective).
References: http://cwe.mitre.org/data/definitions/326.html

**Comment by iambmelt** [comment]
Platform defaults pre API 18 currently use `2048` bit key length -- PoP scenarios explicitly apply `2048` bit keys where possible (API 18+)

/cc @hamiltonha as FYI
