### ISSUE TITLE
User Modifiable Settings Should be Available from a Unified Location

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#249]
Increasingly, MSAL exposes new user-modifiable settings and values to users. Currently, settings are exposed where they are most-relevant:

`Logger.setAllowPii()`
`Logger.setEnableLogCatLog()`
`Telemetry.setAllowPii()`
`MsalUtils.setConnectTimeout()`
`MsalUtils.setReadTimeout()`

I'd like to propose the creation of a designated settings class whose responsibility it is to expose user-modifiable values/flags to users.

Example usage might look like:

`MsalSettings.Logging.setAllowPii()`
`MsalSettings.Logging.setEnableLogCat()`
`MsalSettings.Telemetry.setAllowPii()`
`MsalSettings.Network.setConnectTimeout()`
`MsalSettings.Network.setReadTimeout()`

**Comment by nazukj** [comment]
@rayluo FYI for design

**Comment by iambmelt** [comment]
This is now satisfied by app config see https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Configuring-your-app
