### ISSUE TITLE
ActivityNotFoundException for devices with Chrome app disabled

### ISSUE THREAD

**Issue by imablanco** [AzureAD/microsoft-authentication-library-for-android#257]
For devices with Chrome app disabled but not uninstalled, PackageInfo still returns for Chrome package so library is throwing an unhandled ActivityNotFoundException when trying to start authentication flow.
Reproduced with a Nexus 5.

**Comment by tipa** [comment]
When is this fix expected to show up as a part of an update to the `Microsoft.Identity.Client`-NuGet package to work in Xamarin.Android projects?

**Comment by danieldobalian** [comment]
@imablanco thanks for calling this out.  In the case Chrome is disabled, do you expect the library to fall back on another browser or give the app the option fallback?  

@tipa are you using MSAL .NET and seeing the same exception? Or are you pulling in MSAL Android into your Xamarin project?

**Comment by tipa** [comment]
@danieldobalian I am using this Nugetpackage in my Xamarin.Android project: https://www.nuget.org/packages/Microsoft.Identity.Client/ (version 1.1.2-preview0008).
Using this package results in the exception when Chrome is disabled/not installed. Does this answer your question?

**Comment by imablanco** [comment]
@danieldobalian The ideal scenario is falling back on whatever browser the user has installed.
I made a PR for this issue ( #258 ), just preventing the runtime crash.

**Comment by danieldobalian** [comment]
@tipa yes, thank you. That's MSAL .NET (a separate code base). I'll let that team know of this issue. 

@imablanco Agreed, that's the direction I was thinking as well, but wanted to check.  Thanks for the PR, we'll take a look and see if we can adopt it for the next release.

**Comment by danieldobalian** [comment]
@jmprieur FYI on MSAL .NET having the same runtime crash when Chrome is disabled.

**Comment by tipa** [comment]
This issue is getting old. Any news? Having tons of frustrated users because of this bug

**Comment by tipa** [comment]
How is this issue still not fixed...? :(
The whole OneDrive login process worked flawflessly in the previous SDK, this is a big step back!

**Comment by tipa** [comment]
Any updates?

**Comment by danieldobalian** [comment]
This has been fixed in MSAL 0.2.0 with the introduction of support for all browsers. When Chrome is disabled, we'll fallback to the next browser available on the device.
