### ISSUE TITLE
Support for other browsers than Chrome

### ISSUE THREAD

**Issue by baltuonis** [AzureAD/microsoft-authentication-library-for-android#261]
Support for other browsers than Chrome - like Firefox?

**Comment by danieldobalian** [comment]
Hey @blacktea, we intend on supporting more browsers other than Chrome and Chrome custom tabs before GA. 

Out of curiosity, would you be interested in being able to configure which browser the device uses (in the case the user has multiple browsers)?

**Comment by blacktea** [comment]
@danieldobalian  Thanks for response.

No, at the moment I do not see the reason to worry about the client browser.
We just want to make sure that app is usable and stable

**Comment by danieldobalian** [comment]
Fair enough, thanks for the feedback.  One more question- Was there a specific device that you had problems with (Android version/OEM)?

**Comment by blacktea** [comment]
@danieldobalian - You are welcome, I'm really looking for this library the be more complete until we finish the project.

At the moment I'm writing MSAL Wrappers for React Native and these kind of errors upset our team a lot. However as we are using Azure AD B2C we are locked in with MSAL

Mi phone - Sony Xperia Z2 D6503 Android 5.0.2 latest Chrome

**Comment by danieldobalian** [comment]
@blacktea we're actively working on getting it to a place where you're expecting it to be. Thanks for the help reporting these issues, it helps quite a bit. 

Would you be willing to reach out and chat a bit more offline? I'd like to fully understand your teams project and deep dive into your feedback/issues.  My email is on my github profile.

**Comment by KristofferBerge** [comment]
How can I tell my users that they need to install Chrome? I am unable to catch the exception in my code

```cs
   try
   {
      AuthenticationResult ar = await App.PCA.AcquireTokenAsync(App.Scopes, B2cHelper.GetUserByPolicy(App.PCA.Users, App.PolicySignUpSignIn), App.UiParent);
      await UpdateSignInState(true, ar);
   }
   catch{
   }
```

From log:
>03-22 11:11:07.535 E/mono    ( 2639): Unhandled Exception:
>03-22 11:11:07.535 E/mono    ( 2639): Microsoft.Identity.Client.MsalClientException: Chrome is not installed on the device, cannot proceed with authentication

**Comment by danieldobalian** [comment]
MSAL 0.2.0 has shipped with this support, closing issue.
