### ISSUE TITLE
Support for lower version Minimum SDK 18

### ISSUE THREAD

**Issue by PAYong** [AzureAD/microsoft-authentication-library-for-android#263]
Is there a way that you can support lower version of  Android to API level  18 instead of 21? 
Our app still has a minimum support of SDK18. @_@

**Comment by sittingInFront** [comment]
@PAYong: you can do some trick.
Use `tools:overrideLibrary` for library in manifest and check if installed on device Google Chrome with Custom Tabs support. This can work from API 16.
 It's not so good solution but can help you.

**Comment by danieldobalian** [comment]
@PAYong we intend on dropping the minimum version down before the library GA's.  Marking as investigation as to re-evaluate how we've prioritized supporting more versions.

**Comment by iambmelt** [comment]
Current snapshot of device coverage
![version_dist](https://user-images.githubusercontent.com/990063/41107842-24fd0732-6a41-11e8-9727-86ff25df0728.JPG)

**Comment by heidijinxujia** [comment]
Hi @PAYong , the plan for the next release is to lower the min sdk into 19. Is there any specific reason you need 18? Thanks.

**Comment by iambmelt** [comment]
Current min is 16
