### ISSUE TITLE
Can you make the public isExpired() method to know access token state.

### ISSUE THREAD

**Issue by sittingInFront** [AzureAD/microsoft-authentication-library-for-android#266]
In com.microsoft.identity.client.AuthenticationResult we have public
` public Date getExpiresOn() {
        return mAccessTokenCacheItem.getExpiresOn();
    }`
Could you do the similar
` public boolean isExpired() {
        return mAccessTokenCacheItem.isExpired();
    }`
cause we have the method `mAccessTokenCacheItem.isExpired()`

**Comment by danieldobalian** [comment]
@sittingInFront I like your proposed method. Out of curiosity, what's your primary use case for checking Access token lifetime?  Have you found the `Date` being more complicated?

@shoatman thoughts on this method?

**Comment by sittingInFront** [comment]
We make request to MS Graph API.  So we need the Access token to add it to request header. And before it we should check if Access token expired.
Now I've coded `isExpired()` method by myself (nothing hard) but if we have the same in library we could try to use it.

**Comment by iambmelt** [comment]
@sittingInFront @danieldobalian -- `AuthenticationResult#getAccessToken` should never return an expired AT. If you are encountering an issue where `onSuccess()` is returning an expired token, please open a new issue (as this would represent a bug in the SDK).

So long as `acquireToken` or `acquireTokenSilent` are called prior to make your web service request, you should always have a fresh token. There are no plans to expose a public `isExpired()` method at this time.
