### ISSUE TITLE
Tenant error

### ISSUE THREAD

**Issue by sittingInFront** [AzureAD/microsoft-authentication-library-for-android#267]
I use this library and it works good.
But today when I try to login I get the error below:
`2018-04-06 12:59:33-ERROR- AADSTS90002: Tenant 9188040d-6c67-4c5b-b112-36a304b66dad not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Trace ID: 157d5546-510c-4c33-a1f7-e0c210d80e00
Correlation ID: 532c1996-a7a3-418d-94ae-9f627bb5109e
Timestamp: 2018-04-06 09:59:32Z`
I was getting this error during several hours. Now it seems good.
What was it?
How can I prevent it?

**Comment by danieldobalian** [comment]
Closing as this was related to a brief outage.
