### ISSUE TITLE
Inline javadoc code example is outdated

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#268]
See [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/Logger.java#L45-L51) --  the `ILoggerCallback` definition is missing the `containsPII` parameter

**Comment by danieldobalian** [comment]
Addressed here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/295

**Comment by danieldobalian** [comment]
Merged.
