### ISSUE TITLE
How to manage multiple policies

### ISSUE THREAD

**Issue by sgallego** [AzureAD/microsoft-authentication-library-for-android#270]
We have different policies for sign in and sign up. What is the best approach to manage this case?

In the past we have done something similar with ADAL library using the next authority:
https://login.microsoftonline.com/%s
and then adding extra query parameters over aquireToken call:
p=<policy>&nonce=defaultNonce&scope=openid&idpsource=<idClient>

We can't do this on MSAL because 'https://login.microsoftonline.com/tfp/%s' is an invalid autority. It has to be in format https://login.microsoftonline.com/tfp/%s/%s'

Thanks

**Comment by danieldobalian** [comment]
Hey @sgallego, I recommend checking out our [B2C Android Sample](https://github.com/Azure-Samples/active-directory-b2c-android-native-msal) which does have 2 authorities (SISU, Edit Profile).  In this case, I passed the SISU (in a sense my primary policy) into the `PublicClientApplication` constructor, and then [override the authority](https://github.com/Azure-Samples/active-directory-b2c-android-native-msal/blob/master/android-client/app/src/main/java/com/azuresample/msalandroidapp/AuthenticatedActivity.java#L152) in certain `acquireToken()` requests that are used for Edit Profile.
