### ISSUE TITLE
Fix the broken unit tests due to Common-core Cache Migration

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#279]
- testAcquireTokenExpiresInNotReturned
- testGetTokenCodeSuccessfullyReturnedNoClientInfoReturned
- testGetTokenWithExtraQueryParam
- testAcquireTokenSilentNoAuthorityProvidedMultipleInTheCache
- testAcquireTokenWithUserSucceed
- testGetTokenWithScopeIntersection
- testAcquireTokenSuccess
- testAccessTokenNotValidRTIsUsed
- testSilentRequestScopeNotSameAsTokenCacheItem

![image](https://user-images.githubusercontent.com/16140683/39455861-aca9818c-4c97-11e8-8c14-4305f3c3a7d8.png)

**Comment by heidijinxujia** [comment]
#283 Turns off the useCommonCache flag, not fixing the unit tests. Please correct me if I understood wrong.

**Comment by iambmelt** [comment]
Unit tests were fixed on API 25+ devices in #283 by upgrading `mockito-android` to `2.18.3`. No tests were specifically altered to account for behavior of the common cache on this branch, as it uses the _old schema_ which will never enter into prod.

This work item will 'go away' when the branch `iambmelt/account-credential-schema` merges into `dev`. I will likely begin this work tomorrow (5/3/2018). Any tests which break or are invalidated by that merge I will fix or remove as part of that work. With that rationale, we can close this.
