### ISSUE TITLE
Default Browser selecting behavior for MSAL

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#305]
Right now, MSAL employs the following logic to select which browser to launch on an interactive authorization request: 

`Chrome Custom Tabs` -> `Chrome Browser`

The downside of this is the following:
- Devices without Chrome cannot sign in.
- Devices that have disabled Chrome cannot sign in.
- SSO between the user's `default` browser if isn't Chrome may not occur.
- SSO between apps on the device from the same identity provider built with two different Auth libraries may not occur. 

What is the long term browser behavior and selection for this library?

**Comment by shoatman** [comment]
@danieldobalian - Heidi's proposal differs from what we discussed on Friday.  Here's the documentation for [queryIntentActivities](https://developer.android.com/reference/android/content/pm/PackageManager.html#queryIntentActivities(android.content.Intent,%20int)
).... you can see in the description of "Returns" that the results are ordered from "best to worst"... not exactly a clear description in our scenario, but perhaps the best we can do?

As discussed I'd prefer the first browser over the first browser with custom tabs support.

**Comment by heidijinxujia** [comment]
@shoatman  The order of browsers list is from best to worst. The first package is the return of would be returned by [resolveActivity(Intent, int) ](https://developer.android.com/reference/android/content/pm/PackageManager#resolveActivity(android.content.Intent,%20int)) which is decided by the device setting. This means if the default is not changed, same browser should be launched next time.

**Comment by heidijinxujia** [comment]
```/**
     * Determine the best action to perform for a given Intent.  This is how
     * {@link Intent#resolveActivity} finds an activity if a class has not
     * been explicitly specified.
     *
     * <p><em>Note:</em> if using an implicit Intent (without an explicit ComponentName
     * specified), be sure to consider whether to set the {@link #MATCH_DEFAULT_ONLY}
     * only flag.  You need to do so to resolve the activity in the same way
     * that {@link android.content.Context#startActivity(Intent)} and
     * {@link android.content.Intent#resolveActivity(PackageManager)
     * Intent.resolveActivity(PackageManager)} do.</p>
     *
     * @param intent An intent containing all of the desired specification
     *               (action, data, type, category, and/or component).
     * @param flags Additional option flags.  The most important is
     * {@link #MATCH_DEFAULT_ONLY}, to limit the resolution to only
     * those activities that support the {@link android.content.Intent#CATEGORY_DEFAULT}.
     *
     * @return Returns a ResolveInfo containing the final activity intent that
     *         was determined to be the best action.  Returns null if no
     *         matching activity was found. If multiple matching activities are
     *         found and there is no default set, returns a ResolveInfo
     *         containing something else, such as the activity resolver.
     *
     * @see #MATCH_DEFAULT_ONLY
     * @see #GET_INTENT_FILTERS
     * @see #GET_RESOLVED_FILTER
     */
    public abstract ResolveInfo resolveActivity(Intent intent, int flags);
