### ISSUE TITLE
handleInteractiveRequestRedirect should not throw IllegalStateException for unknown codes

### ISSUE THREAD

**Issue by guillaume-tgl** [AzureAD/microsoft-authentication-library-for-android#315]
When the request code is not equal to `InteractiveRequest.BROWSER_FLOW` (which is not a public constant, `PuvlicClientApplication.handleInteractiveRequestRedirect` throws an `IllegalStateException`, making it impossible to support several request codes without hardcoding `BROWSER_FLOW`.
Usually, classes handling `onActivityResult` lifecycle method don't do anything when the request code is not equal to the request code they started the activity with.

**Comment by iambmelt** [comment]
This piece of API has been removed in the `1.0.0` release
