### ISSUE TITLE
Support starting authentication flow from fragment

### ISSUE THREAD

**Issue by guillaume-tgl** [AzureAD/microsoft-authentication-library-for-android#316]
It's currently not possible to start the authentication flow from a fragment, only from an activity. This means that when using the fragment's activity to start the authentication, the result arrives in the activity method `onActivityResult` and must be forwarded manually to the fragment.
A good improvement instead of the current behavior would be that the `acquireToken` does not start another activity by itself but forwards in a callback the intent that needs to be started. Then, it's the responsibility of the caller to start the intent and it's more flexible.

**Comment by iambmelt** [comment]
Duplicate issue - closing this to track in newer issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/441)
