### ISSUE TITLE
[Telemetry] Add AuthenticationAgent type into telemetry

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#340]

**Comment by iambmelt** [comment]
@shahzaibj Can you confirm whether or not this is already done for MSAL telemetry/ESTS telemetry?

**Comment by shahzaibj** [comment]
@iambmelt This is already done for MSAL Telemetry. 

This is not done for ESTS telemetry and certainly won't be included in the common schema for ESTS telemetry, however, we can include it in the platform specific fields in ESTS telemetry if we feel it is needed.

**Comment by iambmelt** [comment]
Thanks @shahzaibj -- since this is covered in MSAL telemetry and this issue was originally scoped to that effort, I am going to close this issue. Thanks
