### ISSUE TITLE
PublicClientApplication UiBehavior incorrect

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-for-android#372]
Steps to reproduce
- Install test app with latest msal or run AcquireToken Test from automation framework
- Call publicClientApplication.acquireToken() with UIBehavior.SELECT_ACCOUNT and then call publicClientApplication.acquireToken() with UIBehavior.FORCE_LOGIN

Expected :
The user will always be prompted for credentials

Actual :
Select account screen is displayed

**Comment by shoatman** [comment]
@kreedula - I wasn't able to repo this using latest dev.  We're you testing with dev?  If not which build?

**Comment by kreedula** [comment]
@shoatman  can be reproducible with com.microsoft.identity.client:msal 0.2.0-RC1 and com.microsoft.identity:common 0.0.5-RC2 as dependencies in automation test app

Test : AcquireTokenTest : should_be_able_to_acquire_token_with_force_login_select_account()

**Comment by iambmelt** [comment]
Synced with @kreedula - this is reported working
