### ISSUE TITLE
AcquireTokenSilent on Access Token expiry is writing wrong authority to cache

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-for-android#383]
Steps 
- Acquire Token using test app.
- Verify that 4 records( account, access token, refresh token , id token) are written to cache with aliased environment(login.windows.net) in cache key.
- Expire access token 
- Call AcquireTokenSilent

Expected
- New cache records replace the existing records and we would still have 4 records( account, access token, refresh token , id token) in cache with  aliased environment(login.windows.net) in cache key

Actual
- There are 7 records in cache. Old access token record is deleted and a new access token is created with request environment(login.microsoftonline.com) in cache key. Also new records for account, refresh token , id token are created with request environment(login.microsoftonline.com) in cache key.

**Comment by iambmelt** [comment]
@kreedula We can close this now, right?

**Comment by kreedula** [comment]
Fixed this
