### ISSUE TITLE
Kitkat: Samsung galaxy grand not able to get a token

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/microsoft-authentication-library-for-android#399]

**Comment by addev-ashish** [comment]
@shoatman yes its one of our devices. I have not debugged this completely, but the app did get the control back but https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/internal/controllers/LocalMSALController.java#L86 was never reached.

**Comment by shoatman** [comment]
Interesting.  Thanks

**Comment by danieldobalian** [comment]
Was this related to the issues on version 16-19, @addev-ashish?
