### ISSUE TITLE
In chrome custom tabs, the contextual button in the account selection list is too sensitive to the position

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-android#400]
**Repro steps**
In an Android app (tested on Nexus, with Chrome custom tabs), acquire a token

**Expected:**
When I tap with my finger on the .. button on the right of an account, I expect the contextual command/menu to signout.

**Actual**
It's actually quite hard to point to the right location to see this contextual command. I got the default browser contextual menu many times instead (with the option of opening to a new windows etc …)

**Analysis**
This is not an MSAL.Android issue, but rather a service UX issue (that the tapping zone is not big enough, at least on some devices, when you have reasonable sized fingers)

**Comment by iambmelt** [comment]
Following up offline with AAD UX team - thank you for reporting @jmprieur 

@hamiltonha @Om83 You are on the thread
