### ISSUE TITLE
MSA accounts keep requesting consent

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-android#401]
**Repro steps**
Acquire a token and when the user signs-in, s/he chooses to use an Microsoft personal account

**Expected**
Once I've consented for a given set of scopes, I would not want to consent again

**Actual**
I have to consent every time

**Analysis**
This is not an issue with MSAL.Android, but the experience is confusing.

**Comment by iambmelt** [comment]
@jmprieur This is a server-side issue, correct? Has this been resolved?

**Comment by jmprieur** [comment]
@iambmelt : it's by design of MSA ...

**Comment by iambmelt** [comment]
Closing as by-design.
