### ISSUE TITLE
Cache deletion in sample app doesn't work. Possible UI issue.

### ISSUE THREAD

**Issue by pkanher617** [AzureAD/microsoft-authentication-library-for-android#404]

**Comment by pkanher617** [comment]
**Repro**
Acquire token for user, then go to cache and attempt to clear cache.

**Expected**
Should clear cache record when delete is pushed

**Actual**
Records are not cleared.

**Analysis**
Not an issue with the library (probably), but a UI issue that is preventing a feature.

**Comment by danieldobalian** [comment]
Thanks for the report! This is a minor UI bug in the sample app, we'll get it fixed.

**Comment by iambmelt** [comment]
This is dead UI and it is removed from the `dev` branch latest version. Thanks
