### ISSUE TITLE
The request body must contain the following parameter: 'client_id'

### ISSUE THREAD

**Issue by Glennmen** [AzureAD/microsoft-authentication-library-for-android#418]
I am trying out the new version v0.2.0 and importing the config with a json file (I used the example from the wiki).
But I keep getting this error:
```
D/AuthenticationManager: Authentication failed: com.microsoft.identity.client.exception.MsalServiceException: AADSTS90014: The request body must contain the following parameter: 'client_id'.
    Trace ID: f0c80f05-e0c4-4758-9899-be82c5590800
    Correlation ID: 6dc7962d-f038-494d-83aa-52b48e003cdc
    Timestamp: 2018-10-11 07:27:46Z
```

Here is my `auth_config.json`:
```json
{
  "client_id" : "xyz",
  "authorization_user_agent" : "WEBVIEW",
  "redirect_uri" : "xyz://auth",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount"
      }
    }
  ]
}
```

And config import:
`mPublicClientApplication = new PublicClientApplication(App.getContext(), R.raw.auth_config);`

**Comment by shoatman** [comment]
@Glennmen - Thanks for reporting this issue we will investigate and get back to you.

**Comment by shoatman** [comment]
@Glennmen - I'm unable to repo what you've reported.  If you have logs that you're comfortable sharing that might help shed light.

**Comment by Glennmen** [comment]
@shoatman Not sure what I can share, the error above is the only thing that I see in logcat. If you can tell me what exactly I can do to provide you with more info I will be happy to share.

I will try to do some debugging tomorrow.

**Comment by Glennmen** [comment]
@shoatman I logged everything, not sure if this is helpful to you.
[The pastebin will delete in 1 week](https://pastebin.com/7X0yMpev)

**Comment by Glennmen** [comment]
After more testing (also because of updating the sample app microsoftgraph/android-java-connect-sample#19) I have found how to reproduce it.

When I login for the first time (no account info saved) it works, this is why it worked before after wiping app data.
Next time I try to connect again (with Account info saved) using `acquireTokenSilentAsync(Constants.SCOPES, account, null, forceRefresh, getAuthSilentCallback());` it gives the above error.

I was able to reproduce this on both `WEBVIEW` and `DEFAULT`.

**Comment by iambmelt** [comment]
Reopening issue for investigation

**Comment by shoatman** [comment]
Looks like there may be a v2 endpoint behavior difference relative to account types.  client id is not being set here.... 

https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/4bf7cc73e43c10a3ae5b001e2cd9528b59991473/common/src/main/java/com/microsoft/identity/common/internal/providers/microsoft/microsoftsts/MicrosoftStsOAuth2Strategy.java#L247-L257

If this is a behavior difference based on Account type.... we should file a bug against the service as well.  @Glennmen - Thanks for the logs they were a big help.  We'll work on a fix and let you know when it's available.

**Comment by iambmelt** [comment]
At a glance, it looks like AAD is honoring the request as specified by [RFC-6749](https://tools.ietf.org/html/rfc6749#page-47) but in the case of MSA accounts, the request is expected to have [additional information](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token) such as `client_id`, `redirect_uri`...

I can get a PR out to support these extra fields - @shoatman agree we should review consistency with service team

**Comment by iambmelt** [comment]
PRs are out!
- [`common/#285`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/285)
- https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/424

**Comment by iambmelt** [comment]
@Glennmen Glad to hear it! Thanks 😄
