### ISSUE TITLE
if ext_expires_in becomes > expires_in, MSAL will return an expired access token 

### ISSUE THREAD

**Issue by amishra-dev** [AzureAD/microsoft-authentication-library-for-android#420]
See the call here
https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/internal/controllers/LocalMSALController.java#L316

and implementation here
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/dto/AccessTokenRecord.java#L262

Not a burning issue yet as AAD v2 is still returning same value for both expires_in and ext_expires_in
{"token_type":"Bearer","scope":"https://graph.windows.net/User.Read","expires_in":3599,"ext_expires_in":3599," ....

**Comment by iambmelt** [comment]
Thanks for filing this @addev-ashish -- I'll pick up these changes tomorrow for a Monday hotfix.

As for the changes, I'm thinking the hotfix should ignore the `ext_expires` and the larger `0.3.0` release will add `503` support -- any objections?

**Comment by addev-ashish** [comment]
@iambmelt sounds good. Thanks

**Comment by iambmelt** [comment]
Fixed in linked PRs above
