### ISSUE TITLE
Can RequestCode onActivityResult be changed to something else

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#421]
/* Handles the redirect from the System Browser */
@override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
sampleApp.handleInteractiveRequestRedirect(requestCode, resultCode, data);
}

The requestCode is by default 1001. Is there a way we can customize the requestCode to something else. I am using ADAL library and MSAL library, both these libraries doesn't give an option to change it to something else. When onActivityResult gets invoked, we end up getting the same requestCode.

**Comment by iambmelt** [comment]
This has been removed in `1.0.0`
