### ISSUE TITLE
Using password manager with WebView potentially causes a crash

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#422]
@Glennmen - Reported a problem when attempting to use 1password with the webview to sign in.

**Comment by iambmelt** [comment]
Originally reported in #418

**Comment by iambmelt** [comment]
@Glennmen are you still facing this problem with v1.0.x+?

**Comment by Glennmen** [comment]
@iambmelt I will try to test with v1.0 next week and let me you know.

**Comment by iambmelt** [comment]
Cheers, thanks @Glennmen
