### ISSUE TITLE
Username == "Missing from the token response"

### ISSUE THREAD

**Issue by MoBo** [AzureAD/microsoft-authentication-library-for-android#437]
I am using the Version 0.2.1.
Why do I get `Missing from the token response` for `result.account.username`.
I am connected to a B2C AD.

**Comment by iambmelt** [comment]
Hi @MoBo -- This is a known issue with some Identity Providers which have integrated with Azure B2C. Specifically, we have observed this behavior with Google Accounts... if memory serves, the `/token` response received by MSAL does not return an email or username in an OpenId/OAuth 2.0 compliant way. This value is currently used a placeholder to satisfy [cache validation](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/c163b97c328fb470efc0aae8716d588c50599c3d/common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java#L678-L691).

Unfortunately, I do have an ETA for a fix on this, as the format returned by the IdP is unfortunately not under our library's control.

**Comment by danieldobalian** [comment]
Hi @MoBo, 

We're looking into this fix now, will drop you an update soon.

**Comment by Thriven** [comment]
Any ETA on this? 
I'm facing the same issue and is kinda blocker, as I need the username to gather some more user information stored in an application database.

Thanks

**Comment by ahallensleben** [comment]
Same here. Please fix.

**Comment by msc4266** [comment]
Relax, isn't Azure B2C still in Beta? So don't expect anything is working. And, yes, an ETA when Azure B2C gets a "can be used in PROD environment" would be great ... 2021 .. maybe short delay?

**Comment by MoBo** [comment]
I parsed the token on my own and used the property `name`.
`
val jwt = JWTParser.parse(result.accessToken)
return jwt.jwtClaimsSet.getStringClaim(AccountRecord.SerializedNames.NAME)
`

**Comment by xyzwilliamxyz** [comment]
Hi!

we're also facing this issue. 

 MSALBusiness GetAccount: Account:
    ID: *****-b2c_1a_ab2csignin_dr
    ID Token: ****

**Comment by xyzwilliamxyz** [comment]
Hi!

we're also facing this issue using the latest MSAL version. And we're only using B2C as our identity provider. Any updates on this issue? @iambmelt 

Our info:

```
 MSALBusiness GetAccount: Account:
    ID: *****-b2c_1a_ab2csignin_dr
    ID Token: ****
    Auth: https://b2biamgbusdev.b2clogin.com/*****/v2.0/
    Username: Missing from the token response
```


converted token:

```
{
  "exp": 1587657639,
  "nbf": 1587654039,
  "ver": "1.0",
  "iss": "https://b2biamgbusdev.b2clogin.com/*****/v2.0/",
  "sub": "****",
  "aud": "****",
  "acr": "b2c_1a_ab2csignin_dr",
  "iat": 1587654039,
  "auth_time": 1587654039,
  "signInNames.emailAddress": "****+qa1@ciandt.com",
  "name": "Will aaa",
  "given_name": "Will",
  "family_name": "aaa",
  "extension_isMigrated": true,
  "extension_accountids": "[0000437782]",
  "country": "DO",
  "extension_tncaccepteddatetime": 1586289002,
  "tid": "*****",
  "at_hash": "****"
}```

**Comment by MarkusSchmidtPro** [comment]
One year ago ... I failed with Azure B2C,I downloaded the source code of this library and switched to Dart/Flutter ...

**Comment by iambmelt** [comment]
@xyzwilliamxyz @msc4266 This issue is external to the MSAL library and is tagged accordingly. Missing claims, esp those sourced from external identity providers cannot be fixed inside the library, they need to be sourced from the upstream B2C STS and any federation provider it delegates to

**Comment by Rob97** [comment]
Has this been addressed? We are still facing this bug :/

**Comment by AkashSaxenaSaviantConsulting** [comment]
Is this issue fixed?
facing the same issue in one of my applications. Trying to get the username but it gives an error.
