### ISSUE TITLE
MSAL should not export an "AppTheme" style.

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#440]
The [styles.xml](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/master/msal/src/main/res/values/styles.xml) has an "AppTheme" style. 
This causes a lint warning in our own styles.xml where we define an AppTheme, which is the default name for themes when making a new app. 
![image](https://user-images.githubusercontent.com/10838307/47746109-c16bc400-dc5b-11e8-9867-8f74df86496e.png)

The MSAL library should either:
1. Not define a theme
2. Define a theme with a name specific the MSAL so developers do not override it accidentally.

**Comment by iambmelt** [comment]
Hi @wyber -- I have addressed this feedback in #442. This fix will go out in an upcoming release.

Thanks!
