### ISSUE TITLE
PublicClientApplication.acquireToken calls should allow an activity OR fragment

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#441]
Both Activity and Fragments have an onActivityResult API. 

In our App we are making the acquireToken call from a Fragment. When we do so, we have to pass in the parent Activity. When the result is returned, we have to capture it in the Activity, forward to the Fragment, then forward that to PublicClientApplication.handleInteractiveRequestRedirect.

If MSAL allowed acquireToken(fragment,...) we would only have to forward from the Fragment to the Activity.

In our App we are using the SupportNavigationLibrary + multiple modules. Our Activity doesn't know the Fragments hosted in it at compile time which means we need to do reflection to see is we have the correct Fragment for forwarding the auth result.

The API would be simpler for app developers if they could pass the fragment/activity depending on where they are hosting the PublicClientApplication.

**Comment by shoatman** [comment]
@wyber - We're working on a change for the next release.  To remove the need for developers to implement onActivityResult.  We will capture the result in our own activity.  Would that sort of change address your concern?

**Comment by shoatman** [comment]
Correct.  On #1 and #2.  

Your questions are things that we've been testing to understand possible behaviors.  On the first question.... it won't be called earlier... it will be called when we have a result to report.  I believe the answer to your second question... is that the back button is interpreted as user cancel.  I'll double check on that though.

**Comment by saila-itc** [comment]
@shoatman How can access this early version with fragment compatibility?

**Comment by NLLAPPS** [comment]
I would like to have access to it too
