### ISSUE TITLE
Unable to perform cloud discovery

### ISSUE THREAD

**Issue by 4gus71n** [AzureAD/microsoft-authentication-library-for-android#443]
I just moved from `com.microsoft.identity.client:msal:0.1.0` to `com.microsoft.identity.client:msal:0.2.1` with the old version the authentication was working fairly well. However now I got an:

`Authentication failed: com.microsoft.identity.client.exception.MsalClientException: Unable to perform cloud discovery`

When I try to authenticate, I did some googling about this, and apparently I need to configure something on the server, thing is, that in the environment where I'm working that's not possible. 

My question is; There's some property that I can set so it works the same way as before?

**Comment by shoatman** [comment]
@4gus71n - You would see this error if the client was unable to connect to a specific server side endpoint.  It shouldn't happen unless the client was unable to reach that endpoint.

**Comment by 4gus71n** [comment]
Thank you very much for taking the time to reply @shoatman 

The puzzle puzzled itself out basically. I would like to say that I actually changed something, but from one moment to another, just started working.

Again, thanks for your time.

**Comment by iambmelt** [comment]
Thanks for the update @4gus71n - any further issues, please file or reopen this issue :)
