### ISSUE TITLE
Need preinstall Chrome in order to use the lib

### ISSUE THREAD

**Issue by wangyeking** [AzureAD/microsoft-authentication-library-for-android#447]
why the user need to install chrome in order to use the msal lib?
so if I have one feature in my application, and if the application run on an device that chrome is not installed, the function will not be able to work properly.

Is there any way to avoid the dependency?

**Comment by shoatman** [comment]
Which version of the library are you using?  This restriction has been removed in 0.2.0 and above.

**Comment by Glennmen** [comment]
@wangyeking I made a PR to the sample repo that uses `WEBVIEW` instead of default Chrome, maybe it can help you with your project: https://github.com/microsoftgraph/android-java-connect-sample/pull/19

**Comment by danieldobalian** [comment]
@Glennmen, thank you for contributing!

We're trying to drive usage towards `DEFAULT`, effectively using the device browser. There are some significant improvements in terms of SSO, end user UX, and also the way Android is going. In the latest versions of MSAL, `DEFAULT` will work on virtually all OEMs, OS version, and browser type. 

Can you help me understand why you prefer the use of `WEBVIEW`?

**Comment by danieldobalian** [comment]
I left a similar comment on your PR for the sample, let's follow up there. Closing this issue as the requirement to preinstall Chrome was removed after 0.2.0.
