### ISSUE TITLE
Duplicate AccountRecords Can be added to the cache (Need repro, B2C only?)

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#460]
Found during testing #458 

Multiple `AccountRecord` entries found in the cache for test B2C user - `home_account_id` and so forth match but the `environment` field does not appear to have been aliased correctly

![b2c_iss](https://user-images.githubusercontent.com/990063/48724561-608e3680-ebde-11e8-9396-bbf7ad79fd76.jpg)

**Comment by iambmelt** [comment]
`acquireTokenSilent` doesn't appear to be honoring aliasing

**Comment by MoBo** [comment]
@iambmelt Is it already included in version 0.22?

**Comment by iambmelt** [comment]
@MoBo Yep - this fix shipped in our last release

**Comment by MoBo** [comment]
I experienced this issue also in version 0.22

**Comment by iambmelt** [comment]
Specifically, behavior are you observing? An example result demonstrating the issue would be great just make sure not to include any sensitive information such as id_tokens (for a real user), access_token or refresh_token secrets.

You can also follow up with me via email if you'd like: brianmel@microsoft.com
