### ISSUE TITLE
Unable to login with ZTE stock browser

### ISSUE THREAD

**Issue by MoBo** [AzureAD/microsoft-authentication-library-for-android#465]
When I a try to login on a the ZTE phone the stock browser is not able to redirect to my app (MSAL version: 0.2.1). Are there known browsers which are currently not supported?

**Comment by iambmelt** [comment]
Hi @MoBo - Support for browsers _other_ than Chrome is still relatively new functionality for us; as a result, we're still improving our compatibility for a multitude of device/browser configurations.

Presently, there is neither a whitelist nor a blacklist of supported browsers.

The current browser selection functionality works as follows:
- The developer has two top-level options, `Webview` or `Browser` (Default).
- If `WebView` is chosen, MSAL will present an embedded `WebView` within an `Activity` controlled by the auth library
- If `Browser` is chosen, MSAL will launch the 1st available browser,
    * If the browser _supports_ `CustomTabs`, MSAL will use this browser's `CustomTabs`
    * If the browser does _not support_ `CustomTabs` MSAL will launch this browser externally (via an `Intent`, bringing the selected browser to the foreground.

Does the auth flow you are testing work when another confirmed supported browser (such as Chrome) is installed?

So we may investigate this further, can you provide the following information:
- A description of the flow you're implementing, what's expected, and what's happening
- Name and version of the browser
- Make/model of the device
- Logs, picture, video detailing the misbehavior (Remember, we're in public, so please be careful not to include personally/organizationally identifiable information such as access, id, or refresh tokens, app secrets, passwords, or similar)

**Comment by MoBo** [comment]
@iambmelt With Chrome it works.
On stock browser after successful login the redirect to the calling app fails.
Device: ZTE B2017G , Android 6.0.1
Browser: "Internet", Version Browser V3.37.21161107

**Comment by heidijinxujia** [comment]
[A list of browsers](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/3d76cb8e9b2f5a05b7a8aba6e57d905bf02e3109/msal/src/main/res/raw/msal_default_config.json#L22) is configured in the default configuration file, where you can find the known browsers which are currently supported. 
You can also customize the list in your configuration json file by adding the filed like this
```json
"browser_safelist": [
    {
      "browser_package_name": "...",
      "browser_signature_hashes": [
        "..."
      ],
      "browser_use_customTab" : true/false, 
      "browser_version_lower_bound": "..."
    }, 
]
```
