### ISSUE TITLE
[Cache] Allow for the arbitrary insertion of AccountRecords, IdTokenRecords

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#466]
See API outline below....

```java
public abstract class OAuth2TokenCache
        <T extends OAuth2Strategy, U extends AuthorizationRequest, V extends TokenResponse> {
   
     // ... Other methods, things here....

    /**
     * Saves the supplied Account and Credential in the cache.
     *
     * @param accountRecord The AccountRecord to save.
     * @param idTokenRecord The IdTokenRecord to save.
     * @return The {@link ICacheRecord} containing the Account + Credential[s] saved to the cache.
     */
    public abstract ICacheRecord save(final AccountRecord accountRecord,
                                      final IdTokenRecord idTokenRecord
    );
}
```

>Please note: I plan to enforce schema constraints through [`#isAccountSchemaCompliant`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java#L678-L691) and [#isIdTokenSchemaCompliant`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/cache/MsalOAuth2TokenCache.java#L725-L737)

**Comment by iambmelt** [comment]
@kreedula Please provide API feedback, suggestions

**Comment by kreedula** [comment]
Thanks @iambmelt . Looks good :shipit:

**Comment by iambmelt** [comment]
Closed in https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/c491e64f98a01866ad57efc4902c63210b13a577
