### ISSUE TITLE
Add nullability annotations to AuthenticationResult, other classes

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#471]
The Kotlin compiler will detect nullability of Java code if annotations are added:
 https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations

Nullability annotations also serve as a form of documentation for consumers of the API. Example:
`AuthenticationResult.getTenantId()` has a comment indicating nullability. An annotation would communicate this, as well as improve the Kotlin experience.  The other methods (uniqueId, etc) do not indicate if they are nullable/not in comments so I'm forced to assume they may all be null and must write code to handle null's. Adding `@NonNull` would let me treat the values as non-null.

**Comment by iambmelt** [comment]
Thanks for your feedback, @wyber! This looks related to a similar issue filed here: #462 

This is something we've been slowly adding around the project (for instance, most of `PublicClientApplication` has been annotated, with more in the works [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/commit/4a916ddbde8c2962a58be629b096e5945727ccb5)).

We'll continue to chip-away at these annotations as we work -- pull requests/external contributions are, of course, welcome as well.

Thanks for taking a look!

**Comment by iambmelt** [comment]
I am going to rename this issue to specifically be about `AuthenticationResult` for now so that this ask is specifically tracked.

The rest of this projects's files will most likely be annotated in a piecemeal fashion.

**Comment by iambmelt** [comment]
This is now an on-going part of our development process and will be resolved incrementally.
