### ISSUE TITLE
Support for AcquireTokenWithDeviceCodeAsync

### ISSUE THREAD

**Issue by awonglk** [AzureAD/microsoft-authentication-library-for-android#476]
Is there any chance that MSAL 2.0 for Android will support the device code flow (i.e. browserless) similar to what has already been implemented for Dotnet / Xamarin-Android version?

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/642

**Comment by danieldobalian** [comment]
Can you elaborate on the scenario and device you'd want to use this on?

**Comment by awonglk** [comment]
We're attempting to use this on a app developed on Android based head mounted display (with no keyboard, driven entirely with voice command), e.g. Vuzix M300
On app launching, we want to direct the user to login (via PC or mobile browser) with their username/password, in order sign-in to the application on the head mounted display.

Does that help?

**Comment by danieldobalian** [comment]
Yeah, that helps quite a bit. Device code flow is definitely the best UX for that scenario and device type. We'll sync on the request and get back to you. 

What's the timeline you're trying to build this app?

**Comment by awonglk** [comment]
We were hoping to implement this in the next month, but happy to take your guidance on how long this feature could take to enable

**Comment by danieldobalian** [comment]
Mind taking a call for us to learn more about what you're building? If so, can you shoot me an email at dadobali@microsoft.com and I'll find some time.

**Comment by iambmelt** [comment]
Support has been added via https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1103
