### ISSUE TITLE
ClientInfo cannot be null or blank

### ISSUE THREAD

**Issue by awonglk** [AzureAD/microsoft-authentication-library-for-android#477]
Have tested code sample with usual username/password flow which works as expected. However, when switching to "passwordless sign-in" for user, as described here:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-authentication-phone-sign-in

We are getting  the following MsalClientException exception, just after user approved the sign-in:

> D/AuthenticationActivity: Authentication failed: com.microsoft.identity.client.exception.MsalClientException: ClientInfo cannot be null or blank.

**Comment by kreedula** [comment]
Hi @awonglk , Thanks for reporting the issue.

Is this reproducible? If yes, Can you please share the logs of the incident?

**Comment by awonglk** [comment]
See attached..  error occurs on calling "getAuthInteractiveCallback()"

[Error log for MSAL Android - Passwordless Phone Sign-in.docx](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/2670412/Error.log.for.MSAL.Android.-.Passwordless.Phone.Sign-in.docx)

**Comment by iambmelt** [comment]
This should now be fixed in our `1.0.0` release, please open a new issue if you continue to experience problems
