### ISSUE TITLE
checkIntentFilterAddedToAppManifest() should print more clear log message

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [AzureAD/microsoft-authentication-library-for-android#479]
Right now logging is unclear. 

The desired Activity is present in AndroidManifest, however: `!MsalUtils.hasCustomTabRedirectActivity(mAppContext, mRedirectUri)`
does something more - it checks for validness of `mRedirectUri`, i.e. searches its value in intent filters also.

So, intent filter can be there, but redirectUris mismatch.

I suggest renaming the log message:
```
throw new IllegalStateException("Intent filter for: "
                    + BrowserTabActivity.class.getSimpleName() + " is missing or its redirectUri scheme/host does not match the redirectUri provided in PublicClientApplication constructor.  Please refer to the MSAL readme.");
        }
```

**Comment by iambmelt** [comment]
Thanks for the suggestion, @MichalDanielDobrzanski 

If you'd like to submit a PR for review, I'm happy to take a look. If not, this work will be evaluated and prioritized in an upcoming backlog review.

Thanks

**Comment by iambmelt** [comment]
Error messaging has been improved in https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/759 and release in `1.0.0`
