### ISSUE TITLE
MSAL and AndroidX are not compatiable?

### ISSUE THREAD

**Issue by Raysapps** [AzureAD/microsoft-authentication-library-for-android#492]
I am unable to use  active directory B2C authentication in my android project with AndroidX dependencies. The chrome browser shows  blank page when I click on Facebook sign in and I also noticed few log errors in android studio log cat  reported from msal lib.
The same project works fine without androidX dependencies.
Can someone suggest a workaround or a possible fix to resolve this issue?

**Comment by iambmelt** [comment]
Duplicate of #354 and #469. Issue is known but not yet prioritized for a fix.
