### ISSUE TITLE
Callback hits onError instead of onCancel()

### ISSUE THREAD

**Issue by alfetch** [AzureAD/microsoft-authentication-library-for-android#496]
When i'm using "authorization_user_agent" : "WEBVIEW", which i want to use - AuthenticationCallback returns onError when i press on the back button, navigating back. If i use DEFAULT it works fine. Anything also experiencing this, and is it something i can fix without forking the project? :)

**Comment by heidijinxujia** [comment]
Hey @alfetch thank you for filing this issue. Could you paste the logs/stacktrace here?

**Comment by heidijinxujia** [comment]
Did you press the "back" button on the web page or the "back" button on the device? @alfetch

**Comment by alfetch** [comment]
It is not really a crash so no stacktrace, it's a misbehaving way it works :) 

It's when you click back on the device you get onError instead of onCancel. BUT it works correct if it's set to DEFAULT - hence not using the webview.

**Comment by alfetch** [comment]
@heidijinxujia Any ideas? :)

**Comment by 4gus71n** [comment]
My workaround so far:
```
...
        // Yet another obscene workaround
        // https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/496
        if (exception?.errorCode == MicrosoftAuthorizationErrorResponse.AUTHORIZATION_FAILED) {
            providerCallback?.onCancelled()
        } else {
            providerCallback?.onError(exception)
        }
...
```

**Comment by heidijinxujia** [comment]
Let me have a look.

**Comment by heidijinxujia** [comment]
Fixed here https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/351
