### ISSUE TITLE
redirectUri should be able to be passed from code

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [AzureAD/microsoft-authentication-library-for-android#498]
Right now, the redirectUri is ONLY set from JSON config file. 

There is no option to set it via PublicClientApplication constructor, or later setter. 

We should be able to do so, as it defaults to msal<clientId>://auth when using option without JSON file. There are many scenarios when such configuration is not known on the compile time, but it is returned from configuration servers, so using static raw resource seems to be quite old-fashioned.

**Comment by shoatman** [comment]
@danieldobalian - We should think about allowing some aspects of configuration to be set at run-time.  We don't have a usability feedback label so applied "enhancement"

**Comment by MichalDanielDobrzanski** [comment]
@danieldobalian  Thank you for your feedback. You have also PublicClientApplicationConfiguration object for creating configuration, so a quite straightforward enhancement would be to let developer create its own config and pass it as a parameter to PublicClientApplication for instance.

This seems intriguing that there is not such amount of feedback for this. As configuring the MSAL library should be done freely and fully from the code. In my team of Android developers we try to use "Context-related" raw resources for configurations as a last resort. This is also motivated for the sake of having freedom of configuration and not relying upon static file. This has a benefit that library is more modular and easier to change/reconfigure.

**Comment by danieldobalian** [comment]
Thank you for the feedback! 

The configuration is quite new and before then we didn't allow the app to explicitly configure the Redirect URI.  On the surface, this seems like a good change - just a matter of priority. Let us sync internally and get back to you.

**Comment by SwagatRanjit84** [comment]
By default, what is the redirectURI? Where can we set redirect URI? @danieldobalian
