### ISSUE TITLE
Leak of Activity by ApiDispatcher

### ISSUE THREAD

**Issue by bwill** [AzureAD/microsoft-authentication-library-for-android#506]
When running with LeakCanary, it's detecting a leak

```
* GC ROOT static com.microsoft.identity.client.internal.controllers.MSALApiDispatcher.sCommand
* references com.microsoft.identity.client.internal.controllers.MSALInteractiveTokenCommand.mParameters
* references com.microsoft.identity.client.internal.controllers.MSALAcquireTokenOperationParameters.mActivity
```

A potential fix would be to clear out sCommand after `completeInteractive` is called

```
public static void completeInteractive(int requestCode, int resultCode, final Intent data) {
        sCommand.notify(requestCode, resultCode, data);
+       sCommand = null;
}
```

**Comment by bwill** [comment]
In my app, I'm creating `PublicClientApplication` using the application context, but I'm keeping it around after my sign in activity is destroyed (since I may be signing in from multiple activities).

I can probably also avoid this leak by scoping the PublicClientApplication to the activities that actually need to support signing in.

**Comment by MichalDanielDobrzanski** [comment]
Still happens in version 0.2.2. Any update on this?

**Comment by iambmelt** [comment]
Hi @MichalDanielDobrzanski - I'll be picking this up for investigation and will keep the status here updated. Thanks

**Comment by iambmelt** [comment]
PR with proposed fix open here: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/580

**Comment by iambmelt** [comment]
Merged. This will ship in an upcoming release.
