### ISSUE TITLE
Unable to find a matching configuration of project :common: None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by tyrant15** [AzureAD/microsoft-authentication-library-for-android#508]
I want to make a .aar release,but I get a failure.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':msal:compileLocalReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':msal:localReleaseCompileClasspath'.
   > Could not resolve project :common.
     Required by:
         project :msal
      > Unable to find a matching configuration of project :common: None of the consumable configurations have attributes.

Please help me,how can I make a .aar release

**Comment by iambmelt** [comment]
Hi @tyrant15 

Please consult the [build instructions](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-Contributing) for information on cloning and building MSAL.

As of 12/11/2019, you can compile a local release with the following configuration
![build_variants](https://user-images.githubusercontent.com/990063/70648129-46673200-1bff-11ea-91f6-b4e6bac3d987.PNG)
