### ISSUE TITLE
Proguard not supported by default

### ISSUE THREAD

**Issue by guperrot** [AzureAD/microsoft-authentication-library-for-android#513]
When using proguard + msal, the following rules are required to make the client work:

```
# This enum is accessed via reflection in common msal lib thus proguard removes it.
-keep public enum com.microsoft.identity.common.internal.ui.AuthorizationAgent  {
    *;
}

# Classes for below package is used by MSAL library. Ignore warning coming from the dependency.
-dontwarn com.nimbusds.jose.**
```

This rules can be packaged directly in the msal library and common library instead of asking developers to do so.

**Comment by mosess** [comment]
Another missing rule that was causing some problems to me:
```
-keep class com.microsoft.identity.common.** {
  *;
}
```

**Comment by guperrot** [comment]
But it would keep every single class from common with this global rule, defeating the use of Proguard altogether. The fix should be more targeted, what was the issue exactly @mosess?.

**Comment by mosess** [comment]
You're right, it should be more targeted.
I thought that maybe the recommendation of ADAL might be relevant for this library as well, as maybe more issues may arise in other functionalities when making the specific problem work.

The specific error was:
`class com.microsoft.identity.common.internal.providers.a.b.j declares multiple JSON   fields named c`

**Comment by guperrot** [comment]
Quick fix is likely target to `class com.microsoft.identity.common.internal.providers.**` which is narrower scope yet not ideal.

If you can look at the proguard mapping of your application and see what is a.b.j (or with the retrace tool) maybe we can figure out better rules.

**Comment by mosess** [comment]
I agree, that's not ideal.
The ideal solution would be Microsoft mapping the exact parts of the library that might break when using Proguard and define it similar to the ADAL library.
For now, I used the general solution just to make it work.

**Comment by joshfriend** [comment]
New versions of proguard and all versions of R8 will allow you to ship proguard rules inside of an AAR package. [Here's an example of how that is accomplished](https://github.com/JakeWharton/ThreeTenABP/pull/12)

**Comment by guperrot** [comment]
We can already do it in proguard, the Microsoft AppCenter SDK uses this already.

**Comment by guperrot** [comment]
This is what came up when fixing the rules when used in AppCenter:

https://github.com/microsoft/AppCenter-SDK-Android/pull/1149/files#diff-54abb45c98c994c8e22a56dc46f07a0b

This covers basic AAD B2C scenarios but you might want to apply that keep rules to every model or enum used via Gson.

**Comment by guillaume-tgl** [comment]
I have an issue with Proguard too when using MSAL v1.0.0:

```
java.lang.AssertionError: AssertionError (GSON 2.8.5): java.lang.NoSuchFieldException: DEFAULT
        at e.d.d.q.a(Gson.java:944)
        at e.d.d.q.a(Gson.java:892)
        at e.d.d.q.a(Gson.java:841)
        at e.d.d.q.a(Gson.java:813)
        at com.microsoft.identity.client.K.a(PublicClientApplicationConfigurationFactory.java:156)
        at com.microsoft.identity.client.K.b(PublicClientApplicationConfigurationFactory.java:110)
        at com.microsoft.identity.client.K.a(PublicClientApplicationConfigurationFactory.java:66)
```

**Comment by iambmelt** [comment]
@hamiltonha This is a documentation issue; we should document Proguard support and/or explicitly provide a config

**Comment by iambmelt** [comment]
Closed by #987

**Comment by joshfriend** [comment]
The original issue and successive comments have asked for (and described how to add) embedded proguard rules in the artifact. Adding those rules to the readme does not close this issue, please reopen.

**Comment by iambmelt** [comment]
Reopening until rules merge to dev

**Comment by iambmelt** [comment]
@joshfriend I've reopened this issue as opened #989 -- feel free to have a peek at this PR, I'll merge it in later this week if there's no more feedback. cheers

**Comment by iambmelt** [comment]
Thanks for review and input @joshfriend
