### ISSUE TITLE
Is the token_expiration_buffer working?

### ISSUE THREAD

**Issue by 4gus71n** [AzureAD/microsoft-authentication-library-for-android#514]
Hello,

I'm using an `Interceptor` from `Retrofit` to make sure that if the msal token is expired before doing a request, I refresh the token and then proceed with the request.

I need to do some testing over this, but the msal token expires every 60 minutes. Do we have a way to set the expiration time? I thought that was the role of the `token_expiration_buffer` attribute from the `R.raw.auth_config`, but I don't see that value being used anywhere within the library.

Is that option deprecated? Or it's supposed to do something else?

https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Configuring-your-app

**Comment by iambmelt** [comment]
Hi @4gus71n -- The duration of the token validity is configurable from the server side; please note that [this feature is in preview](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes).

As for testing the expiration of the tokens.... are you having an issue where expired tokens are being sent to the service? Our suggested pattern is to authorize the account using `acquireToken` and then, for subsequent requests, use `acquireTokenSilent()`. No interceptors or magic _ought_ to be required ;)

`acquireTokenSilent()` will check the app cache, returning the access token directly from it if it is not expired. In the event that the access token is expired, the refresh token will be used to acquire a new one. There's some caveats to this worth mentioning: certain events like password changes and expired refresh tokens will cause an `MsalException` to be returned in the `onError` callback of `AuthenticationCallback` -- these are expected errors.

The token expiration buffer's documentation here has gotten ahead of development -- this flag has not yet been implemented inside of MSAL (as of this writing 1/29/19). When it is eventually implemented, it will allow consumers of the library the ability to override the _caching_ behavior of MSAL (AKA, refresh tokens sooner or later than the service mandates). That said, **this functionality does not affect the behavior of the server** (AAD will not accept expired tokens) and is useful when accounting for things like clock skew and testing.

**Comment by 4gus71n** [comment]
Awesome, @iambmelt thanks for the info!

Just for the sake of clarity, I want to test the token expiration, mostly for the use case that the user is logged in within the App, then he sends the App to background and comes back to the App one hour after that.

Yeah, there's several approaches to refresh the auth token. I could call the `acquireTokenSilent()` when the App comes back, fire an Event of some sort through `EventBus` or something like that. But all those options are async, meaning that if the user tries to do a Pull-To-Refresh, or refetch data somehow as soon as he lands on the App, there's going to be a running condition between the `acquireTokenSilent()` and the requests to the backend.

My ideal solution for this is hooking the library with a `Retrofit` Interceptor, create an `AuthInterceptor` that is fired right before doing the request to the backend through `Retrofit`. This `AuthInterceptor` refreshes the jwt token if It's near expiration and then proceeds to perform the request to the backend.

Having a way to test this, locally, since I don't have access to the backend, would be great. For now I'm going to see if I can use Charles Proxy to rewrite the response after the login and inject a token that expires sooner.
