### ISSUE TITLE
Document format of IAccountIdentifier and how to use it in your app

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#521]
The IAccountIdentifier has a fairly unique format and may be useful for app developers to understand the format. For most, they will not need to extract specific pieces of data, but at the very least we should a) guide what is inside, b) how to use it, c) guidance on extracting pieces out of it (if encouraged at all).

Should be updated in IAccountIdentifier and IAccount (getters).

**Comment by iambmelt** [comment]
Just leaving notes for us to refer to in the future:

- `IAccount` exposes two types of `IAccountIdentifier`

```java
    /**
     * Gets the {@link IAccountIdentifier} for this Account -- this value is authority-specific.
     *
     * @return The AccountIdentifier.
     */
    IAccountIdentifier getAccountIdentifier();

    /**
     * Gets the home {@link IAccountIdentifier} for this IAccount -- for IAccount types with tenant
     * association[s], this value will be unique. Meaning, it's value is the same
     * in the IAccount's home tenant and in any guest tenants to which it may be associated.
     *
     * @return
     */
    IAccountIdentifier getHomeAccountIdentifier();
```
- Each of these values is backed by a `String` which can be dereferenced by calling `getIdentifier()`
- The value of this `String` is contingent on whether `getAccountIdentifier()` or `getHomeAccountIdentifier()` is called
    * `getAccountIdentifier()` will return the `oid` of the current account within the tenant used to acquire a token - this value will change from tenant-to-tenant. For caching, this maps to the `local_account_id`.
    * `getHomeAccountIdentifier()` will return the `oid` of the current account **within their home tenant**. This value should not change from tenant-to-tenant and maps to the `home_account_id` in the cache.
>Note: If the account was served from v2 and is an AAD account, the `IAccountIdentifier` returned by `getHomeAccountIdentifier()` will be an instance of `AzureActiveDirectoryAccountIdentifier` which exposes the `<tid>` in addition to the `uid`.
```java
new AzureActiveDirectoryAccountIdentifier() {{
                setIdentifier("<home_account_id>"); // this value is the same as <uid>.<utid>
                setObjectIdentifier("<uid>");
                setTenantIdentifier("<utid>");
}};
```

**Comment by iambmelt** [comment]
@danieldobalian My post doesn't cut-it as documentation, so when we're ready to document this or move this to a wiki, I left my post as a kind of starting point

**Comment by iambmelt** [comment]
`IAccountIdentifier` has been removed in `1.0.0`
