### ISSUE TITLE
MsalClientException on calling acquireTokenSilentAsync

### ISSUE THREAD

**Issue by GanapathiGarre** [AzureAD/microsoft-authentication-library-for-android#526]
Hi,
I am using 'com.microsoft.identity.client:msal:0.2.+' in my Android application with B2C configuration. 
It is working as expected when I was trying to login using com.microsoft.identity.client.BrowserTabActivity with my credentials and I am also getting my **accessToken** successfully to use for my server calls.
Before making any server call I am calling **acquireTokenSilentAsync** method to make sure the existing access token is not expired and also to get new token in case of its expiry. The method is returning same token in its call back response **AuthenticationResult** as long as it is not in expired.
But the problem here is, once the token got expired I am not receiving a new token. Instead receiving an exception saying 
**java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $**

Any help would be appreciated. Thank you.

For more info the below is the Kotlin code that I am using to get new token silently

fun getMSALAuthTokenSilently(){
    var accounts = App.loginClientAppContext?.accounts

    accounts?.let {
            
            App.loginClientAppContext?.acquireTokenSilentAsync(arrayOf(App.appContext?.resources?.getString(R.string.redirect_uri_scope)), it[0], object : AuthenticationCallback{
                override fun onSuccess(authenticationResult: AuthenticationResult?) {
                    //Storing ACCESS_TOKEN into preferences
                    authenticationResult?.accessToken?.let { token ->
                        if (token.isNotEmpty()){
                            Log.d("MSALSilent token succ:", token )
                        }else{
                            Log.d("MSALSilent token error:", "token is empty" )
                        }
                    }
                }

                override fun onCancel() {
                    Log.d("MSALSilent token error:", "cancelled" )
                }

                override fun onError(exception: MsalException?) {
                    when (exception) {
                        is MsalClientException -> {
                            /* Exception inside MSAL, more info inside MsalError.java */
                            Log.d("MSALSilent token error:", "MsalClientException "+exception?.message )
                        }
                        is MsalServiceException -> {
                            /* Exception when communicating with the STS, likely config issue */
                            Log.d("MSALSilent token error:", "MsalServiceException "+exception?.message )
                        }
                        is MsalUiRequiredException -> {
                            /* Tokens expired or no session, retry with interactive */
                            Log.d("MSALSilent token error:", "MsalUiRequiredException "+exception?.message )
                        }
                    }
                }
            })
    }
}

**Comment by danieldobalian** [comment]
Hey @GanapathiGarre,

This is interesting and sounds like something is going wrong. MSAL should automatically be able to refresh expired access tokens silently. 

Can you do us a favor and capture verbose logs of this taking place?  If you're not sure how to do this, there's [an article on logging](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Logging) that will help. This will help us take a look at what's happening under the covers and check our service side if something went wrong in the token refresh. 

Thanks!

**Comment by GanapathiGarre** [comment]
Hello Daniel,

Thanks for the response.

I have debugged the library code and found the reason for getting the issue.
(java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $)

Internally when the library is trying to fetch the new token it is receiving the **Html** response with the failed status code. And the library is trying to convert that response into the **JSON** string. So, it is throwing that exception.

I have found the reason for that failed response and fixed it by sending the **authority** parameter value in **acquireTokenSilentAsync** call. (Though I was setting authority type (I was using B2C) in **auth_config.json**, it was not considering that value for the silent token call).

Now it is working fine.

Thanks!

**Comment by vinayak214** [comment]
@GanapathiGarre  - How did you resolve this issue??i'm also getting the same error.

**Comment by eduardothiesen** [comment]
Same error here. And I'm already setting the authority.

**Comment by tajchert** [comment]
In my case fix to this was to:
- update MSAL to 4.0.0 (there were some fixed with ProGuard in that area in 2020 so might be an issue if you use old lib version)
- Call `acquireTokenSilentAsync ` with builder parameter `AcquireTokenSilentParameters.Builder()`
- Change authority from `account.authority`  to one that is in web panel of MSAL and in configFile of MSAL library (I declare it in Gradle flavor and use it in both: config file and in `acquireTokenSilentAsync` call.

I think 3rd point was critical for me to fix this.

**Comment by Yottster** [comment]
@tajchert thank you!
> Change authority from account.authority to one that is in web panel of MSAL and in configFile of MSAL library (I declare it in Gradle flavor and use it in both: config file and in acquireTokenSilentAsync call.

This was exactly what we needed to be able to perform a silent acquire for a scope under another resource. If the 404 would have been handled correctly we would have never found this issue and never figured that out.
