### ISSUE TITLE
Add method to synchronously acquire a token

### ISSUE THREAD

**Issue by joshfriend** [AzureAD/microsoft-authentication-library-for-android#544]
This would be similar to `acquireTokenSilentAsync`, but would instead return the `AuthenticationResult` _synchronously_ and throw the `MsalException` if there was an error.

This would be useful in scenarios where the work is already happening in the background, so an async callback just adds complexity to the code. For example, OkHttp request interceptors work synchronously, so if I want to obtain an auth token and add it to each request that is intercepted, I have to somehow figure out how to block on the `acquireTokenSilentAsync` method.

My hacky temporary solution uses rx to provide a blocking mechanism:

```kotlin
private fun PublicClientApplication.acquireTokenSilent(
  scopes: Array<String>,
  account: IAccount
): AuthenticationResult {
  return Single.defer {
    Single.create<AuthenticationResult> { observer ->
      acquireTokenSilentAsync(scopes, account, object : AuthenticationCallback {
        override fun onSuccess(authenticationResult: AuthenticationResult) {
          observer.onSuccess(authenticationResult)
        }

        override fun onCancel() {
          observer.onError(OperationCanceledException("acquireTokenSilentAsync() was canceled"))
        }

        override fun onError(exception: MsalException) {
          observer.onError(exception)
        }
      })
    }
  }.blockingGet()
}
```

**Comment by shoatman** [comment]
@danieldobalian - Let's discuss.  I'd like to be able to support this.

**Comment by joshfriend** [comment]
Here's the relevant implementation from ADAL: https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/800c89690fd8a1b5daf27ffcf04954cf3efce010/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L568-L714

**Comment by MichalDanielDobrzanski** [comment]
I also use the similar hack to obtain token in OkHttp interceptor, would be nice to support this.

**Comment by iambmelt** [comment]
Synchronous APIs added in https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/668

**Comment by 4gus71n** [comment]
Hellow @MichalDanielDobrzanski 👋 

I'm also trying to use the new synchronous API to have my Interceptor fetch the auth token. The thing is that now I'm getting the `MsalClientException: No refresh token was found.` exceptions. Have you tried using the synchronous API on your code or are you still using the Rx hack?

https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/570#issuecomment-561778662
