### ISSUE TITLE
Remove BrowserTabActivity from code and docs 

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-for-android#595]
Refer : https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/593

cc @heidijinxujia

**Comment by iambmelt** [comment]
Assigning to @kreedula @heidijinxujia for follow-up

**Comment by iambmelt** [comment]
@kreedula Can this now close with #593?

**Comment by iambmelt** [comment]
Closing as no-op: this is still in-use
