### ISSUE TITLE
Provide method to set PublicClientConfiguration 

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#610]
Hi, Is it possible to prove a public method to set PublicClientConfiguration?
In my particular case I would like to decide if DEFAULT, BROWSER or WEBVIEW used for authentication process

**Comment by shoatman** [comment]
Can you provide some additional information about what criteria you will use to decide upon Browser of Webview?  In general, for future looking scenarios we're trying to encourage the use of device browsers in order to be compatible with WebAuthn

**Comment by NLLAPPS** [comment]
I had 2 cases where it might be useful.

1- I was using Nightly version of FireFox mobile which failed to complete the redirection to auth Uri . This was about couple of versions before.

2- A user had Norton Link Guard which blocked redirect to auth without any info (just a white page)

I know these are not concerns of the SDK or my app but user  perceives it that way . To user, it is an issue with my app not

**Comment by NLLAPPS** [comment]
I had two cases where user perceived it as issue with the app. Having ability decide what to use might be useful.

1- Firefox Mobile Nightly was not able to redirect to local auth Uri after authentication couple of versions back

2- User had Norton Link Guard Android app which blocked redirection to local auth Uri in Chrome.

I know these are not concerns of the SDK or even my app but they are to the user.

**Comment by iambmelt** [comment]
@shoatman To follow up

**Comment by shoatman** [comment]
@hamiltonha - Please add this to the backlog for Android.  We need to establish the browser safe list as a web service.  In addition I think it's ok to support this scenario.
