### ISSUE TITLE
com.microsoft.identity.client.exception.MsalServiceException: AADSTS900144: The request body must contain the following parameter: 'grant_type'.

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#613]
Hi, I have suddenly started to receive the following error at PublicClientApplication.acquireToken 
 as soon as interactive authentication login completed.
I am using 0.3.1-alpha

`com.microsoft.identity.client.exception.MsalServiceException: AADSTS900144: The request body must contain the following parameter: 'grant_type'.`

No code changed. Was there some sort of server side change?

**Comment by shoatman** [comment]
Not that I'm aware of.  If you're logging... possible to provide the correlation id of the request.  I can look it up on the server.

**Comment by NLLAPPS** [comment]
It might be related to R8. I have minification enabled and using Latest Android Studio Beta. I am able to authenticate fine without pro guard.
I'll try to find what I need to exclude from minification

**Comment by NLLAPPS** [comment]
-keep class com.microsoft.** { *; }  solves the issue with R8/minification but it is too broad. Any ideas about what to keep?

**Comment by shoatman** [comment]
We'll take a look.  Thanks for raising this.

**Comment by NLLAPPS** [comment]
Thank you. I have narrowed it down to 
`com.microsoft.identity.** { *; }`
It is enough for me for now

**Comment by NLLAPPS** [comment]
I was able to drill up to
`-keep class com.microsoft.identity.common.internal.providers.microsoft.** { *; }`

**Comment by RDLemos** [comment]
Hello,
I got the exact same problem... this is the error I receive on the release version of my app. In the Debug version, it works fine:
05-30 18:11:56.205 22064 22064 D circuit : [MSConnectorManager] Authentication failed: com.microsoft.identity.client.exception.MsalServiceException: AADSTS900144: The request body must contain the following parameter: 'grant_type'.

**Comment by iambmelt** [comment]
Tagging as an enhancement to provide a ProGuard config / documentation thereabout

**Comment by iambmelt** [comment]
Closed by #987
