### ISSUE TITLE
Chrome Custom Tabs and broker interoperability

### ISSUE THREAD

**Issue by dcale** [AzureAD/microsoft-authentication-library-for-android#628]
I'm trying to get your sample app to work with MS Authenticator as broker. For my use case I require Chrome Custom Tabs, since nothing is happening when I click on the "Call Microsoft Graph" (and it was working before adding broker_redirect_uri_registered true). So I have two questions:

1. is the combination Chrome Custom Tabs and SSO for e.g. MS Office Apps using MS Authenticator as Broker compatible at all?
2. if yes, how can you enable broker support with MSAL?

**Comment by iambmelt** [comment]
In our current pre-release, MSAL does not support broker. This functionality is on the way; we'll be publishing a roadmap to our Wiki soon to give the broader community a sense of what's on the way.

Chrome CustomTabs or a WebView can be used by MSAL in standalone mode (ie _without_ broker).

When broker support is released, it will use a WebView to handle all interactive auth. For now, there are no plans to transition away from this as CustomTabs doesn't have the fine-grained APIs necessary to satisfy many of our Conditional Access scenarios
