### ISSUE TITLE
v1.16.3 incompatible with current version of Android Tools Library

### ISSUE THREAD

**Issue by CodyEddings** [AzureAD/microsoft-authentication-library-for-android#630]
Because of the [known requirement](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/574) for Android apps running v1.16.3 to use gson `v2.8.4` there's an incompatibility with common Android libraries that currently implement gson `v2.8.0`. For example, `com.android.tools:sdklib:26.4.1` implements `com.google.code.gson:gson:2.8.0`.

Rather than exclude gson at the project gradle level and explicitly add a dependency for gson `v2.8.4 `everywhere it was easier to just use `v1.16.2 `of your library that doesn't include the breaking change.

**Comment by iambmelt** [comment]
@CodyEddings Are you looking for [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-android)? Please file your issue there
