### ISSUE TITLE
Unable to pass in claims acquireToken() to get deviceID

### ISSUE THREAD

**Issue by rajasooryaKC** [AzureAD/microsoft-authentication-library-for-android#637]
I am trying to get the deviceId as part of the access token and i see that there are no public methods of acquireToken() that accepts claims though there is a private method that does. How do i get the device id?

also, can i use query parameters instead? if yes, what would be the key of the query parameter whose value should be the encoded value of {"access_token":{"deviceid":{"essential":true}

**Comment by iambmelt** [comment]
Hi @rajasooryaKC 

Support for extra claims is available as of our `0.2.2` release - code sample below:

```java
final ClaimsRequest deviceIdClaimsRequest = new ClaimsRequest();
final RequestedClaimAdditionalInformation deviceIdAdditionalInfo = new RequestedClaimAdditionalInformation();
deviceIdAdditionalInfo.setEssential(true);
deviceIdClaimsRequest.requestClaimInAccessToken("deviceid", deviceIdAdditionalInfo);

AcquireTokenParameters parameters = new AcquireTokenParameters.Builder()
    .startAuthorizationFromActivity(activity)
    .withScopes(SCOPES)
    .withLoginHint(loginHint)
    .withUiBehavior(uiBehavior)
    .withOtherScopesToAuthorize(extraScopes)
    .callback(getAuthenticationCallback(notifyCallback))
    .build();
```

Please note, however, that the `deviceid` claim requires use of Workplace Join through the broker which is not yet available for use with MSAL in General Availability. This is will be in our upcoming `1.0.0` release

**Comment by smudireddy** [comment]
Hi,
What scope parameters to use in the Interactive token request in iOS App to push the "Authenticator" goes directly for "Device Registration" service post user got authenticated ?

**Comment by dhirajhimani** [comment]
Tried 
val deviceIdClaimsRequest = ClaimsRequest()
        val deviceIdAdditionalInfo = RequestedClaimAdditionalInformation()
        deviceIdAdditionalInfo.essential = true
        deviceIdAdditionalInfo.value = "deviceid"
        deviceIdClaimsRequest.requestClaimInAccessToken("deviceid", deviceIdAdditionalInfo)

        return AcquireTokenParameters.Builder()
                .startAuthorizationFromActivity(activity)
                .withScopes(getScopes().toMutableList())
                .withClaims(deviceIdClaimsRequest)
                .withCallback(getAuthInteractiveCallback())
                .build()

But nothing seems working, unable to fetch devideid

**Comment by PMien** [comment]
FYI, requestClaimInIdToken works for me

            val deviceIdAdditionalInfo = RequestedClaimAdditionalInformation()
            deviceIdAdditionalInfo.essential = true

            val deviceIdClaimsRequest = ClaimsRequest()
            deviceIdClaimsRequest.requestClaimInIdToken("deviceid", deviceIdAdditionalInfo)

            val parameters: AcquireTokenParameters = AcquireTokenParameters.Builder()
                .startAuthorizationFromActivity(mActivity)
                .withScopes(mScopes.toMutableList())
                .withCallback(getAuthCallback(result))
                .withClaims(deviceIdClaimsRequest)
                .build()
            
            msalApp.acquireToken(parameters)

**Comment by PMien** [comment]
requestClaimInIdToken work for me. 

            val deviceIdAdditionalInfo = RequestedClaimAdditionalInformation()
            deviceIdAdditionalInfo.essential = true

            val deviceIdClaimsRequest = ClaimsRequest()
            deviceIdClaimsRequest.requestClaimInIdToken("deviceid", deviceIdAdditionalInfo)

            val parameters: AcquireTokenParameters = AcquireTokenParameters.Builder()
                .startAuthorizationFromActivity(mActivity)
                .withScopes(mScopes.toMutableList())
                .withCallback(getAuthCallback(result))
                .withClaims(deviceIdClaimsRequest)
                .build()

            msalApp.acquireToken(parameters)
