### ISSUE TITLE
Feedback Requested - Cache Schema Upgrades

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#642]
Hi Folks,

In order to upgrade an existing app from ADAL to MSAL we need to migrate the existing ADAL cache including any existing refresh tokens to the new cache schema.  In fact upgrade the schema of the storage may be something that's required from time to time as the library continues to evolve.  Unfortunately it may be necessary for us as part of schema upgrade to make additional token requests in order to fill in missing data.  

Looking for you feedback on whether upgrading the schema for storage should be an explicit operation in the library.  Perhaps where the library indicates that a schema upgrade is required and you then notify your users ahead of performing schema upgrade.  Or perhaps we integrate schema upgrade into an existing operation.  For example:

- Factory methods for constructing instance of public client applications
- Add to getAccounts (which is supposed to be called prior to making any token requests)
- Other options

Feedback on this?

Thanks

shane

**Comment by iambmelt** [comment]
@shoatman I am going to close this feedback request, as we've now shipped `1.0.0`. Feel free to reopen if I have closed this in error. Thanks
