### ISSUE TITLE
Feedback Requested - Deprecation of overloads for acquireToken and acquireTokenSilent

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#643]
Hi Folks,

Historically ADAL and MSAL, with the introduction of every new parameter to acquireToken and acquireTokenSilent introduce a new overload.  This resulted in dense and potentially complicated set of overloads that made it difficult for developers to know which one of the overloads they should use. Not to mention that code readability suffered.

In recent releases we introduced parameter objects for use with both acquireToken and acquireTokenSilent.  These parameters objects implement the builder pattern for constructing them and expose all of the potential parameters for use with acquireToken and acquireTokenSilent.  

We'd like to encourage the use of these parameter objects as this is where new parameters going forward.  

In addition we'd like to deprecate some of the more complicated existing interfaces.  Specifically we'd like to deprecate any acquiretoken or acquiretokenSilent overload with more than 4 parameters.  

Clearly this a breaking change, but it's one we'd rather take prior to the release of 1.0.  

Please provide and feedback and/or concerns that you may have.

Thanks

shane

**Comment by NLLAPPS** [comment]
Link to examples of this would be great

**Comment by joshfriend** [comment]
sounds like a relatively minor refactor :+1:

**Comment by shoatman** [comment]
@NLLAPPS - Here's a link to some of the acquireToken overloads we'd like to do away with: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/4e6c47303aac681c47ecc354fa50e17cd968bcde/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L594-L715

**Comment by NLLAPPS** [comment]
I am only using 

`  public void acquireToken(@NonNull final Activity activity,
                             @NonNull final String[] scopes,
                             @NonNull final AuthenticationCallback callback) `

and 

` public void acquireTokenSilentAsync(@NonNull final String[] scopes,
                                        @NonNull final IAccount account,
                                        @Nullable final String authority,
                                        final boolean forceRefresh,
                                        @NonNull final AuthenticationCallback callback)`

Whatever the change will be, -ideally- there should be a migration path and (hopefully) synchronous and async versions as well as ability provide all the necessary configuration in the code without creating any assets/files/json

**Comment by iambmelt** [comment]
@shoatman I am going to close this feedback request, as we've now shipped `1.0.0`. Feel free to reopen if I have closed this in error. Thanks
