### ISSUE TITLE
Feedback Requested: Synchronous Methods

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#644]
Hi Folks,

Looking for feedback on the introduction of synchronous methods.  We've received feedback from many of you that synchronous methods are simpler to integrate with and use.  To that end we are considering providing synchronous interfaces (interfaces that do no leverage callbacks) to return results to you.  Since many of operations involve network operations or cross process calls (invoking the authentication broker via bound service and/or Account Manager).  We will annotate these operations with `@WorkerThread` annotation.  In addition if we detect that they are being invoked from the UI thread we will immediately throw an IllegalStateException.  

These methods will be blocking calls.... 

I'd prefer not to add "Sync" to the end of method names, but if you have a suggestion on naming and or related to additional annotations please pass it along.

thanks

shane

**Comment by joshfriend** [comment]
Are you hesitant to call the method `acquireTokenSilent()` (no "sync" or "async" suffix, following the C# conventions) because someone might mistakenly use it because it shows up first in an autocomplete list? I think immediate punishment by exception at runtime is sufficient to help people in that situation realize they chose the wrong one.

One random other idea: I don't think this convention would fit well with your current api setup, but I like the way RxJava lets you convert observables into a synchronous getter with `.blockingGet()`:

```kotlin
acquireTokenSilentAsync(params).blockingGet()
```

**Comment by shoatman** [comment]
I just don't like using terminology from C# in java....

I haven't had the time to invest in this yet; however I've been considering whether or not we should introduce a fluent API such that we build and execute a command.  In that scenario... your suggestion based on RxJava would like something like:

acquireTokenSilent.withAuthority(asdf).withScopes(asdf).execute() //async (I guess could be get... but that overlaps with futures...)
acquireTokenSilent.withAuthority(asdf).withScopes(asdf).blockingGet() // sync

**Comment by joshfriend** [comment]
I like the way that the OkHttp library handles allowing a request to execute synchronously or asynchronously based on if you pass a callback to `execute()`. For MSAL this could look something like:

```kotlin
val params = AcquireTokenParameters.Builder()  // blah, blah...
val request = acquireTokenAsync(params)

// Async execution:
request.execute(callback)

// Synchronous execution:
request.execute()
```

**Comment by shoatman** [comment]
I think I like that the best in terms of not colliding with other existing async/blocking semantics.  Thanks @joshfriend

**Comment by rpdome** [comment]
Introduced in [MSAL v1.0.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.0.0)
