### ISSUE TITLE
Feedback Requested: Declined Scope Exception

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#645]
Hi Folks,

MSAL implements OpenId Connect (OIDC) under the covers.  OIDC requires that authentication servers (authorization servers) ignore unrecognized scopes.  See: [https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

The Microsoft Identity Platform is OIDC compatible meaning that per the OIDC spec that the authorization server must ignore unrecognized scopes.  

In addition MS Graph supports scopes that are only available to organizational users.  For example: Directory.Read.  Users signing in with Microsoft accounts do not have a directory to query.  Since this scope does not apply to Microsoft account users signing in with them will not be asked to consent to this scope and the scope will not be returned as part of token response.  

In order to ensure that clients do not assume, because they received an access token back that the access token contains all of the scopes that they requested.  We are considering introducing a DeclinedScopeException.  This exception would contain a copy of the acquireToken parameters object use to make the request trimmed to only include the scopes that were consented.  In addition you'll be able to get a list of the scopes that were declined in order to modify your user experience as necessary to reflect that you were not granted that scope.  Unfortunately at this time the service is not able to indicate why the scope was not granted.  

Thoughts on this scenario? Concerns?

Thanks

shane

**Comment by iambmelt** [comment]
Implemented here: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/748

Summary of implementation:
If a subset of scopes are granted, a `DeclinedScopesException` is emitted in `onError` with a populated `AcquireTokenSilentParameters` which can be used to initiated a silent request with the granted scopes

```java
/**
 * Exception class to indicate that one or more requested scopes have been declined by the server.
 *
 * Developers can opt to continue acquiring token by passing the silentParametersForGrantedScopes and calling
 * acquireTokenSilent call on this error.
 */
```
