### ISSUE TITLE
LocalMSALController is throwing the wrong exception.

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#646]
https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/4e6c47303aac681c47ecc354fa50e17cd968bcde/msal/src/main/java/com/microsoft/identity/client/internal/controllers/LocalMSALController.java#L213
```
                //TODO need the refactor, should just throw the ui required exception, rather than
                // wrap the exception later in the exception wrapper.
                throw new ClientException(
                        MsalUiRequiredException.NO_TOKENS_FOUND,
                        "No refresh token was found. "
                );
```

I rely on  publicClientApplication.acquireTokenSilentAsync throwing a MsalUiRequiredException to decide if users should be prompted for credentials. This bug means I am showing users an unrecoverable error dialog instead of trying to acquire the tokens with the interactive call.

**Comment by iambmelt** [comment]
Introduced in https://github.com/AzureAD/microsoft-authentication-library-for-android/commit/df49c3303a4426303ee8fc24ffa8e558c9ee8410

**Comment by iambmelt** [comment]
I'll pick this up for a fix

**Comment by iambmelt** [comment]
This issue should close when these changes are merged to `dev` _and_ `master`

**Comment by iambmelt** [comment]
Fix will ship in next release
