### ISSUE TITLE
Feedback Request: Known Authorities

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#647]
Hi Folks,

As part of configuration we've enabled developers to indicate to us a list of authorities that they know/trust.  We merge this with a query for Microsoft Identity Platform known authorities to produce a list of authorities to which client developers are allowed to make token requests.  The library wants to be sure that clients are not making token requests to potentially malicious security token services.  

In ADAL this was achieved using the flag setValidateAuthority.  Unfortunatley, this approach is not compatible with Azure AD B2C or other identity providers that may be supported in the future.  

A couple of questions relative to this:

- We enabled you to indicate via configuration whether a particular authority is the default authority.  This means that if you don't specify an authority when making the token request the default will be used.
- We're thinking about whether you may want to be able to lock down your app to only use a single authority via configuration.  For example: if you specify one authority and mark it as only = true.  We would not allow the use of any authority. 

Thoughts on both of these/feedback suggestions?

Thanks

shane

**Comment by iambmelt** [comment]
@shoatman I am going to close this feedback request, as we've now shipped this functionality in `1.0.0`. Feel free to reopen if I have closed this in error. Thanks
