### ISSUE TITLE
BROKER_RESULT_V2 sometimes dereferenced using getString, getSerializable

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#650]
See https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/649/files
Specifically, https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/649/files#diff-69531cb469279fd01f26e496f6dae4a2R241

and compare with: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/internal/controllers/BrokerMsalController.java#L905

Sometimes, `getString()` is being used, other times, `getSerializable()` -- we should be consistent on this

**Comment by rpdome** [comment]
Replaced with getString() in #651

**Comment by iambmelt** [comment]
Great, thanks @rpdome -- I'll close this.
