### ISSUE TITLE
Remove Account - Potential Issue

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#653]
Based on reading through the code.  I believe there is currently a bug in remove account specifically related to the scenario where:

- Account has been added locally (when no broker was installed on device)
- Broker is then installed
- removeAccount is called

It looks like in this scenario the code will attempt to remove the account from the broker cache rather than removing it from the local cache. 

https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/4e6c47303aac681c47ecc354fa50e17cd968bcde/msal/src/main/java/com/microsoft/identity/client/MultipleAccountPublicClientApplication.java#L268-L276

**Comment by heidijinxujia** [comment]
Yes, it is a bug. It should be 
```java
final RemoveAccountCommand command = new RemoveAccountCommand( 
         params, 
         MSALControllerFactory.getAcquireTokenSilentControllers( 
                 mPublicClientConfiguration.getAppContext(), 
                 params.getAuthority(), 
                 mPublicClientConfiguration 
         ), 
         callback 
 );
```

**Comment by heidijinxujia** [comment]
@rpdome Do you need a similar change for FLW?

**Comment by iambmelt** [comment]
@heidijinxujia @rpdome Also, will UI ever be needed for this `removeAccount` path? If yes, can't use silent controller, if not then no issue. I just remember there was some discussion about localizing messages around account removal

**Comment by rpdome** [comment]
@heidijinxujia Given the current requirement (AuthApp must be installed and provisioned as shared BEFORE any other apps), FLW flow shouldn't use local cache at all. Although for extensibility, it might be a good idea to perform local cache clean up when the mode is switched (from multiple -> single) for the very first time.

@iambmelt  The current FLW removeAccount hasn't migrated to Command yet. It's still using the old pattern - directly call the function inside the controller, set up a connect and make a function call.

**Comment by heidijinxujia** [comment]
The issue is fixed here 
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/654

**Comment by heidijinxujia** [comment]
Reopen this issue. Waiting for the approval for the PR.
