### ISSUE TITLE
[GA] MSAL hello() should not connect to brokers which cannot satisfy TenantProfile responses

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#659]
GA Broker (`3.0.0`) does not support `BrokerResult` with `TenantProfile` -- MSAL should not try to bind to broker versions whose responses MSAL cannot parse.

`hello()` should be updated to _reject_ connections from `brokerVer <= 3.0.0`

```java
If (brokerVersion <= 3.0.0) {
    // request not eligible for broker
} else {
    // Negotiate version & connect
}
```

**Comment by heidijinxujia** [comment]
Hey @iambmelt  have you started working on this? If not, I will assign this task to myself.

**Comment by iambmelt** [comment]
@heidijinxujia I've not started this

**Comment by heidijinxujia** [comment]
Resolved here https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/679
