### ISSUE TITLE
Feedback Requested: External Browser & Memory Optimization/Developer Settings

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#660]
Hi Folks,

It's possible, however unlikely, that when MSAL is using a browser (Chrome, Samsung Internet, etc...) to complete authentication.  That after launching the browser the App that initiated the aquireToken request could be killed.  

Here's the scenario in steps:

-	App calls MSAL acquiretoken using “BROWSER”
-	MSAL launches Chrome
-	Android OS due to memory pressure kills App
-	Authorization completes in Chrome
-	App is relaunched as a result of intent filter defined in app manifest
-	MSAL crashes because the state required to complete the request is gone

In order to ensure that MSAL can complete authentication and successfully return a result to the app.  We have a couple of options:

1. Change how callback provided for interactive requests (acquireToken)
  a) Remove callback from acquireToken method overloads and parameters object
  b) Return handleInteractiveRequest to the public API and have the app developer provide the callback 
2. User an intent to communicate the results of the authentication back to the app... rather than a callback.
3.  Other suggestions?

Thanks

shane

**Comment by NLLAPPS** [comment]
Please make sure you provide overloads for Fragments (platform and support) not just activity if you choose to go handleInteractiveReques route.

As a developer I would prefer intent extras,

**Comment by iambmelt** [comment]
Closing as outdated, no longer taking input on this
