### ISSUE TITLE
AndroidX Migration plan?

### ISSUE THREAD

**Issue by joshfriend** [AzureAD/microsoft-authentication-library-for-android#665]
Version 28.0.0 is [the last version of the classic support library that there will ever be](https://developer.android.com/topic/libraries/support-library/revisions#28-0-0):

> This is the stable release of Support Library 28.0.0 and is suitable for use in production. **This will be the last feature release** under the `android.support` packaging, and developers are encouraged to migrate to AndroidX.

This library currently uses the old support libraries instead of androidx (version `27.1.1`).

I am of the opinion that going AndroidX now (prior to a 1.0 release) would be the best solution, rip off the bandaid now instead of later.

**Comment by shoatman** [comment]
@joshfriend - I agree.  I'm following up with team to see who can pick this up.

**Comment by MichalDanielDobrzanski** [comment]
Hey @shoatman, any updates about migrating to AndroidX? Would it be a time consuming migration process?

**Comment by joshfriend** [comment]
> Would it be a time consuming migration process?

there's a auto-migration tool in android studio that works pretty well

**Comment by shoatman** [comment]
This is going to happen ahead of the next public release.  We actually performed a test run through and everything went relatively smoothly.  I'll update the thread once it's complete so that folks can try it out in the dev branch ahead of the release.

**Comment by rpdome** [comment]
Done in #702
