### ISSUE TITLE
MS Graph Scopes - Prefixed vs Unprefixed

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#672]
https://graph.microsoft.com/User.Read and User.Read are equivalents; however the Android caching logic does not know this.  As a result we experience cache misses.

**Comment by shahzaibj** [comment]
@shoatman Do you know of any other scopes where this can happen? I just tried with Office and Azure AD Graph and they don't accept a token obtain via `User.Read whereas MS Graph does`. So it looks it is just MS Graph, but do you know of any other scopes that are equivalent?

**Comment by shahzaibj** [comment]
I believe any scope of the form `https://graph.microsoft.com/<permission>` is equivalent to `<permission>` where permission is a valid permission defined by Graph. Would that be right @shoatman ?

**Comment by shahzaibj** [comment]
@Om83 we won't be fixing this issue as we believe this should be something that needs to be fixed on the server side. Keeping the issue opened here as we still want to track this issue and be aware of the status of it.
