### ISSUE TITLE
Unable to perform cloud discovery error from MSAL library of Android

### ISSUE THREAD

**Issue by uneeshkrishnan** [AzureAD/microsoft-authentication-library-for-android#676]
Dear Team,

One of our android app is using MSAL library (com.microsoft.identity.client:msal:0.2.+) to validate the user with Microsoft AD.
By following the given documentation, we are able  to validate the user and the user can successfully login to the system.
For testing purpose, we created a proxy server using **Burp Suite** and applied the proxy server details to the emulator.
With this proxy settings the user cannot login to the system, the library returning an error "Unable to perform cloud discovery".
If we disable the proxy its working fine.

Please help us on the same

**Comment by shoatman** [comment]
The library makes a request to a public endpoint on login.microsoftonline.com in order to pull down a list of known authorities (including their aliases and some metadata regarding which authority alias to cache with).  I'm guessing that the proxy is somehow blocking this request.

**Comment by uneeshkrishnan** [comment]
Thanks for your reply. Actually this issue was related to the Android OS security terms.
Android application with API level > 21 have some more security terms. So i think this makes the issue for me. When I tried with lower version of Android, It start to work.

**Comment by iambmelt** [comment]
Customer issue was resolved. Unclear what assertion is made regarding API 21 but we can reopen if another issue presents itself

**Comment by Keepertje** [comment]
I have this issue too #1090

**Comment by whiteLT** [comment]
@uneeshkrishnan Hi, did you managed to find a solution for API > 21 devices. I have the same issue. Old devices work fine.
