### ISSUE TITLE
getAccount api returns null

### ISSUE THREAD

**Issue by fistuk** [AzureAD/microsoft-authentication-library-for-android#684]
The getAccount API returns null even though the getAccounts API returns a valid account. Moreover the second parameter of the getAccount API marked as @Nullable but in fact, when calling this method with null authority exception is thrown:

Steps:
```
val oneDriveClient = PublicClientApplication(context, R.raw.auth_config)

/*** connect ***/

//throws exception - IllegalArgumentException: Invalid authority URL
oneDriveClient.getAccount(account.homeAccountIdentifier.identifier, null)

//returns null
oneDriveClient.getAccount(account.homeAccountIdentifier.identifier,"https://login.microsoftonline.com/common/")

// Prints the connected account successfuly
oneDriveClient.getAccounts {
 Timber.e("$it")
}
```

I'm not sure whether its a configuration issue or an SDK bug. 
version: com.microsoft.identity.client:msal:0.3.2-alpha

**Comment by heidijinxujia** [comment]
Hey @fistuk thank you for filling the issue! We have several API changes for the upcoming release. Please try the dev branch. 
The identifier parameter for getAccount is nonnull. Currently, getAccount can retrieve the IAccount object matching the identifier, which could be homeAccountIdentifier, localAccountIdentifier or username.

Please check the code [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/54ea7039791a9a101d382ba23e8838268163f55a/msal/src/main/java/com/microsoft/identity/client/MultipleAccountPublicClientApplication.java#L249).

**Comment by heidijinxujia** [comment]
Close the issue. Please feel free to reopen this issue if needed.
