### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by tarunchopra** [AzureAD/microsoft-authentication-library-for-android#690]
Getting below exception while trying to compile the code using following command from github command prompt- 
$ ./gradlew clean assembleLocalDebug publishToMavenLocal

**Exception:** 

> Configure project :msal
publishNonDefault is deprecated and has no effect anymore. All variants are now published.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':msal:compileLocalDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':msal:localDebugCompileClasspath'.
   > Could not resolve project :common.
     Required by:
         project :msal
      > Unable to find a matching configuration of project :common: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by heidijinxujia** [comment]
Please try to update/initialize the submodule. 
```
git submodule init
git submodule sync
```
