### ISSUE TITLE
[TrueMAM] IntuneAppProtectionPolicyRequiredException is missing when adapting token result

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#695]

**Comment by heidijinxujia** [comment]
Krishna is working on the related issue: unable to make a silent call from MSAL app to broker when getting the IntuneAppProtectionPolicyRequiredException.

**Comment by iambmelt** [comment]
@kreedula Can we close this issue? Is this now resolved?

**Comment by iambmelt** [comment]
Closed by #571
