### ISSUE TITLE
[Back Compat] getDeviceMode() throws NPE when old broker installed

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#703]
**Description**
getIntentForAuthService() returns null when trying to talk to older v1 broker
Which results with NPE when trying to connect the MicrosoftAuthService.

**Solution**
To fix this issue, we need to refactor the single account/FLW broker calls to align with ApiDispatcher and have the broker eligible checks as Multi accounts broker calls.

The telemetry events integration will also be benefit from this.

**Comment by heidijinxujia** [comment]
Dome is working in this fix.

**Comment by heidijinxujia** [comment]
I will make a separate PR for the refactor.

**Comment by rpdome** [comment]
FYI, wwhat I'm currently working on is that
1. We'll perform a broker eligible check before we get the s.
2. the check didn't pass, we will always return isSharedDevice = false. This means that any FLW operation will NEVER be called even if the device is registered as shared mode (as MSAL will never talk to broker).
