### ISSUE TITLE
GetAcccounts when calls broker to get to broker accounts needs to pass in valid enviroment

### ISSUE THREAD

**Issue by kreedula** [AzureAD/microsoft-authentication-library-for-android#708]
Currently its not passed here : https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/internal/controllers/BrokerAuthServiceStrategy.java#L224

and we have a todo on the callee side  here : https://github.com/AzureAD/ad-accounts-for-android/blob/dev/AADAuthenticator/src/msal/java/com/microsoft/identity/client/MicrosoftAuthService.java#L188

The ideal solution here is to get the enviroment for the instance metadata (cached may be) and use it.

@heidijinxujia assigning to you as part of your getAccount changes

**Comment by heidijinxujia** [comment]
K. Thanks, Krishna.

**Comment by Om83** [comment]
@kreedula Is this still an issue , can you please resolve appropriately?

**Comment by iambmelt** [comment]
Removing @heidijinxujia , assigning to @kreedula to follow up

**Comment by iambmelt** [comment]
Removing assignee as they're no longer contributing to the project
