### ISSUE TITLE
When talking to prod V2 broker, helloWithMicrosoftAuthService is throwing an exception that is hard to understand to app developers.

### ISSUE THREAD

**Issue by rpdome** [AzureAD/microsoft-authentication-library-for-android#712]
i.e. com.microsoft.identity.common.exception.ClientException: Parcelable encountered IOException reading a Serializable object (name = com.microsoft.identity.common.internal.broker.BrokerResult)

We should have a layer that transform these into an error code that the app can use to prompt user to update their broker apps.

(My suspect is that BrokerResult are different, hence Gson wasn't able to read it properly)

**Comment by rpdome** [comment]
need to convert result of hello calls back from BrokerResult to bundle.

**Comment by heidijinxujia** [comment]
Going to working on it this morning.

**Comment by rpdome** [comment]
Fixed with https://github.com/AzureAD/ad-accounts-for-android/pull/1123
