### ISSUE TITLE
link to "Get the app" are broken

### ISSUE THREAD

**Issue by heidijinxujia** [AzureAD/microsoft-authentication-library-for-android#716]
Currently when MAM is required, or device authentication is required, we show a button to “Get the app”, the link on this button starts with msauth://
 
e.g.
```replyUrl?/msauth/wpj?username={0}&app_link=https%3a%2f%2fplay.google.com%2fstore%2fapps%2fdetails%3fid%3dcom.microsoft.windowsintune.companyportal```
 
MSAL doesn’t appear to understand these links, and clicking the button does nothing.

**Comment by Om83** [comment]
@kreedula, Can you please take a look.

**Comment by kreedula** [comment]
Fix on the server side is on test slice, validated it. It should it prod soon. No changes required from the client side , so closing the issue
