### ISSUE TITLE
Is there a way to Clear previously signedIn user token.

### ISSUE THREAD

**Issue by vijayakumarideas2it** [AzureAD/microsoft-authentication-library-for-android#725]
When i try to Logout and login again.it  did not ask for password its logged in as a previous user.Please help me out with Ad logout functionality.

**Comment by iambmelt** [comment]
Similar issues:
- #185 
- #426

Hi @vijayakumarideas2it - Currently signing out does not clear the state of browser cookies (as this is sandboxed to Chrome and signing out would effectively remove SSO state for all apps/websites/etc sharing the system cookies jar. With that in mind, I've posted [some guidance here](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/185#issuecomment-517442017) while we continue to iterate on the user/dev experience.

I'll close this issue, please use #426 to post additional feedback

**Comment by emmano** [comment]
In the meantime I am using the following code to remove all user data and prevent automatic login after sign out. I am using "authorization_user_agent": "WEBVIEW".

(requireContext().getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager).clearApplicationUserData()

**Comment by jamiekeefer** [comment]
A kotlin version of above seems to work when placed in the performOperationSignout:

`var activityManager: ActivityManager = getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        activityManager.clearApplicationUserData()`
