### ISSUE TITLE
Request Codes are hard-coded

### ISSUE THREAD

**Issue by adrianhall** [AzureAD/microsoft-authentication-library-for-android#754]
The request codes for the local and broker webview returns are hard-coded to 1001/1002.  This is a problem since these are fairly common "user-space" request codes.  Other (fairly popular) libraries that don't hard-code request codes use these as defaults.  This causes ordering issues in `onActivityResult`

Request:
1) Add an optional parameter "baseRequestCode: Int?" to the PublicClientApplication that allows me to configure the base request code.
2) Document the number of request codes that you use and the default base request code (as an example, facebook login reserves "100" request codes, but allows you to set the base).

This allows me to easily support multiple providers (e.g. facebook, google, and microsoft) by feeding the request response to the appropriate onActivityResult.

**Comment by shoatman** [comment]
onActivityResult is no longer required in MSAL (>0.3).  This is bug in the readme which will be fixed on Monday.
