### ISSUE TITLE
Request: Add Special Exception Handling for B2C Password Reset Flows

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#757]
Currently if a B2C policy is invoked and the user clicks "Reset Password", MSAL throws an `MsalServiceException` with the following payload:

```
access_denied;AADB2C90118: The user has forgotten their password.
Correlation ID: 05d0dfe3-8a1c-4a61-8cb5-6d3d59de418b
Timestamp: 2019-09-16 23:51:28Z
login_hint: Missing from the token response
error_code: access_denied
```

Leaving it up to users of MSAL to detect this event using something more or less equivalent to the following to detect password reset
```
((MsalServiceException)exception).getCause().getMessage().contains("AADB2C90118")
```

This issue is a request to yield a new `B2CPasswordResetException` or similar to make handling these events less arduous

See also:
- [Documentation of password reset flows in B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-policies#linking-user-flows)

**Comment by iambmelt** [comment]
@shoatman Thoughts on the above?

**Comment by iambmelt** [comment]
> @iambmelt One question regarding the reset flow, do we need two ISingleAccountPublicClientApplication objects, one with a "normal" authority and the other one with password reset authority? I am working on a B2C login application where authority string is different for a reset flow. When this exception is detected _acquireToken()_ is called on the "password reset" application object. Is there a way to provide a different authority when _acquireToken()_ method is called and use a single ISingleAccountPublicClientApplication object?

@abdurahmanadilovic If you need to specify an authority that is declared in your `PublicClientApplicationConfiguration` other than the default, you can use [`fromAuthority()`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/TokenParameters.java#L175-L178) when building your `AcquireTokenParameters` to pass to `acquireToken()`

**Comment by abdurahmanadilovic** [comment]
this is my current auth_config_reset_password.json configuration file
```json
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "https://reacthello.b2clogin.com/tfp/reacthello.onmicrosoft.com/B2C_1_password_reset_mobile_native/"
    }
```

Do I just pass in authority_url to the fromAuthority() method?

**Comment by iambmelt** [comment]
New guidance is available on this:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended

I'll see that the public documentation is updated too.
