### ISSUE TITLE
Improve the logged error when the redirect uri (intent) cannot be found in the AndroidManifest

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/microsoft-authentication-library-for-android#762]
Ahead of GA, it would be helpful to log a useful message when the redirect uri cannot be found in the Manifest.

Log a **useful** error if either of the following conditions are met:
The Intent is missing OR if the redirect Uri does not match.

**Comment by rpdome** [comment]
I could add that as part of my PR. https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/759

Do you think the current exception message is detailed enough?

**Comment by shoatman** [comment]
@iambmelt and I we wondering whether we should just dump the entire XML for the intent filter... and fill in the scheme, host and path based on the package name and signature that we see when running the code.

**Comment by iambmelt** [comment]
@rpdome Let me know if you plan to implement this, otherwise I'll take this on this afternoon

**Comment by rpdome** [comment]
Closed in #759
