### ISSUE TITLE
Upgrade path from 0.3.xx to 1.0.xx

### ISSUE THREAD

**Issue by NLLAPPS** [AzureAD/microsoft-authentication-library-for-android#776]
Thank you for releasing version 1.0.0! It looks like a lot changed. It would be great if you could provide some sort of upgrade path for developers using 0.3 series. 

Perhaps https://github.com/Azure-Samples/ms-identity-android-native can be upgraded from 0.3 to 1 by creating a new branch so developers can see all changes in one place by checking changes between commits

**Comment by shoatman** [comment]
We're in the process of updating the docs... happening over the course of today.  Here's a link to the two new samples that we created:

Kotlin: (https://github.com/Azure-samples/ms-identity-android-kotlin)[https://github.com/Azure-samples/ms-identity-android-kotlin)

Java: (https://github.com/Azure-samples/ms-identity-android-java)[https://github.com/Azure-samples/ms-identity-android-java]

**Comment by shoatman** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-migration-guide-0.3.2-1.0.0

**Comment by iambmelt** [comment]
Thanks for providing docs in the wiki, @shoatman
