### ISSUE TITLE
Multiple Scope not working 

### ISSUE THREAD

**Issue by A86S** [AzureAD/microsoft-authentication-library-for-android#787]
I have registered my android app with azure portal and add the api permissions for yammer and microsoft user.read.

**note : app is also registered with yammer portal.**

 App auth is working fine if i have used single scope but it fails in case of multiple scope. 

cases : 

Working fine in single scope case 
`val SCOPES = arrayOf("https://graph.microsoft.com/.default") `

Not Working in multiple scope case 
`val SCOPES = arrayOf("https://graph.microsoft.com/.default", "https://api.yammer.com/user_impersonation")`

please suggest the way to achieve the solution.

**Comment by iambmelt** [comment]
Hi @A86S -- [Combining static and dynamic consent scopes is not supported](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#the-default-scope) -- you have a few options:

- Request separate tokens for these resources and use the specific for each request as necessary
- Use exclusively dynamic consent scopes
    - Note you can [request consent upfront](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/AcquireTokenParameters.java#L149-L152) if desired ([docs from dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#have-the-user-consent-upfront-for-several-resources), but same principles apply)

**Comment by A86S** [comment]
thanks @iambmelt
