### ISSUE TITLE
Allow passing of an object or string instead of a File to the PublicClientApplication creation methods

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-android#797]
I noticed today that the new factory methods from `PublicClientApplication` only support a `File` as a config value, e.g. `PublicClientApplication.createMultipleAccountPublicClientApplication(context, file)`.

However in our case we use the library dynamically for more than just one "configuration" (b2c, common, specific tenants, etc.). I would appreciate it if you could instead of passing a file, pass something different like:

- a string (json)
- a dictionary / dynamic object (if this exists in Java) 
- a stream (though I'd prefer the other 2 variants)

I think the availability to pass only a file is very restrictive & static, especially compared to the way it was done in the older versions.

**Comment by shoatman** [comment]
I"m not opposed to provide the ability to provide a string, json, etc.... 

With that said, I'm curious about how you intend to use this relative to specific tenants.  Outside of B2C there is no need to specify specific AAD tenants.

**Comment by Nasicus** [comment]
The use case is this I guess:

In our app we have the following login possibilites:
- normal login (will go to `https://login.microsoftonline.com/common`)
- b2c login (will go to `https://login.microsoftonline.com/tfp/ourb2ctenantname.onmicrosoft.com/B2C_1_SignInSignUpPolicy`)
- tenant specific login (from specific login pages for some clients) (will go to `https://login.microsoftonline.com/<clientId>`, note that we do NOT know all the tenant specific client ids in advance....)

**Comment by shoatman** [comment]
Got it... so your app will support multiple B2C tenants that will not be known at dev time.  For the AAD tenants (normal and tenant specific) you just need one configuration file.... you can pass in the tenant specific authorities as parameters to acquireToken and acquireTokenSilent..... 

Thanks!

**Comment by Nasicus** [comment]
Well we only have one B2C tenant, so if you can do `fromAuthority` (from the builder) and it will then replace `/common`  with `/<tenant-id>` I guess this would also be a solution. I didn't see that thanks.

However I still think it would be nice if you could pass something different than a `File` in there (just from the standpoint of dynamic usages).

Thanks for your response.

**Comment by shoatman** [comment]
We've had the same feedback from others.  The main reason we don't do this at the moment is that we're concerned about the library being tricked into navigating the user to a malicious STS (someone posing as a legitmate IDP... and collecting credentials.)  If the authorities being dynamically provided are known to you and verified by you... then that wouldn't necessarily be an issue.  I'll look at this more and am leaving this open for consideration and comment by others.  Thanks!

**Comment by asterehin** [comment]
We also require to have something different to just a file as there will be a a dynamic usage in our projects. iOS version of the library has a builder - would be great to have this option as well. 

@Nasicus  don't  quite see what you mean by "replace /common with /<tenant-id>" . It's smth we need as well, but what is your idea ? 
In my case client_id will be dynamic.

**Comment by Nasicus** [comment]
@asterehin 

I didn't test it, but as far as I understand you can use the static file (where you just have the config with `common`) and then when you do the actualy requests to `acquireToken` you pass as the `authority` (i.e. use the builder for `acquireAsync` with `fromAuthority`) your dynamic `clientId` it may work...

But I didn't test it yet :)

**Comment by MariusVolkhart** [comment]
We'd like to be able to build a `PublicClientApplicationConfiguration` programmatically and provide that.

We ship 2 different flavors of our app that both use intune. Using the current factory methods is a frustrating experience. Our 2 flavors share a client ID and have the same signing key, but have different package names. With the current factory methods requiring a JSON resource, we have to duplicate our entire JSON config into 2 different source sets.

This can easily apply to others too. For example, folks like those in #530 who use different client IDs. Or using multiple signing certs (debug, white label, etc).

To make matters worse, in our case, both the package name and certificate hash can be determined by MSAL at runtime. Developers already provide the appropriate `Context`. 

As an aside, letting us programmatically build the `PublicClientApplicationConfiguration` looks like it would also solve the "can't create client application on main thread" problems that we and others (see #1061 ) have run into.

**Comment by jdaltemus** [comment]
> 

Any updates?

**Comment by jdaltemus** [comment]
We have an Android App that uses local AD, so the custom just sets that up and uses the app. A few are trying to get rid of NTLM authentications, so we are considering MSAL, but we don't want to build a specific app for each customer. What are our options?

**Comment by photon-jasonnoe** [comment]
Hello, I'm currently implementing a B2C SingleAccountPublicClientApplication. Our system requires that the authority be built at runtime using dynamic data such as tenant name, authority host, and sign in policy to build the authority URL. I managed to get everything working with a regular PublicClientApplication, because there is a creation method provided that allows me to specify the clientID, authority URL, and redirect URI inline, and it provides back a PublicClientApplicationCreatedListener.

`public static void create(@NonNull final Context context,
                              @NonNull final String clientId,
                              @Nullable final String authority,
                              @NonNull final String redirectUri,
                              @NonNull final ApplicationCreatedListener listener)`

However, when I attempted to utilize the SingleAccountPublicClientApplication, it does not support the same creation method despite inheriting it from PublicClientApplication. This is because it delivers an "IPublicAccountClientApplication" instead of an "ISingleAccountPublicClientApplication in the onCreated interface.

I am able to make this work by writing all my dynamic data to a file on the user's system, and then providing that file reference to the SingleAccountPublicClientApplication.create() method. I would rather not be writing these details to file, and instead be able to just build dynamically like the base PublicClientApplication. Please let me know if you have plans to support this.
