### ISSUE TITLE
[Feature Request] Need an option to choose microsoft account [Account Chooser]

### ISSUE THREAD

**Issue by A86S** [AzureAD/microsoft-authentication-library-for-android#799]
library does not provide any process which list out the microsoft accounts [outlook, azure] while auth the user [ same functionality like google account chooser which provide short way to login with the already logged in user in gmail or play account]

**Comment by shoatman** [comment]
@A86S - Browsers including the default browser only allow one "Microsoft account" or "live id" to be in signed in at a time.  With that said, you can choose between work accounts (AAD accounts) and a single Microsoft account using Prompt.SELECT_ACCOUNT

**Comment by Om83** [comment]
@A86S , I am closing the issue based on the above response. Please feel free to re-open if additional clarification needed.
