### ISSUE TITLE
Documentation and sample request: AD FS support

### ISSUE THREAD

**Issue by homer-jay** [AzureAD/microsoft-authentication-library-for-android#802]
After hours reading the docs I've not been able to tell if this library supports connecting directly to AD FS, and if so, which versions of ADAL and which version of AD FS. This is very important when developing corporate apps as AD FS 2016 is still very common.

What I'd need as a developer:
- A sample android app showing how to connect to AD FS similar to the [JS equivalent](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/single-page-application-with-ad-fs). Or modifying the current sample with a few comments explaining how to do this (mostly where to pass the AD FS URL). Clarification is also needed on what version of ADAL should be used, as the current Android sample is using v1.14, but the library has evolved to newer versions (2.0.4 alpha as of today) which have a different API similar to MSAL when it comes to calling `acquireToken`.
- A new section in the docs explicitly explaining AD FS support, similar to the one in the C# library [ADFS support in MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/ADFS-support)

If however someone can quickly clarify these points in this issue I'd appreciate it very much.

**Comment by iambmelt** [comment]
Hi @homer-jay -- MSAL does _not_ support connecting directly to ADFS in our `1.0.0` release. This functionality may become available in later releases and will be included in the changelog when such capabilities become available.

For connecting directly to ADFS, [ADAL is the library you're looking for](https://github.com/AzureAD/azure-activedirectory-library-for-android).

I don't have a sample immediately available to which I can link you, however I can share some general pointers: to configure your ADFS authority url, supply the url to `AuthenticationContext` constructor. 

When registering your app in your ADFS instance, mobile applications are registered as native client apps (unlike JS) -- if you need more guidance than that, please file a question on StackOverflow and provide a link or alternatively [file an issue](https://github.com/AzureAD/azure-activedirectory-library-for-android/issues) if there is a gap in the documentation.
