### ISSUE TITLE
Unused Code?

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#814]
**Describe the bug**
Looks like this line of code is [unused...](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/13b0990f45a7af26840ebfd3981c9d3d968f0296/msal/src/main/java/com/microsoft/identity/client/internal/controllers/BrokerMsalController.java#L99)

**Comment by shahzaibj** [comment]
You're right, it is not being used. I can open a PR to remove it.

**Comment by shahzaibj** [comment]
@shoatman Fixed in #815
