### ISSUE TITLE
[Question] is it still possible to be able to use internal microsoft webpage in 1.0+

### ISSUE THREAD

**Issue by dharashahkenya** [AzureAD/microsoft-authentication-library-for-android#818]
In the version 0.2.1 i was able to authenticate a user using the webpage that would load in my own app itself (AuthenticationActivity) in the microsoft sdk . Is it possible to do that same with 1.0.+ version? May i please know the updated methods or documentation of how to use it ? I do not want to use the device browser at all, but rather in-app browser that you provided in 0.2.1.

Could anyone please point me in the right direction?

**Comment by iambmelt** [comment]
Hi @dharashahkenya -- Yes! This is still possible in 1.0.+ but is no longer the desired behavior. Please see the following documentation on configuring your `authorization_user_agent`

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#configuration-settings

**Comment by dharashahkenya** [comment]
@iambmelt , thank u very much for that link. I will try and update code to match the latest sdk then.
