### ISSUE TITLE
SSO Wiki link missing

### ISSUE THREAD

**Issue by nicolgit** [AzureAD/microsoft-authentication-library-for-android#833]
**Describe the bug**
page: https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Configuring-your-app

the text "Read more in the SSO wiki article" ha no direct link to SSO Wiki Article so it is not possible to know where to read more... :-)

**Smartphone (please complete the following information):**
N/A

**Stacktrace**
N/A

**To Reproduce**
N/A

**Expected behavior**
N/A

**Actual Behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by hamiltonha** [comment]
Hello, that article is out of date. Please refer to this doc for [configurating you app](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration). This doc about [brokered auth](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth) will provide an explanation for how to enable SSO through a broker. This doc about [enabling SSO on ADAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-android) also may provide some relevant information.
