### ISSUE TITLE
redirect_uri 与 签名校验问题

### ISSUE THREAD

**Issue by AlexMofer** [AzureAD/microsoft-authentication-library-for-android#846]
**Describe the bug**
使用keytool命令获取的签名与MessageDigest获取的签名不一致。
使用keytool命令：
```
keytool -exportcert -alias *** -keystore ***.jks | openssl sha1 -binary | openssl base64
```
获取得到的SHA1为：  
release alias: "EZGOxkKE4kEUAps55kNgvRZvsQk="
debug alias: "r2AoowJbNe3noUR8yoKWH28PIv0="

使用MessageDigest（采取自你们的校验代码）：
```
        final String packageName = context.getPackageName();
        try {
            final PackageInfo info = context.getPackageManager().getPackageInfo(packageName, PackageManager.GET_SIGNATURES);
            for (final Signature signature : info.signatures) {
                final MessageDigest messageDigest = MessageDigest.getInstance("SHA");
                messageDigest.update(signature.toByteArray());
                final String signatureHash = Base64.encodeToString(messageDigest.digest(), Base64.NO_WRAP);

                final Uri.Builder builder = new Uri.Builder();
                final Uri uri = builder.scheme("msauth")
                        .authority(packageName)
                        .appendPath(signatureHash)
                        .build();
                System.out.println("sig:" + signatureHash);
                System.out.println("url:" + uri.toString());
            }
        } catch (Exception e) {
            // ignore
            e.printStackTrace();
        }
```
获取得到的SHA1为：  
release alias: "Q5gsALBuu/L+a7xVbqcqFb0MZBI="
debug alias: "BB0WxpVdDHHe6ujKwQ6rviWa99Q="

因为你们的包签名校验，使用keytool是无法创建PublicClientApplication，直接崩溃。使用与你们校验算法一致的获取方式获得的包签名则无问题。能创建PublicClientApplication。虽然能创建了，但是通过创建的PublicClientApplication去登录，输入密码后会进入以下页面：  
![截图](https://raw.githubusercontent.com/AlexMofer/ProjectX/master/images/others/bug_msal_2019_11_28.jpg)

该页面中无论点击“继续”或者“取消”，只会关闭页面而无任何回调，且该页面也并不能提供很好的错误反馈。也无从获知为何会进入该页面。  
*程序Debug使用的是自己的Key Store，而非Android Studio的默认调试密钥*
*以上提到的四个签名哈希全都配置到了Azure Portal*
*程序所需的授权SCOPES为：https://graph.microsoft.com/Files.ReadWrite*
**这个版本不再考虑调起的Activity被回收的问题？**

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android Version:  API27
 - Browser: Chrome
 - MSAL Version: 1.0.0

**Comment by iambmelt** [comment]
@AlexMofer Unfortunately, we don't have project contributors who are able to read Chinese; if possible, can you provide a description of your issue in English?

**Comment by AlexMofer** [comment]
## Signature mismatch
If <YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE> means what get by keytool command. This <YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE> wont pass the check code.
keytool command:
```
keytool -exportcert -alias *** -keystore ***.jks | openssl sha1 -binary | openssl base64
```
your check code:
```
    // Verifies broker redirect URI against the app's signature, to make sure that this is legit.
    private void verifyRedirectUriWithAppSignature() {
        final String packageName = mAppContext.getPackageName();
        try {
            final PackageInfo info = mAppContext.getPackageManager().getPackageInfo(packageName, PackageManager.GET_SIGNATURES);
            for (final Signature signature : info.signatures) {
                final MessageDigest messageDigest = MessageDigest.getInstance("SHA");
                messageDigest.update(signature.toByteArray());
                final String signatureHash = Base64.encodeToString(messageDigest.digest(), Base64.NO_WRAP);

                final Uri.Builder builder = new Uri.Builder();
                final Uri uri = builder.scheme("msauth")
                        .authority(packageName)
                        .appendPath(signatureHash)
                        .build();

                if (mRedirectUri.equalsIgnoreCase(uri.toString())) {
                    // Life is good.
                    return;
                }
            }
        } catch (PackageManager.NameNotFoundException | NoSuchAlgorithmException e) {
            Logger.error(TAG, "Unexpected error in verifyRedirectUriWithAppSignature()", e);
        }

        throw new IllegalStateException("The redirect URI in the configuration file doesn't match with the one " +
                "generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.");
    }
```
My <YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE> by keytool command:  
release alias: "EZGOxkKE4kEUAps55kNgvRZvsQk="
debug alias: "r2AoowJbNe3noUR8yoKWH28PIv0="

My <YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE> by MessageDigest:  
release alias: "Q5gsALBuu/L+a7xVbqcqFb0MZBI="
debug alias: "BB0WxpVdDHHe6ujKwQ6rviWa99Q="

Use <YOUR_BASE64_URL_ENCODED_PACKAGE_SIGNATURE> by MessageDigest can pass the check code.

I add those 4 signature to my Azure Portal.

When I into this page: 
![截图](https://raw.githubusercontent.com/AlexMofer/ProjectX/master/images/others/bug_msal_2019_11_28.jpg)
no matter I click "继续" or "取消", it only close page, no callback to the launch authentication Activity.

## No more handle "onActivityResult" method.
Are you sure there is no problem when the launch authentication Activity saved instance state? Still can callback when the launch authentication Activity recreate?

**Comment by AlexMofer** [comment]
@iambmelt

**Comment by iambmelt** [comment]
Thanks @AlexMofer 

@hamiltonha FYI ^^

**Comment by iambmelt** [comment]
@AlexMofer 

Make sure the keystore you are using is same one using by Android studio to produce your `aar` or `apk` -- if you have a project specific keystore, you'll need to provide a path to that keystore when generating your signature hash.

I can report that Android and my command line agree as to what the signature hash is of my keystore

```
brianmel@brianmel-devbox MINGW64 /c/dev/android-complete/gradle (master)
$ keytool -exportcert -alias androiddebugkey -keystore debug.keystore | openssl sha1 -binary | openssl base64
Enter keystore password:  *******

1wIqXSqBj7w+h11ZifsnqwgyKrY=
```

My app config (see [source here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/src/main/res/raw/msal_config.json#L4)):
```json
{
  "client_id" : "4b0db8c2-9f26-4417-8bde-3f0e3656f8e0",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://com.microsoft.identity.client.sample.local/1wIqXSqBj7w%2Bh11ZifsnqwgyKrY%3D",
  "multiple_clouds_supported":true,
  "client_capabilities": "CP1",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount"
      }
    }
  ],
  "telemetry": {
    "pii_enabled": true,
    "notify_on_failure_only": false,
    "debug_enabled": true
  }
}
```

There is a [handy tool provided in the MSAL repo here](https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/dev/package-inspector) which can export the signature hash of an app installed on a device. You can cross reference this value against your configuration in the application and in the Azure Portal.

Here's a screenshot of our test app:
![Screenshot_20191218-143550](https://user-images.githubusercontent.com/990063/71129334-15a96e80-21a4-11ea-8677-899b10d0a6ce.png)

Hopefully this helps, let me know!

**Comment by AlexMofer** [comment]
@iambmelt 
We set the signingConfig in app build gradle, so the keystore cannot be the Android Studio default debug key.
```
...
    buildTypes {
        release {
            minifyEnabled true
            zipAlignEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            shrinkResources true
            signingConfig signingConfigs.release
            manifestPlaceholders = [crashlytics_enabled: "true", onedrive_package_signature_hash : "/Q5gsALBuu/L+a7xVbqcqFb0MZBI="]
        }
        debug {
            minifyEnabled false
            debuggable true
            signingConfig signingConfigs.debug
            manifestPlaceholders = [crashlytics_enabled: "false", onedrive_package_signature_hash : "/BB0WxpVdDHHe6ujKwQ6rviWa99Q="]
            ext.alwaysUpdateBuildId = false
            crunchPngs false
        }
    }
...
```
**The signature hash got by keytool command is not same as the signature hash got by the handy tool.**  
Maybe the openssl or base64 went wrong, but it doesn't matter, we use the signature hash got by code same as the handy tool, so that it can pass the check code, and launch authentication Activity.
But now the problem is that it **cannot call back**(AuthenticationCallback) when the page is closed.

**Comment by iambmelt** [comment]
@AlexMofer Have you checked the value is correctly set in your `AndroidManifest.xml`'s `IntentFilter`?

**Comment by iambmelt** [comment]
I would check the following 3 places for a mismatch:
- The Azure Portal: your defined app registration redirect uri
- The AndroidManifest.xml: [The IntentFilter defining the redirect](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/src/main/AndroidManifest.xml#L61-L63)
- Your config.json file ([sample here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/testapps/testapp/src/main/res/raw/msal_config.json#L4))

**Comment by AlexMofer** [comment]
@iambmelt 
if redirect uri in AndroidManifest.xml not same as config.json, it will crash, I test this. the config.json was download form Azure Portal. So the problem is not here.

**Comment by iambmelt** [comment]
@AlexMofer In that case, more logs/info is necessary to figure out what's going wrong.

Have you tried [our sample](https://github.com/Azure-Samples/ms-identity-android-java)? Does it work on your device? If yes, this would indicate an issue in your project configuration. If not, we'll need to troubleshoot for interoperability on your device/environment.

Please see this documentation on adjusting log levels, enabling logcat:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=android#logging-in-msal-for-android-using-java

I suggest setting a breakpoint in the [`LocalMsalController`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/internal/controllers/LocalMSALController.java#L73-L164) to try and capture the [redirect/response](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#successful-response) to compare to your `redirect_uri`

**Comment by AlexMofer** [comment]
@iambmelt Your sample is fine. At present, I have returned it to the old version. I will check the settings if I have time.

**Comment by iambmelt** [comment]
@AlexMofer Feel free to post back to this thread if you discover an issue in the library; otherwise I am going to assume that our sample unblocked your issue.

Thanks
