### ISSUE TITLE
Shared Preferences on Android are unencrypted

### ISSUE THREAD

**Issue by clindde** [AzureAD/microsoft-authentication-library-for-android#849]
On Android the tokens are stored in the Shared Preferences. These are unencrypted, so an attacker with local access to the device can abuse them.

**Comment by iambmelt** [comment]
Hi @clindde 

This is not correct. They are encrypted on disk by our [`StorageHelper`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java).

We store our built-in token cache using symmetric AES + RSA/ECB/PKCS1Padding wrapped keys with a AES/CBC/PKCS5Padding cipher and HmacSHA256.

**Comment by iambmelt** [comment]
For future reference, please report any security issues, suspected or confirmed, per the instructions in our readme.

[Report Security Issues in MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by clindde** [comment]
Ok, thanks for your reply.
But what is then stored in "/data/user/0/[com.my.application]/shared_prefs/com.microsoft.identity.client.accessToken.xml"?
Because this seems not to be encrypted.

**Comment by iambmelt** [comment]
> Ok, thanks for your reply.
> But what is then stored in "/data/user/0/[com.my.application]/shared_prefs/com.microsoft.identity.client.accessToken.xml"?
> Because this seems not to be encrypted.

I see! So, this is not an artifact of either MSAL or ADAL for Android. However, looking around, this appears to be an artifact of the [dotnet library](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/257eaceea9b6bd7f24d2bce6126a42f2fe6c33cd/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/android/AndroidTokenCacheAccessor.cs#L38). That library is maintained by a separate team.

I will follow up on this. Additionally, please feel free to reach out to me at brianmel@microsoft.com to share any other relevant findings.

**Comment by iambmelt** [comment]
This request is being tracked in here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1544
