### ISSUE TITLE
Add log for what type of cache is used (foci vs targetCache )

### ISSUE THREAD

**Issue by shahzaibj** [AzureAD/microsoft-authentication-library-for-android#872]
We currently have a log that indicates whether an app is foci or not. However, we do not have any log that indicates whether we end up pulling the record from the foci cache or not. This log is needed as we can still use the foci cache even if the app is not known to be foci as we fallback to use foci cache if the app is unknown i.e. we don't currently have a cache for the app.

**Comment by shahzaibj** [comment]
@kreedula I see that you are doing `Logs cleanup` in Q3. Is this something you want to pick up as part of that? 

cc: @iambmelt

**Comment by iambmelt** [comment]
@shahzaibj Feel free to add these logs at your discretion -- I can review and sign-off
