### ISSUE TITLE
Allow Sign-In with Alternate ID (non-email)

### ISSUE THREAD

**Issue by hypino** [AzureAD/microsoft-authentication-library-for-android#880]
Our organization has team members that do not have a corporate email address. These users sign-in using their employee ID, which is an alternate ID on their Active Directory account. This is setup in our organization to be allowed for login. When we go directly to our organization's login page, we can use this ID (with "Domain\" added).

Can this login method be supported? Currently, the user has to enter their email address first which will then forward them to our organization's login page. Of course, Microsoft cannot resolve a numeric ID alone, so this doesn't work.

**Comment by rpdome** [comment]
Hi @hypino 

Unless any specific authority is specified, MSAL will bring the user to the 'common' authority, which will perform an authority look-up based on the given login hint (email address).

You can specify a specific authority in MSAL configuration file.

i.e. in your configuration json file.
"authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "[YOUR_TENANT_ID_HERE]"
      }
    }
  ]

Thanks,
Dome

**Comment by hypino** [comment]
Hi @rpdome,

For clarity, here is the msal.json that I am using:

`
{
  "client_id" : "344834fc-c54f-43d1-9110-faa59367dba2",
  "authorization_user_agent" : "WEBVIEW",
  "redirect_uri" : "<redirect_uri>",
  "account_mode" : "SINGLE",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "<tenant_id>"
      }
    }
  ]
}
`

Even with the authority properly set, the application is first directed to the common authority.

**Comment by rpdome** [comment]
@hypino 

To further debug this issue, would you mind sending the following information to rapong@microsoft.com?

- Your json configuration file and your tenant ID.
- An email and its associated alternate ID (If you could provide a test credential, that would be great. if not, login hint should suffice).

Thanks,
Dome

**Comment by rpdome** [comment]
@hypino ino 

To further debug this issue, would you mind sending the following information to rapong@microsoft.com?

- Your json configuration file and your tenant ID.
- An email and its associated alternate ID (Login hint should suffice - no password needed).

Thanks,
Dome

**Comment by rpdome** [comment]
Hi @hypino,

Android MSAL is currently not supporting direct communication with ADFS (by going through common, we're federating with AAD). We have a work item for that (adding support for ADFS2019) in our backlog, but it's not yet picked up.

Thanks,
Dome

**Comment by rpdome** [comment]
Hi @hypino,

Android MSAL is not supporting direct communication with ADFS. As of now, any ADFS authentication will have to go through the common authority (AAD being federated with ADFS).

We do have a work item for this (adding support for ADFS 2019) in our backlog. 

Thanks,
Dome

**Comment by hypino** [comment]
Hi Dome,

Thank you for looking into this for us. We will await the new feature being added so that MSAL works with ADFS. We'll have to find alternate solutions in the meantime.
