### ISSUE TITLE
[Feature Request] Android shared_prefs should not be used with plain text.

### ISSUE THREAD

**Issue by awasilik** [AzureAD/microsoft-authentication-library-for-android#902]
Is your feature request related to a problem? Please describe.
Android app security is compromised by storing access and refresh token in SharedPreferences as plain text documents. Our pen testers team identified this issue as vulnerability which could potentially expose sensitive user data. We do not need admin access to retrieve those tokens.

Describe the solution you'd like
Tokens should be encrypted like in example github Secure Preferences

Describe alternatives you've considered
Tokens should not be stored in SharedPreferences, instead there could be used more secure place such as AccountManager.

Additional context
Tokens are now stored in:
/data/data/<package_name>/shared_prefs

com.microsoft.identity.client.accessToken.xml
com.microsoft.identity.client.refreshToken.xml

**Comment by iambmelt** [comment]
Hi @awasilik - This is actually a request of [Xamarin.Android](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1544) library; **this** library encrypts tokens on disk using the [`StorageHelper`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java) class using symmetric AES + RSA/ECB/PKCS1Padding wrapped keys with a AES/CBC/PKCS5Padding cipher and HmacSHA256.

Please see the following thread:
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/849

For future reference, please report any security issues, suspected or confirmed, per the instructions in our readme: [Report Security Issues in MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

This request is being tracked in here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1544
