### ISSUE TITLE
Sign-In Once for Multiple Applications

### ISSUE THREAD

**Issue by hypino** [AzureAD/microsoft-authentication-library-for-android#906]
I have a question regarding single-sign-on across multiple Android applications using this library.

**Use Case**
I am trying to write a suite of applications with the goal of having the user sign in one time and have access to all applications as a result. Part of having the applications remain relatively modular, they should know very little about each other with the exception of the authentication application which handles logging in and out of Azure AD.

**What I've tried**
My approach so far would be having a common library which provided a task for retrieving the current account (specifically calling `ISingleAccountPublicClientApplication.getCurrentAccount`), and proceeding if the account is not null, or redirecting to the login application if it is null. However, I've found that even if I have logged in, the current account is always null in all other applications (with the exception being the application that performed the login), even if the other applications are using the same namespace .

**Question**
Is single-sign-on across multiple different Android applications possible using this library? If so, what is the approach that one should take, and is it documented anywhere already that I may have missed?

**Comment by iambmelt** [comment]
Hi @hypino 

X-App SSO is supported in MSAL via [Brokered Authentication](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth) and via use of the [`BROWSER` authorization__user_agent](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#authorization_user_agent).

Brokered auth works basically like this:
- If your app is integrated with a Microsoft Authentication Broker (such as Company Portal or Microsoft Authenticator) you can get _passwordless_ SSO through calling interactive auth (via `acquireToken()`) in your app. "Passwordless" here means that the user will be prompted to select their account from a list of accounts available on the device which have been recently used. If the app requesting signing requires interaction with users such as satisfying an MFA challenge, the user will be prompted to satisfy that challenge.
    * Calling `getAccounts()` or `acquireTokenSilent()` will **not** work for any app that has never before called `acquireToken()` -- this is so that users may see which app they are signing-in to and so that they may agree to and Terms & Conditions and grant [or deny] any consent required by the OAuth flow

Using the `BROWSER` authorization agent leverages another mechanism entirely:
- If MSAL (in all of the applicable apps) is integrated with the browser then AAD will set a session cookie with the browser during authentication
- When subsequent apps prompt the user to authenticate interactively (via `acquireTokenSilent()`) they will be redirected to AAD to select their account - at this point AAD will detect the existing session cookie and, assuming there are no Conditional Access requirements preventing their login, the user will be able to sign-in without having to enter a password. Note that MSAL has the ability to _force_ users to enter their password by specifying the `Prompt.LOGIN` parameters to their `AcquireTokenParameters`

Hope this helps. I am going to close this issue as answered, feel free to post-back if you have further questions and we can reopen if necessary.
