### ISSUE TITLE
Allow WebView Zoom Toggle

### ISSUE THREAD

**Issue by arislomovic** [AzureAD/microsoft-authentication-library-for-android#908]
At the moment, there is no toggle to turn off the webview zoom feature and controls. 

Can we please work on adding that functionality?

**Comment by iambmelt** [comment]
Assigning @hamiltonha (this is a feature request)

**Comment by arislomovic** [comment]
I took . a crack at it 
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pulls

**Comment by rpdome** [comment]
Duplicate with https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/803
