### ISSUE TITLE
ADAL Error to MSAL Error mappings for migration

### ISSUE THREAD

**Issue by SwathyMothilal** [AzureAD/microsoft-authentication-library-for-android#912]
There is an error code returned via ADAL "AUTH_FAILED" for which I could not find corresponding error codes in MSAL.

If these errors are distinguished inside MSAL_SERVICE_EXCEPTION via description in userInfo, please let me know these descriptions as I could not find it in the documentation

And, how to distinguish the exception when the user is deleted and disabled? In ADAL, it is distinguished by the error description under "AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED".

**Comment by arislomovic** [comment]
@SwathyMothilal did you mean the constants inside the ADALError class from the AdalBrokerResultAdapter?

**Comment by shoatman** [comment]
I'm following up with the server team on what exactly is returned on the v2 endpoint as equivalents for the v1 errors.
