### ISSUE TITLE
How to intercept requests inside the WebView

### ISSUE THREAD

**Issue by enirsilvaferraz** [AzureAD/microsoft-authentication-library-for-android#913]
Hi,

I have a situation using MSAL lib where I need to intercept some clicks inside the WebView to take some actions.

For example, in the following screen, if the user taps the forgot password link, I want to intercept this click to take an action on the native app.

![image](https://user-images.githubusercontent.com/12086873/73598882-304d6200-451c-11ea-9830-7f5967805a53.png)

Probably, I will have more than one case like this one on the same screen.

How can I handle that using MSAL lib?

Thanks for this lib. :)

The same thing reported for iOS here -> https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/843

**Comment by shoatman** [comment]
This is not currently supported.  Possible to provide additional information why the behavior associated in the Microsoft Identity Platform provided UI is sufficient for your purposes.  Adding @hamiltonha for follow up on this request.

**Comment by janrk-ciandt** [comment]
@shoatman Probably it is because in our use case we are not using the complete SigninSignup journey on Azure B2C. We have a journey to each one of the steps (Signin, Signup and Forgot password). We do need that somewhat the link inside of a Login journey redirects the user to another journey and afterward the redirect URI is the one user originally called.

**Comment by shoatman** [comment]
@valnav - Is this something that you can help @janrk-ciandt with?  I don't think there is anything that the MSAL team can help with here, but i'm guessing that the B2C team may have some suggestions on how to enable your desired scenario.  I'm going to close this issue for now.

**Comment by valnav** [comment]
> @shoatman Probably it is because in our use case we are not using the complete SigninSignup journey on Azure B2C. We have a journey to each one of the steps (Signin, Signup and Forgot password). We do need that somewhat the link inside of a Login journey redirects the user to another journey and afterward the redirect URI is the one user originally called.

@janrk-ciandt - i wanted to confirm that you are in fact using B2C. Are you using user flows or custom policies? also including my colleague @JasSuri who may be able to answer as well.

**Comment by JasSuri** [comment]
Considering you are embedding links from one journey to another, i presume your are using[ Custom HTML](https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview) to embed these links. 

These links must be links back to your application, and include some indication of the action the user wanted to do (eg myapp.com/redirect/forgotpwd. The application should then handle this and initialise a new msal instance the appropriate authority for the policy you want to execute for the users action.

The links should not be directly to the "Run Now" auth link for a B2C policy.

**Comment by janrk-ciandt** [comment]
> > @shoatman Probably it is because in our use case we are not using the complete SigninSignup journey on Azure B2C. We have a journey to each one of the steps (Signin, Signup and Forgot password). We do need that somewhat the link inside of a Login journey redirects the user to another journey and afterward the redirect URI is the one user originally called.
> 
> @janrk-ciandt - i wanted to confirm that you are in fact using B2C. Are you using user flows or custom policies? also including my colleague @JasSuri who may be able to answer as well.

@valnav Yes. We are using B2C as well as custom policies.
