### ISSUE TITLE
Old claims being returned on acquireTokenSilentAsync response

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#915]
Hello!

I'm using MSAL and I'm facing an issue using the acquireTokenSilentAsync method provided by IMultipleAccountPublicClientApplication class. 

The issue I'm facing is that we have journeys which update the user data by calling the acquireToken, however when I call the acquireTokenSilentAsync passing the most recent account, I receive unupdated user claims, and debugging I can see it has the "acr" from our signIn policy, which from what I've seen should've been the one from the most recent account. At first, I thought there was something wrong with my code, but I checked with an iOS developer which is doing the same thing and it returns the most updated claims and "acr" from the most recent account.

What I'm doing:

```
val params = AcquireTokenSilentParameters
            .Builder()
            .withScopes(scopes)
            .forAccount(account)
            .fromAuthority(getCurrentAuthority())
			.withCallback(
                AuthenticationCallbacks(
                    onSuccess,
                    onFailure,
                    onCancel
                )
            ).build()
			
application.acquireTokenSilentAsync(params)
```
Can someone help with this?

**Comment by shoatman** [comment]
Is it correct to assume that you are using B2C?  If so, which authority are you using to update the user data?  Are you using the same authority when calling acquireTokenSilent?

**Comment by xyzwilliamxyz** [comment]
@shoatman Thanks for the reply.

> are using B2C?

Yes, I'm using B2C. 

> which authority are you using to update the user data?

I'm passing an authority named  **example.b2clogin.com/example.onmicrosoft.com/B2C_1A_AB2CProfileEdit_DR** to acquireToken. 

> Are you using the same authority when calling acquireTokenSilent?

Thanks to you I was able to make some progress. Before your reply I was getting the last account and using its attribute authority, which seems to be wrong since it's always something like this: **htpps://example.b2clogin.com/{clientId}/v2.0/** (should it be this way though?). 

Now I'm passing to acquireTokenSilent **exactly the same authority I passed to the last acquireToken call I made**, which in this case is the update profile authority, and it seems to be working fine. 

However, we have another authority which also updates the user data (B2C_1A_AB2COnboarding_DR), and for some reason, after calling this one it will always return it on acquireTokenSilent, even if I call the profile edit again and pass it to the acquireTokenSilent.

Do you know if it's being done correctly? Or maybe could this be a configuration related to the portal?


PS: placeholder config used in this post

**Comment by shoatman** [comment]
In the case of B2C each authority is completely separate.  Meaning that every account for every authority is also separate.  (This something that we're working with B2C service team to improve).  What are the parameters that you're passing to the silent calls?

**Comment by xyzwilliamxyz** [comment]
Hi @shoatman, thanks for your reply, after some close investigation I was able to find the root cause of this issue.
The issue is that at some moment, MSAL tries to fetch the cached account by passed by localAccountId. 

![image](https://user-images.githubusercontent.com/18970657/73806592-b1b92480-47a8-11ea-84c1-495350523df5.png)
 

However, this id is the same for all accounts.

![image](https://user-images.githubusercontent.com/18970657/73806607-b7166f00-47a8-11ea-9bd2-69e1d3f0c7fc.png)
 

so, instead of passing it, I made a change to pass homeAccountId, which seems to be unique.

I think it localAccountId was mistakenly used on this, I mean, there are some logs for target account not found and it's loggin homeAccountId instead of localAccountId.

` Logger.errorPII(
                    TAG,	                    TAG,
                    "No accounts found for clientId, homeAccountId: ["	                    "No accounts found for clientId, homeAccountId: ["
                            + clientId	                            + clientId
                            + ", "	                            + ", "
                            + homeAccountId	                            + homeAccountId
                            + "]",	                            + "]",
                    null	                    null
            );	            );`

Could you take a look at the PR I opened? By the way, do you think it's better to add a new method and remove the old one or keep both?

Thanks!

**Comment by shoatman** [comment]
Nice catch.  This is the inverse of the normal situation with Accounts for the rest of AAD.  I think this lookup logic needs to be specific to the type of authority.  Hence we may need some additional refactoring here.  I'm adding @iambmelt to assist in reviewing and working with you on a solution that will work for all authority types current and future.

**Comment by xyzwilliamxyz** [comment]
@shoatman Ok, thanks! I will be waiting.
