### ISSUE TITLE
WebView Url should only be loaded once per fragment lifecycle.

### ISSUE THREAD

**Issue by arislomovic** [AzureAD/microsoft-authentication-library-for-android#916]
Currently the LoadUrl function gets called onStart(), which is called every time the activity resumes. This is causing the webview Url to load repeatedly. It should retain its state and only load once.

**Comment by arislomovic** [comment]
I tried to fix this in the common Libs -
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/801

**Comment by shoatman** [comment]
@rpdome - Is this something that you can look at?

**Comment by rpdome** [comment]
Fixed in common.
