### ISSUE TITLE
Webview quickly displays an internet outage error message before closing the screen

### ISSUE THREAD

**Issue by enirsilvaferraz** [AzureAD/microsoft-authentication-library-for-android#921]
Hi guys.
Is there a way to not display this message in the webview when the internet turns off?

When we received the error callback indicating this error the webview has already loaded the standard message.

**To Reproduce**

1. Open a screen that has a button.
2. Turn off the internet.
3. Touch the button.
4. Webview to load the screen with the error message.
5. Webview is closed

**Expected behavior**
The webview needs to close without showing the error message.

**Actual Behavior**
The error is shown on the screen before the error callback

**Screenshots**

![image](https://user-images.githubusercontent.com/12086873/73777527-63843100-4768-11ea-9dea-1435e7ac49d9.png)

**Comment by shoatman** [comment]
We'll take a look at what's possible given that this is likely default webview behavior.  There may be an opportunity to intercept something though.

**Comment by shoatman** [comment]
@enirsilvaferraz - As we discussed on our call this morning.  Feel free to share pointer to code in your fork where you resolved this issue.  Thanks!

**Comment by iambmelt** [comment]
PRs here have merged to `dev` and hotfix branch
