### ISSUE TITLE
Adhere to the semantic versioning scheme

### ISSUE THREAD

**Issue by opt05** [AzureAD/microsoft-authentication-library-for-android#922]
**Is your feature request related to a problem? Please describe.**
Currently, the versioning scheme for the Android library isn't like other Android libraries and therefore causes a linting issue in Gradle as a `-hf1` build would designated as a prerelease build in [semantic versioning](https://semver.org/). 

This also breaks the `+` in version number. For example if we use `1.2.+`, gradle will use `1.2.0` not `1.2.0-hf1` as it sees that as a prerelease build. 
![image](https://user-images.githubusercontent.com/11445911/73949368-f388be80-48bf-11ea-9eff-7307ec34a217.png)

**Describe the solution you'd like**
Use [Semantic Versioning](https://semver.org/), so instead of `1.2.0-hf1` it should be `1.2.1`.

**Describe alternatives you've considered**
Google uses semantic versioning in their libraries; [Google Play Services](https://developers.google.com/android/guides/versioning), [AndroidX](https://developer.android.com/jetpack/androidx/versions), etc. and is the recommended way to version libraries.

**Additional context**
Here is a screenshot from the latest release `1.2.0-hf1` that Android Studio is linting: 
![image](https://user-images.githubusercontent.com/11445911/73948170-3e093b80-48be-11ea-91fc-049a5bc08996.png)

**Comment by shoatman** [comment]
@iambmelt @rpdome

**Comment by shoatman** [comment]
This seems to be a historical practice.  That I agree doesn't make sense.  We're going to fix this with the next release.  Which will be today/tomorrow or Monday.  Thanks

**Comment by iambmelt** [comment]
ACK - we'll take this feedback going forward. As @shoatman mentioned, this is a carryover from the ADAL versioning practice.

I'm going to close this issue; thanks for your feedback @opt05
