### ISSUE TITLE
MsalClientException: Sdk cancelled the auth flow as the app launched a new interactive auth request

### ISSUE THREAD

**Issue by ecramer** [AzureAD/microsoft-authentication-library-for-android#923]
**Describe the bug**
When using application.requireAuthToken or application.login the callback gets cancelled when the browser opens AND 'Don't keep activities' is enabled in the device developer settings

**Smartphone (please complete the following information):**
 - Device: Any
 - Android Version: Any
 - Browser [e.g. Chrome, Edge] Any
 - MSAL Version: 1.2.0

**Stacktrace**
```
com.microsoft.identity.client.exception.MsalClientException: Sdk cancelled the auth flow as the app launched a new interactive auth request.
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:51)
        at com.microsoft.identity.client.PublicClientApplication$9.onError(PublicClientApplication.java:1631)
        at com.microsoft.identity.client.PublicClientApplication$9.onError(PublicClientApplication.java:1621)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3$4.run(CommandDispatcher.java:341)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.microsoft.identity.common.exception.ClientException: Sdk cancelled the auth flow as the app launched a new interactive auth request.
        at com.microsoft.identity.common.internal.controllers.ExceptionAdapter.exceptionFromAcquireTokenResult(ExceptionAdapter.java:93)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:327)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**To Reproduce**

1. Turn on 'Don't keep activities' in the developer settings on your device
2. Try to sign in (reproducible in the app found at the [quickstart](https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-android))
3. Browser opens, you do your auth thing, hit continue
4. Browser closes, nothing happens

**Expected behavior**
Authorization should work

**Actual Behavior**
Authorization does not work

**Comment by shoatman** [comment]
@ecramer - Can you tell me more about your test scenario.  Are you expecting a user to abandon signing in and then return to in minutes, hours, days later?  Generally this setting is use to assess how an app behaves under memory pressure.

**Comment by ecramer** [comment]
It's not just memory pressure. There are lots of phones (new and old) that mimic this behaviour on a regular basis regardless of memory pressure. It is good practice to have your app function with and without this setting enabled.

**Comment by shoatman** [comment]
I'm trying to assess severity of this issue.  Do you have crash reports from a production app that you are trying to resolve or is this test pass completeness.  I understand the best practice aspect; however I've never seen this happen in practice on any device during testing.  Mostly because users who start signing in tend to complete it.  The problem in this case is related to the use of the default browser (separate app) for authentication.  This is actually the new best practice from Google...; however it does lead to challenges since we have state that needs to be verified on return from the other browser that we'd prefer not to persist for security reasons.

**Comment by ecramer** [comment]
> Mostly because users who start signing in tend to complete it
Not sure if this was clear but the user tries to complete it. They go to the browser, they select their email, click continue and when they are redirected back to the app, nothing happens. 

AppAuth also uses the custom tabs to do authentication in the browser and this is not a problem there. I take no issue with the opening of a browser. 

No one has experienced this problem in production yet. However we know we have users where save and restore flow has been a problem in the past. Examples of devices are: Zenfone, Alcatel, emdoor, Kyocera - I doubt you test on these because I know we don't - which is why we use the setting. We don't have a ton of users on these however, we have them.

**Comment by shoatman** [comment]
I can check the app auth code... i'm assuming they've chosen to persist the necessary security state (to prevent man in the middle attacks).  I'll discuss with the team again to see how we feel about doing this from a security perspective.

**Comment by shoatman** [comment]
From AppAuth... where they persist the state of the authorization request.  https://github.com/openid/AppAuth-Android/blob/master/library/java/net/openid/appauth/AuthorizationManagementActivity.java

**Comment by shoatman** [comment]
FWIW - I do understand your scenario.  I've just never seen memory pressure or "Weird" device behavior get in the way of completing authorization in the wild.  Microsoft has several apps using MSAL and we haven't received any crash reports related to this issue.  With that said, most continue to use embedded webview for reliability reasons.  Not all default browsers actually support redirection to apps on android devices.  Meaning that auth cannot complete for another more fundamental reason. Chrome is not installed on my devices.  We've actually discussed with Google creating a browser safe list that can be used to flag browsers and in some cases browser versions that are not compatible with this model.

**Comment by ecramer** [comment]
Might have missed this in the docs - is there a way to use an embedded web view instead? Definitely open to doing that. We've just been using the method outlined in the README which has defaulted to the custom tabs.

**Comment by shoatman** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration - See authorization_user_agent setting

**Comment by ecramer** [comment]
Awesome. I am absolutely going to give this a try. If it works, we'll just do that. Will provide an update when I know. Thank you!

**Comment by shoatman** [comment]
You are most welcome.  Thank you for taking the time to evaluate and provide feedback.  I'm going to followup with the team on this next week to see what their thoughts are.  I'll let you know where we get to on this.

**Comment by ecramer** [comment]
The webview does work with the setting enabled. Thanks again!

**Comment by iambmelt** [comment]
Closing as resolved
