### ISSUE TITLE
In acquireTokenSilent, getting "illegal_argument_exception" - authority is null or empty

### ISSUE THREAD

**Issue by SwathyMothilal** [AzureAD/microsoft-authentication-library-for-android#929]
**Describe the bug**
When I am trying to call acquireTokenSilent, getting an illegal argument exception even though the authority is mentioned.

**Comment by shoatman** [comment]
@SwathyMothilal and I discussed this over phone last week.  It seems when you don't provide an IAccount for forAccount builder parameter that you get the authority error message instead of missing account.

**Comment by shoatman** [comment]
@shahzaibj - Is this something that we can add to our existing tests to verify?

**Comment by shahzaibj** [comment]
Hey @shoatman , we have some tests [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/47776c254c2b21d959a60d5d1c896a4d793bb513/msal/src/test/java/com/microsoft/identity/client/e2e/tests/mocked/AcquireTokenMockTest.java#L265), we are not exactly asserting for the complete error message here, instead we are just asserting for the error code. I can update the tests to look for the descriptions as well.

I did actually debug through them to see what error message we are throwing in these cases and they actually seem to be right.

**Comment by shahzaibj** [comment]
@shoatman @SwathyMothilal These errors are thrown [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/47776c254c2b21d959a60d5d1c896a4d793bb513/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L1256).

@SwathyMothilal Can you provide more details about which Application Type (Single vs Multi Account) you are using and which overload of acquireTokenSilent you are calling?

**Comment by shahzaibj** [comment]
@SwathyMothilal could you also let me know what version of MSAL you are using?

**Comment by SwathyMothilal** [comment]
Hi, the MSAL version is 1.2.0 and it's a Single Account. I have got it now working with the overload below.

AcquireTokenSilentParameters acquireTokenSilentParameters = new AcquireTokenSilentParameters.Builder()
                                .fromAuthority(AAD_AUTHORITY)
                                .withCallback(getSilentAuthenticationCallback(callback))
                                .forAccount(activeAccount)
                                .withScopes(getAadScope())
                                .build();
                        iPublicClientApplication.acquireTokenSilentAsync(acquireTokenSilentParameters);

**Comment by shahzaibj** [comment]
That's great @SwathyMothilal, I'm just curious however why it wasn't working for you earlier. Can you tell me which overload you were using earlier when it wasn't working?

**Comment by shahzaibj** [comment]
Closing this as it is no longer an issue (See comments above).
