### ISSUE TITLE
Crash related to Redirect URL when app is published

### ISSUE THREAD

**Issue by nazmul32** [AzureAD/microsoft-authentication-library-for-android#931]
**Describe the bug**
In our current app, we used this library. We set the proper **signature hash** for generating **Redirect URL**. That was working fine until the app was released to **Google play**.

While uploading app to **Google play**, if there is **App Signing** by Google play is enable, then the app crashes while starting as the signature hash has been changed internally in there. Is there any way to add multiple **Redirect URL** for multiple key hashes. (As supported Google Sign In)

**Stacktrace**
Fatal Exception: java.lang.IllegalStateException: The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.verifyRedirectUriWithAppSignature + 472(PublicClientApplicationConfiguration.java:472)
       at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow + 518(PublicClientApplicationConfiguration.java:518)
       at com.microsoft.identity.client.PublicClientApplication.initializeApplication + 984(PublicClientApplication.java:984)
       at com.microsoft.identity.client.PublicClientApplication.<init> + 966(PublicClientApplication.java:966)
       at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init> + 78(SingleAccountPublicClientApplication.java:78)
       at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted + 864(PublicClientApplication.java:864)
       at com.microsoft.identity.client.PublicClientApplication$2.onTaskCompleted + 852(PublicClientApplication.java:852)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run + 180(CommandDispatcher.java:180)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6692(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)

Thanks. Any help will be appreciated.

**Comment by tanveer-preom** [comment]
Found the exact same issue on my end

**Comment by shoatman** [comment]
See if the information here helps: https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/MSAL-FAQ

**Comment by nazmul32** [comment]
Hi Shoatman,

I understood that part. Actually for debug and release APK both are fine. Actually recently Google play store has an opton to sign an app using its own unique key which restricts user to accidentally install a version over Google play app  from some unknown source. 

https://developer.android.com/studio/publish/app-signing#enroll

The point #1 in **Opt in a new  #app** there. I used that generated key. I have that generated hash there. Does Azure AD Microsoft login supports multiple release hash key? One thing we can do is using **Flavor** in Android. Is there any other option?    

Thanks.

**Comment by shoatman** [comment]
You can register multiple redirect uris in the Azure Portal for your app.  With that said you may wan to consider separate app registrations for development, production etc.... so that you can evaluate changes to your app registration in development ahead of release to production.

**Comment by nazmul32** [comment]
Thanks for prompt response. I saw there can be multiple redirect urls. But there is a JSON file we need to build an APK which can contains only one *redirect url*. What I understood, we need to publish APK on google play with that specific JSON file and unless it is internally released we have no other way to test its functionality. Sorry if I am missing anything. I will be glad if I can contribute in this project.

**Comment by tanveer-preom** [comment]
Hello @shoatman. The problem we are facing that we have to maintain 3 different json files with different redirect urls for 3 variants. One for debug, another for release and another for Google play console if "App Signing" is enabled there. This is creating a little overhead for us. Suppose we changed the json for google play console signing, then we cannot test it locally on our devices. All I am asking that can you manage the redirect url and the signature hash on manifest internally? User will upload the signature hash to the azure portal only and the sdk will handle the rest

**Comment by shoatman** [comment]
We've been exploring using build.config for this.... https://developer.android.com/studio/build/manifest-build-variables Would this approach alleviate your challenge?

**Comment by nazmul32** [comment]
Hi @shoatman, that sounds more like gradle flavor concept or build variant. Thanks for your response.

**Comment by tanveer-preom** [comment]
Hello @shoatman . Actually I agree with @nazmul32 . Using product flavour or manifest build variant will solve issue for debug and release variant. But we will still have problem with Google play "App Signing" . Actually this is the main problem. We cannot test this variant locally as the signature gets changed when .aab is uploaded to play store

**Comment by shoatman** [comment]
I could be wrong, but I thought that even when using google to sign your apk... that you could configure signing configs.... https://developer.android.com/studio/publish/app-signing#sign-auto
I'll try this out later today.

**Comment by nazmul32** [comment]
Hi @shoatman 

After investigating a bit more what was in the code it seems `PublicClientApplicationConfigurationFactor`, the methood `loadConfiguration()` reads config file
and other things like **redirect url**. We have `context` while calling this method. If we can use this

```
private static String getSignatureHash(Context context) {
        try {
            PackageInfo packageInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES);
            String packageSigningSha;
            Signature signature = packageInfo.signatures[0];
            MessageDigest digest;
            digest = MessageDigest.getInstance("SHA");
            digest.update(signature.toByteArray());
            packageSigningSha = Base64.encodeToString(digest.digest(), Base64.NO_WRAP);
            return packageSigningSha;
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        }
        return "";
    }
```

```
private static PublicClientApplicationConfiguration loadConfiguration(final @NonNull Context context, final @NonNull InputStream configStream,
                                                                          final boolean isDefaultConfiguration) {
        //.....................

        final String config = new String(buffer);
        final Gson gson = getGsonForLoadingConfiguration();

        PublicClientApplicationConfiguration publicClientApplicationConfiguration = gson.fromJson(config, PublicClientApplicationConfiguration.class);
        final String signatureHash = getSignatureHash(context);
        try {
            final String redirectUrl = generateRedirectUrl(context.getPackageName(), signatureHash);
            publicClientApplicationConfiguration.setRedirectUri(redirectUrl);
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        return publicClientApplicationConfiguration;
    }

    private static String generateRedirectUrl(String packageName, String signatureHash) throws UnsupportedEncodingException {
        return URLEncoder.encode("msauth://" + packageName + "/" + signatureHash, "UTF-8");
    }
```

Does this thing make **redirect url** dynamic? Sorry if you find it irrelevant.

**Comment by nazmul32** [comment]
If we can generate redirect url dynamically, all we have to add the signature hash to the Azure portal. Users do not have to set **redirect url** for each variant manually. (Seeing the pattern of redirect url and signature hash)

**Comment by rpdome** [comment]
@nazmul32 the redirect url needs to be injected in both manifest and the config file. Is your method covering both?

**Comment by nazmul32** [comment]
Hi @rpdome, 

I was not to able to test this. What I tried is to find from where the redirect url is set. I found this place from where the config file is read. My point was that if we can dynamically generate redirect url then our mentioned problem can be solved. It can be less coupled with manifest and/or JSON file both. Thanks.

**Comment by dusanjovanov** [comment]
> Hi @rpdome,
> 
> I was not to able to test this. What I tried is to find from where the redirect url is set. I found this place from where the config file is read. My point was that if we can dynamically generate redirect url then our mentioned problem can be solved. It can be less coupled with manifest and/or JSON file both. Thanks.

Hi @nazmul32 ,
How do you read the actual redirect uri that is being opened ? The LogCat doesn't show anything

**Comment by uniruddh** [comment]
Hi @shoatman ,

Here is my observations:

1) v1.0.+(Recommendate): App is crashing with following error, even though hash matches:
`The redirect URI in the configuration file doesn't match with the one generated with package name and signature hash. Please verify the uri in the config file and your app registration in Azure portal.`

2) v1.4.0: App isn't crashing but in logs we are seeing same error as above. 

Is there any stable version which works without any issue?

**Comment by uniruddh** [comment]
Hi @rpdome ,

Currently I'm on version 1.5.1 and it didn't crash. Yes, I have "/" before the path and hash is BASE64 encoded.

**Comment by rpdome** [comment]
@uniruddh Were you switching the keystore? I've run into an issue where Android Studio was using the previous (cached) keystore to build the app even when after I switched the keystore. If this is the case, "Invalidate Caches and Restart" will fix it.

You can also try with [our debug keystore in the sample app](https://github.com/Azure-Samples/ms-identity-android-java) and see if you still run into the issue. (This configuration allows the sample app to run out-of-the-box) You can use the Redirect URI value [here](https://github.com/Azure-Samples/ms-identity-android-java/blob/master/app/src/main/AndroidManifest.xml) and [here](https://github.com/Azure-Samples/ms-identity-android-java/blob/master/app/src/main/res/raw/auth_config_single_account.json)

**Comment by sudolibre** [comment]
@rpdome @shoatman i'd like to offer my opinions on the solution to this issue here. I'll start by reframing the problem:

There isn't a good developer story for google managed signing. [This is the officially recommended method for distribution](https://developer.android.com/studio/publish/app-signing#enroll) moving forward and should be considered a first class use case above the manual signing scenario the library and documentation seems to be geared towards currently.

The root disconnect between the library and the play store is the idea that there is one signature for the application. The way google managed signing works is that it verifies your signature when you upload the app and then resigns it with their own certificate for distribution. This means that a single app cannot work both locally and via the playstore.

There are many ways this could be solved but i'd like to suggest a simple solution:
Default to using the generating redirect URI and make the redirectUri property in the config file optional. In Azure portal it asks for the package name and signature hash from the user and generates the redirect URI for you. The app itself has access to both of these pieces of information and [already derives the redirect URI ](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/44b9414f3be233053f441435440db7fbcee312b0/msal/src/main/java/com/microsoft/identity/client/PublicClientApplicationConfiguration.java#L490)from the package name which is why we get this error if the user supplied redirect URI does not match. 

In addition rework the documentation to describe the managed signing as the primary use case. This would include downloading the certificate from the app signing section of the google play store and getting the hash from the downloaded file (e.g.
`openssl x509 -inform der -in deployment_cert.der -outform der | openssl sha1 -binary | openssl base64`). In addition it should describe a method for specifying the path for the intent filter in AndroidManifest at build time or just registering both:
```        <activity
            android:name="com.microsoft.identity.client.BrowserTabActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:host="com.microsoft.identity.client.sample.local"
                    android:path="/1wIqXSqBj7w+h11ZifsnqwgyKrY="
                    android:scheme="msauth" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                        android:host="com.microsoft.identity.client.sample.local"
                        android:path="/thisoneisdifferent="
                        android:scheme="msauth" />
            </intent-filter>
        </activity>
```

A bonus improvement would be not to require a config file at all and allow client code to supply the config.

**Comment by rpdome** [comment]
Thanks for the feedback @sudolibre 

Having the app generating the Redirect URI on the fly has a downside - it would bypass the 'early check' we put here and, if the app is not registered/configured correctly, the developer will be seeing the error down the line, and that error might not be as obvious.

I agree that we should definitely improve our document to take both 'debug' and 'release' signature hashes into account. cc: @hamiltonha

**Comment by sudolibre** [comment]
> Having the app generating the Redirect URI on the fly has a downside - it would bypass the 'early check' we put here and, if the app is not registered/configured correctly, the developer will be seeing the error down the line, and that error might not be as obvious.

I'm not sure that I know what you mean when you refer to the 'early check' but when I saw this error it was when I tapped login and it didn't work. I look at the logs and every time I tap login it logs this error and that's how I found myself here. If you didn't have this check then you would get a redirect URI mismatch error in the response from the server. If i'm understanding everything correctly then I wouldn't have gotten this error much earlier only the time it takes to make a network call. This would make the DX consistent with the iOS, .Net, and JS MSAL libraries as well. Just sharing my experience i'll respectfully butt out now :-D

**Comment by uniruddh** [comment]
Hi @rpdome ,

Apologies for delayed response and thanks for your help. I finally figured out the actual issue. it was failing because of unencoded `redirect_uri`. It is working fine with encoded redirect uri.

**Comment by DivyaYadav25** [comment]
@uniruddh how did you encoded the redirect URI?

**Comment by DivyaYadav25** [comment]
Step 1: 
`{
  "client_id" : "value",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "value",
  "account_mode" : "SINGLE",
  "broker_redirect_uri_registered": false,
  "authorities" : [
    {
      "type": "AAD",
      "authority_url": "value"

    }
  ]
}
`
Step 2: Go to Google play console -> App Signing -> App Certificate -> download it
Step 3: Go to Azure Portal -> App Registrations -> Certificates and Secrets. Upload the file there.

This solution does work!

**Comment by mateohervas** [comment]
> Step 1:
> `{
> "client_id" : "value",
> "authorization_user_agent" : "DEFAULT",
> "redirect_uri" : "value",
> "account_mode" : "SINGLE",
> **"broker_redirect_uri_registered": false,**
> "authorities" : [
> {
> "type": "AAD",
> "authority_url": "value"
> 
> ```
> }
> ```
> 
> ]
> }
> `
> Step 2: Go to Google play console -> App Signing -> App Certificate -> download it
> Step 3: Go to Azure Portal -> App Registrations -> Certificates and Secrets. Upload the file there.
> 
> This solution does work!

It worked like a charm!! thank you very much, you saved me!

**Comment by rpdome** [comment]
> Step

Hi @DivyaYadav25,

The reason you weren't seeing this issue is that you essentially opt out from using the Broker, and that means the check wasn't kicked in. (Broker uses app's package name and signature hash to verify the calling app, therefore we have this check in place).

By opting out of the Broker, your user will not get [single sign-on](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth).

Thanks,
Dome

**Comment by rpdome** [comment]
> > Having the app generating the Redirect URI on the fly has a downside - it would bypass the 'early check' we put here and, if the app is not registered/configured correctly, the developer will be seeing the error down the line, and that error might not be as obvious.
> 
> I'm not sure that I know what you mean when you refer to the 'early check' but when I saw this error it was when I tapped login and it didn't work. I look at the logs and every time I tap login it logs this error and that's how I found myself here. If you didn't have this check then you would get a redirect URI mismatch error in the response from the server. If i'm understanding everything correctly then I wouldn't have gotten this error much earlier only the time it takes to make a network call. This would make the DX consistent with the iOS, .Net, and JS MSAL libraries as well. Just sharing my experience i'll respectfully butt out now :-D

That is a fair point @sudolibre. Thanks for the feedback. I'll discuss with the team on how to improve this experience (most likely we'll have to touch other code to - not just MSAL). Will keep you updated.

**Comment by rpdome** [comment]
> We're having a similar issue, we're re-signing the app with a cert that we do not have access to at build time, so the sighash is being altered, thus the configuration is bad. Anyone actually figured out a work around to the altered sighash?

Hi @rwrife, 

Is it possible to use [the following code](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/44b9414f3be233053f441435440db7fbcee312b0/msal/src/main/java/com/microsoft/identity/client/PublicClientApplicationConfiguration.java#L493) to print your sighash to a log file? (i.e. generate a prod-signed build just for this purpose.)

Thanks,
Dome

**Comment by Maddumage** [comment]
@DivyaYadav25 Your solution worked perfectly!!! Thank you so much. You save my time

**Comment by RoarGronmo** [comment]
1. Has anyone some kind of "blueprint" on how to extract the hash and path when the AAB is uploaded into Google Play (good enough with a message on the screen on the device).

2. Have any seen if there are differences in the hashes on the different APKs generated from the AAB ?

RG

**Comment by SFocus** [comment]
@DivyaYadav25 what hash should I use in this decision? The one generated by my release key or the key signed by Google? (I'm using aab format and google sign my app) I'm not able to debug the production app because can't log in.

**Comment by DivyaYadav25** [comment]
> @DivyaYadav25 what hash should I use in this decision? The one generated by my release key or the key signed by Google? (I'm using aab format and google sign my app) I'm not able to debug the production app because can't log in.

Hash would be the release key that you’re generating by code.

**Comment by DivyaYadav25** [comment]
@SFocus 
Hash would be the release key that you’re generating by code.
