### ISSUE TITLE
Single Account App Login Duration

### ISSUE THREAD

**Issue by nfgallimore** [AzureAD/microsoft-authentication-library-for-android#937]
After the user signs in for the first time on a Single Account App, how long will I be able to get their account using?

`mSingleAccountApp.getCurrentAccountAsync()`

Basically we are looking to only have the user sign in once. This is a service device.

**Comment by shoatman** [comment]
The account is in the cache.  It will be there until you remove it.

**Comment by shoatman** [comment]
If the broker is in use it will be there until you remove it or if the user removes the account from the device via Account Manager (Settings / Accounts)

**Comment by nfgallimore** [comment]
@shoatman Following this guide: https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth it seems that the only thing I have to do is add this `"broker_redirect_uri_registered": true` string to my msal config settings, since I already have a redirect URI set up. But after looking at the chart on the doc it seems necessary to have Microsoft Authenticator or Intune Company Portal apps installed on the device. Am I understanding this correctly? Or can it just use the Setttings/Accounts in Android as you suggest. 

Thus far this is the only helpful document I have found. I would very much like to setup the Broker.

**Comment by shoatman** [comment]
You don't need to sign in to the Authenticator app.  Just install it.  The authenticator app and the Intune company portal both contain an implementation of an abstract account authenticator.  This is what we use to make "Work Account" available in the accounts list within settings.  This is what's actually providing the auth broker support.

**Comment by nfgallimore** [comment]
@shoatman I left my app running on the device overnight and I found it unresponsive this morning. It was constantly trying to re-create the ISingleAccountPublicClientApplication since the singleton service I have running (IOpenIdService) where the msal client lives was null. 

Error log:
[logcat.txt](https://github.com/AzureAD/microsoft-authentication-library-for-android/files/4267590/logcat.txt)

    package com.company.appname.api_interaction.services;

    import android.app.Activity;
    import android.content.Context;
    import android.nfc.Tag;

    import androidx.annotation.NonNull;
    import androidx.annotation.Nullable;

    import com.microsoft.identity.client.AuthenticationCallback;
    import com.microsoft.identity.client.IAccount;
    import com.microsoft.identity.client.IAuthenticationResult;
    import com.microsoft.identity.client.IPublicClientApplication.ISingleAccountApplicationCreatedListener;
    import com.microsoft.identity.client.ISingleAccountPublicClientApplication;
    import com.microsoft.identity.client.ISingleAccountPublicClientApplication.CurrentAccountCallback;
    import com.microsoft.identity.client.SilentAuthenticationCallback;
    import com.microsoft.identity.client.exception.MsalException;
    import com.company.appname.R;
    import com.company.appname.api_interaction.interfaces.IOpenIdService;
    import com.company.appname.helpers.DateHelper;
    import com.company.appname.logging.Logging;

    import java.util.Date;
    import java.util.concurrent.Semaphore;

    import static com.microsoft.identity.client.PublicClientApplication.*;

    public class OpenIdService implements IOpenIdService {

        // semaphore is actually a mutex in this case since it only has 1 permit
        private final static Semaphore semaphore = new Semaphore(1);

        private final String TAG = "OpenId Service";
        private final Context context;

        private IAuthenticationResult authenticationResult = null;
        private Runnable runnable;
        private String[] scopes = {
                ""};
        private ISingleAccountPublicClientApplication singleAccountApp = null;
        public OpenIdService(Context context) {
            this.context = context;
        }

        public void acquireTokenSilent(final Activity activity,
                                       final SilentAuthenticationCallback silentAuthCallback) {

            // If the MSAL service is already created, just acquire the token
            if (singleAccountApp != null && semaphore.availablePermits() == 1) {
                callAcquireTokenSilent(silentAuthCallback);
                runnable = null;
            }

            // Else if something already checked out the semaphore
            // to create the msal service wait for it to finish then call
            // acquireToken silent,
            else if (semaphore.availablePermits() == 0) {
                runnable = new Runnable() {
                    @Override
                    public void run() {
                        try {

                            // Wait for the semaphore to be released then call acquire token
                            semaphore.acquire();

                            Logging.Info(TAG, "Acquired semaphore.");

                            // At this point the singleAccountApp should have been
                            // created by the thread that just released the semaphore
                            if (singleAccountApp == null) {

                                // this should be unreachable code
                                Logging.Error(TAG, "Invalid state, MSAL service is null");
                                return;
                            }

                            // Get the token
                            callAcquireTokenSilent(silentAuthCallback);

                        } catch (InterruptedException e) {
                            Logging.Error(TAG, "Failed acquiring semaphore");

                        } finally {
                            semaphore.release();
                        }
                    }
                };

                // Start running the thread
                Logging.Info(TAG, "Waiting for first thread to finish creating MSAL service.");
                new Thread(runnable).start();
            }

            // Else this is the first thread and we need to create the MSAL service
            else {
                runnable = new Runnable() {
                    @Override
                    public void run() {
                        try {
                            // Acquire a semaphore
                            semaphore.acquire();

                            // create a single account public client application (MSAL service)
                            createSingleAccountPublicClientApplication(context, R.raw.msal_config,
                                    getSingleAccountAppCreatedListener(activity, silentAuthCallback));

                            // Semaphore is released within the getSingleAccountAppCreatedListener:

                            // getSingleAccountAppCreatedListener flow of events:

                            // What we do is simple, first we listen for when the
                            // msal service was created.

                            // Once the msal service is successfully created
                            // we attempt to load the user from cache.

                            // If we are able to load the user from cache,
                            // then we can call acquireToken() and release the semaphore

                            // If we are not able to load the user from cache,
                            // then we have to sign them in.

                            // Once the user successfully signs in,
                            // we can call acquireToken() and release the semaphore

                        } catch (InterruptedException e) {
                            Logging.Error(TAG, "Failed acquiring sempahore");
                            semaphore.release();
                        }
                    }

                };

                // Start running the thread
                Logging.Info(TAG, "First thread, creating new MSAL service.");
                new Thread(runnable).start();
            }
        }

        @Override
        public void setAuthenticationResult(IAuthenticationResult result) {
            this.authenticationResult = result;
        }

        private void callAcquireTokenSilent(SilentAuthenticationCallback silentAuthCallback) {
            String authority = singleAccountApp.getConfiguration()
                    .getDefaultAuthority()
                    .getAuthorityURL()
                    .toString();
            singleAccountApp.acquireTokenSilentAsync(scopes, authority, silentAuthCallback);
        }

        private AuthenticationCallback getSignInCallback(
                final SilentAuthenticationCallback silentAuthCallback) {
            return new AuthenticationCallback() {
                @Override
                public void onCancel() {
                    Logging.Error(TAG, "Signing in user was cancelled.");
                    semaphore.release();
                }

                @Override
                public void onSuccess(IAuthenticationResult authenticationResult) {
                    Logging.Info(TAG, "Successfully signed in user.");
                    callAcquireTokenSilent(silentAuthCallback);
                    semaphore.release();
                }

                @Override
                public void onError(MsalException exception) {
                    Logging.Error(TAG, "Error signing user in", exception);
                    semaphore.release();
                }
            };
        }

        private ISingleAccountApplicationCreatedListener getSingleAccountAppCreatedListener(
                final Activity activity,
                final SilentAuthenticationCallback silentAuthCallback) {
            return new ISingleAccountApplicationCreatedListener() {
                @Override
                public void onCreated(ISingleAccountPublicClientApplication application) {
                    // After creating the client save it and try to load user account
                    Logging.Info(TAG, "Created MSAL ISingleAccountPublicClientApplication");
                    singleAccountApp = application;
                    loadAccount(activity, silentAuthCallback);
                }

                @Override
                public void onError(MsalException exception) {
                    Logging.Error(TAG,
                            "Error creating MSAL ISingleAccountPublicClientApplication",
                            exception);
                    semaphore.release();
                }
            };
        }

        private void loadAccount(final Activity activity,
                                 final SilentAuthenticationCallback silentAuthCallback) {

            Logging.Info(TAG, "Attempting to load account");

            singleAccountApp.getCurrentAccountAsync( new CurrentAccountCallback() {
                @Override
                public void onAccountLoaded(@Nullable IAccount activeAccount) {

                    // If no account is available we have to sign the user in
                    if (activeAccount == null) {
                        Logging.Info(TAG, "Could not load account, signing user in");
                        singleAccountApp.signIn(activity, null, scopes,
                                getSignInCallback(silentAuthCallback));

                    } else {
                        Logging.Info(TAG, "Account loaded");
                        callAcquireTokenSilent(silentAuthCallback);
                        semaphore.release();
                    }
                }

                @Override
                public void onAccountChanged(@Nullable IAccount priorAccount,
                                             @Nullable IAccount currentAccount) {
                    Logging.Info(TAG, "Account has changed.");
                    semaphore.release();
                }

                @Override
                public void onError(@NonNull MsalException exception) {
                    Logging.Error(TAG, "Error getting account", exception);
                    semaphore.release();
                }
            });
        }
    }
