### ISSUE TITLE
complete acquire token error

### ISSUE THREAD

**Issue by jdestefano123** [AzureAD/microsoft-authentication-library-for-android#940]
**Which Version of MSAL are you using ?**
msal:1.1.0-hf1

**Platform**
Android

**What authentication flow has the issue?**
Mobile 
Refresh

Other? - please describe;

**Is this a new or existing app?**

The app is in production, I haven't upgraded MSAL, but started seeing this issue

**Repro**

Unable to reproduce consistently 

**Expected behavior**
User should be logged in upon completion of authentication

**Actual behavior**
App Crashes

**Additional context/ Logs / Screenshots**

com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken
LocalMSALController.java, line 205
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.providers.oauth2.AuthorizationStrategy.completeAuthorization(int, int, android.content.Intent)' on a null object reference

![image](https://user-images.githubusercontent.com/61242902/74852351-73744700-530a-11ea-9b1f-17b5f296cdec.png)

**Comment by shahzaibj** [comment]
@jdestefano123 Thanks for reporting. We are aware of this issue and currently working on fix. I will discuss plans for a hot fix release with our team and will report back to you after that.

**Comment by shahzaibj** [comment]
@jdestefano123 We have a fix for this issue and I've opened up a PR [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/828). We are currently planning to start cutting an MSAL release some time next week. I'll keep you updated on the status of that.

**Comment by shahzaibj** [comment]
@jdestefano123 This issue has been closed as the above linked PR has merged. I am currently working on getting the release process started (can take 2-4 days to complete). I'll give you an update once the release is available in Maven.

**Comment by shahzaibj** [comment]
@jdestefano123 The latest release of MSAL with this fix is available on Maven Central. The release version is `1.4.0`

**Comment by jdestefano123** [comment]
@shahzaibj awesome, thanks for the updates!
