### ISSUE TITLE
[Question] Email value was null when tried to sign in

### ISSUE THREAD

**Issue by kadalcj** [AzureAD/microsoft-authentication-library-for-android#941]
Hi everyone.

Why the browser was straight redirect to password and gave that null value on the email so I can't sign in to test my app. Is this bug or something else?

*edit: It doesn't gave me a chance to fill or select pervious registered account

![Screen Shot 2020-02-21 at 15 24 05](https://user-images.githubusercontent.com/43379893/75017280-3f8e5280-54bf-11ea-9d42-1c5c63cd9049.png)
This is what I mean.

**Comment by shahzaibj** [comment]
Hi @kadalcj Can you provide a bit more information like which version of MSAL you are using? Do you have a consistent repro for this issue? If yes, what are the repro steps?

**Comment by kadalcj** [comment]
This is the version that I use
![image](https://user-images.githubusercontent.com/43379893/75123950-72626180-56de-11ea-84af-665965b89f4f.png)

Yes, I do. Before that happen, I was using the same version. But 2 days ago the sign in page kinda showing something different. It say's "You already sign in" or something like that and there was 2 option, "Sign in with this account" or "Sign in with another account" if I am not mistaken. I choose sign in with another account because I using different azure directory and it set only can sign in with account that registered in the directory itself. I press that, and bamm. They redirect me to the account selector that showing previous account has been sign in to the device, but they redirect me to the password field instantly.

I hope you can help me out. Thank you very much

**Comment by shahzaibj** [comment]
@kadalcj Based on what you describe, it seems like you want to login with AAD accounts but the login page that you are seeing is specific to Personal MSA accounts. What type of [authority](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#authorities) have you declared in your app's config json file?

**Comment by kadalcj** [comment]
This is what I use for the config file.
![Screen Shot 2020-02-27 at 8 36 32](https://user-images.githubusercontent.com/43379893/75404213-71c70680-593c-11ea-998b-7351c61f6fdd.png)

Is I config it wrong? Because what I do is following the guide from the Graph documentation

**Comment by shahzaibj** [comment]
What graph documentation? You should be using MSAL documentation instead

**Comment by kadalcj** [comment]
I mean [this](https://docs.microsoft.com/en-us/graph/tutorials/android?tutorial-step=3). But I change it few parts that different with the config code that generate from AAD.

**Comment by shahzaibj** [comment]
Okay, that's fine. So the config file, looks good to me. Since the authority audience is AAD, it should not be possible to be redirected to `login.live.com`. When the browser opens, the url should be `login.microsoftonline.com`. Which url are you getting in the browser? From the image it seems like the first one and that is going to be wrong

**Comment by kadalcj** [comment]
The browser redirect it to this: 
`https://login.live.com/oauth20_authorize.srf?response_type=code&client_id=51483342-085c-4d86-bf88-cf50c7252078&scope=openid+profile+email+offline_access&response_mode=form_post&display=host&redirect_uri=https%3a%2f%2flogin.microsoftonline.com%2fcommon%2ffederation%2foauth2&state=rQIIAa2Rv2_TQBzFc01aaFSJghhYkIJoBSqycz7bdRyJIW2aljZnh9RJai_R2b40_m3ZCSnZ2BADQoxdkDqhMoAQAsTE3Kkj6tgJMXVESEikqvof8IbP-36XN7yXn-ZYyMKlLGJheUGgPCdDk2ckXoaMgHiZIZLFMyURmXKPh6JM7eRGfv79l8Ip9-Jg_dntiH97-ub7Ppjt-s4TylpRcAiUICXDQb9cLE5elu6RIPYp6_h9EjjhgCYhG6ROEJmOT0kcF5trK6YR1NSULqLaql7ldmq9zdGWvblTstJFvvoVgGMAfgLweioXDn3_ZOqaWpnko3NEiTOm-1lTD9qOrjU9Zb01MKprY3UbQkWz9uqa9xS7eKBo3sjoGK6xXvMwejSud3RB7TQD7K6N65o-wlploFR9X93m-tj1UL2Deay1HWXcD7Dme8bjw-wCvBDPnPMC1uV1qY_ZBUkQOYFYIiPbks0IxJQZWTJtRpRFwhEkm5YEj7L3WilN2CYldiGKaehMrNfznZB2iWXRNC3ESdSbVPQjC45z4Fdu7iqYz9zKFDL3r0PwOwcOpidD3L1z9vKP_Xfr07vPdrw0AEfTRY4M7dRfhRuaOxA9JeynteHmGO9ZVFgOaaAmabq72_BJzcAPpTL3agYczczh7UqdrYR2Ejn22Qx4fiXzbfY_z3iYf6BWXGM0EtpcU-80FKbdELSWsazoqxsrrtcoxf5QIBh3k06r9CEPTvI3EUSTdhGDpAJEZVEuC8j4Bw2&estsfed=1&uaid=e220b7af8a3147a2811d6f33a8e29fc0&fci=4e3190b3-7390-4239-a7c3-852b9f3059ed&username=null`

**Comment by shahzaibj** [comment]
@kadalcj What acquire token method overload are you calling in MSAL? Are you passing any login hint?

**Comment by kadalcj** [comment]
I am sorry, don't quite understand what you mean. Is it something like "User.Read"?

**Comment by shoatman** [comment]
Try specifying Prompt.SELECT_ACCOUNT as part of your parameters ... via .withPrompt().  I suspect that you logged into this browser before using an MSA account.  As a result you're bypassing the ability to choose and/or sign in with a different account.  You can confirm this by deleting your cookies from the default browser on your device.

**Comment by kadalcj** [comment]
I already do that and apparently deleting cookies doesn't do anything, it still jump to password input. It kind of strange but I try remaking it using Java instead of Kotlin and it work. I check two of them side by side, and I found it not too different . So, yeah. I don't know what to say.

**Comment by shahzaibj** [comment]
@kadalcj That's interesting! When you use Java, do you still get redirected to `login.live.com` or a different url?

**Comment by kadalcj** [comment]
Hmmm, it was different. It redirect me to ```login.microsoftonline.com```. I never check it tho, so I didn't even notice if the link was different.

**Comment by kadalcj** [comment]
Do I need 365 subscription to fully utilize all of the function? Currently I was using my hotmail email.
I tried get the picture from one of account that I made in Azure AD, but always give me 404. Someone just told me that 365 subscription, so I want to confirm it.

**Comment by shahzaibj** [comment]
@kadalcj I don't think you would need 365 subscription in your case. I'm also curious what you mean by tried to get the picture? MSAL only provides authentication capabilities, we don't support fetching of images from some backend provider.

I am actually curious to understand why you are being redirected to different url depending on whether you use JAVA or Kotlin. Can you capture MSAL logs, and share them with me so I can investigate? Here are instructions for capturing logs in MSAL:  https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=android

**Comment by kadalcj** [comment]
I was trying to get the profile image of the account. Of course Identity can't perform such a thing because it was design to only provide authentication.  So to do such a perform, I use Graph. Here is the documentation: https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0

Is that so? Because I was trying with my hotmail account that I use to create Azure but when logged in, it was spontaneously crash. But when I use my 365 account that my University provide It was fetch the image perfectly. I know it was wrong repo / forum to ask but I wonder if you guys know that, so yeah.

I will provide you the log ASAP, but I can't do that right now. Please wait okay. Thank you.

**Comment by shahzaibj** [comment]
@kadalcj I would believe that the reason you weren't able to get the photo using hotmail account is probably because it isn't supported. See this documentation: https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0#permissions

It seems like Personal Microsoft Accounts (For example, your hotmail account) aren't supported for this operation, and hence you weren't able to get the image.

**Comment by kadalcj** [comment]
@shahzaibj Oh I see, I don't even know if you didn't pointing out to me. So, at least I know the issue about problem on fetch data from AzureAD.

**Comment by shahzaibj** [comment]
@kadalcj I'm going to close this issue now as I know that it's working for you right now as you build your app using JAVA. If the problem reappears using either JAVA or Kotlin, feel free to reopen this issue and also provide us logs to investigate. Thanks!
