### ISSUE TITLE
No response on "onFailure" callback when calling acquireToken

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#964]
Hi!

when testing on Samsung S6 running android 7.0, we found an issue on when the user has no connection to the internet and he tries to submit a form, the "onFailure" callback from acquireToken is never triggered, thus the user gets stuck on screen.

Can you guys take a look at this?

EDIT: it also happens when I run android 7.0 on an emulator, so it must be something related to this android version and not specifically to some devices.

Best regards,
William

**Comment by kreedula** [comment]
Thanks for reporting. We will triage and pick this up to repro and will get back. Meanwhile if you have any more information regarding this, please share it here.

**Comment by wmiranda** [comment]
@kreedula @shoatman do you guys have any update about this issue?
We have a test case depending on that to be closed.
Tks in adv

**Comment by xyzwilliamxyz** [comment]
I retested this with MSAL 2.0.4 on android 7.0 and it's working now :+1:
