### ISSUE TITLE
Token from Android and Angular are not the same

### ISSUE THREAD

**Issue by nicolasbarb** [AzureAD/microsoft-authentication-library-for-android#965]
**Describe the bug**
Hello, i'm currently working with MSAL on Android device and Angular Web app. Both are using the same application on Azure AD and both connection are returning a token.

My problem is that the token obtained from Android and from Angular doesn't have the same payload but also not the same signature. Indeed, the signature of my Angular token is validated by my server while the Android token is rejected.

I don't understand where the problem comes from since my two applications are based on the same Azure AD application and use the same configuration, the same APP ID and the same TENANT ID.

If you've had this problem before or you can refer me, that would be great.

Best Regards,

Nicolas

**Comment by iambmelt** [comment]
Hi @nicolasbarb - Consider using our support community on [StackOverflow](https://github.com/AzureAD/microsoft-authentication-library-for-android#community-help-and-support) to investigate this issue as it may be configuration/middleware related and not a bug in the Android library
