### ISSUE TITLE
MSAL webview shows login screen instead of designated journey

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#969]
Hi!

We have a journey called _**onboarding**_ where the user needs to be authenticated to open it.

We recently found an issue when we have the following scenario:

**1** - user logs into the app
**2** - close the app
**3** - reopen the app and we perform autoLogin (**acquireTokenSilent**)
**4** - after success callback we call **aquireToken** to open the _**onboarding**_ journey, and it shows the login screen instead.

I was able to avoid this issue by adding a **delay** between step 3 and 4, before calling **aquireToken** to open the new journey.

Another developer here has a theory that it might be something related to cookies not being loaded on time.

Could you guys take a look at it?

Best regards,
William

**Comment by shoatman** [comment]
How much of a delay was added?  Are you including a prompt parameter (withPrompt()) with your request?  If so, which one?

I doubt that the cookies are not loaded, but there may still be a server side issue here rather than a client side one.  If you have a correlation id from this request we can try and see what's happening server side.

**Comment by janrk-ciandt** [comment]
@shoatman We put 5 seconds of delay because accordingly some tests it takes more than 3 seconds to load it. We are not passing the prompt parameter to this journey. 
We are trying to figure out a correlation id here.

**Comment by shoatman** [comment]
What about loginHint?

**Comment by xyzwilliamxyz** [comment]
@shoatman Hi! We don't use loginHint. I couldn't find much about it, what does it do?

**Comment by shoatman** [comment]
It accelerates the UI experience.  If you provide an email address for the account. It will auto-select the matching account and potentially redirect to where the authentication can be completed.  In the case of federated authentication.

**Comment by xyzwilliamxyz** [comment]
I see, thanks! I don't think it's our case.
