### ISSUE TITLE
Migration from ADAL to MSAL is not working seamlessly

### ISSUE THREAD

**Issue by SwathyMothilal** [AzureAD/microsoft-authentication-library-for-android#971]
I am migrating the ADAL library to MSAL library in the app. And when the users are upgrading from the older app [with ADAL implementation] to current app [MSAL implementation], the getAccounts() returns null.

ADAL version -> 1.16.0
MSAL version -> 1.4.0

Unfortunately, I am currently logging out the user after upgrading the app.

**Comment by shoatman** [comment]
We'll take a look at this.

**Comment by shahzaibj** [comment]
Possibly same issue as #967

**Comment by hamiltonha** [comment]
@SwathyMothilal is this still an issue? Looks like it was resolved with #967

**Comment by shoatman** [comment]
Closing this issue due to lack of response.
