### ISSUE TITLE
Issues signing in to AD with a personal account

### ISSUE THREAD

**Issue by josephkniestprometheanworld** [AzureAD/microsoft-authentication-library-for-android#972]
Good day,

An android application with Active Directory sign-in is unable to sign in to personal accounts, however we are able to sign in to an Azure AD account. 

The auth json config is pretty standard as per the tutorial: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android

our auth json looks something like the following with sensitive info stripped out:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/49211274/76657991-54935a00-6530-11ea-97fc-6273410a3b1f.png">

and our app's config for the "com.microsoft.identity.client.BrowserTabActivity" activity within the app's android manifest is also quite standard, shown below with sensitive info stripped out:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/49211274/76658026-670d9380-6530-11ea-805a-f6fbeff0a153.png">

Why are we able to sign in to Azure AD accounts but not personal accounts? Is this a known bug? What's the missing piece of config? Thanks for looking!
<img width="558" alt="image" src="https://user-images.githubusercontent.com/49211274/76656946-f49bb400-652d-11ea-9d8f-bcf4e3770c8c.png">

**Comment by josephkniestprometheanworld** [comment]
For our auth json I have tried both with and without

`"authority_url": "https://login.microsoftonline.com/common"`

inside our one "authorities" object

**Comment by shahzaibj** [comment]
@josephkniestprometheanworld  What account types does your support as listed in the Azure Portal? 

You can check by going to Azure Portal->App Registrations-><YOUR_APP_NAME>->Authentication

Scroll down on the page and you will see a section on supported account types.

Here's a sample screenshot: 

![image](https://user-images.githubusercontent.com/37125644/76665541-7a772980-6545-11ea-9c68-88dd02780bf6.png)

**Comment by josephkniestprometheanworld** [comment]
The issue was we were missing this from our azure AD app manifest json:

`"signInAudience": "AzureADandPersonalMicrosoftAccount",`

this needs to be at the root of the config object, i.e. a sibling of the "id" property.
