### ISSUE TITLE
Cannot resize microsoft sign in activity

### ISSUE THREAD

**Issue by josephkniestprometheanworld** [AzureAD/microsoft-authentication-library-for-android#978]
The sign in activity for MS "com.microsoft.identity.client.BrowserTabActivity" is always full screen. There doesn't seem to be a means of setting the size. I can't inherit from it as it is final

`public final class BrowserTabActivity extends Activity`

and I can't perform the same logic that it does to launch the web view activity

`startActivity(BrowserAuthorizationFragment.createCustomTabResponseIntent(this, getIntent().getDataString()));`

because I don't know where the library containing the type

`com.microsoft.identity.common.internal.providers.oauth2.BrowserAuthorizationFragment`

is located.

The only way I know of for an activity to set its size is programmatically within the activity's onCreate():

<img width="333" alt="Screen Shot 2020-03-20 at 9 09 28 AM" src="https://user-images.githubusercontent.com/49211274/77182890-b866d700-6a8a-11ea-9db0-e272f5c35887.png">

but there is no opportunity to do this with the given sdk. I think the sdk needs to expose some method of allowing the activity to have its dimensions specified by the consumer. Where can I find the library "com.microsoft.identity.common.internal.providers.oauth2.BrowserAuthorizationFragment" ?

Thanks for looking at this.

**Comment by josephkniestprometheanworld** [comment]
I have tried using android styles <style> and themes as well. The styles and themes referrenced seem to be simply ignored. 

<img width="993" alt="Screen Shot 2020-03-20 at 9 44 43 AM" src="https://user-images.githubusercontent.com/49211274/77185965-73916f00-6a8f-11ea-87de-150001a4376e.png">

**Comment by shahzaibj** [comment]
@josephkniestprometheanworld `BrowserTabActivity` does not have UI. It's just there to capture the result of the authentication. Can you elaborate more on what exactly are you trying to achieve? Which UI do you want to resize and why?

**Comment by josephkniestprometheanworld** [comment]
I would like to resize an activity that displays the azure sign in web app inside an android WebView. 

`final Intent responseIntent = BrowserAuthorizationFragment.createCustomTabResponseIntent(this, getIntent().getDataString());`

That line appears to be getting the intent that was fired to start the activity in the first place and puts some authorization stuff on the intent. What entity fires the intent to start the BrowserTabActivity?

Can you provide a code sample of how to create your own custom activity with a WebView that you can control/customize that loads the azure sign in web app into its WebView? All samples I have seen don't do this, they simply define the config for their version of the BrowserTabActivity which then launches implicitly.

Thanks!

**Comment by shahzaibj** [comment]
@josephkniestprometheanworld `BrowserTabActivity` is launched by the Android OS via the Intent filter declared in the Android Manifest. That activity is just for the result. My understanding is that you want to resize the activity that holds the WebView. In this case that would be the `WebViewAuthorizationFragment`.

With that being said doesn't the Activity automatically resize when the user switches to dual-task mode and opens multiple apps side by side? Is that what you are trying to achieve? Because if there is only one app open on the device, my understanding is that is has to be full screen. Hey @rpdome Do you know if Android support this? Or do we support it in our library?

**Comment by josephkniestprometheanworld** [comment]
So should I subclass `common/common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/WebViewAuthorizationFragment.java` ?

**Comment by rpdome** [comment]
@shahzaibj @josephkniestprometheanworld Unfortunately, we do not support resizing the sign-in activity.

**Comment by shahzaibj** [comment]
@josephkniestprometheanworld See comment from Dome above. I'm going to close this issue as we do not support this behavior.
