### ISSUE TITLE
Google login fails when non standard browser is installed

### ISSUE THREAD

**Issue by abdurahmanadilovic** [AzureAD/microsoft-authentication-library-for-android#994]
**Describe the bug**
A number of our users can't log in with google option during the login flow, "disallower_agent" message is shown. Some users are reporting the same issue when they have chrome installed but I could not reproduce this issue with chrome installed, only when no browser is available on the device. Some people are claiming that setting user agent on a webview fixes this issue, more on that [on this SO link](https://stackoverflow.com/a/43973356). 

We have also reports saying that they only have firefox nightly installed, one user got this message with these browsers installed DuckDuckgo+Brave+Chrome.

Currently we don't have any "authorization_user_agent" set in the .json config file in the app which means the "DEFAULT" value is set?

**Smartphone (please complete the following information):**
 - Device: [not available]
 - Android Version: [not available]
 - Browser [probably webview]
 - MSAL Version 1.4.0 (B2C type)

**To Reproduce**
1. Uninstall all browsers from a device to force login on a webview
2. Pick google as login option

**Expected behavior**
Should be able to login in with google in a webview

**Actual Behavior**
Error is shown "disallowed_useragent"

**Screenshots**
[Screenshot_20200401-174957](https://user-images.githubusercontent.com/25008241/78368994-ceb17e80-75c4-11ea-86cf-bc0f0daeeff7.jpg)

**Comment by shoatman** [comment]
Yes.  The default is "DEFAULT", which attempts to use a known safe browser on the device first and if none-available is supposed to fallback to the android embedded webview.

**Comment by shoatman** [comment]
I think the message that you are seeing is from Google... rather than from the library.  Google requires the use of a browser rather than an embedded webview.  SEe the following blog post form 2016: https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

**Comment by abdurahmanadilovic** [comment]
Is there a way for me to tell the msal to inject user agent in the webview so that google does not show that message? According to this link https://stackoverflow.com/a/57918590/1057820 all that needs to be done is to have user agent property in the webview. 

The problem is when msal detects no viable browser, webview will be used to do sign in, and if user selects google, sign in on webview for google does not work currently.

**Comment by iambmelt** [comment]
Behavior is by-design; we don't intend to allow developer to bypass Google security behavior of disallowing WebView access to Google Sign-In
