### ISSUE TITLE
[ADAL] Unable to retrieve IdToken via acquireTokenSilentAsync()

### ISSUE THREAD

**Issue by Ishita-Pandey** [AzureAD/microsoft-authentication-library-for-android#997]
**Describe the bug**
Currently we onboard our application via an interactive sign-in flow. User info is stored locally which is used to fetch subsequent tokens.
However, now the scenario is that no interactive sign-in prompt should show up [i.e account picker screen must not show up] and the token authorization must happen silently.
I fetched the userId [mUniqueId] for the user who is signed into Company portal and passed the correct resourceId, clientId, userid and AuthenticationCallback<AuthenticationResult>.
To my surprise, authenticationResult comes back with valid access token but the idToken field is blank.

**Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - Android Version: API 29
 - Browser N/A
 - MSAL Version : **com.microsoft.aad:adal:1.15.1**

**To Reproduce**

1. Fetch _userId_ of the user signed into company portal
2. Do _acquireTokenSilentAsync()_ for the userId retrieved above.
3. Check for the idToken by doing _authenticationResult.getIdToken()_
4. IdToken comes out to be blank

**Expected behavior**
The idToken must be a vaid non-null value just like we get it in interactive auth flow

**Actual Behavior**
idToken comes out to be blank, although non-null access token is correctly retrieved

**Screenshots**
![image](https://user-images.githubusercontent.com/49427683/79118562-e7cbe380-7dab-11ea-966d-b7072ca32294.png)

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by shoatman** [comment]
Hi @Ishita-Pandey , just to confirm you are using ADAL and not MSAL correct?  YOu indicated: com.microsoft.aad:adal:1.15.1

**Comment by shoatman** [comment]
If you are using ADAL.  Please start by upgrade to the latest ADAL version.  If your app is already migrated to AndroidX would be 3.01. Otherwise i'd recommend ADAL 1.16.3

**Comment by Ishita-Pandey** [comment]
Upgrading to latest ADAL version didn't help either :(

**Comment by shoatman** [comment]
I took a look at the broker logs submitted.  Can you tell me more about the test device.  How was the account on the device added?  It looks like the account was not found in the cache, but was found in android account manager.  I need to determine why the account information was also not in the cache and the history on how the account was added to the device will help.

**Comment by Ishita-Pandey** [comment]
The test device is Samsung S10+ (Android 10). I installed company portal and signed into it using my demo tenant admin credentials. Then I installed my application and triggered the silent token fetch auth flow. I'm not sure of the cache involvement here and if this should be handled explicitly.

**Comment by shoatman** [comment]
Did you enroll the device in Intune?

**Comment by Ishita-Pandey** [comment]
Yes the device was enrolled after which I retrieved the userId from BrokerUsers and then tried the silent auth token fetching.

**Comment by shoatman** [comment]
Is BrokerUsers an interface/api in the company portal?  If so, what's being return as a user_id?  A UPN or a GUID?

**Comment by Ishita-Pandey** [comment]
This is the code block that fetches userId for the currently signed user in company portal - 
```
final UserInfo[] users = mAuthContext.getBrokerUsers();
                    if (users.length < 1)
                        return "no user id available for silent auth";

                    // Note: if there is more than one user, just use the first one.
                    String userId = users[0].getUserId();
```
getBrokerUsers() is an API in com.microsoft.aad.adal.AuthenticationContext class that gets the userInfo.
I was able to extract userId [unique GUID] fro this userInfo.
I have also verified that the GUID is same when silent auth token fetch is triggered and with interactive sign-in prompt route. The tokenId is fetched correctly via interactive sign-in that uses the same userId GUID

**Comment by Ishita-Pandey** [comment]
Hi Shane, Any luck with this issue?
We have a customer release awaiting this blocker. Kind request to help us unblock this.

**Comment by Ishita-Pandey** [comment]
Hi Shane, following up on this. Any updates that you could share with me.

**Comment by rpdome** [comment]
Fixed in https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1530. Will be shipped with 3.0.2

**Comment by Ishita-Pandey** [comment]
Thank you so much @rpdome for looking into this!
When would 3.0.2 be shipped?

**Comment by rpdome** [comment]
@Ishita-Pandey It's in the process as we speak. Might take a day to roll out to public maven repository.

**Comment by Ishita-Pandey** [comment]
Awesome!
